### ISSUE TITLE
docs: fix examples in tutorial and api gw handler

### ISSUE THREAD

**Issue by michaelbrewer** [awslabs/aws-lambda-powertools-python#1013]
**What were you initially searching for in the docs?**

- Working code examples.

**Is this related to an existing part of the documentation? Please share a link**

- api gw handler (https://awslabs.github.io/aws-lambda-powertools-python/latest/core/event_handler/api_gateway/)
- appsync handler (https://awslabs.github.io/aws-lambda-powertools-python/latest/core/event_handler/appsync/)
- tutorials (https://awslabs.github.io/aws-lambda-powertools-python/latest/tutorial/)
- feature flag (https://awslabs.github.io/aws-lambda-powertools-python/latest/utilities/feature_flags/)

**Describe how we could make it clearer**

- Fix code examples

**If you have a proposed update, please share it here**

List of things to fix:
- fix line number highlights
- fix missing imports
- fix syntax error
- fix indents
- fix example code rendering

Indent issue example:
<img width="1079" alt="Screen Shot 2022-02-07 at 10 17 20 PM" src="https://user-images.githubusercontent.com/5442469/152929369-48b671da-83b5-437e-a53a-4fcfdf7d125d.png">

Syntax Error example:
<img width="1091" alt="Screen Shot 2022-02-07 at 10 20 59 PM" src="https://user-images.githubusercontent.com/5442469/152929738-d35a7355-316f-4a26-9da4-70cce33548c3.png">

Missing import example for `json` example:
<img width="1062" alt="Screen Shot 2022-02-07 at 10 22 54 PM" src="https://user-images.githubusercontent.com/5442469/152930018-c21137d4-382e-45a6-857d-9c298c9b2a5d.png">

Code rendering example:
<img width="1100" alt="Screen Shot 2022-02-07 at 10 23 59 PM" src="https://user-images.githubusercontent.com/5442469/152930156-99084509-a9ba-409a-8e08-5397f4840530.png">

PR:
- https://github.com/awslabs/aws-lambda-powertools-python/pull/1004

**Comment by heitorlessa** [comment]
now available as part of 1.25.0 release
