### ISSUE TITLE
Documentation: change project name to "AWS Lambda Powertools for Python"

### ISSUE THREAD

**Issue by saragerion** [awslabs/aws-lambda-powertools-python#1056]
## Description of the improvement

**Summary of the proposal**

Change project name being referenced from these versions:

- AWS Lambda Powertools (Python)
- Lambda Powertools Python
- AWS Lambda Powertools Python

To this: 
AWS Lambda Powertools for Python

**[See related RFC for more information](https://github.com/awslabs/aws-lambda-powertools-roadmap/issues/80)**

**How, where did you look for information**

- Readme files (root folder, nested project folders)
- Mkdocs files in `docs`
- Code
- ...

We probably need to do a text search in the whole repo.

**Missing or unclear documentation**

Inconsistent naming convention, see related RFC.

**Improvement**

A consistent name throught the project.

### Related existing documentation
N/A

### Related issues, RFCs

https://github.com/awslabs/aws-lambda-powertools-roadmap/issues/80

**Comment by heitorlessa** [comment]
Done now.
