### ISSUE TITLE
Logger examples for logging exception

### ISSUE THREAD

**Issue by michaelbrewer** [awslabs/aws-lambda-powertools-python#107]
**What were you initially searching for in the docs?**

I am looking for code examples for logging an error with the exception

**Is this related to an existing part of the documentation? Please share a link**
https://awslabs.github.io/aws-lambda-powertools-python/core/logger/

**Describe how we could make it clearer**
Some examples of logging an exception and maybe more examples using other levels. Currently non of the code completion works in PyCharm. 

**If you have a proposed update, please share it here**

Some sample examples or have python stubs to be used with Pycharm or VSCode.

```python3
    try:
        logger.debug("Some which might fail")
    except SomeErrorWeSuppress as e:
        logger.exception(e)
```

**Comment by heitorlessa** [comment]
Hey Michael - I've just released that in 1.1.2 -- There shouldn't need a docs update as that should be a given from our side ;).

Thanks as usual for flagging these
