### ISSUE TITLE
Reduce Pydantic package size with no-binary flag when support is out

### ISSUE THREAD

**Issue by zrothberg** [awslabs/aws-lambda-powertools-python#1078]
I was reading through the docs and saw that pydantic adds over 70 mbs. Poking around the pydantic repo there are a few threads about this subject. https://github.com/samuelcolvin/pydantic/issues/2276 https://github.com/samuelcolvin/pydantic/pull/2517. I was wondering if it was possible to use the --no-binary flag in your package level requirements.txt. I had seen this comment https://github.com/awslabs/aws-lambda-powertools-python/issues/481#issuecomment-863907997 and am unsure if the same issue that prevents the smaller cython binaries would prevent this from working. I also saw that poetry doesn't allow the --no-binary flag so wasn't sure if that could be a reason that preventing this from being recommended. Or if this works but wasn't mentioned in the docs due to speed concerns.

**Comment by heitorlessa** [comment]
assigning to @rubenfonseca as we've managed to make a HUGE improvement for V2, getting down to Pydantic fully optimized with Cython, yet ~2MB final Lambda Layer with ALL deps installed!

**Comment by rubenfonseca** [comment]
We are now close to release the v2 layer with all the optimizations mentioned on this issue, thank you so much for your great tips! You can check the current implementation on our CDK Layer construct: https://github.com/awslabs/cdk-aws-lambda-powertools-layer/blob/main/layer/Python/Dockerfile#L31-L47

**Comment by heitorlessa** [comment]
Closing as we're wrap to launch V2
