### ISSUE TITLE
feat(parameters): Allow settings boto3.client() arguments

### ISSUE THREAD

**Issue by gshpychka** [awslabs/aws-lambda-powertools-python#1079]
**Is your feature request related to a problem? Please describe.**
I'm using VPC endpoints with private DNS disabled, so I have to pass `endpoint_url` to `boto3.client` to use the endpoint-specific host name. I am not able to use `parameters` because this is not supported.

**Describe the solution you'd like**
Perhaps allowing to pass additional keyword arguments to the `client` method.

**Comment by ran-isenberg** [comment]
Hey, to my understanding this is already supported.
Take a look at https://awslabs.github.io/aws-lambda-powertools-python/latest/utilities/parameters/#passing-additional-sdk-arguments
or https://awslabs.github.io/aws-lambda-powertools-python/latest/utilities/parameters/#customizing-boto-configuration

**Comment by gshpychka** [comment]
> Hey, to my understanding this is already supported. Take a look at https://awslabs.github.io/aws-lambda-powertools-python/latest/utilities/parameters/#passing-additional-sdk-arguments or https://awslabs.github.io/aws-lambda-powertools-python/latest/utilities/parameters/#customizing-boto-configuration

The former only allows me to pass arguments to the client's methods, and the latter allows me to modify the session, but none of these allow me to modify the client initialization.

**Comment by ran-isenberg** [comment]
look at the appconfig example
config = Config(region_name="us-west-1")
appconf_provider = parameters.AppConfigProvider(environment="my_env", application="my_app", config=config)

config is sent to the client initalization and points it to a specific region.

**Comment by gshpychka** [comment]
> look at the appconfig example config = Config(region_name="us-west-1") appconf_provider = parameters.AppConfigProvider(environment="my_env", application="my_app", config=config)
> 
> config is sent to the client initalization and points it to a specific region.

Right, but the `endpoint_url` cannot be set with the Config object, it has to be passed as a separate argument to the client.

**Comment by gshpychka** [comment]
@ran-isenberg can you confirm that I'm not missing anything here?

**Comment by ran-isenberg** [comment]
where did you see endpoint_url parameter? i dont see it in the  docs: https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/appconfig.html#client

**Comment by ran-isenberg** [comment]
@gshpychka  I'm not familiar with this field BUT to my understand, unless you can set it via the config param:
https://botocore.amazonaws.com/v1/documentation/api/latest/reference/config.html
then you can't do.

I think you are right.
What do you use endpoint_url for if i may ask?

**Comment by gshpychka** [comment]
> @gshpychka I'm not familiar with this field BUT to my understand, unless you can set it via the config param: https://botocore.amazonaws.com/v1/documentation/api/latest/reference/config.html then you can't do.
> 
> I think you are right. What do you use endpoint_url for if i may ask?

Yes, exactly. As stated in the issue description, I'm using VPC endpoints with private DNS disabled, so I have to pass endpoint_url to boto3.client to use the endpoint-specific host name.

**Comment by ran-isenberg** [comment]
@heitorlessa  I think we should allow people to send qwargs to the init function, not just config.

**Comment by heitorlessa** [comment]
Thanks everyone! The more I look into the Parameters utility the more I find we should've accepted a whole boto Client only. It would simplify our logic to maintain it, and also make it easier for customers to stub for unit testing, use snapshot testing with placebo, or in this case pass a different endpoint_url.

We won't be able to add this now due to our [pause and bandwidth](https://github.com/awslabs/aws-lambda-powertools-python/issues/1076). I do believe there are other customers who will eventually be blocked by this too, so if anyone could create a PR to accept a Client I'll happily work with you to get it merged as an exception.

Note: I'm following [this issue for boto to eventually add support to `endpoint_url` via environment variables](https://github.com/boto/boto3/issues/1375) as it's a common ask.

**Comment by ran-isenberg** [comment]
@heitorlessa A boto client in addition to the session or instead?

**Comment by heitorlessa** [comment]
It’d have to be in addition to not break customers using the boto3_session
argument. If they pass a session, we create a client from it. If they pass
a client, we use that instead.

**Comment by ran-isenberg** [comment]
@heitorlessa  FYI https://github.com/awslabs/aws-lambda-powertools-python/pull/1096

**Comment by heitorlessa** [comment]
Releasing it first thing tomorrow morning @gshpychka

**Comment by heitorlessa** [comment]
@gshpychka this is available on PyPi and SAR already - a new Lambda Layer will be available in a few hours. Docs are here: https://awslabs.github.io/aws-lambda-powertools-python/latest/utilities/parameters/#bring-your-own-boto-client

Please do feel free to reopen if this has not solved your problem. We took liberty to add for others to address a related testing challenge with Parameters too.
