### ISSUE TITLE
Reusing Tracer across your code disables patching boto3

### ISSUE THREAD

**Issue by michaelbrewer** [awslabs/aws-lambda-powertools-python#108]
**What were you trying to accomplish?**
I am have my shared code include `@tracer` but i don't want to double patch boto3 etc..

## Expected Behavior

`tracer = Tracer(auto_patch=False)` should not disable patching in the main lambda handler

## Current Behavior

When i go into the console now of the boto3 activity appears

```python
# main.py
from aws_lambda_powertools import Tracer
from app import shared

tracer = Tracer(service="payment")

@tracer.capture_lambda_handler
def handler(event, context):
     pass
```

```python
# shared.py
from aws_lambda_powertools import Tracer

tracer = Tracer(auto_patch=False)
```

## Possible Solution

I think because the shared.py - `tracer = Tracer(auto_patch=False)`  code is called before the main.py. The patching has already been disabled.

## Environment

* **Powertools version used**:  1.1.1

**Comment by heitorlessa** [comment]
That’s exactly it Michael - Could you try removing auto_patch from your
shared?

Under the hood, a module is only patched once by X-Ray SDK as it uses the
importlib package.

I’ll leave this open to add a clarification note in the docs about this

**Comment by michaelbrewer** [comment]
Ok. Then I must have misunderstood the docs. I thought if you don't want to double patch you turn it off in the shared code but it will patch in the main handler file. 

Currently I don't include it and it works. I guess it is a matter looking closely at the docs.

**Comment by heitorlessa** [comment]
Nope, it’s on us - I had a second look at the docs and the wording isn’t
right; I‘ll fix it

**Comment by heitorlessa** [comment]
@michaelbrewer When you can, could you please review the docs statement to make sure it's clearer?

**Comment by heitorlessa** [comment]
Just released :) https://awslabs.github.io/aws-lambda-powertools-python/core/tracer/#reusing-tracer-across-your-code
