### ISSUE TITLE
Logger clear_state flip removing structure keys

### ISSUE THREAD

**Issue by alexanderluiscampino** [awslabs/aws-lambda-powertools-python#1084]
Using the `clear_state` argument in the logger decorator for lambda handlers is destroying the default structured keys. 

**What were you trying to accomplish?**
Just trying to get some lambda logs with custom keys, which ideally would be cleaned up after each warm call, such that those custom key values do not trickle to the next invocation.

## Expected Behavior
Using the clear_state argument should not remove the default structured keys. Those should remain fixed. Only custom keys should be removed upon new invocation.

## Current Behavior
Currently, default structured keys are being removed from the get-go.

## Steps to Reproduce (for bugs)
First, this:
```python
from aws_lambda_powertools import logging
from aws_lambda_powertools.utilities.typing import LambdaContext


logger = logging.Logger()

@logger.inject_lambda_context(clear_state=False)
def lambda_handler(event: dict, context: LambdaContext):
    logger.info("HEREEE")
```
Output:
```json
{
    "level": "INFO",
    "location": "lambda_handler:21",
    "message": "HEREEE",
    "timestamp": "2022-03-29 17:53:56,985+0000",
    "service": "service_undefined",
    "cold_start": true,
    "function_name": "alex-test-layers",
    "function_memory_size": "1024",
    "function_arn": "arn:aws:lambda:us-west-2:111111111111:function:alex-test-layers",
    "function_request_id": "a1453466-2abe-4a55-ad9e-640e745f4133",
    "xray_trace_id": "1-624347b4-589b3226782e49797249edb1"
}
```
Now this `clear_state=True`
```python
from aws_lambda_powertools import logging
from aws_lambda_powertools.utilities.typing import LambdaContext


logger = logging.Logger()

@logger.inject_lambda_context(clear_state=True)
def lambda_handler(event: dict, context: LambdaContext):
    logger.info("HEREEE")
```
Output:
```json
{
    "message": "HEREEE",
    "service": "service_undefined",
    "cold_start": true,
    "function_name": "alex-test-layers",
    "function_memory_size": "1024",
    "function_arn": "arn:aws:lambda:us-west-2:111111111111:function:alex-test-layers",
    "function_request_id": "e3cf7717-88ea-43dc-b80c-57754bc6b8c9",
    "xray_trace_id": "1-62435f24-54e5827e68d838640494dca4"
}
```

## Environment

* **Powertools version used**: aws-lambda-powertools==1.25.5
* **Packaging format (Layers, PyPi):** Layers
* **AWS Lambda function runtime:** Python 3.8
* **Debugging logs**: Above.

**Comment by heitorlessa** [comment]
Thank you @alexanderluiscampino for filing a high quality bug reporting -- We'll look into this week and release a patch release once as soon as we can.

Thank you

**Comment by heitorlessa** [comment]
Reproduced and found the regression was introduced in 1.25.3 when fixing a custom formatter. Tests were insufficient for clear_state=True hence we didn't catch it -- working on better tests and will make a release by EOD the latest.

**Comment by heitorlessa** [comment]
Thanks to your super high quality bug report we managed to reproduce and improved tests as part of the fix - the latest version 1.25.6 has this fix now. Lambda Layers upcoming version **16** will take a few hours to be available in multiple AWS commercial regions.

**Comment by heitorlessa** [comment]
Hey @eliasbrange! For bugs we can reproduce, we welcome the PRs ;) 

This seemed like an easy win for custom for matters at first, but it continues to cause edge cases that our tests were not covering clear_state well enough - my apologies.

I'm with customers until Thursday evening, but if you could make a bug report and a PR I'll gladly accept it (and enrich if necessary)

Thank you 🙏

**Comment by eliasbrange** [comment]
@heitorlessa PR is up and running!

**Comment by heitorlessa** [comment]
Just merged - I plan to have a patch release out today with this fix.

**Comment by eliasbrange** [comment]
Sweet, thanks for the quick review!

**Comment by heitorlessa** [comment]
Layers version 17 should be out in 2h max across all regions we support
