### ISSUE TITLE
Code using the event_source decorator fails pyright checks

### ISSUE THREAD

**Issue by ericbn** [awslabs/aws-lambda-powertools-python#1085]
**What were you trying to accomplish?**
Check code that uses aws_lambda_powertools using pyright.

## Expected Behavior

Checking code that correctly uses aws_lambda_powertools should be successful.

## Current Behavior

Checking code that uses the `event_source` decorator as documented fails with:
```
lambda_function.py
  lambda_function.py:6:15 - error: No parameter named "data_class" (reportGeneralTypeIssues)
  lambda_function.py:6:2 - error: Argument missing for parameter "context" (reportGeneralTypeIssues)
```

Here's the code used:
```python
import json

from aws_lambda_powertools.utilities.data_classes import event_source, APIGatewayProxyEventV2


@event_source(data_class=APIGatewayProxyEventV2)
def lambda_handler(event: APIGatewayProxyEventV2, context):
    return {
        "statusCode": 200,
        "body": json.dumps({"message": f"hello {event.json_body['name']}!"})
    }
```

Other types might be affected too. Here's the output when pyright with the special option "--verifytypes" is called on aws_lambda_powertools:

```
Symbols exported by "aws_lambda_powertools": 2095
  With known type: 1733
  With ambiguous type: 77
  With unknown type: 285

Type completeness score: 82.7%
```
This means about 17% of the symbols exposed are not properly annotated.

See [this comment here](https://github.com/microsoft/pyright/issues/3265#issuecomment-1081102819).

## Possible Solution

Complete the type annotations.

## Steps to Reproduce (for bugs)

```
❯ python3 -m venv venv
❯ . venv/bin/activate
❯ pip install aws_lambda_powertools pyright
❯ mkdir src
❯ >>! src/lambda_function.py <<\EOF
import json

from aws_lambda_powertools.utilities.data_classes import event_source, APIGatewayProxyEventV2


@event_source(data_class=APIGatewayProxyEventV2)
def lambda_handler(event: APIGatewayProxyEventV2, context):
    return {
        "statusCode": 200,
        "body": json.dumps({"message": f"hello {event.json_body['name']}!"})
    }
EOF
❯ >>! pyproject.toml <<\EOF
[tool.pyright]
pythonPlatform = "Linux"
pythonVersion = "3.9"
stubPath = ""
executionEnvironments = [
    {root = "src"},
]
EOF
❯ pyright
No configuration file found.
pyproject.toml file found at /tmp/test.
Loading pyproject.toml file at /tmp/test/pyproject.toml
No include entries specified; assuming /tmp/test
Auto-excluding **/node_modules
Auto-excluding **/__pycache__
Auto-excluding **/.*
Searching for source files
Auto-excluding /tmp/test/venv
Found 1 source file
/tmp/test/src/lambda_function.py
  /tmp/test/src/lambda_function.py:6:15 - error: No parameter named "data_class" (reportGeneralTypeIssues)
  /tmp/test/src/lambda_function.py:6:2 - error: Argument missing for parameter "context" (reportGeneralTypeIssues)
2 errors, 0 warnings, 0 informations
Completed in 0.767sec
```

## Environment

* **Powertools version used**: 1.25.5
* **Packaging format (Layers, PyPi)**: N/A
* **AWS Lambda function runtime:** N/A
* **Debugging logs**
N/A

**Comment by michaelbrewer** [comment]
Related to https://github.com/awslabs/aws-lambda-powertools-python/issues/1060

**Comment by heitorlessa** [comment]
Hi @ericbn, thank you for opening your first issue and flagging a type def to us!

As of now, we don't support Pyright but Mypy (non-strict mode) - we had mixed results last year that. When trying so, we found it quite difficult to keep the code maintainable and ensure 100% accuracy due to heavy use of metaprogramming (plus supporting older versions of Python that don't yet have certain mechanisms).

I'm changing the label from bug to static_typing. We welcome any targeted solution to this specific type def that also works for 3.6+ as well as Mypy. We had tried some solutions in #1060 but wasn't enough to cover different Python versions and satisfy either Mypy in strict mode as well as Pyright - We do want to revisit it in the future, tho.

Thank you!

**Comment by heitorlessa** [comment]
Forgot to also thank you for checking upstream. That comment was helpful to understand how much Pyright progressed since we tried early last year, and how we could use that info to improve our existing type def in the future.

**Comment by heitorlessa** [comment]
Checking this a year later... apparently Pyright is happy with us now. Nevertheless, I'll go try type the decorator factory as this will help us towards mypy strict which is related. 

```python
> pyright --verbose
No configuration file found.
pyproject.toml file found at /private/tmp/pyright-test.
Loading pyproject.toml file at /private/tmp/pyright-test/pyproject.toml
No include entries specified; assuming /private/tmp/pyright-test
Auto-excluding **/node_modules
Auto-excluding **/__pycache__
Auto-excluding **/.*
Search paths for /private/tmp/pyright-test/src
  /Users/lessa/.cache/pyright-python/1.1.304/node_modules/pyright/dist/typeshed-fallback/stdlib
  /private/tmp/pyright-test/src
  /private/tmp/pyright-test
  /Users/lessa/.cache/pyright-python/1.1.304/node_modules/pyright/dist/typeshed-fallback/stubs/...
  /Users/lessa/.pyenv/versions/3.10.11/lib/python3.10
  /Users/lessa/.pyenv/versions/3.10.11/lib/python3.10/lib-dynload
  /Users/lessa/.pyenv/versions/3.10.11/lib/python3.10/site-packages
Searching for source files
Found 1 source file
pyright 1.1.304
0 errors, 0 warnings, 0 informations 
Completed in 0.485sec
```

**pyproject.toml**

```toml
[tool.pyright]
pythonPlatform = "Linux"
pythonVersion = "3.9"
stubPath = ""
executionEnvironments = [
{root = "src"},
]
```

**src/lambda_function.py**

```python
import json

from aws_lambda_powertools.utilities.data_classes import event_source, APIGatewayProxyEventV2


@event_source(data_class=APIGatewayProxyEventV2)
def lambda_handler(event: APIGatewayProxyEventV2, context):
    return {
        "statusCode": 200,
        "body": json.dumps({"message": f"hello {event.json_body['name']}!"})
    }
```

**Comment by heitorlessa** [comment]
Closing as narrowing types further hits a bug in ParamSpec when using Concatenate in a decorator factory logic: https://github.com/python/mypy/issues/12595.

As of now, both mypy and pyright are working (please let us know otherwise).
