### ISSUE TITLE
sam build instruction to build examples from the powertools ' tutorial fails

### ISSUE THREAD

**Issue by iapostol-69** [awslabs/aws-lambda-powertools-python#1109]
**Runtime:** 
Python (maybe in other runtimes too - not tested)

**Is your feature request related to a problem? Please describe**
When I tried to run the powertools examples on my Windows 10 pc, the instruction *sam build* would fail with some obscure message. As it turns out, this is a 'known issue' with sam - unrelated to powertools -, you need to run *sam build --use-container* and the build will succeed

**Describe the solution you'd like**
I suggest that the potential problem and related solution are documented in the Tutorial

**Describe alternatives you've considered**
Clearly this should be fixed by the *sam cli* team, however until this is done users have to be informed of this possible issue

**If you provide guidance, is this something you'd like to contribute?** Sure

**Additional context**

**Comment by heitorlessa** [comment]
hey @iapostol-69, could you give that a try again with the latest SAM CLI, please? We collaborated with SAM CLI team to address it at the core, though we weren't 100% certain on Windows 10 (it did fix for all Linux distro and Mac [intel, ARM]).

If it's not solved, we can update our docs while we work with the SAM CLI team on bootstrapping a Windows box so we can fix it permanently.

Thank you!

**Comment by heitorlessa** [comment]
Closing due to the lack of response. Please feel free to reopen if that still persists.
