### ISSUE TITLE
Bug: no clarity on when pull requests are allow

### ISSUE THREAD

**Issue by michaelbrewer** [awslabs/aws-lambda-powertools-python#1110]
### Expected Behaviour

In the contributing guide a clear call out of when a pull request can be make. 

### Current Behaviour

Pull requests are not closed citing the contributing guide

### Code snippet

```python
NA
```

### Possible Solution

Clarify that, before a pull request can be made:

1. Check if any existing issue exists
2. Create new issue
3. What for the issue to be approved
4. Then make the pull request if you can

### Steps to Reproduce

1. Create a Github issue 
2. Create a fix for it as a Pull Request 

### AWS Lambda Powertools for Python version

latest

### AWS Lambda function runtime

3.6

### Packaging format used

Lambda Layers, PyPi

### Debugging logs

```python
NA
```

**Comment by sthuber90** [comment]
The contribution guidelines mention it. Also, it's stated that contribution to features is on hold until July 2022. However, I'm glad we got this small bug resolved so quickly and I just prepared code on my end because it was so present in my head 😅

**Comment by sthulb** [comment]
@sthuber90 is correct. The contribution guidelines state when a PR is welcome.

**Comment by michaelbrewer** [comment]
So no pull requests even if there is an issue and you run into production issues?

**Comment by michaelbrewer** [comment]
Possible changing it too "We are stopping all external contributions unless we request for a pull request until end of July 2022."?

@sthuber90 yes that was awesome to see and glad it worked out

**Comment by michaelbrewer** [comment]
ah i just realized i tagged the wrong person. oh boy. sorry `sthuber90`
