### ISSUE TITLE
Bug: JMESPath semantic version mismatch with boto3

### ISSUE THREAD

**Issue by corey-cole** [awslabs/aws-lambda-powertools-python#1138]
### Expected Behaviour

I should be able to install an unpinned version of boto3 and aws-lambda-powertools without a dependency error

### Current Behaviour

Installing boto3 and aws-lambda-powertools==1.25.7 results in the following error message during installation.

```
aws-lambda-powertools 1.25.7 requires jmespath<0.11.0,>=0.10.0, but you'll have jmespath 1.0.0 which is incompatible.
```

### Code snippet

```python
N/A
```

### Possible Solution

boto3 added support for JMESPath 1.0 in this PR:  https://github.com/boto/boto3/pull/3189.  Didn't appear to require any code changes, just opening up the allowable versions to something less than 2.0

### Steps to Reproduce

cat requirements.txt
wheel
boto3
aws-lambda-powertools[pydantic]==1.25.7

pip install -r requirements.txt

### AWS Lambda Powertools for Python version

1.25.7

### AWS Lambda function runtime

3.9

### Packaging format used

PyPi

**Comment by michaelbrewer** [comment]
@corey-cole  works for me using Python 3.9.12 and using the same requirements file


<img width="1284" alt="Screen Shot 2022-04-20 at 6 06 42 PM" src="https://user-images.githubusercontent.com/5442469/164351388-f65b072f-2738-4471-ba23-4882eb20763e.png">

**Comment by michaelbrewer** [comment]
Finally it looks like [jmespath.py](https://github.com/jmespath/jmespath.py) has dropped support for Python 3.6:

- https://github.com/jmespath/jmespath.py/compare/0.10.0...1.0.0

<img width="2026" alt="Screen Shot 2022-04-20 at 6 16 40 PM" src="https://user-images.githubusercontent.com/5442469/164352372-594b9e70-0f18-4f54-a717-f7f882fa8595.png">

**Comment by michaelbrewer** [comment]
@corey-cole a possible solution can be made ie: https://github.com/awslabs/aws-lambda-powertools-python/pull/1139

**Comment by heitorlessa** [comment]
Thanks for reporting this issue @corey-cole and thanks for sending a quick dep range fix @michaelbrewer.

We were conservative in adding `jmespath` as an explicit dependency after exposing custom JMESPath functions, instead of relying on boto3 vending jmespath. I took a look at boto and they initially added jmespath 1.0 only, then corrected their markers in a subsequent release as it broke to <3.6 etc. Looking at `jmespath` 1.0 it's only dropping 3.6.

I'll give them a ping as this will also block Lambda runtime to upgrade the runtime dependency, bringing another array of issues.

Merging Michael's PR and making a release ahead of flagging this with the Lambda and the SDK team.

**Comment by heitorlessa** [comment]
Reverting Michael's PR by removing the Python 3.6 marker (tiny change), and publishing 1.25.9 shortly

**Comment by heitorlessa** [comment]
1.25.9 is now out. @corey-cole @michaelbrewer  could you give that a try please?

**Comment by michaelbrewer** [comment]
Looking forward to seeing python 3.6 support getting dropped or these integration tests safe guarding against this. I will test  locally with the above use case.

**Comment by michaelbrewer** [comment]
@heitorlessa  works for me with the following test case:

`requirements.txt` :

```
boto3
jmespath==1.0.0
aws-lambda-powertools==1.25.9
```

```shell
(.venv) ➜  xx pip install -r requirements.txt    
Collecting boto3
  Using cached boto3-1.21.44-py3-none-any.whl (132 kB)
Collecting jmespath==1.0.0
  Using cached jmespath-1.0.0-py3-none-any.whl (23 kB)
Collecting aws-lambda-powertools==1.25.9
  Using cached aws_lambda_powertools-1.25.9-py3-none-any.whl (171 kB)
Collecting fastjsonschema<3.0.0,>=2.14.5
  Using cached fastjsonschema-2.15.3-py3-none-any.whl (22 kB)
Collecting aws-xray-sdk<3.0.0,>=2.8.0
  Using cached aws_xray_sdk-2.9.0-py2.py3-none-any.whl (98 kB)
Collecting s3transfer<0.6.0,>=0.5.0
  Using cached s3transfer-0.5.2-py3-none-any.whl (79 kB)
Collecting botocore<1.25.0,>=1.24.44
  Using cached botocore-1.24.44-py3-none-any.whl (8.7 MB)
Collecting wrapt
  Using cached wrapt-1.14.0-cp39-cp39-macosx_11_0_arm64.whl (35 kB)
Collecting future
  Using cached future-0.18.2-py3-none-any.whl
Collecting urllib3<1.27,>=1.25.4
  Using cached urllib3-1.26.9-py2.py3-none-any.whl (138 kB)
Collecting python-dateutil<3.0.0,>=2.1
  Using cached python_dateutil-2.8.2-py2.py3-none-any.whl (247 kB)
Collecting six>=1.5
  Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
Installing collected packages: fastjsonschema, wrapt, urllib3, six, jmespath, future, python-dateutil, botocore, s3transfer, aws-xray-sdk, boto3, aws-lambda-powertools
Successfully installed aws-lambda-powertools-1.25.9 aws-xray-sdk-2.9.0 boto3-1.21.44 botocore-1.24.44 fastjsonschema-2.15.3 future-0.18.2 jmespath-1.0.0 python-dateutil-2.8.2 s3transfer-0.5.2 six-1.16.0 urllib3-1.26.9 wrapt-1.14.0
(.venv) ➜  xx pip list
Package               Version
--------------------- -------
aws-lambda-powertools 1.25.9
aws-xray-sdk          2.9.0
boto3                 1.21.44
botocore              1.24.44
fastjsonschema        2.15.3
future                0.18.2
jmespath              1.0.0
pip                   22.0.4
python-dateutil       2.8.2
s3transfer            0.5.2
setuptools            60.10.0
six                   1.16.0
urllib3               1.26.9
wrapt                 1.14.0
```

**Comment by michaelbrewer** [comment]
@heitorlessa FYI, as a related issue on the poetry docs :( 

https://github.com/python-poetry/poetry/issues/5473

**Comment by heitorlessa** [comment]
no problem at all - I suspected it was something with Poetry; glad it's solved.

Once we have room to design a v2, we will highly likely have to move away from Poetry, as I couldn't see (yet) implicit namespace packages support there - but that's a long road from here. 

> NOTE: This is the tiny project I used in the past to automate poetry to setup.py: https://pypi.org/project/poetry2setup/

Thanks a lot everyone!

**Comment by matschaffer-roblox** [comment]
Incase anyone else ends up here, I naively added `jmespath` to my local requirements after running into this error:

```
 ModuleNotFoundError: No module named 'jmespath'
```

This led to the boto version mismatch shown in this github issue. If you did the same thing, remove the `jmespath` entry you added and check https://awslabs.github.io/aws-lambda-powertools-python/ for the correct way to add aws-lambda-powertools to your project.
