### ISSUE TITLE
Feature request: Add integration tests

### ISSUE THREAD

**Issue by michaelbrewer** [awslabs/aws-lambda-powertools-python#1140]
### Use case

Some releases of AWS Lambda Powertools have run into runtime regression. So without integration tests, customers of this library would have to run their own integration tests

### Solution/User Experience

AWS Lambda Powertools would include a series of integration tests for the supported runtimes. 

See how this was resolved in the typescript version https://github.com/awslabs/aws-lambda-powertools-typescript/issues/418

Or how AWS CDK runs full suite of integration tests for every release and PR

### Alternative solutions

Each usage of AWS Lambda Powertools should also include integration tests. Especially for features that are mocked locally like idempotency.

### Acknowledgment

- [X] This feature request meets [Lambda Powertools Tenets](https://awslabs.github.io/aws-lambda-powertools-python/latest/#tenets)
- [X] Should this be considered in other Lambda Powertools languages? i.e. [Java](https://github.com/awslabs/aws-lambda-powertools-java/), [TypeScript](https://github.com/awslabs/aws-lambda-powertools-typescript/)

**Comment by heitorlessa** [comment]
Closing as @mploski (maintainer) is already working on that as part of our operational readiness review.

**Comment by michaelbrewer** [comment]
It's there a tracking issue for this ? Michael brewer (contributor & customer)
