### ISSUE TITLE
Remove AWS SDK from Lambda Layer to reduce package size by 90.5%

### ISSUE THREAD

**Issue by mccauleyp** [awslabs/aws-lambda-powertools-python#1164]
**Is your feature request related to a problem? Please describe.**
In trying to upgrade to v1.22.0, I ran into the deployment error `Layers consume more than the available size of 262144000 bytes`. This is for a Lambda function that uses both the Lambda Powertools Layer and the latest [AWS Data Wrangler Layer](https://serverlessrepo.aws.amazon.com/applications/us-east-1/336392948345/aws-data-wrangler-layer-py3-8). I think the new Powertools layer is only a little larger than the previous version but enough to tip over the limit when combined with the AWS Data Wrangler layer.  

I pulled down the Powertools zip contents following the "[Get the Layer .zip contents](https://awslabs.github.io/aws-lambda-powertools-python/latest/#lambda-layer)" instructions, and it looks like most of the size (~70 MB unzipped)  comes from botocore (~63 MB). 

Is it necessary to include botocore and boto3 in the layer's zip file given that these are available by default in the Lambda runtime? If not, it would be helpful to remove them from the pre-built layer to help avoid hitting the overall size limit. 

**Describe the solution you'd like**
Remove botocore and boto3 from the Lambda layer zip archive. 

**Describe alternatives you've considered**
I could build my own layer that doesn't include botocore and boto3. I tried this already by downloading the existing layer .zip, deleting those packages, zipping it back up and deploying it. That seems to work in my application, but it would be great if creating my own layer wasn't necessary. 

**Additional context**
You could replicate the error by trying to deploy a function with both the pre-built AWS Lambda Powertools and AWS Data Wrangler layers included. The code size coming from my application is negligible compared to the layer sizes. 

P.S. Thanks for the great resource! This has been a very helpful package for me and my team :)

**Comment by heitorlessa** [comment]
Update: @am29d is working on migrating our internal Lambda Layers pipeline to CodePipeline in a Powertools AWS account. Once that's done (~H2), we should be able to expand to more AWS regions - that said, GovCloud is a special region and might take longer for us to get approval to do so.

In parallel, @mploski is working on our E2E test framework. Both will give us the confidence we need to remove Boto at runtime.

You can follow progress here: [github.com/orgs/awslabs/projects/51/views/11](https://github.com/orgs/awslabs/projects/51/views/11)

**Comment by heitorlessa** [comment]
We found a solution! @mploski will be working on some rigorous tests to ensure we don't break anyone when including a ~500K botocore in the final PyPi asset and Lambda Layer, but I'm super super excited we've made progress here with the help from the AWS Python SDK team <3

**Comment by heitorlessa** [comment]
We're enabling E2E at the merge level and will be able to test this more confidently as we increase coverage. Meantime, @mploski is finishing another project in his day-to-day role and will resume exploratory tests on the new squashed boto to see whether we accidentally cause any conflict with the Lambda's boto runtime dep

**Comment by rubenfonseca** [comment]
We ran some [load testing to measure the impact of the layer size in the coldstart](https://github.com/awslabs/cdk-aws-lambda-powertools-layer/pull/10). Findings:

**1/** Layer size doesn't seems to have a meaningful impact on the coldstart time (at least when the layer doubles in size and it's < 5M)
**2/** Using native compiled code ([cython](https://pypi.org/project/Cython/)) reduces coldstart time (even though the layer size is bigger)

Based on this we're launching the v2 layer with [compiled native code for each architecture](https://github.com/awslabs/cdk-aws-lambda-powertools-layer/blob/main/layer/Python/Dockerfile#L29-L32).

Current Lambda Layer size: 2.6MB

**Comment by heitorlessa** [comment]
@mccauleyp it took us a while but you'll be please to see V2 results this month ;) we now have E2E framework in place to detect regressions in case Lambda runtime changes a dependency ahead of a release.

Thank you for sticking with us all this time!

**Comment by rubenfonseca** [comment]
For reference here are the benchmark results we did to measure cold start impact of loading the different libraries:

arm64, 128mb

Baseline (empty handler, no powertools):
-------------------------------------------------------------
| coldStart | count |   p50   |   p90   |   p99   |   max   |
|-----------|-------|---------|---------|---------|---------|
| 1         | 16    | 114.55  | 133.96  | 141.66  | 141.66  |
-------------------------------------------------------------

Just logger:
------------------------------------------------------------
| coldStart | count |   p50   |   p90   |  p99   |   max   |
|-----------|-------|---------|---------|--------|---------|
| 1         | 10    | 144.12  | 158.07  | 161.87 | 161.87  |
------------------------------------------------------------

Just parser:
-------------------------------------------------------------
| coldStart | count |   p50   |   p90   |   p99   |   max   |
|-----------|-------|---------|---------|---------|---------|
| 1         | 10    | 443.89  | 465.09  | 471.02  | 471.02  |
-------------------------------------------------------------

Logger + Parser:
------------------------------------------------------------
| coldStart | count |   p50   |  p90   |   p99   |   max   |
|-----------|-------|---------|--------|---------|---------|
| 1         | 10    | 449.56  | 468.42 | 469.58  | 469.58  |
------------------------------------------------------------

Just tracer:
-------------------------------------------------------------------
| coldStart | count |    p50    |    p90    |    p99    |   max   |
|-----------|-------|-----------|-----------|-----------|---------|
| 1         | 15    | 293.8763  | 309.8637  | 326.7208  | 330.03  |
-------------------------------------------------------------------

**Comment by heitorlessa** [comment]
Changing it to Coming soon as we expect to launch V2 with these optimizations by EOW.

Updates: https://github.com/awslabs/aws-lambda-powertools-python/issues/1459#issuecomment-1283807471
