### ISSUE TITLE
Appending values to existing entries via extra to structure_logs(append=True) entries

### ISSUE THREAD

**Issue by bml1g12** [awslabs/aws-lambda-powertools-python#1176]
**Is your feature request related to a problem? Please describe.**
After having set an attribute globally:

e.g.
```
LOGGER.structure_logs(append=True,
                        context={"device_name": device_name})
```

I would like to log additional items to the context attribute e.g. 
```
LOGGER.info("hello world", 
            extra={"context": {"device_location": "UK"}})
```

**Describe the solution you'd like**

LOGGER.info("hello world")  would include a JSON payload with both device_location and device_name in the above example whereas currently it overwrites the context attribute with the new entry,  

**Describe alternatives you've considered**

I could do:
```
LOGGER.info("hello world", 
            extra={"context": {"device_name": device_name, 
                                        "device_location": "UK"}})
```
But if the device_name is not globally available throughout the code base, it is not ideal.

**Comment by heitorlessa** [comment]
Closing as we haven't had an update ever since. Please please do reopen if you have answers or thoughts to those questions.

Thank you!!
