### ISSUE TITLE
Support Python native dataclass APIs in Event Source Data Classes utility

### ISSUE THREAD

**Issue by LouisAmon** [awslabs/aws-lambda-powertools-python#1177]
**What were you initially searching for in the docs?**

I'm using the @event_source decorator and I was looking for a way to print my event in my Cloudwatch logs.

When I simply `print(event)`, I just get a class instance, but I want to be able to see the actual keys and values :)

Being used to working with Python dataclasses, I naturally tried [asdict](https://docs.python.org/3/library/dataclasses.html#dataclasses.asdict):
```python
print(event.asdict())
```

Or even...
```python
import dataclasses

dataclasses.asdict(event)
```
...and I was very surprised by the result:
```
asdict() should be called on dataclass instances
```
**Is this related to an existing part of the documentation? Please share a link**

https://awslabs.github.io/aws-lambda-powertools-python/latest/utilities/data_classes/

**Describe how we could make it clearer**

Dataclasses are meant to be a Pythonic way to define a data model.

If you define your own class (`DictWrapper` in your case) which inherits from nothing then all the APIs and principles behind dataclasses are lost.

Dataclasses are used in libraries such as sqlalchemy or strawberry to define a unified way to communicate with a database or build a GraphQL API... dataclasses provides unity between all these, so why not AWS Lambda ? :)

**If you have a proposed update, please share it here**

I think we should either revamp the code to actually define proper data classes, or stop calling it as such : it's just confusing.

What do you think ?

**Comment by heitorlessa** [comment]
Closing as we will only be able to rename it completely in v3. Data classes confirmed to be too slow. We're following Pydantic v2 closely for a faster and closer API model. As there isn't a date, `raw_event` property does the job.
