### ISSUE TITLE
Allow get_parameters to return a tree of parameters instead of Dict<str,str> with flatten keys

### ISSUE THREAD

**Issue by xpayn** [awslabs/aws-lambda-powertools-python#1182]
When using get_parameters to get a parameter tree, it returns keys looking like "foo/bar", which is not convenient.

It would nice if get_parameters allow key parsing to restore the tree by setting an option to True (ie. `tree=True`)

Right now we have to do that by hand, or construct the key by joining with '/'

**Comment by heitorlessa** [comment]
This week, we launched [`get_parameters_by_name`](https://awslabs.github.io/aws-lambda-powertools-python/2.2.0/utilities/parameters/#fetching-parameters) which returns a Dict where the key is the parameters name along with its value.

I should've asked for an example output earlier, but hopefully this might address the original ask IIRC. Please re-open if that's not what you meant along with an example output. 

Thank you for the prolonged patience on this!

```python
from typing import Any

from aws_lambda_powertools.utilities import get_parameters_by_name

parameters = {
  "/develop/service/commons/telemetry/config": {"max_age": 300, "transform": "json"},
  "/no_cache_param": {"max_age": 0},
  # inherit default values
  "/develop/service/payment/api/capture/url": {},
}

def handler(event, context):
    # This returns a dict with the parameter name as key
    response: dict[str, Any] = parameters.get_parameters_by_name(parameters=parameters, max_age=60)
    for parameter, value in response.items():
        print(f"{parameter}: {value}")
       # {
       #     "/develop/service/commons/telemetry/config": <value>,
       #     "/no_cache_param": <value>,
       #     "/develop/service/payment/api/capture/url": <value>
       # }
```
