### ISSUE TITLE
Feature request: Support cookies in Lambda function response for format 2.0

### ISSUE THREAD

**Issue by eflopez** [awslabs/aws-lambda-powertools-python#1192]
### Use case

I am using the `Router` class to setup some resolvers for use with `APIGatewayHttpResolver`, and I would like to be able to set cookies in my customised `Response` object, but this is not currently possible.

According to the [APIGateway response documentation](https://docs.aws.amazon.com/apigateway/latest/developerguide/http-api-develop-integrations-lambda.html), the format for this is 
```json
{
    "cookies" : ["cookie1", "cookie2"],
    "isBase64Encoded": true|false,
    "statusCode": httpStatusCode,
    "headers": { "headername": "headervalue", ... },
    "body": "Hello from Lambda!"
}
```

### Solution/User Experience

Would be great to be able to just be able to do something like 
```python
    return Response(
        status_code=418,
        cookies=["cookie1", "cookie2"],
        content_type="application/json",
        body=payload,
        headers=custom_headers,
    )
```

### Acknowledgment

- [X] This feature request meets [Lambda Powertools Tenets](https://awslabs.github.io/aws-lambda-powertools-python/latest/#tenets)
- [ ] Should this be considered in other Lambda Powertools languages? i.e. [Java](https://github.com/awslabs/aws-lambda-powertools-java/), [TypeScript](https://github.com/awslabs/aws-lambda-powertools-typescript/)

**Comment by michaelbrewer** [comment]
Good idea! There are more cumbersome way, but format 2.0 does make it easier. Once this has been "approved" / "triaged", it should be an easy addition to the API GW handler.

**Comment by michaelbrewer** [comment]
@eflopez For discussion purpose i created a PR #1196

This will also allow for a more convenient method to set cookies for ALB, Http and Rest apis.

**Comment by heitorlessa** [comment]
Removing `help wanted` as @rubenfonseca will start working on this next week.

**Comment by heitorlessa** [comment]
Closing as we're wrap to launch V2
