### ISSUE TITLE
Bug: BaseBatchProcessingError.child_exceptions doesn't handle None case

### ISSUE THREAD

**Issue by peterschutt** [awslabs/aws-lambda-powertools-python#1203]
### Expected Behaviour

This is a bit of a nitpick but something I noticed on my travels...

https://github.com/awslabs/aws-lambda-powertools-python/blob/1ca74d36af7165f41dc2d6b39a8f36caacd69677/aws_lambda_powertools/utilities/batch/exceptions.py#L11-L24

`child_exceptions` parameter is typed `Optional[List[ExceptionInfo]]` but the `None` case isn't handled anywhere before iteration over the attribute occurs in `format_exceptions()` method.

### Current Behaviour

Instantiating the exception and calling `format_exceptions()` without providing a list for the `child_exceptions` param will raise an exception.

### Code snippet

```python
from aws_lambda_powertools.utilities.batch.exceptions import BaseBatchProcessingError

err = BaseBatchProcessingError(msg="something")  # types ok
err.format_exceptions("parent exception string")
```

### Possible Solution

Most likely just make sure attrib is always a list without having to change the signature of the class.

```python
class BaseBatchProcessingError(Exception):
    def __init__(self, msg="", child_exceptions: Optional[List[ExceptionInfo]] = None):
        ...
        self.child_exceptions = child_exceptions or []
```

### Steps to Reproduce

See code snippet above.

### AWS Lambda Powertools for Python version

latest

### AWS Lambda function runtime

3.9

### Packaging format used

PyPi

**Comment by michaelbrewer** [comment]
More likely to fail before this, so maybe `child_exceptions` should not be optional.

```python3
            raise SQSBatchProcessingError(
                msg=f"Not all records processed successfully. {len(self.exceptions)} individual errors logged "
                f"separately below.",
                child_exceptions=self.exceptions,
            )
```

**Comment by michaelbrewer** [comment]
@peterschutt if this is accepted as an 'issue', i made a PR (https://github.com/awslabs/aws-lambda-powertools-python/pull/1205) based on your fix.

**Comment by michaelbrewer** [comment]
I fully understand the risk of putting my unpaid time into this.

In this case, this is a bug and not a feature, so out of respect for my fellow Powertools users i submitted a fix PR for the one offending line 

_Feel free to drop these PRs or ignore until August 2022_

**Comment by heitorlessa** [comment]
hey @peterschutt thank you for flagging another piece we can improve :pray:. We'll look into it after some major changes in exposing the roadmap, list of maintainers, and our new end-to-end testing framework (internal, but we might explore ways to expose to customers).

If you however ran into an issue with Batch without explicitly calling `format_exceptions`, please do let us know and either of the maintainers[1] can prioritize it ASAP. 

From memory, the `Optional` was a leftover type hint after several refactoring attempts (legacy SQS -> new SQS), and while we're [passing an actual exception](https://github.com/awslabs/aws-lambda-powertools-python/blob/develop/aws_lambda_powertools/utilities/batch/base.py#L151:L151) as part of our [failure_handler mechanics](https://github.com/awslabs/aws-lambda-powertools-python/blob/develop/aws_lambda_powertools/utilities/batch/sqs.py#L117:L117).... we can surely do better - besides this, I just spotted a few other areas for internal improvements so we can handle them altogether.

[1] Currrent maintainers: @am29d @mploski @sthulb @heitorlessa. 

Thank you!

**Comment by michaelbrewer** [comment]
At Fiserv, our developers run into this kind of misleading typing and error handling within the library all of the time. Hopefully some stability comes through.

**Comment by michaelbrewer** [comment]
A typing based via would actually have to be a breaking change:

As `msg` becomes a required parameter to allow for `child_exceptions` to be an none-optional list

patch below:

```diff
diff --git a/aws_lambda_powertools/utilities/batch/exceptions.py b/aws_lambda_powertools/utilities/batch/exceptions.py
index d90c25f1..f33f6aef 100644
--- a/aws_lambda_powertools/utilities/batch/exceptions.py
+++ b/aws_lambda_powertools/utilities/batch/exceptions.py
@@ -9,7 +9,7 @@ ExceptionInfo = Tuple[Optional[Type[BaseException]], Optional[BaseException], Op


 class BaseBatchProcessingError(Exception):
-    def __init__(self, msg="", child_exceptions: Optional[List[ExceptionInfo]] = None):
+    def __init__(self, msg: str, child_exceptions: List[ExceptionInfo]):
         super().__init__(msg)
         self.msg = msg
         self.child_exceptions = child_exceptions
@@ -27,7 +27,7 @@ class BaseBatchProcessingError(Exception):
 class SQSBatchProcessingError(BaseBatchProcessingError):
     """When at least one message within a batch could not be processed"""

-    def __init__(self, msg="", child_exceptions: Optional[List[ExceptionInfo]] = None):
+    def __init__(self, msg: str, child_exceptions: List[ExceptionInfo]):
         super().__init__(msg, child_exceptions)

     # Overriding this method so we can output all child exception tracebacks when we raise this exception to prevent
@@ -40,7 +40,7 @@ class SQSBatchProcessingError(BaseBatchProcessingError):
 class BatchProcessingError(BaseBatchProcessingError):
     """When all batch records failed to be processed"""

-    def __init__(self, msg="", child_exceptions: Optional[List[ExceptionInfo]] = None):
+    def __init__(self, msg: str, child_exceptions: List[ExceptionInfo]):
         super().__init__(msg, child_exceptions)

     def __str__(self):
diff --git a/tests/functional/test_utilities_batch.py b/tests/functional/test_utilities_batch.py
index a5e1e706..3db2ec20 100644
--- a/tests/functional/test_utilities_batch.py
+++ b/tests/functional/test_utilities_batch.py
@@ -908,3 +908,7 @@ def test_batch_processor_error_when_entire_batch_fails(sqs_event_factory, record

     # THEN raise BatchProcessingError
     assert "All records failed processing. " in str(e.value)
+
+
+def test_child_exceptions_is_required():
+    assert SQSBatchProcessingError(msg="required", child_exceptions=[]).format_exceptions("example") == "example\n"
```

**Comment by peterschutt** [comment]
> A typing based change would actually have to be a breaking change:

Quite possible that somewhere downstream people are relying on `self.child_exceptions` being `None` if not passed in. If you accept that, then my original suggestion of `child_exceptions or []` in `__init__()` isn't really a safe change either.

The safest change would be to address it right at the point of iteration in `format_exceptions()`, e.g., : 

```python
     def format_exceptions(self, parent_exception_str): 
         ...
         for exception in self.child_exceptions or []: 
         ...
```

... then could use warnings and deprecate the behavior of not passing in the `child_exceptions` param when instantiating the error with the aim to eventually have it all nice and tidy. 

Another point, the exception class doesn't really care that the exceptions are a list or not, just that they can be iterated over in `format_exceptions()`, so probably the constructor could be typed a little more liberally as well, `Iterable` or `Collection`.

**Comment by michaelbrewer** [comment]
If you rely on "self.child_exceptions" being None, then you are likely running into the same bug and have a runtime error. Either runtime fix makes sense. My PR is for the simplest one.

**Comment by peterschutt** [comment]
> If you rely on self.child_exceptions being None, then you are likely running into the same bug and have a runtime error.

... if the way you use the exception results in it getting serialized via `__str__()`, sure.

> My PR is for your one.

If I was lodging the same bug again I'd definitely make the change in `format_exceptions()` and not in the constructor. It maintains the existing interface, ensures the class at least honors the existing interface, and eliminates any issues arising from the surface area of the change.

In any case, the impression that I get from @sthulb and @heitorlessa is that there are some higher level things worthy of more attention at the moment. I only lodged the report because it didn't look right, not because I was directly affected by the issue in any meaningful way.

@michaelbrewer Thanks for doing the PR though, and if @sthulb or @heitorlessa want to merge it, I'll be happy to make any changes at that point.

**Comment by heitorlessa** [comment]
That’s correct Peter, we’d want to change format_exceptions instead— we’d
be more than happy to take your PR as a fix instead.

Thanks a lot!

**Comment by michaelbrewer** [comment]
PR is already up 

<img width="2551" alt="Screen Shot 2022-05-17 at 8 56 52 PM" src="https://user-images.githubusercontent.com/5442469/168954107-99334797-0c2b-4175-8dfd-ae841f26d6aa.png">

**Comment by michaelbrewer** [comment]
@peterschutt sure, i update the PR to match all of the feedback. As we use powertools in production at Fiserv, this will likely help us there too.

**Comment by peterschutt** [comment]
@heitorlessa I was curious why this wasn't already picked up by mypy - as you prob. know it is because that method itself is untyped so mypy is ignoring. Is more complete typing the sort of thing that you are working on?

I've been developing in python for quite a number of years now, we static check everything strict here and I'm using lambda and this library significantly for the first time. If I can help in any way, let me know how best to find something useful to do and I'll look to allocate a bit of time. This is a nice library, cheers!

**Comment by heitorlessa** [comment]
> @heitorlessa I was curious why this wasn't already picked up by mypy - as you prob. know it is because that method itself is untyped so mypy is ignoring. Is more complete typing the sort of thing that you are working on?
> 
> 
> 
> I've been developing in python for quite a number of years now, we static check everything strict here and I'm using lambda and this library significantly for the first time. If I can help in any way, let me know how best to find something useful to do and I'll look to allocate a bit of time. This is a nice library, cheers!

Exactly my thought too - it'd be great to hear from you on strategies to do that (strict mode) without increasing the bar to contribution too high for those inexperienced.

Mind shooting us an email and we can arrange a call? 

aws-lambda-powertools-feedback@amazon.com

Strict typing is new to us, we experimented with Cython, Mypyc, and MyPy in strict mode but far from experts. We introduced mypy last year and addresses roughly ~614 issues.

We tried mypy --strict earlier this year but had a number of false positives, areas we couldn't see solutions for, or changes that would affect performance negatively -- help here will be amazing.

**Comment by peterschutt** [comment]
Sure, I'm in UTC + 10, so I'll email when I'm in the office tomorrow.

It would be good to hear more about what you were trying to optimize with cython/mypyc. I've got a cython module in prod that I built well before typing was popular and have an upcoming opportunity to refactor it. I'm looking forward to experiment with those tools again and see how they look now.

Hopefully I can make some meaningful contribution.

**Comment by michaelbrewer** [comment]
@peterschutt @heitorlessa Pylance picks this up fine. However we can't add it as part of the project as the library still supports Python 3.6. Also MyPy has not been upgraded for a while.

<img width="1217" alt="Screen Shot 2022-05-18 at 7 06 40 AM" src="https://user-images.githubusercontent.com/5442469/169061363-cac1685e-a630-4a61-9964-062d0db855c0.png">

With the fix applied

<img width="1033" alt="Screen Shot 2022-05-18 at 7 08 24 AM" src="https://user-images.githubusercontent.com/5442469/169061439-66ea6500-a2f8-4856-8fc7-37ff1a5d9eca.png">

**Comment by michaelbrewer** [comment]
I did some work after adding the initial MyPy updates (#357 , #365 , #508 etc..), i started looking at the fixes recommended by Pylance and found that some of our code is just to make work around for MyPy 

And example being this code in `aws_lambda_powertools/utilities/parameters/appconfig.py`

<img width="1233" alt="Screen Shot 2022-05-19 at 10 52 13 AM" src="https://user-images.githubusercontent.com/5442469/169365481-0f88e3f9-54fb-4578-be17-d2cdd3b30d4f.png">

`client: Any = None` is a hack to make MyPy happy as the assignment would fail.

**Comment by peterschutt** [comment]
Hey @michaelbrewer. I haven't spent any time looking deeper at the typing yet, but appreciate the extra context. As per @heitorlessa's earlier message I've emailed to arrange a chat, just waiting on that as I don't really want to put the time into it until I understand what the objectives/constraints are and how the work would fit into their roadmap.

> However we can't add it as part of the project as the library still supports Python 3.6.

I assume this library just has to track the lambda runtime environment support, which is August 17 per [this](https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html#runtime-support-policy) (8 months after the true EOL of 3.6). Assuming that 3.7 is supported for as long after actual EOL, then we've probably got until early 2024 to support 3.7. Supporting 3.7+ with this work means we could use [typing-extensions](https://pypi.org/project/typing-extensions/) which has already dropped 3.6.

> client: Any = None is a hack to make MyPy happy as the assignment would fail.

Mypy should just assume the type based on the self assignment in `__init__()` ([ref](https://mypy.readthedocs.io/en/stable/class_basics.html#instance-and-class-attributes)). If I comment out the `client: Any = None` class variable assignment, mypy doesn't raise any issue for me (using project's mypy config). However, that is on line 63 in the develop branch, and on line 68 in your image above and the `self.client` assignment is different in the develop version to your image above, so maybe not comparing apples with apples.

I'll talk about typing all day @michaelbrewer but we seem to have jumped away from the original issue here and prob. just making unnecessary noise for the maintainers. Feel free to email me.
