### ISSUE TITLE
Docs: location parameter goes in the formatter constructor, not the logger constructor

### ISSUE THREAD

**Issue by Nogginboink** [awslabs/aws-lambda-powertools-python#1265]
### What were you searching in the docs?

Overriding log record format

### Is this related to an existing documentation section?

https://awslabs.github.io/aws-lambda-powertools-python/latest/core/logger/#overriding-log-records

### How can we improve?

```markdown
The documentation at https://awslabs.github.io/aws-lambda-powertools-python/latest/core/logger/#overriding-log-records shows that the location formatter is part of the Logger constructor. Actually, it's part of the formatter constructor. The sample code in the code box under the line "Logger allows you to either change the format or suppress the following keys altogether at the initialization: location, timestamp, level, xray_trace_id." should be updated.
```

### Acknowledgment

- [X] I understand the final update might be different from my proposed suggestion, or refused.

**Comment by heitorlessa** [comment]
Hey @Nogginboink, thanks a lot for helping us improve the documentation! `Logger` [propagates these to the formatter](https://awslabs.github.io/aws-lambda-powertools-python/latest/core/logger/#lambdapowertoolsformatter) for convenience, hence why the docs show that.

> Logger propagates a few formatting configurations to the built-in `LambdaPowertoolsFormatter` logging formatter.

Perhaps we can bring that earlier OR alternatively also show case the longer version by instantiating a Formatter and passing that via `logger_formatter` - what do you think?

**Comment by heitorlessa** [comment]
No problem. I've tested and it worked. We're also in the process of moving all doc code snippets as runnable code so we can verify them continuously - appreciate the feedback either way.

Closing.

![image](https://user-images.githubusercontent.com/3340292/176253161-49ce1fe8-79e6-4651-b336-2e22a26c7be4.png)
