### ISSUE TITLE
Bug: Unable to inject lambda context in handler with additional arguments

### ISSUE THREAD

**Issue by RonRademaker** [awslabs/aws-lambda-powertools-python#1277]
### Expected Behaviour

Possible to decorate a lambda handler with additional arguments with `@logger.inject_lambda_context`

### Current Behaviour

`TypeError: decorate() takes 2 positional arguments but 3 were given`

### Code snippet

```python
@logger.inject_lambda_context
def handler(event, context, planet, str_end="."):
    logger.info(f"Hello {planet}{str_end}")
```
```


### Possible Solution

See https://github.com/awslabs/aws-lambda-powertools-python/pull/1276

### Steps to Reproduce

See code snippet

### AWS Lambda Powertools for Python version

latest

### AWS Lambda function runtime

3.9

### Packaging format used

PyPi

### Debugging logs

_No response_

**Comment by heitorlessa** [comment]
Thank you @RonRademaker ! This should be out by EOD, aiming at releasing in the afternoon after another fix is done

**Comment by heitorlessa** [comment]
hey @RonRademaker it's now on PyPi. Lambda Layers should be out in a few hours for all AWS commercial regions. Thank you again ;-)
