### ISSUE TITLE
Docs: change module name in shared logger example to match import

### ISSUE THREAD

**Issue by peterschutt** [awslabs/aws-lambda-powertools-python#1285]
### What were you searching in the docs?

Reading example.

### Is this related to an existing documentation section?

https://github.com/awslabs/aws-lambda-powertools-python/blob/2ded8a6481836da7bdccf7a005fbe31bdf9dbd68/docs/core/logger.md?plain=1#L301-L305

### How can we improve?

```markdown
Always a great experience with this lib, thanks!
```

### Got a suggestion in mind?

Possibly this should change to `=== "logger_reuse_payment.py"` so that the tab title lines up with the module import name.

### Acknowledgment

- [X] I understand the final update might be different from my proposed suggestion, or refused.

**Comment by heitorlessa** [comment]
I'm glad you brought it up, as I thought it would've been too much of an OCD from my side :D Changing all snippets to match their filenames so it's easier for anyone to go and explore.

**Comment by heitorlessa** [comment]
Now live ;) Closing and thanks again for flagging it

![image](https://user-images.githubusercontent.com/3340292/178017181-e2a807f7-ad79-4b19-820b-fc286cafa4e8.png)
