### ISSUE TITLE
Feature request: APIGatewayRestResolver local server 

### ISSUE THREAD

**Issue by bauer-jan** [awslabs/aws-lambda-powertools-python#1288]
### Use case

When developing an API in Lambda which is interacting over boto3 with the AWS environment a local server would speed up the devlopment. I would like to be able to use uvicorn to spin up the local development server to test it with Postman. So i dont need to re-deploy my stack to aws whenever i make some changes. As a reference the FastAPI documentation can be used (see: https://fastapi.tiangolo.com/tutorial/first-steps/).

### Solution/User Experience

Option to locally use the APIGatewayRestResolver with uvicorn for running a test server.

### Acknowledgment

- [X] This feature request meets [Lambda Powertools Tenets](https://awslabs.github.io/aws-lambda-powertools-python/latest/#tenets)
- [ ] Should this be considered in other Lambda Powertools languages? i.e. [Java](https://github.com/awslabs/aws-lambda-powertools-java/), [TypeScript](https://github.com/awslabs/aws-lambda-powertools-typescript/)

**Comment by leandrodamascena** [comment]
Hello @bauerjan93. Hope you are doing well.

Well, I understand the motivation for asking for an environment where you can write and test your APIs quickly, but I don't think that's one of the responsibilities of this project. I mean this project is a suite to help everyone with a set of utilities for AWS Lambda functions such tracking, logging, metrics, batching and others.

In your case, why don't you try another framwework to help you? I don't know if you know AWS SAM (https://aws.amazon.com/en/serverless/sam/). This is an open source framework for building serverless applications (especially Lambda) and is also maintained by AWS. You can find a great example [here](https://awslabs.github.io/aws-lambda-powertools-python/latest/tutorial/) of how to instrument and test your application locally using AWS SAM + Lambda Powertools. 

Another option is [Serverless Framework](https://www.serverless.com/), where you can also test its functions locally and uses Lambda Powertools.

I hope this help you.

**Comment by bauer-jan** [comment]
Thanks for pointing SAM and Serverless Framework out! This just came up since i have currently a Terraform project where i face the challenge described above. So far i always used FastAPI with Mangum (https://github.com/jordaneremieff/mangum) for running ASGI applications in AWS Lambda to handle Function URL, API Gateway. This seeded up development by several factors and i wanted to highlight an integration in powertools would simplify dependencies and complexity.

**Comment by heitorlessa** [comment]
thank you @leandrodamascena!

hey @bauerjan93, the SAM CLI team is [looking for feedback on the upcoming integration with Terraform](https://github.com/aws/aws-sam-cli/issues/3154). Once released, it'll help you start a local API Gateway (both REST and HTTP API), a local Lambda API, among other features like hot-reloading etc. - @praneetap (Product Manager) would love to hear your feedback on what the Terraform user experience should look like.

As Leandro mentioned, we focus on Lambda runtime only since projects like SAM CLI, [CDK](https://aws.amazon.com/cdk/), [Serverless.tf](https://serverless.tf/) address any infrastructure construct better than we ever would.

Closing.

Thank you!

**Comment by praneetap** [comment]
@bauerjan93  happy to chat! Feel free to DM me on Twitter to set some time up twitter.com/praneetaprakash
