### ISSUE TITLE
Feature request: support BatchInvoke when using AppSyncResolver

### ISSUE THREAD

**Issue by cponfick** [awslabs/aws-lambda-powertools-python#1303]
### Use case

Currently, an event is expected to be of type ```Dict[str,Any]```. When using 'BatchInvoke' in a direct lambda resolver, the event becomes type ```List[Dict[str,Any]]```. Hence, it is not possible to route the event to the expected resolver. 

A use case is given by the  [official dev guide](https://docs.aws.amazon.com/appsync/latest/devguide/tutorial-lambda-resolvers.html). Without the ability to use 'BatchInvoke' users will run into n + 1 problems, when using appsync-GraphQl.

### Solution/User Experience

I am not 100% sure how a good solution would look like. Maybe it would be possible to use the ```AppSyncResolverEvent``` to handle one individual event, or a list of events. 
Given the described use case, the events should usually only diverge in the source.

### Acknowledgment

- [X] This feature request meets [Lambda Powertools Tenets](https://awslabs.github.io/aws-lambda-powertools-python/latest/#tenets)
- [X] Should this be considered in other Lambda Powertools languages? i.e. [Java](https://github.com/awslabs/aws-lambda-powertools-java/), [TypeScript](https://github.com/awslabs/aws-lambda-powertools-typescript/)

**Comment by heitorlessa** [comment]
hey @cponfick-bhs thank you for raising this, it makes sense. We'd need to do some digging and experiment with a few UX - would you be able to share a sample event with batch resolver? 

That will help speed this up as we'd need to create some tests, find most optimal type definitions, check whether we need some additional fields/methods, and then refactor in a non-breaking change fashion.

Thanks a lot!

**Comment by cponfick** [comment]
> hey @cponfick-bhs thank you for raising this, it makes sense. We'd need to do some digging and experiment with a few UX - would you be able to share a sample event with batch resolver?

Sure, I can construct an example.
Assume the following GraphQl-Schema:

```graphql
type Query{
   getProducts(): [Product]
}

type Product {
   name: String
   comments: [Comment!]
}

type Comment {
   text: String!
   userName: String!
}
```
The resolvers are attached as follows:

- `ParentTypeName: Query` and `FieldName: getProducts`
- `ParentTypeName: Product` and `FieldName: comments`

When using the usual Invoke, Appsync creates one event for the ```Query```:

 ```json
{
        "arguments": {},
        "identity": {
            "claims": {},
            "defaultAuthStrategy": "ALLOW",
            "groups": null,
            "issuer": "",
            "sourceIp": [""],
            "sub": "",
            "username": ""
        },
        "source": null,
        "request": {
            "headers": {},
            "domainName": null
        },
        "prev": null,
        "info": {
            "selectionSetList":["EVERYTHING"],
            "fieldName": "getProducts",
            "parentTypeName": "Query",
            "variables": {}
        },
        "stash": {}
    }
```
and  for every product, an additional event and lambda invocation for the comments:
```json
{
        "arguments": {},
        "identity": {
            "claims": {},
            "defaultAuthStrategy": "ALLOW",
            "groups": null,
            "issuer": "",
            "sourceIp": [""],
            "sub": "",
            "username": ""
        },
        "source": {THE FIELDS OF THE PRODUCT},
        "request": {
            "headers": {},
            "domainName": null
        },
        "prev": null,
        "info": {
            "selectionSetList":["EVERYTHING"],
            "fieldName": "comments",
            "parentTypeName": "Product",
            "variables": {}
        },
        "stash": {}
    }
```
Hence, for every `Product` an additional lambda invoke is executed. 

When using "BatchInvoke", the first event remains the same, but the calls that return the comments for each product are "merged" into one lambda call with a list of events.
```json
[{
        "arguments": {},
        "identity": {
            "claims": {},
            "defaultAuthStrategy": "ALLOW",
            "groups": null,
            "issuer": "",
            "sourceIp": [""],
            "sub": "",
            "username": ""
        },
        "source": {THE FIELDS OF THE PRODUCT 0},
        "request": {
            "headers": {},
            "domainName": null
        },
        "prev": null,
        "info": {
            "selectionSetList":["EVERYTHING"],
            "fieldName": "comments",
            "parentTypeName": "Product",
            "variables": {}
        },
        "stash": {}
    },
{
        "arguments": {},
        "identity": {
            "claims": {},
            "defaultAuthStrategy": "ALLOW",
            "groups": null,
            "issuer": "",
            "sourceIp": [""],
            "sub": "",
            "username": ""
        },
        "source": {THE FIELDS OF THE PRODUCT 1},
        "request": {
            "headers": {},
            "domainName": null
        },
        "prev": null,
        "info": {
            "selectionSetList":["EVERYTHING"],
            "fieldName": "comments",
            "parentTypeName": "Product",
            "variables": {}
        },
        "stash": {}
    },
{
        "arguments": {},
        "identity": {
            "claims": {},
            "defaultAuthStrategy": "ALLOW",
            "groups": null,
            "issuer": "",
            "sourceIp": [""],
            "sub": "",
            "username": ""
        },
        "source": {THE FIELDS OF THE PRODUCT 2},
        "request": {
            "headers": {},
            "domainName": null
        },
        "prev": null,
        "info": {
            "selectionSetList":["EVERYTHING"],
            "fieldName": "comments",
            "parentTypeName": "Product",
            "variables": {}
        },
        "stash": {}
    }]
```
Appsync now expects a list of responses associated with the corresponding sources. The fields of the events depend on the `ResponseMappingTemplate` used for the resolver.

@heitorlessa I hope this helps a bit.

### Work Around
Currently, I work around this issue using the following `AppSyncResolverEvent`:
```python
class MyAppSyncResolverEvent(appsync.AppSyncResolverEvent):
    def __init__(self, data: Union[dict, list]):
        if isinstance(data, dict):
            super().__init__(data)
        else:
            super().__init__(data[0])
            self._sources = [event.get('source', {}) for event in data]

    @property
    def arguments(self) -> Dict[str, Any]:
        if isinstance(self._data, dict):
            return self["arguments"]
        else:
            return {}

    @property
    def sources(self) -> List[Dict[str, Any]]:
        return self._sources
```
I must admit that this is not clean, but for now it works.

**Comment by heitorlessa** [comment]
Updating the status so we can revisit early next year.

**Comment by thenamanpatwari** [comment]
@cponfick-bhs We are in a similar position and used a similar class to route our requests accordingly.
However we are unable to get AppSync to parse our response for the batch lambda. 

We return a list of objects as expected but AppSync is parsing them as null. Could you provide some more information about the `ResponseMappingTemplate` you used after the Lambda invocation?

**Comment by thenamanpatwari** [comment]
+1
We had to build to a similar class as created by @cponfick-bhs

**Comment by leandrodamascena** [comment]
Hi @cponfick-bhs and @thenamanpatwari! 

I was on parental leave and I'm returning to work now. I created an example similar to the one reported here to understand the behavior and look for the best solution.

By the middle of next week I'll be back on this issue with some updates on what I found.

Thanks

**Comment by leandrodamascena** [comment]
Hi all! Updating here, I still haven't been able to fully analyze this and a possible solution. I'm focused on bringing you an update ASAP.

**Comment by heitorlessa** [comment]
Leandro and @mploski will be updating it this week

**Comment by mploski** [comment]
I was able to replicate the issue. Indeed, if we enable batch processing on AppSync side, resolver lambda gets list of events which is something we don't expect. Execution fails  with `[ERROR] AttributeError: 'list' object has no attribute 'get'` in `aws_lambda_powertools/utilities/data_classes/appsync_resolver_event.py`. Attached  SAM project zip with lambda and template that allow us to replicate it reliably. [appsync-batch-debug.tar.gz](https://github.com/awslabs/aws-lambda-powertools-python/files/10837057/appsync-batch-debug.tar.gz)
I will work together with @leandrodamascena  on the solution.

**Comment by heitorlessa** [comment]
**UPDATE**: @mploski is working on an update by EOW.

**Comment by mploski** [comment]
> **UPDATE**: @mploski is working on an update by EOW.

Hey sorry for lack of response here before. I was fully booked with other things for last month. We agreed that @leandrodamascena will support me in the further development so we can close it soon

**Comment by leandrodamascena** [comment]
Hey everyone! We are working on this PR https://github.com/aws-powertools/powertools-lambda-python/pull/1998 to add this support as quickly as possible. The most up-to-date situation is:

> We will have an internal meeting with the AppSync Service team to discuss error handling when consuming an AppSync batch process. We want to hear from them about use cases and what challenges customers are facing.

> After this meeting, I will update this PR. The expectation of having this feature in the next release remains, but I will update this PR if we have any additional news from this meeting.

Thanks

**Comment by heitorlessa** [comment]
**Update**. We're going through the final documentation touches to get this released in the next version.

Since last week, we've added partial failure support so parts of the batch item could fail, letting AppSync or your own response mapping templates propagate partial errors accordingly.

```python
from typing import Dict, Optional

from aws_lambda_powertools.event_handler import AppSyncResolver
from aws_lambda_powertools.utilities.data_classes import AppSyncResolverEvent
from aws_lambda_powertools.utilities.typing import LambdaContext

app = AppSyncResolver()


posts_related = {
    "1": {"title": "post1"},
    "2": {"title": "post2"},
    "3": {"title": "post3"},
}


class PostRelatedNotFound(Exception):
    ...


@app.batch_resolver(type_name="Query", field_name="relatedPosts", raise_on_error=True)  
def related_posts(event: AppSyncResolverEvent, post_id: str) -> Optional[Dict]:
    post_found = posts_related.get(post_id, None)

    if not post_found:
        raise PostRelatedNotFound(f"Unable to find a related post with ID {post_id}.")

    return post_found


def lambda_handler(event, context: LambdaContext) -> dict:
    return app.resolve(event, context)

```

**Comment by heitorlessa** [comment]
We're making a patch release today with numerous bugfixes, and the next feature release will have this feature released.

Deepest apologies on the delay here

**Comment by heitorlessa** [comment]
We're marking this for release this Thursday

**Comment by leandrodamascena** [comment]
Hi @cponfick! It took a long time, longer than we expected, but we will be releasing this feature tomorrow! 🚀

Thanks for opening this issue and we hope that it can be helpful in your applications.
