### ISSUE TITLE
Feature request: Allow for removing CloudWatch metrics field from logged metrics 

### ISSUE THREAD

**Issue by amrabed** [awslabs/aws-lambda-powertools-python#1305]
### Use case

This [line](https://github.com/awslabs/aws-lambda-powertools-python/blob/b28c7a9aff0d17ffdb3c740214c2bcfd3b38356e/aws_lambda_powertools/metrics/base.py#L206) forces the addition of the `CloudWatchMetrics` field to all logs of the metrics when the `log_metrics` decorator is used. That can at least double the log cost compared to what is actually necessary when logging the metrics (basically the name and value of the metrics)

### Solution/User Experience

Add a flag parameter to the `log_metrics` decorator to allow for **not** including this field in the log record

### Acknowledgment

- [X] This feature request meets [Lambda Powertools Tenets](https://awslabs.github.io/aws-lambda-powertools-python/latest/#tenets)
- [ ] Should this be considered in other Lambda Powertools languages? i.e. [Java](https://github.com/awslabs/aws-lambda-powertools-java/), [TypeScript](https://github.com/awslabs/aws-lambda-powertools-typescript/)

**Comment by heitorlessa** [comment]
Hi @amrabed thank you for opening an issue. We're following [CloudWatch Embedded Metric Format Specification](https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/CloudWatch_Embedded_Metric_Format_Specification.html) and that field is [mandatory](https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/CloudWatch_Embedded_Metric_Format_Specification.html#CloudWatch_Embedded_Metric_Format_Specification_structure_root).

![image](https://user-images.githubusercontent.com/3340292/179483762-c9af529e-8d3b-444f-8900-adb40cf4a670.png)

With that in mind, could you clarify what you meant with

> That can at least double the log cost compared to what is actually necessary when logging the metrics (basically the name and value of the metrics)

If we were to remove that, those metrics wouldn't be created in CloudWatch leading to data loss.

Thank you

**Comment by amrabed** [comment]
@heitorlessa I see. Thanks for the clarification. I am only now seeing that the `log_metrics` decorator is actually required to "flush" the metrics to CloudWatch not just optionally "log" the metrics object

Here is what I had in mind when I mentioned impacting the CloudWatch Logs cost. Let's say we have 3 count metrics. The actual necessary information in the log record (i.e., what we would actually include if we just log the values manually) is:
```
{
  "metirc1": [1],
  "metric2": [2],
  "metric3": [3]
}
```

What actually gets printed when using `log_metrics` is:
```
{
  "_aws": {
    "Timestamp": 1574109732004,
    "CloudWatchMetrics": [
      {
        "Metrics": [
          {
            "Name": "metric1",
            "Unit": "Count"
          },
          {
            "Name": "metric2",
            "Unit": "Count"
          },
          {
            "Name": "metric3",
            "Unit": "Count"
          }
        ]
      }
    ]
  },
  "metirc1": [1],
  "metric2": [2],
  "metric3": [3]
}
```

You can see that the overhead is way more than double the original log record size compared to the original data since we have to include the name and type of all 3 metrics in every single record. Anyway, I guess there is no way around that given the required EMF format

**Comment by heitorlessa** [comment]
Yes exactly, it’s EMF who requires this format.

If you could you share your AWS Account ID via email, we can pass +1 a
feature request for a leaner specification to the CloudWatch team -
***@***.***
