### ISSUE TITLE
Docs: Security.md missing

### ISSUE THREAD

**Issue by sliedig** [awslabs/aws-lambda-powertools-python#1310]
### What were you searching in the docs?

I was reading [MAINTAINERS.md](https://github.com/awslabs/aws-lambda-powertools-python/blob/develop/MAINTAINERS.md) and came upon a missing reference to [SECURITY.md](https://github.com/awslabs/aws-lambda-powertools-python/blob/develop/SECURITY.md)

> Prioritize Security
Security is your number one priority. Maintainer's Github keys must be password protected securely and any reported security vulnerabilities are addressed before features or bugs.
Note that this repository is monitored and supported 24/7 by Amazon Security, see [Reporting a Vulnerability](https://github.com/awslabs/aws-lambda-powertools-python/blob/develop/SECURITY.md) for details.

### Is this related to an existing documentation section?

https://github.com/awslabs/aws-lambda-powertools-python/blob/develop/MAINTAINERS.md

### How can we improve?

```markdown
Add the SECURITY.md file
```

### Acknowledgment

- [X] I understand the final update might be different from my proposed suggestion, or refused.

**Comment by heitorlessa** [comment]
Fixed by https://github.com/awslabs/aws-lambda-powertools-python/commit/182531d57857a57d2e9e15807ebd2cc30a8237e6
