### ISSUE TITLE
Bug: regression in pip release that included mypy-boto3-* dev dependencies

### ISSUE THREAD

**Issue by tb102122** [awslabs/aws-lambda-powertools-python#1321]
### Which AWS Lambda Powertools utility does this relate to?

Other

### Summary

Why do we need the dependency in the final release build?

mypy-boto3-cloudwatch = "^1.24.0"
mypy-boto3-lambda = "^1.24.0"
mypy-boto3-xray = "^1.24.0"

### Use case

reduce package size

### Proposal

remove dependency

### Out of scope

n/a

### Potential challenges

n/a

### Acknowledgment

- [X] This feature request meets [Lambda Powertools Tenets](https://awslabs.github.io/aws-lambda-powertools-python/latest/#tenets)
- [ ] Should this be considered in other Lambda Powertools languages? i.e. [Java](https://github.com/awslabs/aws-lambda-powertools-java/), [TypeScript](https://github.com/awslabs/aws-lambda-powertools-typescript/)

**Comment by heitorlessa** [comment]
hey @tb102122 that's a bug, this should have been a dev dependency like other mypy types we have; an oversight from our part when merging @mploski E2E testing PR: https://github.com/awslabs/aws-lambda-powertools-python/blame/develop/pyproject.toml#L29

We'll make a patch release in the next 2 hours to address it

**Comment by tb102122** [comment]
Great thanks!

**Comment by heitorlessa** [comment]
@tb102122 now live on PyPi and SAR (v1.26.5) -- Lambda Layer might take a few hours to update across regions. 

Huge thanks again @tb102122
