### ISSUE TITLE
Maintenance: Remove PR labels if title changes

### ISSUE THREAD

**Issue by heitorlessa** [awslabs/aws-lambda-powertools-python#1335]
### Summary

As of now, we [label PRs based on semantic title and areas](https://github.com/awslabs/aws-lambda-powertools-python/blob/develop/.github/scripts/label_pr_based_on_title.js). When a title change occurs, a new label is added (correctly) but the previous label remains.

We need to extend this logic by keeping state (GH Artifacts?).

### Why is this needed?

Keeps PR labels synchronized with their title and intentions of what change that represents.

### Which area does this relate to?

Automation, Governance

### Acknowledgment

- [X] This request meets [Lambda Powertools Tenets](https://awslabs.github.io/aws-lambda-powertools-python/latest/#tenets)
- [X] Should this be considered in other Lambda Powertools languages? i.e. [Java](https://github.com/awslabs/aws-lambda-powertools-java/), [TypeScript](https://github.com/awslabs/aws-lambda-powertools-typescript/)

**Comment by leandrodamascena** [comment]
Hey @sthulb! Can you help here? I'm assigning this issue for you and please let me know when you can fix it.

**Comment by leandrodamascena** [comment]
Closed as completed.
