### ISSUE TITLE
Maintenance: optimize End to End tests mechanism to create powertools Layer once

### ISSUE THREAD

**Issue by mploski** [awslabs/aws-lambda-powertools-python#1345]
### Summary

Currently we create new powertools layer for every test group in our e2e tests. It means we create 3 layers per test execution. If we multiply it by number of Python runtime we run tests in parallel (python 3.7,3.8, 3.9) we have 9 layers built for every github action executed.
It consumes resources (CPU, IOPS, Network Bandwidth) and can slow down overall test execution on constraint environments like github action workers.

### Why is this needed?

It optimize resource utilization  on build machine and thus lower down time needed to conduct tests and enable better scalability/cost control

### Acknowledgment

- [X] This request meets [Lambda Powertools Tenets](https://awslabs.github.io/aws-lambda-powertools-python/latest/#tenets)
- [ ] Should this be considered in other Lambda Powertools languages? i.e. [Java](https://github.com/awslabs/aws-lambda-powertools-java/), [TypeScript](https://github.com/awslabs/aws-lambda-powertools-typescript/)

**Comment by heitorlessa** [comment]
Implemented by #1466
