### ISSUE TITLE
Maintenance: Run end to end tests automatically on merge request

### ISSUE THREAD

**Issue by mploski** [awslabs/aws-lambda-powertools-python#1346]
### Summary

We should automate end to end tests execution on every merge to master branch. This will help us discover potential problems before we release new package

### Why is this needed?

To automate manual steps, simplifying maintainer effort and to discover potential problems before new layer pypi package is released

### Acknowledgment

- [X] This request meets [Lambda Powertools Tenets](https://awslabs.github.io/aws-lambda-powertools-python/latest/#tenets)
- [ ] Should this be considered in other Lambda Powertools languages? i.e. [Java](https://github.com/awslabs/aws-lambda-powertools-java/), [TypeScript](https://github.com/awslabs/aws-lambda-powertools-typescript/)

**Comment by leandrodamascena** [comment]
Closing this issue, as it has already been implemented!

https://github.com/awslabs/aws-lambda-powertools-python/actions/workflows/run-e2e-tests.yml
