### ISSUE TITLE
Maintenance: Define E2E tests needed

### ISSUE THREAD

**Issue by mploski** [awslabs/aws-lambda-powertools-python#1347]
### Summary

Currently, we developed only example end2end tests - just to validate our new mechanism. We should consider what functionalities we want to test and implement tests

### Why is this needed?

To start using newly integrated mechanism and start benefiting from it

### Acknowledgment

- [X] This request meets [Lambda Powertools Tenets](https://awslabs.github.io/aws-lambda-powertools-python/latest/#tenets)
- [ ] Should this be considered in other Lambda Powertools languages? i.e. [Java](https://github.com/awslabs/aws-lambda-powertools-java/), [TypeScript](https://github.com/awslabs/aws-lambda-powertools-typescript/)

**Comment by heitorlessa** [comment]
Renamed to best suit the description. We should create one issue per utility we want to create E2E test. This Friday, we should reconvene on maintainers sync to discuss areas we want to do E2E test and which ones will be covered by integ test (if at all)

**Comment by heitorlessa** [comment]
Done in https://github.com/awslabs/aws-lambda-powertools-python/blob/develop/CONTRIBUTING.md#testing-definition
