### ISSUE TITLE
Python 3.6 deprecation: Add `cfn-lint` as a dev dependency and update `python_docs` GH workflow

### ISSUE THREAD

**Issue by heitorlessa** [awslabs/aws-lambda-powertools-python#1378]

**Comment by rubenfonseca** [comment]
@heitorlessa what would we use `cfn-lint` for in the repository?

**Comment by heitorlessa** [comment]
We use it to lint SAM templates available in examples/ folder as part of pre-commit hooks.

I wanted to add as part of docs build workflow too but py 3.6 was an issue - we now can!
