### ISSUE TITLE
Python 3.6 deprecation: Launch a new Lambda Layer `AWSLambdaPowertoolsPythonV2`

### ISSUE THREAD

**Issue by heitorlessa** [awslabs/aws-lambda-powertools-python#1379]

**Comment by rubenfonseca** [comment]
Notes from internal meeting:

- we will publish one layer with powertools + extras, without boto3
- layer will be published in two flavours: x86_64, and arm64
- naming as follows: `AWSLambdaPowertoolsV2`, `AWSLambdaPowertoolsV2-Arm64`
