### ISSUE TITLE
Expose version function in package root 

### ISSUE THREAD

**Issue by heitorlessa** [awslabs/aws-lambda-powertools-python#1382]
With Python 3.6 being dropped in v2, we can use use `importlib` to expose a version function. 

Since `importlib` looks up DIST files to gather package information, it'll impact cold start performance. Instead, we should create a version and use lazy import to amortize the overhead.

NOTE: `importlib.metadata` is only available in 3.8. Reducing priority and assigning a `help wanted`.

**Comment by leandrodamascena** [comment]
Hi @heitorlessa! I include this in User Agent PR.
