### ISSUE TITLE
How to became a contributor?

### ISSUE THREAD

**Issue by ypolon7kiy** [awslabs/aws-lambda-powertools-python#139]
**What were you initially searching for in the docs?**
Where to send contribution intent.

Just pulling the repo and trying to push branch for pull request returns 403.

**Describe how we could make it clearer**
Add contacts of the person how can grant access to the repo for contribution.

**Is this related to an existing part of the documentation? Please share a link**
`https://github.com/awslabs/aws-lambda-powertools-python/blob/develop/CONTRIBUTING.md`

**Comment by Nr18** [comment]
You need to fork the repo and then create a branch and push your changes there and then open a pull request. 

When it's reviewed and approved it will be merged.

**Comment by am29d** [comment]
Hi @ypolon7kiy 

in the `CONTRIBUTING.md` there is a section with the steps:

```
Dev setup

To send us a pull request, please follow these steps:

Fork the repository.
Install dependencies in a virtual env with poetry, and pre-commit hooks: make dev
Create a new branch to focus on the specific change you are contributing e.g. improv/logger-debug-sampling
Run all tests, and code baseline checks: make pr
Git hooks will run linting and formatting while make pr run deep checks that also run in the CI process
Commit to your fork using clear commit messages.
Send us a pull request with a conventional semantic title, and answering any default questions in the pull request interface.
Pay attention to any automated CI failures reported in the pull request, and stay involved in the conversation.
```

Which of the steps is failing for you? Would be good to get your feedback and fix the documentation so others can also start contributing.

**Comment by ypolon7kiy** [comment]
Hi Alex,
Thank you for your response.

I did everything by the book.

Doing:
              git push --set-upstream origin
feat/make-log-line-to-start-with-log-message
Getting:
              remote: Permission to
awslabs/aws-lambda-powertools-python.git denied to ypolon7kiy.
              fatal: unable to access '
https://github.com/awslabs/aws-lambda-powertools-python.git/': The
requested URL returned error: 403

**Comment by ypolon7kiy** [comment]
Hi Alex.
Sorry if i did not understand correctly.

Should I fork not clone ?

Thanks!

**Comment by heitorlessa** [comment]
Yep - please Fork. You can use the GitHub CLI to then quickly create a PR against this repo from your repo

1. Fork this repo
2. Clone your repo
3. Create a local branch, and work on what you want
4. Use "gh pr create" to do the heavy lifting for you, or the browser too

**Comment by am29d** [comment]
I also recommend to setup an upstream remote on your fork so you can fetch changes from the upstream, update your fork and early resolve any merge conflicts, if exists. Here is a good short description how to do that:

https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/configuring-a-remote-for-a-fork
 
It's optional, but helps to keep up with the changes.

**Comment by heitorlessa** [comment]
Following up to confirm whether you succeeded setting up your dev setup using GitHub documentation @ypolon7kiy.

**Comment by ypolon7kiy** [comment]
Hi Heitor.
Thanks for your email.
 Yes everything worked.

But the feature I wanted to add was already added by Michael.

Regards

**Comment by heitorlessa** [comment]
@michaelbrewer is too quick, I'll give him that.

I'll close this issue then :)
