### ISSUE TITLE
Maintenance: Remove support to devcontainer

### ISSUE THREAD

**Issue by leandrodamascena** [awslabs/aws-lambda-powertools-python#1410]
### Summary

Indeed the Visual Studio Code Remote - Containers extension is an excellent tool to help create isolated and customized development environments, but I believe we have a problem using this extension in this project.

1 - Currently the devcontainer configuration doesn't work because the project needs docker to run some operations

![image](https://user-images.githubusercontent.com/4295173/182662331-6ef7e659-61e5-4039-81da-d6193e7e8b97.png)

2 - The official image (mcr.microsoft.com/vscode/devcontainers/python-*) does not support docker installation.

![image](https://user-images.githubusercontent.com/4295173/182662847-453bedf2-b419-4d0f-8fbc-3e8c757baed6.png)

3 - Gitpod can be used as an alternative for those who don't want to configure a local environment.

### Why is this needed?

To avoid problems setting up a development environment.

### Which area does this relate to?

Governance, Other

### Acknowledgment

- [X] This request meets [Lambda Powertools Tenets](https://awslabs.github.io/aws-lambda-powertools-python/latest/#tenets)
- [X] Should this be considered in other Lambda Powertools languages? i.e. [Java](https://github.com/awslabs/aws-lambda-powertools-java/), [TypeScript](https://github.com/awslabs/aws-lambda-powertools-typescript/)

**Comment by heitorlessa** [comment]
Thanks Leandro! GitPod it is
