### ISSUE TITLE
Maintenance: change the maximum number of user-defined metric dimensions to 29

### ISSUE THREAD

**Issue by gshpychka** [awslabs/aws-lambda-powertools-python#1413]
### Summary

AWS increased the quotas for CloudWatch today; specifically,  the maximum number of dimensions a metric can have was increased from 10 to 30 (https://aws.amazon.com/about-aws/whats-new/2022/08/amazon-cloudwatch-metrics-increases-throughput)

The validation should take this into account and raise the limit accordingly.

### Why is this needed?

Previously, the limit was 10 dimensions per metric, and this was raised to 30 today. We should reflect it and allow the user to take advantage of this

### Solution

Change https://github.com/awslabs/aws-lambda-powertools-python/blob/bb1eda742583d58790219942a49a5d2489ea91ea/aws_lambda_powertools/metrics/base.py#L17 to `MAX_DIMENSIONS = 29`

### Acknowledgment

- [X] This request meets [Lambda Powertools Tenets](https://awslabs.github.io/aws-lambda-powertools-python/latest/#tenets)
- [X] Should this be considered in other Lambda Powertools languages? i.e. [Java](https://github.com/awslabs/aws-lambda-powertools-java/), [TypeScript](https://github.com/awslabs/aws-lambda-powertools-typescript/)

**Comment by heitorlessa** [comment]
Thanks for flagging it @gshpychka! We had a chat with the CloudWatch team before making it public. 

@rubenfonseca @leandrodamascena should we treat this as a breaking change or not? We'd have to change the `MAX_DIMENSIONS` and our tests as the ValidationError will no longer occur past 9.

If you think this is not a breaking change, we can bundle it for our release this Friday.

**Comment by rubenfonseca** [comment]
I don't see this as a breaking change: the old code should continue to work unchanged (unless customers are triggering the SchemaValidationError on purpose). So an upgrade in the max dimensions should not cause existing code to break.

**Comment by leandrodamascena** [comment]
I don't think this is a breaking change change either. The old code will continue to work with a maximum of 9 dimensions and the new one will be able to use a maximum of 29. 

it's a nice improvement to add more metrics/dimensions to Cloudwatch and I'm sure customers will be happy about it.

**Comment by heitorlessa** [comment]
Alright then! @gshpychka, would you like to do the honours and make a PR for this change?

We can craft a PR if you don't have the bandwidth

**Comment by leandrodamascena** [comment]
Hi @gshpychka. I think I can submit a PR for this issue if you're busy. I think (not sure) that tomorrow there should be a release and it would be interesting to have this improvement.

**Comment by gshpychka** [comment]
Apologies, couldn't get to it yesterday.

**Comment by heitorlessa** [comment]
no problem at all @gshpychka, we only "rushed" a bit because we're releasing this to everyone today ;) 

Thanks for checking in (and more importantly for flagging it)
