### ISSUE TITLE
Feature request: Add CloudMap parameters utility

### ISSUE THREAD

**Issue by ran-isenberg** [awslabs/aws-lambda-powertools-python#1424]
### Use case

We use Cloudmap for both deployment and runtime service endpoints. We wrote custom code to properly extract and parse the responses.

### Solution/User Experience

A similar utility to SSM with cache built it.

### Acknowledgment

- [X] This feature request meets [Lambda Powertools Tenets](https://awslabs.github.io/aws-lambda-powertools-python/latest/#tenets)
- [X] Should this be considered in other Lambda Powertools languages? i.e. [Java](https://github.com/awslabs/aws-lambda-powertools-java/), [TypeScript](https://github.com/awslabs/aws-lambda-powertools-typescript/)

**Comment by heitorlessa** [comment]
Thanks a lot Ran for the feature request. I've just added a label to signal we're looking for customer feedback on this.

**Comment by heitorlessa** [comment]
We're closing feature requests older than a year that haven't received enough customers +1 or that we were unable to prioritize. For newer customers interested in, please feel free to comment and we can reopen it.
