### ISSUE TITLE
Feature request: Add Parser official support for Lambda Function URL

### ISSUE THREAD

**Issue by ran-isenberg** [awslabs/aws-lambda-powertools-python#1425]
### Use case

Lambda function support was added to event handlers. Parser should also be able to support it out of the box.

### Solution/User Experience

Have parser add an envelope and model for lambda function events.
Let me know when I can add it.

### Acknowledgment

- [X] This feature request meets [Lambda Powertools Tenets](https://awslabs.github.io/aws-lambda-powertools-python/latest/#tenets)
- [ ] Should this be considered in other Lambda Powertools languages? i.e. [Java](https://github.com/awslabs/aws-lambda-powertools-java/), [TypeScript](https://github.com/awslabs/aws-lambda-powertools-typescript/)

**Comment by heitorlessa** [comment]
Thank you Ran, I've just updated the title and removed triage. Feel free to make a PR, I also added a `help wanted` label for anyone else if you don't have the bandwidth. I also remember you shared there were some validation issues - let us know if we can help.

**Comment by ran-isenberg** [comment]
I'll prepare a PR, no problem, should be easy.

**Comment by heitorlessa** [comment]
We'll release it by EOW the latest. Got an announcement to make tomorrow before we schedule the best date for the release.
