### ISSUE TITLE
Feature request: support DynamoDB image values to dict with built-in Python types 

### ISSUE THREAD

**Issue by shanab** [awslabs/aws-lambda-powertools-python#1432]
### Use case

When using `DynamoDBRecord` class, the values for `old_image` and `new_image` are represented as `Dict[str, AttributeValue]`. This representation is sufficient when the data parsed is simple and does not contain nested maps/lists.
But when the data parsed contains nested maps/lists, then it becomes hard to get to the data that `AttributeValue` represents.
One would need to recursively parse the `AttributeValue` objects in the nested dicts to get to the underlying data.

### Solution/User Experience

Using a deserializer similar to the `TypeDeserializer` provided by boto3 ([link to code](https://github.com/boto/boto3/blob/d581014c3f4bc7810e1868807481d3fe69e9e3b6/boto3/dynamodb/types.py#L242)), one would be able to convert image to a Python dict where the values would be built-in Python types.

### Acknowledgment

- [X] This feature request meets [Lambda Powertools Tenets](https://awslabs.github.io/aws-lambda-powertools-python/latest/#tenets)
- [ ] Should this be considered in other Lambda Powertools languages? i.e. [Java](https://github.com/awslabs/aws-lambda-powertools-java/), [TypeScript](https://github.com/awslabs/aws-lambda-powertools-typescript/)

**Comment by heitorlessa** [comment]
Thanks a lot for taking the time to raise it Ahmed. I can’t wait to see
this PR.

**Comment by ran-isenberg** [comment]
@shanab 
did you try using the parser? you can specify models for the images and it all gets parsed nicely.
https://awslabs.github.io/aws-lambda-powertools-python/latest/utilities/parser/#built-in-envelopes
There's a DynamoDBStreamEnvelope class.

It seems like the data classes features is trying to implement parsing features IMO.

**Comment by shanab** [comment]
@ran-isenberg the problem in our case was that the service was not using Pydantic, and we did not want to introduce it only to parse the DynamoDB record.
I agree that there is an overlap between data classes and Parser, but IMO data classes should still allow traversing the fields of a record.
Also looking at the [data classes docs](https://github.com/awslabs/aws-lambda-powertools-python/blob/develop/docs/utilities/data_classes.md#key-features), one of the key features mentioned is "Helper functions for decoding/deserializing nested fields"

**Comment by heitorlessa** [comment]
hey @shanab Ahmed, checking in to see if you still have the bandwidth to contribute as you already had the code working.

Thank you!

**Comment by shanab** [comment]
@heitorlessa yes, I should have time this week to have a first draft. Sorry for leaving this open until now!

**Comment by jplock** [comment]
What about using boto3's [TypeDeserializer](https://github.com/boto/boto3/blob/develop/boto3/dynamodb/types.py#L242) ?

**Comment by shanab** [comment]
> What about using boto3's [TypeDeserializer](https://github.com/boto/boto3/blob/develop/boto3/dynamodb/types.py#L242) ?

That can be an option, but to my knowledge then one would not be able to do the following:

```python
@event_source(data_class=DynamoDBStreamEvent)
def lambda_handler(event: DynamoDBStreamEvent, context):
    pass
```
because you'd need the raw Python dictionary for `NewImage` and `OldImage` to be able to use `TypeDeserializer`, and the event won't expose that.

**Comment by heitorlessa** [comment]
Released in V2 now ;) https://github.com/awslabs/aws-lambda-powertools-python/releases/tag/v2.0.0
