### ISSUE TITLE
Feature request: Event source mapping for custom CloudWatch dashboard widgets

### ISSUE THREAD

**Issue by sthuber90** [awslabs/aws-lambda-powertools-python#1461]
### Use case

When invoking a Lambda function to create a custom widget in a CloudWatch dashboard, a event source mapping class for the incoming event can help to ensure type safety and make the event attributes easier accessible than going through [the documentation](https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/add_custom_widget_dashboard_about.html)

### Solution/User Experience

Add a CloudWatch dashboard custom widget event source into *data_classes*

### Acknowledgment

- [X] This feature request meets [Lambda Powertools Tenets](https://awslabs.github.io/aws-lambda-powertools-python/latest/#tenets)
- [X] Should this be considered in other Lambda Powertools languages? i.e. [Java](https://github.com/awslabs/aws-lambda-powertools-java/), [TypeScript](https://github.com/awslabs/aws-lambda-powertools-typescript/)

**Comment by rubenfonseca** [comment]
Hi @sthuber90 thank you for opening this feature! Since python 3.6 runtime was just removed from Lambda, [we are focusing our efforts on a new major release of Powertools.](https://github.com/awslabs/aws-lambda-powertools-python/issues/1459)

Do you have the bandwidth the implement this feature?

**Comment by sthuber90** [comment]
I will try to create a PR for it 👍
