### ISSUE TITLE
Maintenance: remove legacy SQS Batch Processor

### ISSUE THREAD

**Issue by rubenfonseca** [awslabs/aws-lambda-powertools-python#1462]
### Summary

We kept the first implementation of the SQS Batch Processor for historical reasons. As of November 2021, it was no longer needed because native support was added to the services.

### Why is this needed?

We've been recommending the native solution since we launched it. It's not worth to maintain two code paths to achieve the same functionality. 

### Which area does this relate to?

Batch processing

### Solution

- Immediately deprecate the feature with a warning (both for the `sqs_batch_processor` decorator and `PartialSQSProcessor` classes.
- Completely remove the code on the next major version of Powertools

### Acknowledgment

- [X] This request meets [Lambda Powertools Tenets](https://awslabs.github.io/aws-lambda-powertools-python/latest/#tenets)
- [ ] Should this be considered in other Lambda Powertools languages? i.e. [Java](https://github.com/awslabs/aws-lambda-powertools-java/), [TypeScript](https://github.com/awslabs/aws-lambda-powertools-typescript/)

**Comment by heitorlessa** [comment]
Closing as we're wrap to launch V2
