### ISSUE TITLE
Feature request: Kafka Event Data Class

### ISSUE THREAD

**Issue by lyoung-confluent** [awslabs/aws-lambda-powertools-python#1484]
### Use case

When using a Kafka event source either from [self-managed Apache Kafka](https://docs.aws.amazon.com/lambda/latest/dg/with-kafka.html) or [Amazon MSK](https://docs.aws.amazon.com/lambda/latest/dg/with-msk.html) there should be a relevant data class for easy iteration/decoding.

Such functionality [is implemented already in aws-lambda-go](https://github.com/aws/aws-lambda-go/blob/main/events/kafka.go) and [in aws-lambda-java-libs](https://github.com/aws/aws-lambda-java-libs/blob/da593256513d3cec2849bb3955ad9ec3ebf38545/aws-lambda-java-events/src/main/java/com/amazonaws/services/lambda/runtime/events/KafkaEvent.java).

### Solution/User Experience

Similar to other streaming data sources a `records` property should be iterable returning a `KafkaEventRecord` that transparently decodes the values from JSON:
```py
from aws_lambda_powertools.utilities.data_classes import event_source, KafkaEvent

@event_source(data_class=KafkaEvent)
def handler(event: KafkaEvent, context: LambdaContext):
	for record in event.records:
		print(record.decoded_key, record.json_value)
```

### Acknowledgment

- [X] This feature request meets [Lambda Powertools Tenets](https://awslabs.github.io/aws-lambda-powertools-python/latest/#tenets)
- [X] Should this be considered in other Lambda Powertools languages? i.e. [Java](https://github.com/awslabs/aws-lambda-powertools-java/), [TypeScript](https://github.com/awslabs/aws-lambda-powertools-typescript/)

**Comment by rubenfonseca** [comment]
Thank you so much for the feature request @lyoung-confluent! It makes a lot of sense to cover Kafka events too. We're looking forward to review your PR tomorrow!

**Comment by ran-isenberg** [comment]
@rubenfonseca  i think we should also create a similar parser event for this one. what do you think?

**Comment by ran-isenberg** [comment]
see also  https://github.com/awslabs/aws-lambda-powertools-python/pull/1499
