### ISSUE TITLE
Static typing: Errors when importing top-level modules such as Logger

### ISSUE THREAD

**Issue by kmkhr** [awslabs/aws-lambda-powertools-python#1511]
### Static type checker used

pyright/pylance

### AWS Lambda function runtime

3.9

### AWS Lambda Powertools for Python version

latest

### Static type checker info

"Logger" is not exported from module "aws_lambda_powertools"
  Import from "aws_lambda_powertools.logging" instead Pylance [reportPrivateImportUsage](https://github.com/microsoft/pylance-release/blob/main/DIAGNOSTIC_SEVERITY_RULES.md#diagnostic-severity-rules)

### Code snippet

```python
from aws_lambda_powertools import Logger
```

### Possible Solution

The following changes need to be made to `aws_lambda_powertools/__init__.py`.

```python
# re-export it as Logger
from .logging import Logger as Logger # noqa: F401
```

or

```python
from .logging import Logger # noqa: F401
# include it in __all__
__all__ = ["Logger"]
```

reference:
- https://mypy.readthedocs.io/en/stable/command_line.html#cmdoption-mypy-no-implicit-reexport
- https://github.com/python/typing/blob/master/docs/source/libraries.rst#how-much-of-my-library-needs-types

**Comment by heitorlessa** [comment]
Closing as we're wrap to launch V2
