### ISSUE TITLE
Bug: APIGatewayProxyEventV2Model not deserializing str to custom model

### ISSUE THREAD

**Issue by nleipi** [awslabs/aws-lambda-powertools-python#1518]
### Expected Behaviour

It should be possible to use own model classes for body in APIGatewayProxyEventV2Model 

### Current Behaviour

When I extend APIGatewayProxyEventV2Model model to include my own model for the body following exception is raised `1 validation error for Event\nbody\n  value is not a valid dict (type=type_error.dict)`. I suppose the reason for that is that body of apigw v2 event is a string

### Code snippet

```python
from aws_lambda_powertools.utilities.parser import BaseModel
from aws_lambda_powertools.utilities.parser.models import (
    APIGatewayProxyEventV2Model
)


class OrderCancelationRequest(BaseModel):
    reason: str
    orderNo: str


class MyEventModel(APIGatewayProxyEventV2Model):
    body: OrderCancelationRequest
```

### Steps to Reproduce

parse(model=MyEventModel, event=any valid apigw event)

### AWS Lambda Powertools for Python version

latest

### AWS Lambda function runtime

3.9

### Packaging format used

PyPi

**Comment by ran-isenberg** [comment]
hey @nleipi ,
There's no bug,  i got it working. There's a slight gotcha here.
The body is defined as a string, and since you extend the model to be a dataclass and dont use the envelope, you need to transform the string into a dict yourself. That's what the envelope does for you.


Here's a sample code that will get it working for you:

```python
from aws_lambda_powertools.utilities.parser import BaseModel
from aws_lambda_powertools.utilities.parser.models import (
    APIGatewayProxyEventV2Model
)
import json
from pydantic import validator

class OrderCancelationRequest(BaseModel):
    reason: str
    orderNo: str


class MyEventModel(APIGatewayProxyEventV2Model):
    body: OrderCancelationRequest

    @validator("body", pre=True)
    def transform_body_to_dict(cls, value: str):
        return json.loads(value)
```

@leandrodamascena  maybe we should include this example in the docs for extending the models that have a non dict base type like this one.

**Comment by nleipi** [comment]
I think the correct way to handle this is to use pydantics own Json type as a wrapper for the model.
```
class MyEventModel(APIGatewayProxyEventV2Model):
    body: Json[OrderCancelationRequest]
```
That should be definitely highlighted in the documentation.

**Comment by ran-isenberg** [comment]
> I think the correct way to handle this is to use pydantics own Json type as a wrapper for the model.
> 
> ```
> class MyEventModel(APIGatewayProxyEventV2Model):
>     body: Json[OrderCancelationRequest]
> ```
> 
> That should be definitely highlighted in the documentation.

Nice! even prettier

**Comment by rubenfonseca** [comment]
Hi @nleipi, thanks for opening this! As @ran-isenberg mentioned, [parser envelopes](https://awslabs.github.io/aws-lambda-powertools-python/latest/utilities/parser/#envelopes) were created exactly with this use case in mind.

In your case, the code would look something like this:

```python
from aws_lambda_powertools.utilities.parser import event_parser, BaseModel, envelopes
from aws_lambda_powertools.utilities.typing import LambdaContext

class OrderCancelationRequest(BaseModel):
    reason: str
    orderNo: str

@event_parser(model=OrderCancelationRequest, envelope=envelopes.ApiGatewayV2Envelope)
def handler(event: OrderCancelationRequest, context: LambdaContext):
    assert event.reason != ""
```

What do you think of giving this a try?

**Comment by nleipi** [comment]
I would have used envelope approach, but I need access to pathParamters. Can I access them in other way than through event model?

**Comment by ran-isenberg** [comment]
In order to get the path params, you must extend the model like you did and not use the envelope.
The APIGatewayProxyEventV2Model defines path params too. You can even change them from dict to a custom class and get even stronger validation.

```python
class MyEventModel(APIGatewayProxyEventV2Model):
    body: OrderCancelationRequest
    pathParameters: MyPathParams

    @validator("body", pre=True)
    def transform_body_to_dict(cls, value: str):
        return json.loads(value)

**Comment by nleipi** [comment]
Stronger validation of pathParameters is a really good point, thanks!

**Comment by rubenfonseca** [comment]
Thanks! We already have some documentation about [extending built-in modules](https://awslabs.github.io/aws-lambda-powertools-python/latest/utilities/parser/#extending-built-in-models). Do you think people could benefit from [this example too](https://github.com/awslabs/aws-lambda-powertools-python/issues/1518#issuecomment-1249061010)?

**Comment by ran-isenberg** [comment]
The example describes a simple use case where the business payload param is a dict.
Here, it's a string and requires an extra trick.
It makes to sense to add it.

**Comment by rubenfonseca** [comment]
Thank you so much for your input! I've opened a PR now to add this use case to our parser docs :)

**Comment by rubenfonseca** [comment]
> I think the correct way to handle this is to use pydantics own Json type as a wrapper for the model.
> 
> ```
> class MyEventModel(APIGatewayProxyEventV2Model):
>     body: Json[OrderCancelationRequest]
> ```
> 
> That should be definitely highlighted in the documentation.

Hi @nleipi @ran-isenberg I was trying out this snippet, but I still got a mypy error on the body field:

`error: "str" expects no type arguments, but 1 given  [type-arg]`

Can you check if it's the same, or if I'm missing something? I'm starting to feel that the only way around this is to use the validator route.

**Comment by ran-isenberg** [comment]
> > I think the correct way to handle this is to use pydantics own Json type as a wrapper for the model.
> > ```
> > class MyEventModel(APIGatewayProxyEventV2Model):
> >     body: Json[OrderCancelationRequest]
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > That should be definitely highlighted in the documentation.
> 
> Hi @nleipi @ran-isenberg I was trying out this snippet, but I still got a mypy error on the body field:
> 
> `error: "str" expects no type arguments, but 1 given [type-arg]`
> 
> Can you check if it's the same, or if I'm missing something? I'm starting to feel that the only way around this is to use the validator route.

Sorry, I dont use mypy that extensively.
If memory serves right, mypy and pydantic work fine only when you do a union of str, BaseModel etc. I  still think the example should be just Json. maybe add a mypy ignore?
