### ISSUE TITLE
Feature request: Kinesis Data Firehose event data class

### ISSUE THREAD

**Issue by ryandeivert** [awslabs/aws-lambda-powertools-python#1539]
### Use case

Kinesis Firehose supports data transformation via Lambda. The event is a standard format, documented [here](https://docs.aws.amazon.com/lambda/latest/dg/services-kinesisfirehose.html).

Ref: [Kinesis Data Transformation](https://docs.aws.amazon.com/firehose/latest/dev/data-transformation.html)
Example event from [aws-lambda-go sdk](https://github.com/aws/aws-lambda-go/blob/v1.34.1/events/firehose.go#L14)

### Solution/User Experience

Add `KinesisFirehoseEvent` data class for handling events of this type.

### Alternative solutions

```markdown
N/A
```

### Acknowledgment

- [X] This feature request meets [Lambda Powertools Tenets](https://awslabs.github.io/aws-lambda-powertools-python/latest/#tenets)
- [X] Should this be considered in other Lambda Powertools languages? i.e. [Java](https://github.com/awslabs/aws-lambda-powertools-java/), [TypeScript](https://github.com/awslabs/aws-lambda-powertools-typescript/)

**Comment by rubenfonseca** [comment]
Thank yo so much for opening this! We will be reviewing your PR very soon :)
