### ISSUE TITLE
Maintenance: Deprecate SAR extras for v2

### ISSUE THREAD

**Issue by rubenfonseca** [awslabs/aws-lambda-powertools-python#1543]
### Summary

When v2 is released, we will only have a [single layer that will include](https://github.com/awslabs/aws-lambda-powertools-python/issues/1379) all the extra dependencies. 

This means we won't need to have a "SAR extras" for v2. Hence we should deprecate it.

### Why is this needed?

To reduce the maintenance efforts. 

### Which area does this relate to?

Governance

### Acknowledgment

- [X] This request meets [Lambda Powertools Tenets](https://awslabs.github.io/aws-lambda-powertools-python/latest/#tenets)
- [ ] Should this be considered in other Lambda Powertools languages? i.e. [Java](https://github.com/awslabs/aws-lambda-powertools-java/), [TypeScript](https://github.com/awslabs/aws-lambda-powertools-typescript/)

**Comment by heitorlessa** [comment]
now complete with v2: https://github.com/awslabs/aws-lambda-powertools-python/releases/tag/v2.0.0
