### ISSUE TITLE
Unit tests not passing

### ISSUE THREAD

**Issue by mickog** [awslabs/aws-lambda-powertools-python#156]
running unit tests, before the unit tests are ran i am setting ```os.environ["POWERTOOLS_TRACE_DISABLED"] = "true"```
I am still getting the error ```aws_xray_sdk.core.exceptions.exceptions.SegmentNotFoundException: cannot find the current segment/subsegment, please make sure you have a segment open```
Is there another step I am missing?

**Comment by Nr18** [comment]
I have the following in my `__init__.py` to disable it...

```python
os.environ["POWERTOOLS_TRACE_DISABLED"] = "1"
```

You could give it a try

**Comment by mickog** [comment]
Thanks for the quick reply, tried this but still no luck! not sure what is going on here, any ideas?

**Comment by mickog** [comment]
Was setting the env var after i imported my execute method to the test.

**Comment by heitorlessa** [comment]
Hey @mickog is there a snippet/gist you can share?

I can give this a try tomorrow morning. 

What it'd be helpful to try reproducing/diagnosing:

- How you're running the tests (test runner, command)
- Excerpt of how Tracer is used in your code (perhaps it's an issue on our side)
- Excerpt of your test
- Powertools debug log (it'll tell us whether Tracer is in fact being disabled)


https://awslabs.github.io/aws-lambda-powertools-python/#debug-mode

**Comment by michaelbrewer** [comment]
@heitorlessa  i think @mickog  has it working now based on his last comment. 

I do find doing things like this feels a bit like a hack, but there is a cleaner way

```python3
import os

# Setup our environment variables before importing app
os.environ["AWS_DEFAULT_REGION"] = "us-east-1"
os.environ["AWS_ACCESS_KEY_ID"] = "fake"
os.environ["AWS_SECRET_ACCESS_KEY"] = "fake"
os.environ["POWERTOOLS_TRACE_DISABLED"] = "1"
# other environment variables

from src import app
```

**Comment by mickog** [comment]
Yea I have I working now, thanks

**Comment by heitorlessa** [comment]
@michaelbrewer it shouldn't need to do that for testing, this could be setup as part of the test runner - You can either:

1. **Define before running the test runner**: `POWERTOOLS_TRACE_DISABLED=1 pytest`
2. **Use a Pytest fixture to set them up for all tests/specific tests**: [pytest monkeypatch setenv method](https://docs.pytest.org/en/latest/monkeypatch.html)
3. **Use a Pytest plugin**: [pytest-dotenv](https://pypi.org/project/pytest-dotenv/)

I'll close this issue now as @mickog got it working :)
