### ISSUE TITLE
Maintenance: Convert deprecated `set-output` command on Github Actions workflows

### ISSUE THREAD

**Issue by rubenfonseca** [awslabs/aws-lambda-powertools-python#1591]
### Summary

We need to convert all the calls to `set-output` commands to the new format: https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#setting-an-output-parameter

### Why is this needed?

GH is deprecating set-output (no ETA yet): https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

### Which area does this relate to?

Automation

### Acknowledgment

- [X] This request meets [Lambda Powertools Tenets](https://awslabs.github.io/aws-lambda-powertools-python/latest/#tenets)
- [X] Should this be considered in other Lambda Powertools languages? i.e. [Java](https://github.com/awslabs/aws-lambda-powertools-java/), [TypeScript](https://github.com/awslabs/aws-lambda-powertools-typescript/)

**Comment by dreamorosi** [comment]
The deprecation now has a target date according to the linked page:
> Starting 1st June 2023 workflows using save-state or set-output commands via stdout will fail with an error.
