### ISSUE TITLE
Maintenance: Extract inline script from SAR GH action

### ISSUE THREAD

**Issue by rubenfonseca** [awslabs/aws-lambda-powertools-python#1592]
### Summary

We should extract the inline scripts from the `reusable_deploy_v2_sar` GH action workflow into scripts into a `scripts/` folder.

### Why is this needed?

To prevent error-prone updates and make it easier to test.

### Which area does this relate to?

Automation

### Acknowledgment

- [X] This request meets [Lambda Powertools Tenets](https://awslabs.github.io/aws-lambda-powertools-python/latest/#tenets)
- [ ] Should this be considered in other Lambda Powertools languages? i.e. [Java](https://github.com/awslabs/aws-lambda-powertools-java/), [TypeScript](https://github.com/awslabs/aws-lambda-powertools-typescript/)

**Comment by leandrodamascena** [comment]
Hey @sthulb! This issue is related to GH actions cross-repo clean up.

**Comment by leandrodamascena** [comment]
> Is there a practical reason to move this to it's own script file?

@rubenfonseca started moving inline scripts into their own script file to clean up our actions, make them more readable, maintainable and even reuse the script in other actions.

**Comment by sthulb** [comment]
I'm going to close this as not a requirement – this seems like the main body (https://github.com/aws-powertools/powertools-lambda-python/blob/develop/.github/workflows/reusable_deploy_v2_sar.yml#L166-L201) is just a bunch of AWS CLI commands, there's not much point in extracting it
