### ISSUE TITLE
Docs: typo of `utilities/idempotency`

### ISSUE THREAD

**Issue by senmm** [awslabs/aws-lambda-powertools-python#1595]
### What were you searching in the docs?

I found a typo in `utilities/idempotency`.

### Is this related to an existing documentation section?

https://awslabs.github.io/aws-lambda-powertools-python/latest/utilities/idempotency/#bring-your-own-persistent-store

### How can we improve?

```markdown
The typo is Persisntence, I have a suggested change to Persistence.
```

### Got a suggestion in mind?

Yes. I'd like to create Pull Requests.

### Acknowledgment

- [X] I understand the final update might be different from my proposed suggestion, or refused.

**Comment by heitorlessa** [comment]
Hey @senmm! Thank you so much for helping us improve the documentation <3

**Comment by heitorlessa** [comment]
released in v2: https://github.com/awslabs/aws-lambda-powertools-python/releases/tag/v2.0.0
