### ISSUE TITLE
Logger prints all messages and then all Context info

### ISSUE THREAD

**Issue by bisoldi** [awslabs/aws-lambda-powertools-python#160]
**General Summary**
While migrating from the Python logging package, I noticed a scenario where the Powertools Logger prints all messages (the actual payload provided to the logger).  Then it prints all of the associated JSON Context information.  

This appears to be because at some point in my codebase, I called `logging.basicConfig(level=LOGGER_LEVEL)` using the Python logging package.  I was no longer using the Python logger to log out messages and this was called AFTER initializing the Powertools Logger, however just simply calling `basicConfig` anywhere is enough to initialize the logging package and duplicate the logs.

For example:

```
INFO:FUNCTION_NAME:Logging Starting Lambda
ERROR:FUNCTION_NAME:Logging Almost done with Lambda
INFO:FUNCTION_NAME:Logging Finishing Lambda
{"level": "INFO", "location": "_lambda_wrapper:40", "message": "Starting Lambda", "timestamp": "2020-09-09 08:31:22,745", "service": "SERVICE_NAME", "sampling_rate": 0.0, "cold_start": true, "function_name": "FUNCTION_NAME", "function_memory_size": "128", "function_arn": "FUNCTION_ARN", "function_request_id": "a3de505e-f16b-42f4-b3e6-bcd2e4a73903"}
{"level": "ERROR", "location": "_lambda_wrapper:45", "message": "Almost done with Lambda", "timestamp": "2020-09-09 08:31:24,745", "service": "SERVICE_NAME", "sampling_rate": 0.0, "cold_start": true, "function_name": "FUNCTION_NAME", "function_memory_size": "128", "function_arn": "FUNCTION_ARN", "function_request_id": "a3de505e-f16b-42f4-b3e6-bcd2e4a73903"}
{"level": "INFO", "location": "_lambda_wrapper:40", "message": "Finishing Lambda", "timestamp": "2020-09-09 08:31:25,745", "service": "SERVICE_NAME", "sampling_rate": 0.0, "cold_start": true, "function_name": "FUNCTION_NAME", "function_memory_size": "128", "function_arn": "FUNCTION_ARN", "function_request_id": "a3de505e-f16b-42f4-b3e6-bcd2e4a73903"}
```

**What were you trying to accomplish?**
I imagine this can easily confuse the developer as well as anyone looking through the logs.  

## Expected Behavior
Powertools' Logger should take priority and only log once.

## Current Behavior
Powertools' Logger doesn't seem to create the root logger and allows multiple handlers/loggers.

## Possible Solution
IDEA: In _init_logger(self, **kwargs), call logging.basicConfig(..., force=True)

## Steps to Reproduce (for bugs)
```
from aws_lambda_powertools import Tracer, Logger
import logging
logger = Logger(
        service=FUNCTION_NAME,
        level=LOGGER_LEVEL
    )

if len(logging.getLogger().handlers) > 0:
    logging.getLogger().setLevel(level=LOGGER_LEVEL)
else:
    logging.basicConfig(level=LOGGER_LEVEL)

logger.info('My message')
```

## Environment

* **Powertools version used**:
1.5.0
* **Packaging format (Layers, PyPi)**:
PyPi
* **AWS Lambda function runtime:**
Only tested in local runtime (Python 3.8)
* **Debugging logs**

```python
2020-09-09 09:10:27,188 aws_lambda_powertools.tracing.tracer [DEBUG] Verifying whether Tracing has been disabled
2020-09-09 09:10:27,188 aws_lambda_powertools.tracing.tracer [DEBUG] Tracing has been disabled via env var POWERTOOLS_TRACE_DISABLED
2020-09-09 09:10:27,189 aws_lambda_powertools.tracing.tracer [DEBUG] Disabling tracer provider...
2020-09-09 09:10:27,189 aws_lambda_powertools.tracing.tracer [DEBUG] Tracing has been disabled, aborting patch
2020-09-09 09:10:27,189 aws_lambda_powertools.logging.logger [DEBUG] Removing Lambda root handler whether it exists
2020-09-09 09:10:27,251 aws_lambda_powertools.tracing.tracer [DEBUG] Annotating cold start
2020-09-09 09:10:27,251 aws_lambda_powertools.tracing.tracer [DEBUG] Calling lambda handler
2020-09-09 09:10:27,255 aws_lambda_powertools.tracing.tracer [DEBUG] Received lambda handler response successfully
```

**Comment by heitorlessa** [comment]
Hey @bisoldi thanks for opening the issue with as many details as possible - [This is the correct behaviour](https://github.com/awslabs/aws-lambda-powertools-python/blob/063d8cdde554e4b7c8ccbbd81e4a54210663486a/aws_lambda_powertools/logging/logger.py#L150), because you are explicitly configuring the Root Logger, created by Lambda, with a stream handler when using `basicConfig` that was disabled during Logger initialization. 

That's the reason you see duplicated outputs, because the log message record is emitted by the Root Logger and by Powertools Logger.

We shouldn't, as a library, configure the Root Logger.

Let me know if that helps, and I'm happy to expand if that isn't clear too

**Comment by bisoldi** [comment]
Makes sense now....Thank you for the response!
