### ISSUE TITLE
[Support Lambda Powertools]: CPQi (Exadel financial services) 

### ISSUE THREAD

**Issue by jcesarcpqi** [awslabs/aws-lambda-powertools-python#1605]
### Organization Name

CPQi (Exadel Financial Services) 

### Your Name

JULIO C CAMPOS NETO

### Your current position

LATAM Chief Architect 

### (Optional) Company logo

https://cpqi.com/wp-content/uploads/MicrosoftTeams-image-59.png

### Also using other Lambda Powertools languages?

- [X] Java
- [ ] TypeScript
- [ ] .NET

**Comment by heitorlessa** [comment]
Hey @jcesarcpqi **THANK YOU** <3. Thank you for allowing us to list CPQi in our docs - I'll create the docs by EOW.
