### ISSUE TITLE
Maintenance: Remove email-validator dependency for v2

### ISSUE THREAD

**Issue by rubenfonseca** [awslabs/aws-lambda-powertools-python#1607]
### Summary

We should remove the `email-validator` dependency from the v2 Lambda Layer and SAR.

### Why is this needed?

As we try to reduce the size of our v2 layer, we noticed that the [email-validator](https://pypi.org/project/email-validator/) is only needed if you use the [pydantic's  `EmailStr` validator](https://pydantic-docs.helpmanual.io/usage/types/#pydantic-types). 

Currently, adding `email-validator` adds ~400KB to our compressed layer size.

### Which area does this relate to?

Validation

### Acknowledgment

- [X] This request meets [Lambda Powertools Tenets](https://awslabs.github.io/aws-lambda-powertools-python/latest/#tenets)
- [ ] Should this be considered in other Lambda Powertools languages? i.e. [Java](https://github.com/awslabs/aws-lambda-powertools-java/), [TypeScript](https://github.com/awslabs/aws-lambda-powertools-typescript/)

**Comment by ran-isenberg** [comment]
@rubenfonseca i think this removal will break the parser SES model that expect this depedancy during import.

from pydantic.networks import EmailStr

is 400KB really that big of a deal?

**Comment by rubenfonseca** [comment]
Hi @ran-isenberg! Thanks for your feedback! We thought about the cost-benefit of adding an extra dependency to validate something that is sent by AWS, and that the user (AFAIK) has little to no control. We believe it's not worth it and we could use a simple string validation instead.

400KB might not seem a very big deal, but currently is twice the size of Powertools :) We could do a lot more with that space!

I also just update the PR to remove the dependency you mentioned during the import, so hopefully no crashes during import :)

**Comment by heitorlessa** [comment]
linking the original issue by @huonw https://github.com/awslabs/aws-lambda-powertools-python/issues/998

and linking Pydantic ~330ms overhead at cold start (largely due to reflection; it's expected to get a lot better in Pydantic V2): https://github.com/awslabs/aws-lambda-powertools-python/issues/1164#issuecomment-1282049432

**Comment by heitorlessa** [comment]
Closing as we're wrap to launch V2
