### ISSUE TITLE
QUESTIONS: Pushing Metrics to the CloudWatch Metrics service

### ISSUE THREAD

**Issue by bisoldi** [awslabs/aws-lambda-powertools-python#162]
Hope you don't mind my using this space to ask some questions...

1- Reading through the Metrics class it appears the flush only serializes and prints to stdout.  Admittedly, I haven't actually deployed my code, so apologies if this is a silly question...I was under the impression the Metrics would be pushed out to the CloudWatch Metrics service, but I don't see any boto3 or interface code or any way to grab the metrics manually while still using the `@metrics.log_metrics` decorator.  If I'm right and the decorator does not push the metrics to the CW Metrics service, what is the best way to do so on my own?  If it does indeed push the metrics to CW Metrics, can you point me to the code that does so?

2- There is a relevant question on SO (https://stackoverflow.com/questions/63639377/aws-lambda-powertools-metrics-only-logging-last-metric-in-loop).  Does this utility not aggregate the values for each dimension?  

3- In the Metrics scenario, can you elaborate on what the intended differences between `service`, `function_name` and `namespace` are?

Thanks and great utility!

**Comment by bisoldi** [comment]
I realize now this is trying to take advantage of CloudWatch's new EMF capability.  Is it the intent that the metrics get logged out to stdout which redirects to CloudWatch Logs and then CloudWatch Metrics automatically picks it up and creates a custom Metric from it?

If so, is there a difference between using this library and the aws-embedded-metrics library?  
https://github.com/awslabs/aws-embedded-metrics-python

**Comment by heitorlessa** [comment]
Hey Brooks - Not at all, please ask away ;-) it's also a great opportunity for us to improve the docs.

On 1.

This is a feature of CloudWatch called Embedded Metric Format (EMF, for short). It allows us to dump a serialised JSON blob that conforms to EMF Spec, and Metrics will be created a synchronously - No more calls to CloudWatch via boto, no performance impact, no TCP/TLS handshakes necessary, and you can use any high cardinal data too (metrics.add_metadata) to easily search within your Logs. 

Lambda has a native integration with it, so as soon as Lambda logs are written, and they have the EMF format, CloudWatch will create Metrics automatically for you - We simply provide a nicer way to define these metrics, along with validation for common mistakes, as EMF fails silently when a JSON Blob doesn't conform with the spec (if you were to do that JSON Blob by hand)

On 2.

I'm not on my laptop to reply on SO, but the issue there is that Metric Name has to be unique, so what's happening there is simply overriding with the last value in the for loop.

EMF doesn't support multiple values for a single metric. That's the reason we also provide a "with single_metric" context manager - This will serialize a single EMF JSON Blob, however it'd be somewhat wasteful log storage and metric wise, so best revisiting the use case.

On 3.

Namespace is a Metrics container, where all your metrics and dimensions are going to be grouped -- e.g AWS/Lambda, AWS/EC2, ServerlessAirline, MyECommerce

Function_name is a dimension we use when you're explicitly using "capture_cold_start" feature, so when we emit a ColdStart metric name, you'll know which function that metric belongs to (metric dimension)

Service, within Metrics utility, is used as a default dimension to help you group metrics by the service you're developing - for example: Metrics(service="payment")... all metrics created by all functions that make up the Payment service will be grouped in CloudWatch

Here's a detailed blog post that has a great image to visualize these CloudWatch concepts 

https://aws.amazon.com/blogs/opensource/simplifying-serverless-best-practices-with-lambda-powertools/

PS: We also have a Slack channel if you want to hang out with us ;)

Let me know if that helps clarify

**Comment by heitorlessa** [comment]
As for the difference between Powertools Metrics utility and the official EMF lib, we have a few differences:

- We capture cold start metrics if you enable it
- We validate metrics against common mistakes so it doesn't fail silently
- We provide a way to add a single metric only (no aggregation), typically used for metrics with multiple values, or metrics that have unique dimensions
- We automagically serialize, validate, and flush metrics once you reached the maximum supported by EMF (100)

Other than that, the end result of creating metrics asynchronously is the same :)

**Comment by bisoldi** [comment]
Perfect explanation, thank you!  I completely missed the EMF announcement, that makes life so.  much.  easier.

It would be beneficial to provide built-in aggregation of metrics at some point.  This would be basically pre-processing before generating the metric.  If that's something you'd be open to considering, I can add a feature request.  Otherwise, it's just something we need to keep track of and aggregate.

What is the slack workspace/channel?

Thanks again!

**Comment by bisoldi** [comment]
Hey - all's working beautifully.  Created a middleware component for all of my Lambdas that's instrumented with the library.

I'd love to check into your slack channel...Let me know where?

**Comment by heitorlessa** [comment]
This is awesome to hear Brooks!!!

The Slack link is in the main readme, here it is:

https://join.slack.com/t/awsdevelopers/shared_invite/zt-gu30gquv-EhwIYq3kHhhysaZ2aIX7ew

As for aggregating metric, isn't what Metrics() utility does? We aggregate up to 100 metrics before flushing it.

Unless you meant aggregating Metrics with the same name with different values, then creating one EMF blob each at the end - If that's the case, that would rapidly increase Log Ingestion and Log Storage if one is not careful

**Comment by heitorlessa** [comment]
@bisoldi I'm gonna close this as the main question is answered, but please feel free to reopen if you think it's not 100% clear yet.
