### ISSUE TITLE
Maintenance: Parallelize CDK Layer Stack synthesization 

### ISSUE THREAD

**Issue by rubenfonseca** [awslabs/aws-lambda-powertools-python#1640]
### Summary

During the release process, we build the public Lambda Layers [using a CDK stack](https://github.com/awslabs/aws-lambda-powertools-python/blob/develop/layer/layer/layer_stack.py).

Right now both `X86_64` and `ARM64` layers are inside the same CDK stack. This means we can't parallelize the synthesization of the layers, which is a very expensive process (currently, ARM64 layer takes 28 minutes to build, because of the ARM64 emulation via QEMU).

### Why is this needed?

We could improve the release time by creating one CDK stack for each Lambda Layer architecture, and run them in parallel.

In the future, this will also make it easy to run the ARM64 Layer Stack on a dedicated ARM64 host.

### Which area does this relate to?

Automation

### Acknowledgment

- [X] This request meets [Lambda Powertools Tenets](https://awslabs.github.io/aws-lambda-powertools-python/latest/#tenets)
- [ ] Should this be considered in other Lambda Powertools languages? i.e. [Java](https://github.com/awslabs/aws-lambda-powertools-java/), [TypeScript](https://github.com/awslabs/aws-lambda-powertools-typescript/)

**Comment by ivica-k** [comment]
Hey @rubenfonseca I could take a stab at this. In broad strokes, can you tell me how you would approach this? Separating the `ARM64` layer to a different stack?

Is there anything else needed in your opinion?

:edit:

I'm also on the Powertools Discord so we can communicate there.

**Comment by rubenfonseca** [comment]
Closing this since it's fast enough now due to the use of custom workers.
