### ISSUE TITLE
[Support Lambda Powertools]: CyberArk

### ISSUE THREAD

**Issue by ran-isenberg** [awslabs/aws-lambda-powertools-python#1644]
### Organization Name

CyberArk

### Your Name

Ran Isenberg

### Your current position

Principal Software Architect

### (Optional) Company logo

https://www.cyberark.com/wp-content/uploads/2021/01/cyberark-logo-dark.svg

### Also using other Lambda Powertools languages?

- [ ] Java
- [ ] TypeScript
- [ ] .NET

**Comment by heitorlessa** [comment]
Thank you so so much Ran!
