### ISSUE TITLE
Docs: Fix made by community twitter/linkedin links 

### ISSUE THREAD

**Issue by ran-isenberg** [awslabs/aws-lambda-powertools-python#1653]
### What were you searching in the docs?

The links to my twitter and linkedin handler were broken.

### Is this related to an existing documentation section?

We Made This (Community)

### How can we improve?

```markdown
-
```

### Acknowledgment

- [X] I understand the final update might be different from my proposed suggestion, or refused.

**Comment by heitorlessa** [comment]
Apologies Ran for the incorrect Twitter handler (despite the review).

I'll rebuild the latest docs tomorrow morning

**Comment by ran-isenberg** [comment]
@heitorlessa  no worries! thank you for sharing my work. I really appreciate it.

**Comment by heitorlessa** [comment]
Now corrected in the latest version: https://awslabs.github.io/aws-lambda-powertools-python/2.0.0/we_made_this/
