### ISSUE TITLE
Feature request: AWS Config Rule event data class

### ISSUE THREAD

**Issue by ctacka** [awslabs/aws-lambda-powertools-python#1667]
### Use case

Lambda functions could be used by [AWS Config Custom Rules](https://docs.aws.amazon.com/config/latest/developerguide/evaluate-config_develop-rules_lambda-functions.html)
AWS Config Event (one of 3 types) will be passed as event.

### Solution/User Experience

It would be nice to have data class to work with AWS Config Rule event in the same manner, as we are working with SQS, SNS, etc.

### Acknowledgment

- [X] This feature request meets [Lambda Powertools Tenets](https://awslabs.github.io/aws-lambda-powertools-python/latest/#tenets)
- [X] Should this be considered in other Lambda Powertools languages? i.e. [Java](https://github.com/awslabs/aws-lambda-powertools-java/), [TypeScript](https://github.com/awslabs/aws-lambda-powertools-typescript/)

**Comment by heitorlessa** [comment]
@pcolazurdo you have tons of experience with Config - are there any known gotchas with [events from Config](https://docs.aws.amazon.com/config/latest/developerguide/evaluate-config_develop-rules_example-events.html)? e.g., structure changes slightly when X is configured

@ctacka thank you for the feature request! Besides the data class, are there any repetitive task that we could make it easier as part of this new data class?

Added the correct labels to watch for +1 to help us prioritize.

Thank you!

**Comment by pcolazurdo** [comment]
As mentioned by @ctacka there are tree types of Config Rules events: Evaluations Triggered by Configuration Changes, Evaluations Triggered by Oversized Configuration Changes and Evaluations Triggered by Periodic Frequency. The three events have a lot of common fields, and they are around 10 (as of today) in total. 

Two of these fields encode most of the important information about the rule evaluation. They come encoded as JSON string and they don't have a well defined schema as they depend on the rule itself.

IMHO, the added value of these three new data classes will be limited. Considering the effort to maintain this feature over time, I would try to capture addition additional interest on this feature before adding it into the project.

As the [AWS config Rule Development Kit (RDK)](https://github.com/awslabs/aws-config-rdk) is the tool specifically designed to help create Config Rules, I would try to consider if that is not a better place to suggest improvements around the experience of Config Rules development.

**Comment by ran-isenberg** [comment]
+1 for Parser support too. Once there's a dataclass example, the parser can be implemented easily

**Comment by gdenn** [comment]
@pcolazurdo @heitorlessa I am new to the community. Any chance I could work on this issue? I am familiar with the AWS Config basics but I would need some guidance for this.

**Comment by leandrodamascena** [comment]
Hi @gdenn! How are you? Thank you for your interest in helping us create this new feature, we always love it when the community gets involved to contribute to this project. Sorry for the late reply, but March was a busy month and we are revisiting any issues to update and move forward.

Powertools is a project that aims to help customers adopt serverless quickly and following best practices, and one of the utilities we have to fulfill this mission is the "[Event Source Data Class](https://awslabs.github.io/aws-lambda-powertools-python/2.12.0/utilities/data_classes/)". This utility creates classes based on the services that can invoke the lambda (and there are many), these classes help to make the code cleaner and help the developer to access the objects/properties of that class more easily. Look at this [example](https://awslabs.github.io/aws-lambda-powertools-python/2.12.0/utilities/data_classes/#s3) where a developer can use a specific event source class for S3 event. With just a few lines of code, the developer can access the properties of an [S3 event that invokes Lambda](https://docs.aws.amazon.com/lambda/latest/dg/with-s3-example.html).

To add a new EventSource Class you need to create a class and a test for that new class. [You can check this PR](https://github.com/awslabs/aws-lambda-powertools-python/pull/1540/files) where we added a class for KinesisFirehoseEvent.

I'm still not sure if we'll be adding this new EventSource in upcoming releases, but if so, are you still available to do this? We can work together and I can help you with some guidance.

Thank you so much.

**Comment by leandrodamascena** [comment]
Starting to add this feature.
