### ISSUE TITLE
[Support Lambda Powertools]: TopSport

### ISSUE THREAD

**Issue by peterschutt** [awslabs/aws-lambda-powertools-python#1673]
### Organization Name

TopSport.com.au

### Your Name

Peter Schutt

### Your current position

Engineer

### (Optional) Company logo

https://www.topsport.com.au/assets/images/logo_pulse.svg

### Also using other Lambda Powertools languages?

- [ ] Java
- [ ] TypeScript
- [ ] .NET

**Comment by heitorlessa** [comment]
Thank you so much Pete!!
