### ISSUE TITLE
Docs: Explain the use of AWS X-Ray SDK over the OpenTelemetry/ADOT for tracing instrumentation

### ISSUE THREAD

**Issue by Dilski** [awslabs/aws-lambda-powertools-python#1675]
### What were you searching in the docs?

At time of writing, the [AWS X-Ray SDK for Python](https://github.com/aws/aws-xray-sdk-python) project recommends the following:

> AWS X-Ray recommends using AWS Distro for OpenTelemetry (ADOT) to instrument your application instead of this X-Ray SDK due to its wider range of features and instrumentations.

However the AWS Lambda Powertools, whose aim is to "..to ease adopting best practices such as tracing...", uses the X-Ray SDK. This could be confusing for folks looking for AWS's recommended best practices regarding how to trace their Python Lambda functions.

### How can we improve?

It would be useful to include documentation in the Tracing powertools docs page to explain the reasons for using the X-Ray SDK in python lambda functions (and why ADOT is not _yet_ used by Powertools).

Separately, the [X-Ray developer guide](https://github.com/awsdocs/aws-xray-developer-guide/blob/main/doc-source/xray-instrumenting-your-app.md) should include this information in it's section "Choosing between the AWS Distro for OpenTelemetry and X-Ray SDKs".

### Acknowledgment

- [X] I understand the final update might be different from my proposed suggestion, or refused.

**Comment by heitorlessa** [comment]
Thanks for opening the issue @Dilski :) Quick update: We spoke to the X-Ray SDK team and they'll update the repository and Docs to better reflect **when** OTel/ADOT is recommended.

From our side, we should have this by Friday EOD

**Comment by Dilski** [comment]
@heitorlessa thanks a bunch!

**Comment by heitorlessa** [comment]
hey @Dilski [this is now available](https://awslabs.github.io/aws-lambda-powertools-python/2.2.0/core/tracer/#getting-started) as part of 2.2.0 release - lemme know if that doesn't suffice.

[Lambda docs](https://docs.aws.amazon.com/lambda/latest/dg/python-tracing.html) have also been updated with the following - marked the specific in bold (X-Ray docs is WIP):

> ADOT is the preferred method for instrumenting your Lambda functions. We recommend using ADOT for all new applications. However, due to the flexibility OpenTelemetry offers, your Lambda function invocations may experience cold start latency increases. **If you're optimizing for low-latency and also do not require OpenTelemetry's advanced capabilities such as telemetry correlation and dynamically configurable backend destinations, you may want to use the AWS X-Ray SDK over ADOT**.

<img width="1358" alt="image" src="https://user-images.githubusercontent.com/3340292/200374661-ecc9bdb0-fd24-450e-9682-247990d72dea.png">

Thank you again for helping us be more precise on multiple channels.

**Comment by Dilski** [comment]
@heitorlessa amazing, thank you!

**Comment by cristianocca** [comment]
Hello, xray is getting deprecated and will be end of life in 2027 (https://github.com/aws/aws-xray-sdk-python/?tab=readme-ov-file), is using X-Ray over ADOT still a good option?

**Comment by leandrodamascena** [comment]
> Hello, xray is getting deprecated and will be end of life in 2027 ([aws/aws-xray-sdk-python](https://github.com/aws/aws-xray-sdk-python/?tab=readme-ov-file)), is using X-Ray over ADOT still a good option?

Hey @cristianocca! thanks a lot for commenting in this issue and raising your concerns! We are aware of this deprecation, and it will specifically affect customers using our tracer utility. You can use XRay yet and I think it's still a good option while you plan a migration to OTEL.

As always, we are actively working to provide the best for our customers, and we already have an RFC in place to discuss the OTEL implementation in Powertools.
XRay EOL is planned for early 2027, which gives us time to ensure a smooth transition for customers from the XRay SDK to OTEL.

I encourage you to join the discussion that will help shape our future with OTEL support: https://github.com/aws-powertools/powertools-lambda/discussions/90.

Thanks a lot.
