### ISSUE TITLE
Docs: Update `POWERTOOLS_DEV` default value

### ISSUE THREAD

**Issue by dreamorosi** [awslabs/aws-lambda-powertools-python#1694]
### What were you searching in the docs?

Me and @ijemmy were checking the default value of the newly introduced `POWERTOOLS_DEV` environment variable in the docs.

In doing so we noticed that the current version of the docs says the value is `0` instead of `false`.

### Is this related to an existing documentation section?

https://awslabs.github.io/aws-lambda-powertools-python/2.2.0/#environment-variables

### How can we improve?

```markdown
There's an opportunity to improve clarity on that env var by specifying that the default value is `false`.
```

### Got a suggestion in mind?

The value should be `false` instead of `0`.

### Acknowledgment

- [X] I understand the final update might be different from my proposed suggestion, or refused.

**Comment by heitorlessa** [comment]
Thanks a lot Andrea! Just rebuilt the latest docs with your PR ;)
