### ISSUE TITLE
Bug: missing tag for 2.4.0

### ISSUE THREAD

**Issue by tonnico** [awslabs/aws-lambda-powertools-python#1748]
### Expected Behaviour

tag 2.4.0 exists

### Current Behaviour

pypi.org has 2.4.0 but latest tag is 2.3.1

### Code snippet

```python
n/a
```

### Steps to Reproduce

look into current tags in the repository

### AWS Lambda Powertools for Python version

2.4.0

### AWS Lambda function runtime

3.9

### Packaging format used

PyPi

**Comment by heitorlessa** [comment]
We're affected by a GitHub Pages disruption @Wurstnase - we will publish the release notes along with the tag as soon as that's [resolved](https://github.com/actions/deploy-pages/issues/81).

**Comment by rubenfonseca** [comment]
We were finally able to publish the documentation and craft a new release. Thank you for your patience!
