### ISSUE TITLE
Fix Idempotent Batch Processing example

### ISSUE THREAD

**Issue by andrewhharmon** [awslabs/aws-lambda-powertools-python#1763]
### What were you searching in the docs?

Trying to understand why my code was throwing the following warning when trying to process SQS records with an idempotent function `UserWarning: Couldn't determine the remaining time left. Did you call register_lambda_context on IdempotencyConfig?` 

### Is this related to an existing documentation section?

https://awslabs.github.io/aws-lambda-powertools-python/2.4.0/utilities/idempotency/#idempotent_function-decorator

### How can we improve?

Please see the discussion [here](https://github.com/awslabs/aws-lambda-powertools-python/discussions/1762). 

### Acknowledgment

- [X] I understand the final update might be different from my proposed suggestion, or refused.

**Comment by heitorlessa** [comment]
Just rebuilt the latest docs to include the new improvements @andrewhharmon - thank you again for helping improve everyone's experience!

I extracted the batch integration into its own sub-section to make it easier to spot. Included the full snippet with comments, and a note about uniqueness as it's key for idempotency.

https://awslabs.github.io/aws-lambda-powertools-python/2.4.0/utilities/idempotency/#batch-integration

<img width="1148" alt="image" src="https://user-images.githubusercontent.com/3340292/207363157-410cefe1-722b-40f7-a59a-b3d5e0d89164.png">
