### ISSUE TITLE
Docs: Validation jmespath functions link

### ISSUE THREAD

**Issue by niko-achilles** [awslabs/aws-lambda-powertools-python#1766]
### What were you searching in the docs?

Searching for validation,  
events or responses that contain non-encoded JSON, where  decoding before validating is needed.

### Is this related to an existing documentation section?

https://awslabs.github.io/aws-lambda-powertools-python/2.4.0/utilities/validation/#built-in-jmespath-functions

### How can we improve?

The Link https://awslabs.github.io/utilities/jmespath_functions
responses back as page not found .

So the correct link is needed to designate the reader to right direction.

### Got a suggestion in mind?

I think that this link has the potential to be the correct one: https://awslabs.github.io/aws-lambda-powertools-python/2.4.0/utilities/jmespath_functions/

### Acknowledgment

- [X] I understand the final update might be different from my proposed suggestion, or refused.

**Comment by heitorlessa** [comment]
Ugh, another doc we haven't managed to refactor it yet completely - thank you so much for flagging that @niko-achilles ;)

Sending a fix shortly

**Comment by heitorlessa** [comment]
Just rebuilt the latest docs with the fix ;) Thank you again Niko for helping us improve everyone's experience.

https://awslabs.github.io/aws-lambda-powertools-python/2.4.0/utilities/validation/#validating-custom-formats

<img width="1396" alt="image" src="https://user-images.githubusercontent.com/3340292/207362925-ab34365e-c65c-4717-a939-2be7c972f318.png">
