### ISSUE TITLE
Feature request: introduce ALBRouter, etc. to set the type of current_event in the REST API Router

### ISSUE THREAD

**Issue by kmkhr** [awslabs/aws-lambda-powertools-python#1781]
### Use case

In #761, `APIGatewayRestResolver`, `APIGatewayHttpResolver`, `ALBResolver`, and `LambdaFunctionUrlResolver` were created to access all properties from `current_event`.
I would like to access all properties from `current_event` in router as well.

### Solution/User Experience

```python
router = ALBRouter()

@router.get("/todos")
def get_todos():
    router.current_event.request_context.elb_target_group_arn
```

### Acknowledgment

- [X] This feature request meets [Lambda Powertools Tenets](https://awslabs.github.io/aws-lambda-powertools-python/latest/#tenets)
- [ ] Should this be considered in other Lambda Powertools languages? i.e. [Java](https://github.com/awslabs/aws-lambda-powertools-java/), [TypeScript](https://github.com/awslabs/aws-lambda-powertools-typescript/)

**Comment by heitorlessa** [comment]
hey @kt-hr, did you run into any issue when accessing `current_event` from a Router instance?

It should work, please let us know otherwise with a snippet we can reproduce - [Test](https://github.com/awslabs/aws-lambda-powertools-python/blob/develop/tests/functional/event_handler/test_api_gateway.py#L1094), [Docs Example](https://github.com/awslabs/aws-lambda-powertools-python/blob/develop/examples/event_handler_rest/src/split_route_module.py#L16), [API reference](https://awslabs.github.io/aws-lambda-powertools-python/2.4.0/api/event_handler/api_gateway.html#aws_lambda_powertools.event_handler.api_gateway.Router)

<img width="1196" alt="image" src="https://user-images.githubusercontent.com/3340292/207410851-862921a0-2bcb-49b2-8e72-166e1355eddf.png">

**Comment by kmkhr** [comment]
hi @heitorlessa , thank you for your confirmation. Sorry, let me correct the content.

I mistakenly thought I could not access properties because the IDE was showing an error.

The type of `current_event` is `BaseProxyEvent`, so when I want to access properties such as elb_target_group_arn, the IDE completion does not work.
Although the completion will work by informing the IDE of the type with `cast`, we think it would be easier to understand if it were `ALBRouter`, etc.

**Comment by heitorlessa** [comment]
Ahhh that makes more sense now - thanks for clarifying and updating the title. Let's do it - it should be fairly trivial as you can simply subclass, [override the type like we did for each explicit resolver class](https://github.com/awslabs/aws-lambda-powertools-python/blob/develop/aws_lambda_powertools/event_handler/api_gateway.py#L853) (`ALBResolver`), and call out in the docs that each corresponding resolver has a Router for accurate static typing.

Feel free to create a PR and we can review in January after we're back from winter holidays.

Thank you!

**Comment by rubenfonseca** [comment]
Hi @kt-hr just so I can understand this problem better, why are you not using `ALBResolver` in your code in the first place? Why are you using the bare `Router` when you know you're processing ALB events?

**Comment by kmkhr** [comment]
Hi, @rubenfonseca thank you for checking.

In my use case, I want to access properties such as `router.current_event.request_context.authorizer.principal_id` when I split it into separate modules as in the [Split routes with Router](https://awslabs.github.io/aws-lambda-powertools-python/2.5.0/core/event_handler/api_gateway/#split-routes-with-router) example.  
Cast as `typed_event = cast(APIGatewayProxyEvent, router.current_event)` to enable IDE completion.

`_router` in `APIGatewayRestResolver` `APIGatewayHttpResolver` `ALBResolver` is `List[Route]`, but `_router` in `Router` is `Dict[tuple, Callable]`, so I think they are incompatible.

**Comment by rubenfonseca** [comment]
Great, I now get the problem! Will work on this today :)

**Comment by rubenfonseca** [comment]
@kt-hr I opened a PR to fix the UX above, please feel free to leave your comment before we merge!

**Comment by kmkhr** [comment]
@rubenfonseca thank you very much. Very helpful.

I have nothing to add to that.
