### ISSUE TITLE
[Support Lambda Powertools]: globaldatanet

### ISSUE THREAD

**Issue by sthuber90** [awslabs/aws-lambda-powertools-python#1783]
### Organization Name

globaldatanet

### Your Name

Stephan Huber

### Your current position

AWS Cloud Developer

### (Optional) Company logo

https://raw.githubusercontent.com/globaldatanet/.github/main/profile/logo.png

### Also using other Lambda Powertools languages?

- [ ] Java
- [X] TypeScript
- [ ] .NET

**Comment by heitorlessa** [comment]
thank you so so much @sthuber90 <3. We'll revert as soon as we confirm placement in our docs/Powertoolsl website.

cc @dreamorosi on TS.
