### ISSUE TITLE
Brief pause on new features for winter holidays until January

### ISSUE THREAD

**Issue by heitorlessa** [awslabs/aws-lambda-powertools-python#1784]
## Brief pause

Hey everyone! Due to parental leaves and winter holidays, we will have low coverage to support [discussions](https://github.com/awslabs/aws-lambda-powertools-python/discussions), [feature requests](https://github.com/awslabs/aws-lambda-powertools-python/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3Afeature-request), and [Discord](https://discord.gg/B8zZKbbyET) until January.

## Bug prioritization

If you reported a bug that is impacting you in production, please mention @sthulb, @mploski or @heitorlessa and we will prioritize it.

We appreciate everyone's understanding and we wish you an amazing holidays (or Christmas depending on your religious orientation)!

**Comment by leandrodamascena** [comment]
We're all back, closing the issue!
