### ISSUE TITLE
`make pr` fails

### ISSUE THREAD

**Issue by michaelbrewer** [awslabs/aws-lambda-powertools-python#179]
By removing `poetry install --extras "jmespath"` from the Makefile all local builds (for a fresh environment) fails

---

## Fix

Fix would be to still run the `poetry install` minus the  jmespath part?

**Comment by heitorlessa** [comment]
What's the error? 

jmespath is a deps in pyproject.toml so this was a leftover hence removal

**Comment by heitorlessa** [comment]
Fixed it: https://github.com/awslabs/aws-lambda-powertools-python/commit/8ff6bc9db5dd638dc15148d8f255853aaf75dcbe
