### ISSUE TITLE
Error `TypeError: object of type 'NoneType' has no len()` thrown when I have the following header set 'Access-Control-Allow-Origin': None

### ISSUE THREAD

**Issue by jasmarc** [awslabs/aws-lambda-powertools-python#1791]
I'm seeing `TypeError: object of type 'NoneType' has no len()` when I have the following header set:

```
'Access-Control-Allow-Origin': None
```

_Originally posted by @jasmarc in https://github.com/awslabs/aws-lambda-powertools-python/pull/1455#discussion_r1052828216_

**Comment by leandrodamascena** [comment]
Hello @jasmarc! We merged the PR with the code to fix this issue and tomorrow we will release a new version in production. Thanks!

**Comment by jasmarc** [comment]
Awesome! Thank you :)
