### ISSUE TITLE
Docs: injected Lambda context keys do not match documentation 

### ISSUE THREAD

**Issue by aidansteele** [awslabs/aws-lambda-powertools-python#1828]
### What were you searching in the docs?

The `inject_lambda_context_output.json` example says the following keys should be emitted:

```json
{
  "cold_start": true,
  "lambda_function_name": "test",
  "lambda_function_memory_size": 128,
  "lambda_function_arn": "arn:aws:lambda:eu-west-1:12345678910:function:test",
  "lambda_request_id": "52fdfc07-2182-154f-163f-5f0f9a621d72"
}
```

The actual keys (as of version 2.5.0, layer version 17) that get emitted are: 

```json
{
  "cold_start": true,
  "function_name": "test",
  "function_memory_size": 128,
  "function_arn": "arn:aws:lambda:eu-west-1:12345678910:function:test",
  "function_request_id": "52fdfc07-2182-154f-163f-5f0f9a621d72"
}
```

Specifically: the `lambda_` prefix is dropped from `lambda_function_name`, `lambda_function_memory_size`, `lambda_function_arn` and the `lambda_request_id` is renamed to `function_request_id`.

### Is this related to an existing documentation section?

https://awslabs.github.io/aws-lambda-powertools-python/2.5.0/core/logger/#capturing-lambda-context-info

### How can we improve?

The examples should match the output generated by the library.

### Got a suggestion in mind?

It's not clear if this is a bug in the docs or the code. [This GitHub search results page](https://github.com/search?q=repo%3Aawslabs%2Faws-lambda-powertools-python%20lambda_request_id&type=code) shows where the incorrect keys appear in the docs - I suspect it's easier to fix the docs? But I'll defer to the maintainer's judgment. 

### Acknowledgment

- [X] I understand the final update might be different from my proposed suggestion, or refused.

**Comment by rubenfonseca** [comment]
Hi @aidansteele thank you so much for catching this! The documentation is wrong, I can see that the keys never had the `lambda_` prefix. Do you want to submit a PR to fix the documentation?

**Comment by aidansteele** [comment]
@rubenfonseca thanks for confirming. Sure, I'll submit a PR ASAP 👍
