### ISSUE TITLE
[Support Lambda Powertools]: Capital One

### ISSUE THREAD

**Issue by djfurman** [awslabs/aws-lambda-powertools-python#1852]
### Organization Name

Capital One

### Your Name

Daniel Furman

### Your current position

Distinguished Engineer

### (Optional) Company logo

Local SVG file, please advise where I can add it; you may resize as needed

### (Optional) Use case

Across Capital One, teams are embracing Lambda functions to build high impact serverless applications. 

After evaluation, our Python language guild has shared guidance with teams in our community discussions as well as our corporate guidelines that teams developing Lambda functions in Python leverage `aws-lambda-powertools`. This guidance has already been adopted across ~700 functions, and is a topic for each of our language guilds where we also see increasing adoption.

Our teams leverage Lambda Powertools for observability, RequestResponse event-routing, type-hinting for IDE productivity, middleware, and batch processing to name only a few of our uses.

Before Lambda Powertools, several internal projects helped to enhance developer productivity, though we are actively retiring these in-house solutions in favor of the best practices codified by this project.

Our language guild and engineers look forward to contributing this project and continuing to leverage Lambda Powertools in our serverless journey!

### Also using other Lambda Powertools languages?

- [X] Java
- [X] TypeScript
- [ ] .NET

**Comment by heitorlessa** [comment]
THANK YOU @djfurman - that's fantastic news ;)

For logo, you can create a PR to add it under "docs/media/logos" folder (need to be created).

We'll share updates on the Powertools docs location or website as soon as we can.
