### ISSUE TITLE
single_metric() to inherit default dimensions

### ISSUE THREAD

**Issue by prudnikov** [awslabs/aws-lambda-powertools-python#1859]
### Use case

At the root level I define default metric which is environment name in my case.

```
metrics = Metrics()
metrics.set_default_dimensions(Environment=ENVIRONMENT)
```

This is all fine and `Environment` gets propagated to all metrics. However, when `single_metric()` is used this default dimension is ignored. This is what I do to overcome that.
```
metrics = Metrics()

with single_metric(
    name="Metric1", unit=MetricUnit.Milliseconds, value=elapsed_ms
) as this_metric:
    this_metric.add_dimension(name="TableName", value=self.table_name)


    for name, value in metrics.default_dimensions.items():
        this_metric.add_dimension(name=name, value=value)
```

or it should be possible with `this_metric.default_dimensions = metrics.default_dimensions`, I did not tried this.

This way all the default dimensions are propagated with a single metric. 

### Solution/User Experience

When creating a `SingleMetric` with `single_metric` context manager default dimensions should be copied to a SingleMetric instance.

I can imagine the situation when you don't want to propagate default dimensions to the SingleMetric. 

To keep existing usage untouched I suppose the default behavior should be to not propagate default dimensions. So the solution can be the additional keyword argument `inherit_default_dimensions: bool = False`
```
with single_metric("Name", MetricUnit.Count, 1, inherit_default_dimensions=True) as this_metric:
    this_metric.add_dimension(name="Dim1", value="Val")
```

### Acknowledgment

- [X] This feature request meets [Lambda Powertools Tenets](https://awslabs.github.io/aws-lambda-powertools-python/latest/#tenets)
- [X] Should this be considered in other Lambda Powertools languages? i.e. [Java](https://github.com/awslabs/aws-lambda-powertools-java/), [TypeScript](https://github.com/awslabs/aws-lambda-powertools-typescript/)

**Comment by prudnikov** [comment]
I'll be happy to contribute to this feature.

**Comment by rubenfonseca** [comment]
Hi @prudnikov thank you so much for opening this issue, it's very well written and very clear! We would be happy to merge your contribution and this feature. Kudos!

**Comment by rubenfonseca** [comment]
Hi @prudnikov do you have the time to submit a PR for this issue? We would love to review it and merge it :)

**Comment by prudnikov** [comment]
@rubenfonseca I'll try to finish this today. 
By they way, this will require extracting of `SingleMetric` and `single_metric` to a separate module. I'll create `single_metric.py` and move them to this module. Otherwise there is a circular import. I need to use `Metrics` inside the `single_metric`

**Comment by prudnikov** [comment]
I just created a PR, I changed design a little bit, my motivation for that is described in the PR.
