### ISSUE TITLE
Maintenance: Add header to LICENSE

### ISSUE THREAD

**Issue by e42sh** [awslabs/aws-lambda-powertools-python#1881]
### Summary

Missing header may lead to issues with license checkers, e.g. Nexus IQ.

### Why is this needed?

Avoid false / positives when license is checked programmatically.

### Solution

Add the header `MIT No Attribution` as a first line.

### Acknowledgment

- [X] This request meets [Lambda Powertools Tenets](https://awslabs.github.io/aws-lambda-powertools-python/latest/#tenets)
- [X] Should this be considered in other Lambda Powertools languages? i.e. [Java](https://github.com/awslabs/aws-lambda-powertools-java/), [TypeScript](https://github.com/awslabs/aws-lambda-powertools-typescript/)

**Comment by heitorlessa** [comment]
Thanks a lot @meckhardt - Merging it within the next hour.

**Comment by e42sh** [comment]
@heitorlessa got feedback from Sonatype. They verified that the current license is proprietary and mentioned the metadata presented in PKG-INFO, when downloading https://files.pythonhosted.org/packages/1a/a0/e31457a2b66aa09fce91353141fcbde53cf1084328ec1c088aab215e76bd/aws_lambda_powertools-2.7.0.tar.gz.

![pic](https://user-images.githubusercontent.com/827666/216030435-4f7dbf38-7241-4662-bc5d-ecc20d45c366.png)
See https://pypi.org/project/aws-lambda-powertools/

I provided a fix, but better poetry / poetry-core must be fixed to generate the correct license metadata in PKG-INFO.

**Comment by heitorlessa** [comment]
Thanks for the heads up! Forgot for a second that Poetry generated that - I'll revert right after lunch

**Comment by heitorlessa** [comment]
Merged the last one. For attribution in the release notes, is it correct to assume you work for Sonatype @meckhardt?

Thank you again!!!

**Comment by heitorlessa** [comment]
Released 2.7.1 - could you check one more time @meckhardt please?

<img width="309" alt="image" src="https://user-images.githubusercontent.com/3340292/216065839-444921ee-7f6e-4358-a03f-12a404544886.png">


Thanks!

**Comment by e42sh** [comment]
@heitorlessa ❤️

License check from Nexus IQ runs through. Many thanks! 

>  For attribution in the release notes, is it correct to assume you work for Sonatype @meckhardt?

No, I'm freelancing and one of my customers uses Nexus IQ (Sonatype product). They scan packages for license issues and vulnurabilities and, well, there was a finding :-)

**Comment by rubenfonseca** [comment]
@meckhardt we really appreciate raising this issue and your patience while we triple checked everything was kosher. We appreciate your support and your contribution!
