### ISSUE TITLE
Understanding of the compress option

### ISSUE THREAD

**Issue by rubenfonseca** [awslabs/aws-lambda-powertools-python#1890]
### Discussed in https://github.com/awslabs/aws-lambda-powertools-python/discussions/1885

<div type='discussions-op-text'>

<sup>Originally posted by **nilsm0hr** February  1, 2023</sup>
Hi, 

I tired to understand the compress option in PowerTools. We have started to implement powertools on our functions. Some of them compressed the Lambda response in our python code and returned the base64 payload to enable larger payloads.

The documentation suggests that you just return an object, rather than the Response object powertools provides. Looking at the source code, I managed to use the powertools response object after I dumped my json response to a string. 

Would it be possible to make the docs a bit clearer around this? Not quite sure if I am misunderstanding something here.

https://awslabs.github.io/aws-lambda-powertools-python/2.7.1/core/event_handler/api_gateway/#compress

Thanks</div>

**Comment by heitorlessa** [comment]
creating a PR for this now...

hey @nilsm0hr, I've read between the lines that you didn't pass a `str` or `bytes` to the `Response(body=...)`. Then after investigating the code, or type hints in your IDE within Response, you've noticed we take string or bytes, then use Gzip to compress it hence changing to a string.

I suspect you went from:

```python
@app.get("/todos", compress=True)
def get_todos():
    return Response(200, content_types.APPLICATION_JSON, {"hello": "blah"})
```

To:

```python
@app.get("/todos", compress=True)
def get_todos():
    return Response(200, content_types.APPLICATION_JSON, json.dumps({"hello": "blah"}))
```

**Comment by heitorlessa** [comment]
Expanded the `compress` section example with an additional route using `Response` as the return. PR incoming

<img width="1501" alt="image" src="https://github.com/awslabs/aws-lambda-powertools-python/assets/3340292/0b59ceac-6fbb-4056-9ca4-7993953be683">
