### ISSUE TITLE
Bug: Object of type Response is not JSON serializable

### ISSUE THREAD

**Issue by jplauri** [awslabs/aws-lambda-powertools-python#1897]
### Expected Behaviour

I'm rather new to Powertools, but noticed there's a [Response object part of the event handler](https://awslabs.github.io/aws-lambda-powertools-python/2.7.1/api/event_handler/index.html#aws_lambda_powertools.event_handler.Response) I figured I could use to replace my own hand-crafted response.

Taking directly the use of the Response object from [Event Handler / Handling not found routes](https://awslabs.github.io/aws-lambda-powertools-python/2.7.1/core/event_handler/api_gateway/#handling-not-found-routes) results in "Unable to marshal response: Object of type Response is not JSON serializable". I'm not sure if this is a bug or just me trying to use the Response object in a way it's not intended to be used.

### Current Behaviour

Returning e.g. `Response(status_code=200)` from a lambda handler results in "Unable to marshal response: Object of type Response is not JSON serializable".

### Code snippet

```python
from aws_lambda_powertools.event_handler import (
    Response,
    content_types
)

def lambda_handler(event, context) -> Response:
    return Response(
        status_code=418, 
        content_type=content_types.TEXT_PLAIN, 
        body="I'm a teapot!") # or just return e.g., Response(status_code=200)
```

### Steps to Reproduce

1. Author from scratch a new Python 3.9 runtime lambda function from the console.
2. Add a layer, I used "arn:aws:lambda:eu-north-1:017000801446:layer:AWSLambdaPowertoolsPythonV2:20" as ARN.
3. Replace the handler code with the attached snippet.
4. Use the default test event, deploy and click test.
5. Observe the error message saying the Response object is not JSON serializable. 

### AWS Lambda Powertools for Python version

latest

### AWS Lambda function runtime

3.9

### Packaging format used

Lambda Layers

**Comment by jplauri** [comment]
Oh, perhaps I always need an event resolver. Maybe I was too quick with my "bug" report.

**Comment by jplauri** [comment]
If you read the docs carefully enough, the Response object says that "... provides greater control over what is returned from the proxy event". Further, the docs state that "you need to initialize a resolver". Indeed, if you try out:

```
from aws_lambda_powertools.event_handler import Response, content_types
from aws_lambda_powertools.event_handler import APIGatewayRestResolver
from aws_lambda_powertools.event_handler.exceptions import NotFoundError

app = APIGatewayRestResolver()

@app.not_found
def handle_not_found_errors(exc) -> Response:
    return Response(status_code=418, content_type=content_types.TEXT_PLAIN, body="I'm a teapot!")

def lambda_handler(event, context) -> Response:
    return app.resolve(event, context)
```

This works fine, so consider this as user error.

**Comment by heitorlessa** [comment]
Hey hey @jplauri - firstly, a big welcome, we're glad you're trying out Powertools ;) 

Please join us on Discord and feel free to bring any question on the #python channel as you go along - doc issues also help us find areas where we can improve guidance, onboarding etc. 

Allow me to share some quick light on this..besides the docs and our getting started tutorial

Event Handler is essentially a lightweight routing and serialisation mechanism. We take API Gateway/ALB/Function URLs event payload, and try to call the respective user function that match a given route regex.

Response class is a builder that helps serialize the response in the correct format, so these upstream services (Lambda Event Sources) don't fail the request with a HTTP 5xx, leaving no logging and trace anywhere to be found.

The app.resolve(event, context) takes the central act - it decides:

* routing - whether there's any registered function that match the URL pattern (route+HTTP Method)
* encodes the raw HTTP request into helpful properties and methods (app.current_event)
* makes the Lambda context available to your routing/view functions should you need additional metadata or know how long you left before the request times out
* call your registered function, inspects the return - if it's a dict, a tuple (dict+status code), or a Response
* build a Response (if necessary) and serializes the correct output along with HTTP Headers like CORS, and any Compression, Binary base64 responses if any

Hopefully that makes more sense but happy to show you any part around if you want more details.

Have a great weekend!

Heitor Lessa

**Comment by jplauri** [comment]
@heitorlessa Makes perfect sense, thanks for the friendly & detailed description :-)
