### ISSUE TITLE
Docs: Add IAM permissions in Idempotency

### ISSUE THREAD

**Issue by heitorlessa** [awslabs/aws-lambda-powertools-python#1901]
### What were you searching in the docs?

As described by @mattyweb in https://github.com/awslabs/aws-lambda-powertools-python/issues/1772#issuecomment-1418295944:

---

Just found this thread and upgraded to the new PowerTools in order to troubleshoot. Trying an idempotent lambda in python and this was my first time using DynamoDB.

Had to add the following actions to my lambda config:
            "Action": [
                "dynamodb:GetItem",
                "dynamodb:PutItem",
                "dynamodb:UpdateItem",
                "dynamodb:DeleteItem"
            ],

Don't know how I would have figured this out otherwise. Might be good to add this to the PowerTools Idempotency docs! (Unless I just missed it!)

---

### Is this related to an existing documentation section?

https://awslabs.github.io/aws-lambda-powertools-python/2.7.1/utilities/idempotency/

### How can we improve?

Add a dedicated section to IAM similar to other places like Parameters: https://awslabs.github.io/aws-lambda-powertools-python/2.7.1/utilities/parameters/#iam-permissions

### Acknowledgment

- [X] I understand the final update might be different from my proposed suggestion, or refused.

**Comment by leandrodamascena** [comment]
> ### How can we improve?
> Add a dedicated section to IAM similar to other places like Parameters: [awslabs.github.io/aws-lambda-powertools-python/2.7.1/utilities/parameters/#iam-permissions](https://awslabs.github.io/aws-lambda-powertools-python/2.7.1/utilities/parameters/#iam-permissions)

This is a good example, but I don't think we need to create a table for this, because we only have one resource: DynamoDB. We could do what we did here https://awslabs.github.io/aws-lambda-powertools-python/2.7.1/utilities/feature_flags/#iam-permissions.

Could be something like this:
![image](https://user-images.githubusercontent.com/4295173/216972116-6e74a08a-b789-459b-a2f2-7205201aeae9.png)

**Comment by heitorlessa** [comment]
Agree. We can expand when #1181 completes or when we add additional providers. Let's wait by EOD (Central European Time - CET) to hear whether @mattyweb would like to make his first contribution with our help, OR decide to go ahead with the change and credit Matt for spotting it (crediting should happen either way).

**Comment by heitorlessa** [comment]
Now live! Closing: https://awslabs.github.io/aws-lambda-powertools-python/2.7.1/utilities/idempotency/#iam-permissions
