### ISSUE TITLE
Bug: RuleAction Enum type was changed

### ISSUE THREAD

**Issue by royygael** [awslabs/aws-lambda-powertools-python#1909]
### Expected Behaviour

Enum should be serilizeable to dict like it was.
Now it is a breaking change

### Current Behaviour

Enum breaks when sent not as a value

### Code snippet

```python
HOUR_MIN_SEPARATOR = ":"


class RuleAction(Enum): # This should be "class RuleAction(str, Enum):"
    EQUALS = "EQUALS"
    NOT_EQUALS = "NOT_EQUALS"
    KEY_GREATER_THAN_VALUE = "KEY_GREATER_THAN_VALUE"
```

### Possible Solution

class RuleAction(str, Enum):
    EQUALS = "EQUALS"
    NOT_EQUALS = "NOT_EQUALS"
    KEY_GREATER_THAN_VALUE = "KEY_GREATER_THAN_VALUE"

### Steps to Reproduce

N/A

### AWS Lambda Powertools for Python version

latest

### AWS Lambda function runtime

3.6

### Packaging format used

Lambda Layers

**Comment by leandrodamascena** [comment]
Hi @royygael, thanks for opening this issue! I'll take a look at this, but I need help understanding it in more detail:

- Can you give more details about this? How are you using this feature? Do you have a code snippet to simulate this? I tested it in my local environment, in Lambda Runtime and everything worked as expected.

This looks like a [Hyrum's law issue](https://www.hyrumslaw.com/), but we don't want to assume anything hence more details before we decide how to proceed it. 

Thank you for providing the requested information above.

**Comment by royygael** [comment]
Hey,

Oh, yes that was indeed a typo. We are using 3.8.

Regarding the snippet, its a bit of a problem because its spread in several
places.
The issue is that we create a new class using the RuleAction as one of the
parameters. After that we assemble another class which is an aggregation of
the first class containing the RuleAction.
Upon creating the aggregation class there is an error thrown which we are
trying to save an Enum where a string should be.
If this was from the beginning like this then it wouldnt be an issue and we
would of dealt with it differently yet now it is a breaking change

Thank you


‫בתאריך יום ד׳, 8 בפבר׳ 2023 ב-17:04 מאת ‪Leandro Damascena‬‏ <‪
***@***.***‬‏>:‬

**Comment by heitorlessa** [comment]
thanks @royygael that makes sense. Let's revert it @leandrodamascena, the perf cost is minimum and we file under https://www.hyrumslaw.com/ type of unexpected dependency of an use case we didn't envision (BUT, we should be sympathetic to our customers who invested like @royygael on that assumption)

**Comment by leandrodamascena** [comment]
Ok @heitorlessa! Reverting this.

**Comment by heitorlessa** [comment]
Adding `pending-release` and connecting the PR that implemented this. The only thing we missed was an actual test to prevent this "regression" in this future

#1910
