### ISSUE TITLE
Lambda extensions?

### ISSUE THREAD

**Issue by mwarkentin** [awslabs/aws-lambda-powertools-python#191]
The [AWS Lambda Extensions announcement](https://aws.amazon.com/blogs/compute/introducing-aws-lambda-extensions-in-preview/) sounded very interesting, and seems like a lot of described use cases overlap with some things that lambda-powertools provides (secret / config fetching, metrics, logging). I'm curious if the team has looked into it and if there are any plans to hook into the new lifecycle stages that are available.

Other refs:

* https://developer.squareup.com/blog/using-aws-lambda-extensions-to-accelerate-aws-secrets-manager-access
* https://github.com/square/lambda-secrets-prefetch

Really just want to hear if the team is thinking about it and what new use cases you might see it enabling!

**Comment by heitorlessa** [comment]
hey Michael - I'll respond to this once I'm back from PTO (next week). We haven't looked into it extensively, but at first glance, external extensions could be written in Rust to help w/ multiple languages, and to also prevent an extension to equally impact startup time. 

What would you like to see as an extension (internal or external)? We'd love to hear what experience you'd like to have :)... maybe we could work something out

**Comment by nmoutschen** [comment]
Adding to this, I though that some of the main tools we have in Powertools could be useful for people developing extensions.
E.g. being able to use logging, metrics or even tracing within an extension, where we don't necessarily have a handler.

**Comment by mwarkentin** [comment]
@heitorlessa agreed, I think metrics / logging would be a stretch.

Something like the config fetching from paramstore, etc sounds kind of similar to the stuff that Square built and described in the links. Wonder if that would be a good fit? Sounded like it had some nice performance benefits, etc.

**Comment by heitorlessa** [comment]
hey @mwarkentin we decided not to go forward with an extension as the operational overhead outweigh the value it provides to customers - Extensions like Secrets and Configuration would be best handled and owned by each Product team separately a.g. AppConfig one. We'll spend the next cycles paying some tech debts instead.
