### ISSUE TITLE
Docs: Add section on how to contribute tests to the overall project

### ISSUE THREAD

**Issue by sthulb** [awslabs/aws-lambda-powertools-python#1916]
### What were you searching in the docs?

I was trying to find a section on how to setup a local test harness so I could write some tests

### How can we improve?

There needs to be a contributing/testing section in the docs to help people get up to speed faster with writing tests for the project.

### Acknowledgment

- [X] I understand the final update might be different from my proposed suggestion, or refused.

**Comment by leandrodamascena** [comment]
Hi @sthulb! Are you talking about testing in general with Powertools? In our contributing guide we have a GitPod template ready to run the Powertools tests (local + e2e) and I wonder if that's not enough.

https://github.com/aws-powertools/powertools-lambda-python/blob/develop/CONTRIBUTING.md#contributing-via-pull-requests

Thank you.

**Comment by sthulb** [comment]
@leandrodamascena I was thinking more like adding a section like: https://developer.hashicorp.com/terraform/plugin/testing/testing-patterns

**Comment by rubenfonseca** [comment]
While there may not be a dedicated "testing" section in the documentation, it's worth noting that each utility within the aws-powertools library typically includes a "Testing Your Code" section. (Example: [batch processing](https://docs.powertools.aws.dev/lambda/python/latest/utilities/batch/#testing-your-code)). This section provides guidance on how to write tests specifically for that utility.

Expanding this with a dedicated section for testing will exponentially increase the effort to maintain the code. For now I will close the issue, and I ask you to reopen if necessary.

**Comment by leandrodamascena** [comment]
@heitorlessa is working on this documentation.

Reopening.
