### ISSUE TITLE
Docs: HTTP options not supported in decorator

### ISSUE THREAD

**Issue by TownCube** [awslabs/aws-lambda-powertools-python#1922]
### What were you searching in the docs?

[HTTP Methods](https://awslabs.github.io/aws-lambda-powertools-python/2.8.0/core/event_handler/api_gateway/#http-methods) states:

`You can use named decorators to specify the HTTP method that should be handled in your functions. That is, app.<http_method>, where the HTTP method could be get, post, put, patch, delete, and options.`

However when you try and use app.options you get:

`AttributeError: 'APIGatewayRestResolver' object has no attribue 'options'`

### Is this related to an existing documentation section?

https://awslabs.github.io/aws-lambda-powertools-python/2.8.0/core/event_handler/api_gateway/#http-methods

### How can we improve?

Amend the documentation to make it clear not all HTTP methods are supported.

### Acknowledgment

- [X] I understand the final update might be different from my proposed suggestion, or refused.

**Comment by heitorlessa** [comment]
Thank you @TownCube for flagging it - we'll get it fixed tomorrow.

Out of curiosity, how do you plan on handling pre-flight requests? Maybe the [CORSConfig](https://awslabs.github.io/aws-lambda-powertools-python/2.8.0/core/event_handler/api_gateway/#cors)[1] feature can help?

If CORSConfig isn't sufficient, you can use app.route("*", method="OPTIONS") in the meantime.

Thank you for helping us improve everyone's experience.

[1] CORSConfig handles both pre-flight and auto-injecting CORS headers for responses/errors. Code snippet below from the docs

```python

import requests
from requests import Response

from aws_lambda_powertools import Logger, Tracer
from aws_lambda_powertools.event_handler import APIGatewayRestResolver, CORSConfig
from aws_lambda_powertools.logging import correlation_paths
from aws_lambda_powertools.utilities.typing import LambdaContext

tracer = Tracer()
logger = Logger()
cors_config = CORSConfig(allow_origin="https://example.com", max_age=300)
app = APIGatewayRestResolver(cors=cors_config)


@app.get("/todos")
@tracer.capture_method
def get_todos():
    todos: Response = requests.get("https://jsonplaceholder.typicode.com/todos")
    todos.raise_for_status()

    # for brevity, we'll limit to the first 10 only
    return {"todos": todos.json()[:10]}


@app.get("/todos/<todo_id>")
@tracer.capture_method
def get_todo_by_id(todo_id: str):  # value come as str
    todos: Response = requests.get(f"https://jsonplaceholder.typicode.com/todos/{todo_id}")
    todos.raise_for_status()

    return {"todos": todos.json()}


@app.get("/healthcheck", cors=False)  # optionally removes CORS for a given route
@tracer.capture_method
def am_i_alive():
    return {"am_i_alive": "yes"}


# You can continue to use other utilities just as before
@logger.inject_lambda_context(correlation_id_path=correlation_paths.API_GATEWAY_REST)
@tracer.capture_lambda_handler
def lambda_handler(event: dict, context: LambdaContext) -> dict:
    return app.resolve(event, context)
```

**Comment by leandrodamascena** [comment]
Hi @TownCube! I assigned this problem to myself, but I need to understand this in detail, mainly because we can help others to explain how to use `app.options` on their system.

As @heitorlessa mentioned, I'm also curious about what scenarios might be useful for these options and how can we handle pre-flight requests. Of course, we can add the `app.options` method to make this work according to the documentation, but can you help us explain these scenarios so we can write examples and explain them in detail? Or maybe you have bandwidth to submit a PR with this code and documentation modification? We can work together to have that. Would be amazing having your contribution here.

Thank you

**Comment by TownCube** [comment]
My use case is for dynamic CORS for both internal and external pages (so two CORS URLs) that consume the same API, hopefully I'll no longer need this once #1006 is resolved.

**Comment by leandrodamascena** [comment]
Hi @TownCube!
We understand your needs and we've reflected on this. For today's release, we will fix the docs and remove the OPTIONS method. After that, we will prioritize multiple [CORS Sources](https://github.com/awslabs/aws-lambda-powertools-python/issues/1006) in the safest possible manner, and document the ways in which customers should do this (infra+runtime). As we need a definitive solution, we will strive to add this feature to avoid more workarounds that end up creating tech debt that nobody wants.

What do you think about collaborating on this new feature submitting a PR, or even reviewing the code once we have the PR ready?

Thank you so much.
