### ISSUE TITLE
Feature request: Handle SQS FIFO queues with the Bach Processing utility

### ISSUE THREAD

**Issue by rubenfonseca** [awslabs/aws-lambda-powertools-python#1927]
### Discussed in https://github.com/awslabs/aws-lambda-powertools-python/discussions/1913

<div type='discussions-op-text'>

<sup>Originally posted by **whoDoneItAgain** February  8, 2023</sup>
I've been reading over the documentation and I cant find an answer.

Does Powertools stop processing items after a failed and marks the failed plus all subsequent as failed in its response back to SQS?

Ex. r1,r2,r3,r4,r5 is sent. function fails on r3. ReportBatchItemFailures includes r3 as well as r4 and r5.

</div>

**Comment by rubenfonseca** [comment]
I've reduced the implementation this this

```python
class SQSFifoCircuitBreakerError(Exception):
    pass

class SQSFifoPartialProcessor(BasePartialBatchProcessor):
    def _process_record(self, record: dict):
        if self.fail_messages:
            return self.failure_handler(
                record=record, exception=(SQSFifoCircuitBreakerError, SQSFifoCircuitBreakerError(), None)
            )

        return super()._process_record(record)

    async def _async_process_record(self, record: dict):
        raise NotImplementedError()
```

However, I'm unsure about two things:

1. The implementation is so simple that I wonder if it makes sense to add a `fifo` flag to the `PartialBatchProcessor` instead, and tweak the implementation to support this
2. Does it make sense to support this operation for other backends? (Kinesis, DynamoDB, etc), or should we keep the `SQS` name only?

@heitorlessa @leandrodamascena

**Comment by heitorlessa** [comment]
Atm, only SQS offers FIFO guarantees while DynamoDB/Kinesis offers ordering guarantees on a per shard-level (this goes to the drain when handling batch processing and various producer patterns) - so I'd keep it focused for SQS only for now, keeping it reusable so we could eventually add to others if they improve (by they I mean Kinesis/DynamoDB Stream).

The only semantic I'm not sure is whether it'd be useful to have a flag (like you said) in the `PartialBatchProcessor` to indicate that **we will stop at the first failure while marking subsequent unprocessed messages as failed too**.

If the answer isn't clear, I'd vote for having a specialized class for SQS to avoid confusion in other fronts, then port it to others once we have a clearer semantic in place.

PS: Implementation will be slightly more elaborated than that (you'll need to collect all message IDs to fail not process subsequent ones). I know you know, editing just in case.

**Comment by heitorlessa** [comment]
removed `triage` label
