### ISSUE TITLE
[Support Lambda Powertools]: Propellor.ai

### ISSUE THREAD

**Issue by dheerajinampudi** [awslabs/aws-lambda-powertools-python#1941]
### Organization Name

propellor.ai

### Your Name

Dheeraj

### Your current position

Chief Technology Officer

### (Optional) Company logo

https://i0.wp.com/propellor.ai/wp-content/uploads/2022/07/propellor-ai.png?fit=1116%2C261&ssl=1

### (Optional) Use case

We used to use the stock python "Logging" library, but it was hard to figure out the context and traces for the logging library. Added to that structured logging is also as issue.  I'm looking for a version of AWS and found powertools in 2021. We used Powertools to do simple logging till date, but now we want to use it to its fullest potential.

### Also using other Lambda Powertools languages?

- [ ] Java
- [ ] TypeScript
- [ ] .NET

**Comment by heitorlessa** [comment]
hey @dheerajinampudi this is awesome, **THANK YOU**! We'll feature Propellor as soon as we finish our landing page this year.

Meanwhile, if we can help with any advisory to explore its full potential of Powertools please don't hesitate in reaching out to us here, on Discord, or via e-mail if you find a call is better - aws-lambda-powertools-feedback@amazon.com
