### ISSUE TITLE
Maintenance: Automate the layer version update in the Tracer, Logger and Metrics documentation. 

### ISSUE THREAD

**Issue by leandrodamascena** [awslabs/aws-lambda-powertools-python#1969]
### Summary

The Tracer, Logger and Metrics documentation are using an old version of Lambda Layer and we must update this.

Tracer:
![image](https://user-images.githubusercontent.com/4295173/222240904-b80268af-826e-4e13-ac67-75a23d1541aa.png)

Logger:
![image](https://user-images.githubusercontent.com/4295173/222240835-34d2b799-e004-433f-9275-8c8cea1fb741.png)

Metrics:
![image](https://user-images.githubusercontent.com/4295173/222240805-6ed25ce1-6959-4ebf-95d1-dd06081e2d99.png)

### Why is this needed?

To prevent the customers from using an outdated layer.

### Acknowledgment

- [X] This request meets [Lambda Powertools Tenets](https://awslabs.github.io/aws-lambda-powertools-python/latest/#tenets)
- [ ] Should this be considered in other Lambda Powertools languages? i.e. [Java](https://github.com/awslabs/aws-lambda-powertools-java/), [TypeScript](https://github.com/awslabs/aws-lambda-powertools-typescript/)

**Comment by heitorlessa** [comment]
Most plausible explanation is that it happened after I triggered the
“rebuild documentation latest version” workflow, as it was correct since
the release (already automated)

**Comment by heitorlessa** [comment]
Actually no I take it back, I saw the notification on my phone as "layer outdated" and "damn!!!"

The installation and homepage layers are correct (V22)

But this part isn't covered in the Layer release process as it's under examples - shouldn't be hard to fix it

**Comment by leandrodamascena** [comment]
@rubenfonseca I'm assigning this issue to you because you are more familiar with the layer release process. Do you think it is possible to adjust this for the next release or do we leave it for later?
