### ISSUE TITLE
Bug: ModuleNotFoundError: No module named 'jmespath'

### ISSUE THREAD

**Issue by Tishka17** [awslabs/aws-lambda-powertools-python#1986]
### Expected Behaviour

Import will not fail

### Current Behaviour

Import is not possible. 
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "venv/lib/python3.10/site-packages/aws_lambda_powertools/__init__.py", line 7, in <module>
    from .logging import Logger
  File "venv/lib/python3.10/site-packages/aws_lambda_powertools/logging/__init__.py", line 3, in <module>
    from .logger import Logger
  File "venv/lib/python3.10/site-packages/aws_lambda_powertools/logging/logger.py", line 26, in <module>
    import jmespath
ModuleNotFoundError: No module named 'jmespath'
```

### Code snippet

```python
import aws_lambda_powertools
```

### Steps to Reproduce

1. Create new venv (I use python 3.8 and python 3.10):
```sh
python3 -m venv venv
```

2. Activate venv
```sh
source venv/bin/activate
```

3. Install powertools (tested with 2.9.1)
```sh
pip install aws-lambda-powertools==2.9.1
```

4. Try to import it in python code:
```sh
python -c "import aws_lambda_powertools"    
```

### AWS Lambda Powertools for Python version

latest

### AWS Lambda function runtime

3.8

### Packaging format used

PyPi

**Comment by heitorlessa** [comment]
hey @Tishka17, I was unable to reproduce it - could you share more on how you built the project?

I've used SAM CLI with `sam init` to scaffold a new project, built with `sam build --use-container`, deployed, and worked as expected - URL: https://76kafjxzok.execute-api.eu-west-1.amazonaws.com/Prod/hello/

Repo: https://github.com/heitorlessa/pt-issue-1986

**Comment by Tishka17** [comment]
Ok, thank you. Looks likemit is described here:
https://awslabs.github.io/aws-lambda-powertools-python/2.9.1/#local-development

**Comment by heitorlessa** [comment]
@Tishka17 yep, but thank you for opening the bug report either way... better safe than sorry. I'm rebuilding the latest docs with our new revamped Install section with more details on this, as I reckon it can be easily missed at first.

Staged docs with more details: https://awslabs.github.io/aws-lambda-powertools-python/develop/#local-development
