### ISSUE TITLE
Bug: poetry-core changed build behaviour 

### ISSUE THREAD

**Issue by sthulb** [awslabs/aws-lambda-powertools-python#2012]
### Expected Behaviour

When we run `poetry build` a setup.py file should be generated

### Current Behaviour

Because of a behaviour change in poetry-core (https://github.com/python-poetry/poetry-core/pull/318), PT no longer generates a setup.py file and this breaks for downstream users.

### Code snippet

```python
N/A
```

### Possible Solution

add: 
```
[tool.poetry.build]
generate-setup-file = true
```
to the pyproject.toml

### Steps to Reproduce

1. poetry build
2. inspect dist for setup.py

### AWS Lambda Powertools for Python version

latest

### AWS Lambda function runtime

3.6

### Packaging format used

PyPi

**Comment by heitorlessa** [comment]
>PT no longer generates a setup.py file and this breaks for downstream users.

For downstream users using custom build tools that **depend** on `setup.py` being present. :)
