### ISSUE TITLE
Docs: Link in PT language - Adding high-resolution metrics

### ISSUE THREAD

**Issue by niko-achilles** [awslabs/aws-lambda-powertools-python#2016]
### What were you searching in the docs?

Adding high-resolution metrics

### Is this related to an existing documentation section?

https://awslabs.github.io/aws-lambda-powertools-python/2.9.1/core/metrics/#adding-high-resolution-metrics

### How can we improve?

Link for creating making point to aws announcement support of high resolution metrics,
however in language `portuguese` . 
It could point to the EN version of the announcement.    

### Got a suggestion in mind?

EN version of announcement : https://aws.amazon.com/about-aws/whats-new/2023/02/amazon-cloudwatch-high-resolution-metric-extraction-structured-logs/

### Acknowledgment

- [X] I understand the final update might be different from my proposed suggestion, or refused.

**Comment by heitorlessa** [comment]
Oh wow, thank you so much @niko-achilles for catching this - that's a first.

We'll revert before releasing tomorrow
