### ISSUE TITLE
Feature request: ability to set `maxAge` and `decrypt` via environment variables for Parameters

### ISSUE THREAD

**Issue by dreamorosi** [awslabs/aws-lambda-powertools-python#2041]
### Use case

This is a cross-post from awslabs/aws-lambda-powertools-typescript#1380 opened by [mikebroberts](https://github.com/mikebroberts), in turn generated by [this Discord discussion](https://discordapp.com/channels/1006478942305263677/1088151329538580631/1088483265003925564).

Quoting:
> I typically want to always set "decrypt" to true when getting parameters (since that works just fine whether an underlying SSM param is encrypted or not, and I'm accessing infrequently enough that costs and rate limiting is not a concern), and further I'd like to have a much longer default TTL for caching parameters so that I don't have to configure on every request.

Additional context: 
At the moment customers have to specify `maxAge` and `decrypt` whenever they retrieve a parameter value. Some customer, like the OP, would instead like to set these settings at the function/environment level via env variable.

The original discussion/issue was requested for the `SSMProvider` specifically, but I believe that `maxAge` could apply to other providers as well.

### Solution/User Experience

Be able to set env vars for default values for the parameters module, e.g. :

```py
POWERTOOLS_PARAMETERS_TTL = 86400 # (1 day)
POWERTOOLS_PARAMETERS_DECRYPT = True
```

### Alternative solutions

```markdown
Creating custom wrappers around methods.
```

### Acknowledgment

- [X] This feature request meets [Lambda Powertools Tenets](https://awslabs.github.io/aws-lambda-powertools-python/latest/#tenets)
- [ ] Should this be considered in other Lambda Powertools languages? i.e. [Java](https://github.com/awslabs/aws-lambda-powertools-java/), [TypeScript](https://github.com/awslabs/aws-lambda-powertools-typescript/)

**Comment by heitorlessa** [comment]
thank you @dreamorosi !! As fast as lightning.. ⚡

**Comment by leandrodamascena** [comment]
Hey @dreamorosi! Thank you for opening this issue. I see that you suggested setting the environment variable as `POWERTOOLS_PARAMETERS_TTL` and `POWERTOOLS_PARAMETERS_DECRYPT` in this issue, but looking at the TS code, I see that you created these variable as `POWERTOOLS_PARAMETERS_MAX_AGE` and `POWERTOOLS_PARAMETERS_SSM_DECRYPT`. Reference: https://github.com/awslabs/aws-lambda-powertools-typescript/pull/1384/files#diff-b4d68dc855d0f9476d3f2ee343853bd21bf82ea9960d0cf06661baa244439dd6R308

I think it makes sense that we keep (when possible) the same configuration in all languages and will use the same name you used in Typescript.

Any objections @heitorlessa @rubenfonseca?

**Comment by dreamorosi** [comment]
Hi Leandro, I created this issue using an initial suggestion from the customer before implementing it in our repo.

Heitor has already reviewed the names in the PR, I think you should be good to go with `POWERTOOLS_PARAMETERS_MAX_AGE` and `POWERTOOLS_PARAMETERS_SSM_DECRYPT` :)

**Comment by leandrodamascena** [comment]
> Hi Leandro, I created this issue using an initial suggestion from the customer before implementing it in our repo.
> 
> Heitor has already reviewed the names in the PR, I think you should be good to go with `POWERTOOLS_PARAMETERS_MAX_AGE` and `POWERTOOLS_PARAMETERS_SSM_DECRYPT` :)

Thanks for the prompt reply @dreamorosi! You are unstoppable :)

**Comment by satishbpatil** [comment]
Easy it easier to understand POWERTOOLS_CACHE_TTL than POWERTOOLS_PARAMETERS_TTL

**Comment by leandrodamascena** [comment]
Hi @satishbpatil thanks for this suggestion. I agree that the variable name `POWERTOOLS_PARAMETERS_TTL` is confusing to understand and we changed it to `POWERTOOLS_PARAMETERS_MAX_AGE` to go the [same way](https://github.com/awslabs/aws-lambda-powertools-typescript/pull/1384/files#diff-b4d68dc855d0f9476d3f2ee343853bd21bf82ea9960d0cf06661baa244439dd6R308) that Powertools Typescript did.
