### ISSUE TITLE
SESEvent KeyError

### ISSUE THREAD

**Issue by rprentyaws** [awslabs/aws-lambda-powertools-python#208]
**What were you trying to accomplish?**

## Expected Behavior
I am trying to process an SES event using Lambda powertools for python.

## Current Behavior
Error using [this snippet](https://awslabs.github.io/aws-lambda-powertools-python/utilities/data_classes/#ses):
```
[ERROR] KeyError: 0
Traceback (most recent call last):
  File "/var/task/lambda_function.py", line 11, in lambda_handler
    common_headers = list(mail.common_headers)
  File "/opt/python/aws_lambda_powertools/utilities/data_classes/common.py", line 11, in __getitem__
    return self._data[key]

```
## Steps to Reproduce (for bugs)
1. Use the code in [this snippet](https://awslabs.github.io/aws-lambda-powertools-python/utilities/data_classes/#ses) with powertools
2. Use a test event of SES email, or just process an inbound SES email as the trigger. 
3. Check CloudWatch logs. 

## Environment

* **Powertools version used**: 1.7.0
* **Packaging format (Layers, PyPi)**: Layers
* **AWS Lambda function runtime:** Python 3.4
* **Debugging logs**

> [How to enable debug mode](https://awslabs.github.io/aws-lambda-powertools-python/#debug-mode)**

```python
[ERROR] KeyError: 0
Traceback (most recent call last):
  File "/var/task/lambda_function.py", line 11, in lambda_handler
    common_headers = list(mail.common_headers)
  File "/opt/python/aws_lambda_powertools/utilities/data_classes/common.py", line 11, in __getitem__
    return self._data[key]
```

**Comment by cakepietoast** [comment]
This is a documentation error: `common_headers` is not an iterable, so the `list()` call fails. I'll submit a PR to fix this, but in the mean time this is the corrected example:

```
from aws_lambda_powertools.utilities.data_classes import SESEvent

def lambda_handler(event, context):
    event: SESEvent = SESEvent(event)

    # Multiple records can be delivered in a single event
    for record in event.records:
        mail = record.ses.mail
        common_headers = mail.common_headers

        do_something_with(common_headers.to, common_headers.subject)
```

**Comment by heitorlessa** [comment]
Now available in the docs - closing it :)
