### ISSUE TITLE
Feature request: API Swagger documentation generator

### ISSUE THREAD

**Issue by ran-isenberg** [awslabs/aws-lambda-powertools-python#2082]
### Use case

I'd like to generate swagger JSON files describing my service out of my lambda handlers functions.
I've seen utilities such as FasTAPI do that but I want a more simplified and native lambda experience.

### Solution/User Experience

A simple decorator is added to the function handler. In runtime it will not do anything and will not impact performance.
However, the utility will supply a CLI command that will generate the JSON output file so it can be committed into the repository. 

Similar to FastAPI it can supports the following arguments:
1. general description
2. path parameters description
3. Pydantic body schema support
4. response codes
5. query parameters support

We can create a wrapper around FastAPI or write it from scratch.

### Acknowledgment

- [X] This feature request meets [Lambda Powertools Tenets](https://awslabs.github.io/aws-lambda-powertools-python/latest/#tenets)
- [X] Should this be considered in other Lambda Powertools languages? i.e. [Java](https://github.com/awslabs/aws-lambda-powertools-java/), [TypeScript](https://github.com/awslabs/aws-lambda-powertools-typescript/)

**Comment by leandrodamascena** [comment]
Hi @ran-isenberg! Thank you for opening this issue. I'm moving this topic to "On Hold" because I know @heitorlessa wants to get some ideas on this and he is out this week.

Thank you.

**Comment by pharindoko** [comment]
@ran-isenberg this issue already describes it #1236

**Comment by heitorlessa** [comment]
hey Ran, I'm closing this in favour of generating it at runtime with a new route (Swagger UI + OpenAPI generated for you): https://github.com/awslabs/aws-lambda-powertools-python/issues/2421

It'd be great to get your feedback from a Pydantic customer perspective - I suspect we might need a new Event Handler implementation altogether to make Pydantic a first class citizen like FastAPI.

https://github.com/awslabs/aws-lambda-powertools-python/issues/2421
