### ISSUE TITLE
Feature request: Reduce Batch boilerplate with a facade

### ISSUE THREAD

**Issue by heitorlessa** [awslabs/aws-lambda-powertools-python#2083]
### Use case

Customers have to decorate their Lambda handler with `batch_processor` decorator to repeatedly call a record handler for each record it walks through. 

Historically, this was kept for backwards compatibility reasons as we moved from the original Batch that used AWS SDK to delete successful messages to the [native Lambda integration launched two years later](https://docs.aws.amazon.com/lambda/latest/dg/with-sqs.html#services-sqs-batchfailurereporting).

The new integration required a strict response to make it work, so we introduced a new property `.response` in the processor, so the Lambda handler could return it in the right format.

Now that we introduced async along with some refactoring and the new typing extensions, we have access to better tools and we can make it easier to customers onboard to the Batch feature by removing this unnecessary boilerplate in a backwards compatible way.

![image](https://user-images.githubusercontent.com/3340292/229773256-37e3a717-2f67-46cc-887f-5789f3023e0b.png)

### Solution/User Experience

We can introduce a new function, call it `process_partial_response` for the sake of argument, that is responsible to:

* Extract `Records[*]` from the event, whether that is a dict or a Parser's SQS Model
* Call the processor `.process` sync using the given record handler
* Extract the final response from the processor and simply return it to the caller

**Benefits**. Besides reducing boilerplate and accelerate on-boarding, it'll reduce the call stack in Python improving performance a tiny wee bit.

![image](https://user-images.githubusercontent.com/3340292/229775274-375b269f-8636-4650-9428-4b0f79943221.png)

### Acknowledgment

- [X] This feature request meets [Lambda Powertools Tenets](https://awslabs.github.io/aws-lambda-powertools-python/latest/#tenets)
- [ ] Should this be considered in other Lambda Powertools languages? i.e. [Java](https://github.com/awslabs/aws-lambda-powertools-java/), [TypeScript](https://github.com/awslabs/aws-lambda-powertools-typescript/)

**Comment by leandrodamascena** [comment]
Hi @heitorlessa! I understand the developer experience proposition behind this change and it makes sense to create this new function `process_partial_response`. When you send the PR I can review.
