### ISSUE TITLE
Feature request: Add A method to manually flush metrics

### ISSUE THREAD

**Issue by JeffDGAWS** [awslabs/aws-lambda-powertools-python#2109]
### Use case

When not running within a standard Lambda handler (in my case, running within the Lambda Web Adapter), the @log_metrics decorator does not function. It is expecting the standard Lambda event,context parameters to be passed in.

Would be helpful to have a function that you could manually call before returning from a function to flush the metrics out to stdout so that they get logged.

### Solution/User Experience

Based on the decorator code, I built the is as a function in my code that flushes the metrics, but would be more resilient if it were in the class.

`def flush_metrics(a=None):
    m = metrics.serialize_metric_set()
    metrics.clear_metrics()
    print(json.dumps(m, separators=(",", ":")))    
    return a`

Note the parameter (a) there is not used in the function at all, and is simply returned to the caller. This was done so that I could wrap the "flush" and return into one line such as:

`    return flush_metrics({"message": f"Count: {count}"})`

### Acknowledgment

- [X] This feature request meets [Lambda Powertools Tenets](https://awslabs.github.io/aws-lambda-powertools-python/latest/#tenets)
- [ ] Should this be considered in other Lambda Powertools languages? i.e. [Java](https://github.com/awslabs/aws-lambda-powertools-java/), [TypeScript](https://github.com/awslabs/aws-lambda-powertools-typescript/)

**Comment by leandrodamascena** [comment]
Hi @JeffDGAWS! Thank you for opening this issue and helping us understand the special use cases where Powertools can help.

I'm adding this issue to our backlog to keep our eyes on it and start a discussion on how we can best do this.

**Comment by dreamorosi** [comment]
Hi Leandro, in the TS version we expose a method to do this which is called `publishStoredMetrics()`.

I'm just sharing this in case you might want to consider using a similar name (with snake_case of course), and to share [the implementation](https://github.com/awslabs/aws-lambda-powertools-typescript/blob/main/packages/metrics/src/Metrics.ts#L315-L344) & [docs](https://awslabs.github.io/aws-lambda-powertools-typescript/latest/core/metrics/#adding-default-dimensions).

**Comment by leandrodamascena** [comment]
Hello @dreamorosi! Thanks so much for sharing the TS implementation and documentation. You make things easy!! :rocket:

**Comment by rubenfonseca** [comment]
Working on this today
