### ISSUE TITLE
Maintenance: Force Powertools layer to use pydantic 1.x major version

### ISSUE THREAD

**Issue by leandrodamascena** [awslabs/aws-lambda-powertools-python#2119]
### Summary

[Pydantic 2.x will soon](https://docs.pydantic.dev/blog/pydantic-v2/) be released and requires some major changes to our Powertools code.

### Why is this needed?

This change prevents pydantic 2.x to be included with the python layer and possible break changes.

### Which area does this relate to?

Automation

### Acknowledgment

- [X] This request meets [Lambda Powertools Tenets](https://awslabs.github.io/aws-lambda-powertools-python/latest/#tenets)
- [ ] Should this be considered in other Lambda Powertools languages? i.e. [Java](https://github.com/awslabs/aws-lambda-powertools-java/), [TypeScript](https://github.com/awslabs/aws-lambda-powertools-typescript/)

**Comment by rubenfonseca** [comment]
Waiting for the new version of the cdk-aws-lambda-powertools-layer, and will submit a PR to update our repo.
