### ISSUE TITLE
feat: Add Ses lambda event support to Parser utility

### ISSUE THREAD

**Issue by risenberg-cyberark** [awslabs/aws-lambda-powertools-python#213]
This schema is currently supported in the validator utility.
This issue will add the schema to the parser utility.
Please note that there's no need for an envelope in this case, just a schema class.

**Comment by igorlg** [comment]
Can this issue be closed? #214 seems to have been merged

**Comment by heitorlessa** [comment]
Yes it can @igorlg i thought I did ;) thanks for flagging it
