### ISSUE TITLE
Maintenance: Meta-Documentation

### ISSUE THREAD

**Issue by neilramsay** [awslabs/aws-lambda-powertools-python#2181]
### Why is this needed?

Recently I received [great documentation guidance](https://github.com/awslabs/aws-lambda-powertools-python/pull/2129#issuecomment-1523082490) on a PR (#2129).

I greatly valued the guidance, and believe that others could benefit with a distilled/improved version of it.

### Which area does this relate to?

Other

### Solution

Create a `CONTRIBUTING-DOCUMENTATION.md` guide, linked from `CONTRIBUTING.md`.

I would like continue the discussion from PR #2129 to provide the "what, how, and why" for providing documentation.

### Acknowledgment

- [X] This request meets [Lambda Powertools Tenets](https://awslabs.github.io/aws-lambda-powertools-python/latest/#tenets)
- [X] Should this be considered in other Lambda Powertools languages? i.e. [TypeScript](https://github.com/awslabs/aws-lambda-powertools-typescript/)

**Comment by leandrodamascena** [comment]
Hi @neilramsay! Thank you for submitting this issue. In fact this text by @heitorlessa is an excellent guide on how we try to guide the project.

We are working on some items for this release and I have added this issue to our backlog. We'll start working on it as soon as possible.

**Comment by heitorlessa** [comment]
Starting planning this now, hopefully we can get it done by end of the year :) 

<img width="1380" alt="image" src="https://github.com/aws-powertools/powertools-lambda-python/assets/3340292/77072e80-38b3-450b-a0a6-2a2b33a53ff1">
