### ISSUE TITLE
Feature request: support custom JSON deserializer in event source classes

### ISSUE THREAD

**Issue by leandrodamascena** [awslabs/aws-lambda-powertools-python#2199]
### Use case

In some event classes (such as SQS, Kafka, and others), certain string fields (such as `body`) can be converted to JSON using the `json.loads` function. However, it is possible that the customer may have created the message with a JSON serialization method that differs from the default `json` class. To cover these scenarios, we need to provide customers with the flexibility to use a custom deserialization function of their choice.

This is important because by allowing customers to use their preferred deserialization function, we can ensure that their messages are properly deserialized into the intended format.

The default if nothing is informed will continue to be `json.loads`

### Solution/User Experience

To address the issue, we can modify the DictWrapper class to introduce a new parameter. This parameter would allow customers to provide their preferred deserialization function for converting string fields to JSON.

```python
class DictWrapper(Mapping):
    """Provides a single read only access to a wrapper dict"""

    def __init__(self, data: Dict[str, Any], json_deserializer: Optional[Callable] = None):
        self._data = data
        self._json_data: Optional[Any] = None
        self._json_deserializer = json_deserializer or json.loads
```

### Acknowledgment

- [X] This feature request meets [Lambda Powertools Tenets](https://awslabs.github.io/aws-lambda-powertools-python/latest/#tenets)
- [ ] Should this be considered in other Lambda Powertools languages? i.e. [Java](https://github.com/awslabs/aws-lambda-powertools-java/), [TypeScript](https://github.com/awslabs/aws-lambda-powertools-typescript/), and [.NET](https://github.com/awslabs/aws-lambda-powertools-dotnet/)

**Comment by facu-01** [comment]
How this can be used in APIGatewayRestResolver? i cant find the way to inject the custom json_deserializer.
```
from decimal import Decimal
from typing_extensions import Annotated
from pydantic import BaseModel
from aws_lambda_powertools.event_handler import APIGatewayRestResolver
from aws_lambda_powertools.event_handler.openapi.params import Body

app = APIGatewayRestResolver(enable_validation=True)

class DataIn(BaseModel):
    current: Decimal

@app.post('/data')
def save_data(
    data: Annotated[DataIn,  Body()],
): 
    
    return data

def lambda_handler(event, context):
    return app.resolve(event, context)
```
if a make a post with json :

```
{
    "currency": 1.00
}
``` 

The last zero is removed, this issue could be solved using `json.loads(parse_float=Decimal)`
