### ISSUE TITLE
Docs: only one non-obvious link to github on a page, and it is broken

### ISSUE THREAD

**Issue by huonw** [awslabs/aws-lambda-powertools-python#220]
**What were you initially searching for in the docs?**

A link to the repository in order to look at the source code for the `aws_lambda_powertools.utilities.typing.LambdaContext` class.

**Is this related to an existing part of the documentation? Please share a link**

I started on a subpage https://awslabs.github.io/aws-lambda-powertools-python/utilities/typing/ and then moved to the homepage https://awslabs.github.io/aws-lambda-powertools-python/ .

**Describe how we could make it clearer**

I think there's two issues here:

1. the "Edit on Github" link (that is nominally for editing the documentation) in the sidebar is broken. For instance, neither of the pages linked work:
   - https://github.com/awslabs/aws-lambda-powertools-python/tree/HEAD/content/utilities/typing.mdx
   - https://github.com/awslabs/aws-lambda-powertools-python/tree/HEAD/content/index.mdx
2. there's no obvious "here's the repository" link on either of those pages (or any others)

**If you have a proposed update, please share it here**

1. fix the links, which might require wrangling gatsby to use `develop/docs` instead of `HEAD`
2. many projects have a link to their repository as part of the docs template, and so visible on every page; for instance, one or more of:
   - https://aws.github.io/chalice/main.html (header)
   - https://aws-data-wrangler.readthedocs.io/en/stable/ (header)
   - https://cdk8s.io/docs/v1.0.0-beta.3/ (header and footer)
   - https://awslabs.github.io/sockeye/ (sidebar)
   - https://requests.readthedocs.io/en/master/ (sidebar and "Fork Me" banner: https://www.gatsbyjs.com/plugins/gatsby-plugin-github-ribbon/)

**Comment by heitorlessa** [comment]
Hi @huonw - Thank you for flagging this. This is not the experience we want customers to have.

We'll get this fixed by EOW and ping you here.

**Comment by heitorlessa** [comment]
Hi @huonw Addressed both feedbacks and we'll publish a new docs version today - Here's how the new link to the source code looks like

![image](https://user-images.githubusercontent.com/3340292/100431613-b2ed7200-3098-11eb-9cbc-0a34e83e76b2.png)

**Comment by heitorlessa** [comment]
This is now available in the docs - Thanks a lot for the feedback @huonw to help us improve it

**Comment by huonw** [comment]
Looks great!
