### ISSUE TITLE
Maintenance: Configure scheduled workflows to run only in the main repository

### ISSUE THREAD

**Issue by leandrodamascena** [awslabs/aws-lambda-powertools-python#2223]
### Why is this needed?

A customer raised a question on the [Powertools Discord](https://discord.com/channels/1006478942305263677/1006527385409179678/1104985255414349824) asking why some automations were failing in the fork they made. We need to fix this by adding a condition to run these workflows only on the main repository.

### Which area does this relate to?

Automation

### Solution

Add a condition to run these workflows only on the main repository.

### Acknowledgment

- [X] This request meets [Lambda Powertools Tenets](https://awslabs.github.io/aws-lambda-powertools-python/latest/#tenets)
- [X] Should this be considered in other Lambda Powertools languages? i.e. [Java](https://github.com/awslabs/aws-lambda-powertools-java/), [TypeScript](https://github.com/awslabs/aws-lambda-powertools-typescript/), and [.NET](https://github.com/awslabs/aws-lambda-powertools-dotnet/)

**Comment by heitorlessa** [comment]
looking
