### ISSUE TITLE
feat: Add Kinesis lambda event support to Parser utility

### ISSUE THREAD

**Issue by risenberg-cyberark** [awslabs/aws-lambda-powertools-python#226]
This schema is currently supported in the validator utility.
This issue will add the schema to the parser utility and a new envelope.
The envelope will base64 decode the user data and if a model input was given, will also parse the decoded string as a pydantic BaseModel or string.
This will allow full parsing and message extraction by using only one decorator.

If you dont supply a model, the data type of the extracted data is bytes (not base64 encoded string).

**Comment by heitorlessa** [comment]
Launched in 1.9.0 now
