### ISSUE TITLE
Feature request: Parser support for custom resource

### ISSUE THREAD

**Issue by ran-isenberg** [awslabs/aws-lambda-powertools-python#2295]
### Use case

CFN Custom resource can trigger a lambda function with a set of events: create, delete and update.
There's a clear envelope and user payload which makes it a classic candidate for the parser.
I printed the actual events and wrote an event generator for testing purposes in my own application.
here's the gist: https://gist.github.com/ran-isenberg/9a49fad3d607245f7d615696353d1a36

### Solution/User Experience
```
@event_parser(model=UserModel, envelope=envelopes.CustomResourceEnvelope)
def handler(event: UserModel, context: LambdaContext):
    assert event.password1 == event.password2
```

### Acknowledgment

- [X] This feature request meets [Lambda Powertools Tenets](https://awslabs.github.io/aws-lambda-powertools-python/latest/#tenets)
- [X] Should this be considered in other Lambda Powertools languages? i.e. [Java](https://github.com/awslabs/aws-lambda-powertools-java/), [TypeScript](https://github.com/awslabs/aws-lambda-powertools-typescript/), and [.NET](https://github.com/awslabs/aws-lambda-powertools-dotnet/)

**Comment by ran-isenberg** [comment]
I can work on it later this month if that's ok with you

**Comment by rubenfonseca** [comment]
For reference: typed structs from Go: https://github.com/aws/aws-lambda-go/blob/771b391678d3f54bfa38531774d656f5e0f2ab58/cfn/event.go

**Comment by heitorlessa** [comment]
Careful here, envelope could lead to resources being deleted: https://github.com/awslabs/aws-lambda-powertools-java/issues/1081

[on various meetings :/ so being brief]

**Comment by ran-isenberg** [comment]
@heitorlessa  any unhandled exception can cause that. I think decorator usage in this case is less ideal. But regular parse function with try/except is fine.
Are you ok with me working on it nonetheless?
I'm planning a blog post on the subject and would like to showcase the parser too.

**Comment by ran-isenberg** [comment]
> For reference: typed structs from Go: https://github.com/aws/aws-lambda-go/blob/771b391678d3f54bfa38531774d656f5e0f2ab58/cfn/event.go

it's similar to my gist, but it's not accurate 100%. OldResourceProperties does not appear in create/delete events. Only in update from my experience.

**Comment by heitorlessa** [comment]
It’s more complicated than error handling only - we had a ton of issues
with custom resources  in prod supporting internal teams.

I’m totally supportive of having a Parser model but not an envelope — it’s
easy to make mistakes and can be irreversible in some cases.

For custom resources, we keep a cross-link to handle these tricky scenarios
for that reason.


https://github.com/aws-cloudformation/custom-resource-helper

**Comment by ran-isenberg** [comment]
@heitorlessa  np, then model it is.
I'm familiar with the helper, we use it too.

**Comment by leandrodamascena** [comment]
Hi @ran-isenberg! So in this case, can you send the PR to add this support?

We are planning to release a version on Friday, so if you can send the PR by then we can include it in the next version, if not we will include it in the next release.

Thank you!
