### ISSUE TITLE
feat: Add cloudwatch lambda event support to Parser utility

### ISSUE THREAD

**Issue by risenberg-cyberark** [awslabs/aws-lambda-powertools-python#230]
This schema is currently supported in the validator utility.
This issue will add the schema to the parser utility and a new envelope.
The envelope will base64 decode the log data, and decompress it into a new field called decoded_data.   If a model input was given, it will also parse the decoded string as a pydantic BaseModel or string.
This will allow full parsing and log extraction by using only one decorator.

If you dont supply a model, the data type of the extracted data is str.

**Comment by heitorlessa** [comment]
Launched in 1.9.0 now
