### ISSUE TITLE
Bug: programmatically changing the log level fails

### ISSUE THREAD

**Issue by paulsuh** [awslabs/aws-lambda-powertools-python#2303]
### Expected Behaviour

When changing the log level of a Logger via code, the log level should be changed. 
```
from aws_lambda_powertools import Logger
powertools_logger = Logger()
powertools_logger.setLevel("DEBUG")    # the log level should become DEBUG
powertools_logger.debug("Hello, world!")    # this should produce a log message
```

### Current Behaviour

When changing the log level of a Logger via code, the log level is not changed. 
```
from aws_lambda_powertools import Logger
powertools_logger = Logger()
powertools_logger.setLevel("DEBUG")    # the log level remains at the default, INFO
powertools_logger.debug("Hello, world!")    # no log message comes out
```

### Code snippet

```python
See above, also the linked repo below
```

### Steps to Reproduce

See https://github.com/paulsuh/aws-powertools-logging-test-sam for detailed test cases and output. 

### AWS Lambda Powertools for Python version

latest

### AWS Lambda function runtime

3.9

### Packaging format used

Serverless Application Repository (SAR) App

**Comment by heitorlessa** [comment]
Hey Paul, thank you so much for reporting this — could you tell me if
setting the log_level attribute to debug works?

powertools_logger.log_level = logging.DEBUG

If it does work, I suspect setLevel is changing the superclass and not
._logger as it should be.

Thanks a lot taking the time to report it, we should fix it — we welcome a
PR if you know your way around Python logging (logger.py file)

**Comment by leandrodamascena** [comment]
Hi @heitorlessa and @paulsuh! I could reproduce the error and it's changing the superclass `logging.Logger` instead of changing the Powertools instance: .`_logger` in this case.

Paul, do you want to send a PR to fix this and get your first contribution to Powertools? If not, I can send the PR to fix this and give you the credits.

Thank you

**Comment by paulsuh** [comment]
Let me clone the repo and see what I can do

**Comment by leandrodamascena** [comment]
Hello @paulsuh! Can I help you write this fix? We are planning to release a new version today or tomorrow and it would be nice if we could include this fix.
No pressure here, we know everyone is busy with different things at work, I'm really here to offer help or even just write this and discuss the solution together when sending the PR.

Thank you so much!
