### ISSUE TITLE
Feature request: (Logger) New timestamp format - UNIX time

### ISSUE THREAD

**Issue by sk0g** [awslabs/aws-lambda-powertools-python#2336]
### Use case

The current logger supports RFC3339, as well as arbitrary `datefmt` strings.
Latter gets you close with `%s`, but it has two issues:
1. `%s` is an undocumented feature, and not always available
2. More importantly, it may be timezone-sensitive, depending on your system

### Solution/User Experience

It should be possible to elect to get epoch time (as millisecond integer) as the timestamps attached to logs.

When creating a logger variable, you should be able to indicate that preference, something like
```py
logger = aws_lambda_powertools.Logger(timestamp_format=TimestampFormat.EPOCH_MS)
```

### Alternative solutions

```py
int(datetime.datetime.now().timestamp() * 1000)
```

I would be happy to create a PR potentially, but the interface for selecting a timestamp format is already getting complicated. The simple solution, yet another flag, may be quite awkward to use or grok.

### Acknowledgment

- [X] This feature request meets [Lambda Powertools Tenets](https://awslabs.github.io/aws-lambda-powertools-python/latest/#tenets)
- [ ] Should this be considered in other Lambda Powertools languages? i.e. [Java](https://github.com/awslabs/aws-lambda-powertools-java/), [TypeScript](https://github.com/awslabs/aws-lambda-powertools-typescript/), and [.NET](https://github.com/awslabs/aws-lambda-powertools-dotnet/)

**Comment by rubenfonseca** [comment]
Thanks for your suggestion! While we understand the desire for epoch time as a timestamp format, I have concerns about its consistency and potential complexities. Adding a new flag or parameter to the logger constructor solely for selecting the timestamp format could increase complexity and may not align with our goal of providing a straightforward and intuitive interface. We strive to keep the API surface as clean as possible, avoiding unnecessary flags or options that may confuse users.

Of course you could always implement your [own formatter to have complete control over the logger output.](https://awslabs.github.io/aws-lambda-powertools-python/2.15.0/core/logger/#bring-your-own-formatter) But I would love to hear @heitorlessa and @leandrodamascena opinions on this one!

**Comment by leandrodamascena** [comment]
Hi @sk0g and @rubenfonseca! It's great to see such an interesting discussion. I completely understand the motivation behind having a different timestamp format to cover to specific cases. However, as Ruben rightly pointed out, we already offer support for customization by creating your own provider. Furthermore, if you bring your own custom format you can include other default fields in your log if necessary.

I created an example and I hope it can be useful for you.

```python
from aws_lambda_powertools import Logger
import datetime
from aws_lambda_powertools.logging.formatter import LambdaPowertoolsFormatter


class CustomFormatter(LambdaPowertoolsFormatter):
    def serialize(self, log: dict) -> str:
        log["timestamp"] = int(datetime.datetime.now().timestamp() * 1000)
        return self.json_serializer(log)  # use configured json serializer
    

logger = Logger(service="default_format", use_rfc3339=True)
logger.info("Default date format")

logger_custom_format = Logger(service="custom_format", logger_formatter=CustomFormatter())
logger_custom_format.info("Epoch time")
```

**OUTPUT**
```sh
{"level":"INFO","location":"<module>:14","message":"Default date format","timestamp":"2023-05-30T22:46:40.868+01:00","service":"default_format"}
{"level":"INFO","location":"<module>:17","message":"Epoch time","timestamp":1685483200868,"service":"custom_format"}
```

**Comment by heitorlessa** [comment]
Adding the appropriate label so we can revisit whether there's interest from more customers, as I understand is a niche use case and using a custom formatter OR overriding `formatTime` was already considered.

If epoch in seconds was okay, then the official logging attribute - `%(created)f` - would have worked too:

```python
logger = Logger(service="default_format", timestamp="%(created)f")
```

```json
{"level":"INFO","location":"<module>:21","message":"Default date format","timestamp":"1685973601.156706","service":"default_format"}
```

**Comment by heitorlessa** [comment]
Closing due to lack of demand. We'll be happy to reopen should that change in the future (10+ unique customers). A custom formatter is the preferred solution for this need.
