### ISSUE TITLE
Feature request: Add function to decode nested messages on SQS events

### ISSUE THREAD

**Issue by rafaelgsr** [awslabs/aws-lambda-powertools-python#2348]
### Use case

SQS events can encapsulate events originated in other AWS resources, such as S3 and SNS. When processing a `SQSEvent` in a Lambda function, a function to decode these nested events - returning the desired data class - would improve the user experience.

### Solution/User Experience

```
@event_source(data_class=SQSEvent)
def lambda_handler(event: SQSEvent, context):
     for record in event.records:
        nested_event: S3Event = record.decode_nested_s3_event
```

### Acknowledgment

- [X] This feature request meets [Powertools for AWS Lambda (Python) Tenets](https://awslabs.github.io/aws-lambda-powertools-python/latest/#tenets)
- [X] Should this be considered in other Powertools for AWS Lambda languages? i.e. [Java](https://github.com/awslabs/aws-lambda-powertools-java/), [TypeScript](https://github.com/awslabs/aws-lambda-powertools-typescript/), and [.NET](https://github.com/awslabs/aws-lambda-powertools-dotnet/)

**Comment by leandrodamascena** [comment]
Hello @rafaelgsr! Muito bom :smile: 

Thanks so much man for working on this. Surely unwrapping such user cases as SNS -> SQS -> Lambda will make users' lives much simpler.
Let's work on getting it merged into next week, okay?
