### ISSUE TITLE
Feature request: Add Data Class to handle VPC Lattice Event type

### ISSUE THREAD

**Issue by stephenbawks** [awslabs/aws-lambda-powertools-python#2359]
### Use case

New data class to handle event types that would be coming into Lambda from VPC Lattice.

https://docs.aws.amazon.com/vpc-lattice/latest/ug/lambda-functions.html

### Solution/User Experience

Adding new data class to accept the event type from VPC Lattice.  It has a slightly different event type.

### Acknowledgment

- [X] This feature request meets [Powertools for AWS Lambda (Python) Tenets](https://awslabs.github.io/aws-lambda-powertools-python/latest/#tenets)
- [X] Should this be considered in other Powertools for AWS Lambda languages? i.e. [Java](https://github.com/awslabs/aws-lambda-powertools-java/), [TypeScript](https://github.com/awslabs/aws-lambda-powertools-typescript/), and [.NET](https://github.com/awslabs/aws-lambda-powertools-dotnet/)

**Comment by leandrodamascena** [comment]
Thank you for opening this issue and sending the PR @stephenbawks!
I've already added this to our project board to work on next week to get it merged.
