### ISSUE TITLE
Static typing: The add_handler API from logger was removed

### ISSUE THREAD

**Issue by alexandreczg** [awslabs/aws-lambda-powertools-python#2377]
### Expected Behaviour

In version 2.4.0 adding a handler to the log was easy. I would expect adding a handler to my log to be as simple as addHandler.

### Current Behaviour

Method doesn't exist

![image](https://github.com/awslabs/aws-lambda-powertools-python/assets/131292734/aa59639e-c7fe-46ea-a064-6de1fcf3f695)

### Code snippet

```python
logger = logging.Logger()
logger.addHandler(additional_handler)
```
But that API was removed on version 2.15.0. I depend on it to be able to log to cloudwatch and other places. I was reading the changelog but could not find any reference to this. 

the only way around of this is to mess with the internals:
```python
logger._logger.addHandler(additional_handler)
```
```


### Possible Solution

Semver would dictate that the public API doesn't change with a minor version upgrade. Did I miss something something regarding this breaking change? Is there another workaround?

### Steps to Reproduce

Above

### Powertools for AWS Lambda (Python) version

latest

### AWS Lambda function runtime

3.10

### Packaging format used

PyPi

### Debugging logs

_No response_

**Comment by alexandreczg** [comment]
Apologies, closing, cannot reproduce it again.

**Comment by heitorlessa** [comment]
> Apologies, closing, cannot reproduce it again. 

Hey @alexandreczg - did you get a runtime error or was a static checker error saying the method doesn't exist?

The former would be a regression tho I can't reproduce it either. If it's the latter, we can address that with a PR to implement it and proxy it to _logger.addHandler so mypy is happy.

This is the change I made that would cause the latter but not the former (tested with a stream handler + file log handler now).

Please let us know ;)

PS: No need to apologise, better safe than sorry and we appreciate your time flagging it very much!!

https://github.com/awslabs/aws-lambda-powertools-python/pull/2334

**Comment by alexandreczg** [comment]
Hey @heitorlessa, thank your for addressing this, commendable your dedication!

It was a typing error actually, not runtime. I use pyright/pylance (vscode). I freaked out since it had been a long hours day and when I was about to push my code I start getting that error. Couldn't really understand it since it had been working. I regressed to version 2.4.0 (it was my last stable version) but quickly realized that I had implemented the new batch partial processor (SQS). So, I went back to 2.16.0 and magically the linting error went way... I'm not sure what or how it all happened, but when I introspected the logger class, I couldn't find the `addHandler` method. 

I'll keep your and this thread updated if something is to change now that I have pushed my code to AWS and using latest layer. 🤞

**Comment by alexandreczg** [comment]
@heitorlessa , okay in version 2.16.1 the issue is back

![image](https://github.com/awslabs/aws-lambda-powertools-python/assets/131292734/4f87159b-6d7e-4a59-9a93-0fcdbfb092ba)

**Comment by heitorlessa** [comment]
> @heitorlessa , okay in version 2.16.1 the issue is back
> 
> 
> 
> ![image](https://github.com/awslabs/aws-lambda-powertools-python/assets/131292734/4f87159b-6d7e-4a59-9a93-0fcdbfb092ba)
> 
> 

That's the piece I mentioned it's expected -- does it fail if you run it?

Pyright (what Pylance uses) can't infer through the object proxy so it believes it doesn't exist. At runtime, it works.

If you can confirm it works, feel free to make a PR adding a "addHandler" method that call self._logger.addHandler so Pylance will be happy in the next release - more than happy to accommodate that ;)

**Comment by alexandreczg** [comment]
Hi @heitorlessa, I can confirm it works. I will look into how I can open a PR to fix the linting. Another note, unrelated but would like your eyes on the batch_processor. I don't think it is working as it should:

![image](https://github.com/awslabs/aws-lambda-powertools-python/assets/131292734/58af856c-1bd4-496d-9ea9-b5b275a8b088)

It is doing `records: List[Dict] = event.get("Records", [])` but catching any `AttributeError` that comes from that line. I don't believe this will ever catch anything. BAsically, I'm passing any event to it, and it's just going into the:

```python
with processor(records, record_handler, context):
        processor.process()
```

with an empty list of records which of course returns: 

```
{'batchItemFailures': []}
```

I don't think this is supposed to happen. Please, correct me if I am wrong. I will create a new bug ticket if needed for tracking purposes. 

Edit: Better screenshot with filename included.

**Comment by heitorlessa** [comment]
hey @alexandreczg - we included the `addHandler` as part of an emergency release we had to make, so v2.16.2 (or Layer v34) will make Pylance happy; there'll surely be many opportunities for contribution.

on Batch, please create an issue describing your intended outcome. The reason we're defensively catching `AttributeError` is that some customers don't pass the event like you are (expected usage) - if they pass a list of records this will fail with an `AttributeError`, therefore raising a more helpful error on why that's the case.

As to `{'batchItemFailures': []}`, [this is expected when you don't have any error](https://awslabs.github.io/aws-lambda-powertools-python/2.16.2/utilities/batch/#partial-failure-mechanics). Batch will include message IDs that failed to be processed. If you throw any exception in your record handler function, you'll see this populated.

An empty `{'batchItemFailures': []}` means: "Entire batch processed successfully, please delete all messages".

```python
from aws_lambda_powertools.utilities.batch import (
    AsyncBatchProcessor,
    EventType,
    async_process_partial_response,
)
from aws_lambda_powertools.utilities.data_classes.sqs_event import SQSRecord
from aws_lambda_powertools.utilities.typing import LambdaContext

processor = AsyncBatchProcessor(event_type=EventType.SQS)


async def async_record_handler(record: SQSRecord):
    ...


def lambda_handler(event, context: LambdaContext):
    records = event.get("Records", [])

    # This will fail because `records` is no longer a Dict
    return async_process_partial_response(
        event=records, record_handler=async_record_handler, processor=processor, context=context
    )
```

**Comment by alexandreczg** [comment]
@heitorlessa thank your for the quick around on this 🙇
