### ISSUE TITLE
Maintenance: Add Ruff as the linter 

### ISSUE THREAD

**Issue by leandrodamascena** [awslabs/aws-lambda-powertools-python#2380]
### Why is this needed?

Ruff is an extremely fast Python linter and code transformation tool, written in Rust. 

Ruff can be used to replace [Flake8](https://pypi.org/project/flake8/) (plus dozens of plugins), [isort](https://pypi.org/project/isort/), [pydocstyle](https://pypi.org/project/pydocstyle/), [yesqa](https://github.com/asottile/yesqa), [eradicate](https://pypi.org/project/eradicate/), [pyupgrade](https://pypi.org/project/pyupgrade/), and [autoflake](https://pypi.org/project/autoflake/), all while executing tens or hundreds of times faster than any individual tool.

https://beta.ruff.rs/docs/

- [x] #2529
- [x] #2530
- [x] #2531
- [x] #2532
- [x] #2533
- [x] #2534
- [x] #2535

### Which area does this relate to?

Tests, Automation

### Acknowledgment

- [X] This request meets [Powertools for AWS Lambda (Python) Tenets](https://awslabs.github.io/aws-lambda-powertools-python/latest/#tenets)
- [ ] Should this be considered in other Powertools for AWS Lambda languages? i.e. [Java](https://github.com/awslabs/aws-lambda-powertools-java/), [TypeScript](https://github.com/awslabs/aws-lambda-powertools-typescript/), and [.NET](https://github.com/awslabs/aws-lambda-powertools-dotnet/)

**Comment by heitorlessa** [comment]
YES! Make sure to take note of the speed improvement in CI too (this should
decrease our installation step + linting, and `make pr` both locally and in
CI)

**Comment by leandrodamascena** [comment]
> YES! Make sure to take note of the speed improvement in CI too (this should decrease our installation step + linting, and `make pr` both locally and in CI)
> […](#)

This is a good first impression :smile: 

![image](https://github.com/awslabs/aws-lambda-powertools-python/assets/4295173/8a07e8c1-ff1f-42bd-b70d-a9d6dc1cb264)
