### ISSUE TITLE
Bug: v2.16.1 [ERROR] Runtime.ImportModuleError: Unable to import module 'src.generate_token': aws-lambda-powertools Traceback (most recent call last):

### ISSUE THREAD

**Issue by bronzeson** [awslabs/aws-lambda-powertools-python#2381]
### Expected Behaviour

Expected our lambdas to run normally with the new version of aws-lambda-powertools

### Current Behaviour

We get errors on importing aws-lambda-powertools with v2.16.1, but v2.15.0 works fine.

We experienced errors on all of our lambdas that use aws-lambda-powertools with 2.16.1. We import 'aws_lambda_powertools' in a requirements.txt file in a layer.

Then we attach that layer to a lambda. The lambda calls import like this 
'''
from aws_lambda_powertools import Logger
'''

This is where we get the failure:
'''
[ERROR] Runtime.ImportModuleError: Unable to import module 'src.generate_token': aws-lambda-powertools Traceback (most recent call last):
'''

There is no other information, and it is really difficult to tell why it is failing. But pinning the requirements.txt file to 2.15.0 fixed everything.

### Code snippet

```python
'''
from aws_lambda_powertools import Logger
'''
```

### Possible Solution

Roll back to 2.15.0

### Steps to Reproduce

- Create a requirements.txt file with aws_lambda_powertools (note: we use underscores here but have seen it different in different places. We did try with dashes, but experienced failure)
- Create a Lambda Layer with the requirements.txt file
- Create a Lambda that uses the Layer
- Import aws_lambda_powertools Logger (from aws_lambda_powertools import Logger)

### Powertools for AWS Lambda (Python) version

latest

### AWS Lambda function runtime

3.9

### Packaging format used

Lambda Layers

**Comment by leandrodamascena** [comment]
Hello @bronzeson! Thank you very much for opening this issue and reporting that. We really want to understand if this is 
 a bug or if it might be one of your dependencies. 

I tried to reproduce it here but I couldn't. Could you please check my steps and see if I'm missing something? 

```sh
mkdir testlayer
cd testlayer
python -m venv .env
source .env/bin/activate
echo aws_lambda_powertools > requirements.txt
pip install -r requirements.txt
mkdir python
cp -pR .env/lib/python3.10/site-packages/* python
zip -r layer.zip python
aws lambda publish-layer-version --layer-name "test-layer-issue-2381" --region=us-east-1 --zip-file "fileb://layer.zip"
```

**LAYER**
![image](https://github.com/awslabs/aws-lambda-powertools-python/assets/4295173/9bddb575-7a65-4512-b27e-9a6394b705c6)

**FUNCTION**
![image](https://github.com/awslabs/aws-lambda-powertools-python/assets/4295173/bf132c34-9b42-4c52-b1f6-a24aaeaa1c30)

**CODE**
![image](https://github.com/awslabs/aws-lambda-powertools-python/assets/4295173/42a8f95d-6174-43ba-ac89-6a3c5780f3ab)


**EXECUTION**
![image](https://github.com/awslabs/aws-lambda-powertools-python/assets/4295173/a9f18860-6ae4-4326-8329-be218d815da7)

**Comment by leandrodamascena** [comment]
I am adding the `cant-reproduce` label for now.

**Comment by heitorlessa** [comment]
Runtime.ImportModuleError is typically a build error - another dependency
that makes use of  C-extensions end up being built in another architecture
then fail at runtime.

If you could share how you’re building these layers, and what else is in
your dependencies (requirements.txt), we should be able to get close to
your environment.

If it’s on us, we’ll happily make a patch release ASAP

**Comment by CJTurpie** [comment]
I had a similar issue yesterday that might be related and help shed some light on the issue. I received the following error in our cloudwatch logs when attempting to use v2.16.1 but no error with v2.15.0:

`Unable to import module 'platform_api.main': No package metadata was found for aws-lambda-powertools`

I'm deploying a lambda using the serverless framework (with serverless-python-requirements) using a pipfile with the following line:
`aws-lambda-powertools = {extras = ["pydantic"], version = "*"}`

we are using Python 3.10

**Comment by heitorlessa** [comment]
This is super useful @CJTurpie, thank you so much for jumping in. This means the `METADATA` folder is being removed as part of the `serverless-python-requirements` build process, which is not advisable.

We'll look into a solution that works for any custom build now and release 2.16.2.

**Comment by heitorlessa** [comment]
Got a solution that is safe to use in prod. Testing one more time before we merge and kick off a patch release.

**Comment by heitorlessa** [comment]
Making a test release to triple check: https://github.com/heitorlessa/aws-lambda-powertools-test/actions/runs/5186318297

**Comment by heitorlessa** [comment]
Kicked off prod release: https://github.com/awslabs/aws-lambda-powertools-python/actions/runs/5186799960

**Comment by heitorlessa** [comment]
Everyone - It's now available in PyPi 2.16.2. Building layers to deploy across all AWS regions (+canary testing etc etc.)

Next Layer version will be 34. 

Appreciate everyone's patience while we tested corner cases out.

**Comment by heitorlessa** [comment]
release completed: PyPi (2.16.2), Layer (34). Latest docs might take a few minutes for CDN to invalidate etc.

@bronzeson @CJTurpie @dionearle - would you mind triple checking with your build please?

I've tested with the latest Serverless framework and python-requirements plugin but want to be sure before we close it.

Thank you!

**Comment by CJTurpie** [comment]
That seems to have fixed my issue

**Comment by heitorlessa** [comment]
Great! Thank you, Carl!

**Comment by heitorlessa** [comment]
I'm closing it, please feel free to reopen otherwise @bronzeson. Confirmed with other customers it's a non-issue in the latest release.

**Comment by bronzeson** [comment]
We were indeed using serverless too. I was able to test successfully with the new release 😃 
Thanks so much for fixing this so quickly!! Much appreciated.
