### ISSUE TITLE
Maintenance: Speed up GitHub Actions

### ISSUE THREAD

**Issue by heitorlessa** [awslabs/aws-lambda-powertools-python#240]
**Problem**:

* All workflows are not using caching for Poetry (needs a special configuration), thus increasing installs time by ~1m31s 
    - whereas this could've been up to 30s in the worst case
* ~~Release workflow is running the full PR checks (tests, linters, etc.) when it could've been tested in previous PRs~~
    - ~~review whether we want to keep that as a guardrail~~
* Docs workflow are not parallel and Gatsby has a new experimental incremental build which could cut the build from ~4m to seconds

**Comment by nmoutschen** [comment]
For the second bullet point, what's the time impact to keep it as a guardrail if we do the other optimisations?

I'm personally for keeping it, as this would make the process more resilient against workflow changes in the future or if we ever need to do emergency hotfixes.

**Comment by heitorlessa** [comment]
> For the second bullet point, what's the time impact to keep it as a guardrail if we do the other optimisations?
> 
> I'm personally for keeping it, as this would make the process more resilient against workflow changes in the future or if we ever need to do emergency hotfixes.

Not enough would be the answer - Takes ~1m42s, removing it might finish in 30s. The longest here is docs build followed by Poetry cache - I'm removing the 2nd
