### ISSUE TITLE
Add support to inject additional annotations to capture_lambda_handler and capture_method in Tracer

### ISSUE THREAD

**Issue by hanninen** [awslabs/aws-lambda-powertools-python#243]
**Is your feature request related to a problem? Please describe.**
We would like to provide default annotations that are always added to the decorated functions without writing any additional calls.

**Describe the solution you'd like**
Able to pass a `Callable` as an argument to `Tracer.capture_lambda_handler` and `Tracer.capture_method` that could implement the annotation logic.

**Describe alternatives you've considered**
I first implemented a new class that inherits the `Tracer` and has this functionality as an instance method. But this needs to be added to all decorated functions separately and is easily missed.

**Comment by heitorlessa** [comment]
Hey @hanninen - You can achieve this with the middleware factory.

https://awslabs.github.io/aws-lambda-powertools-python/utilities/middleware_factory/

I do this here in this example as I add a number of common annotations as well as Logger keys 

https://github.com/aws-samples/aws-serverless-airline-booking/blob/develop/src/backend/shared/libs/src/process_booking/middleware.py

Does this help?

**Comment by heitorlessa** [comment]
hey Aki - I'm closing this as it's been over a month. Please feel free to reopen if the previous answer doesn't help you
