### ISSUE TITLE
Docs: Idempotency CDK example

### ISSUE THREAD

**Issue by ran-isenberg** [awslabs/aws-lambda-powertools-python#2433]
### What were you searching in the docs?

I was looking for a CDK idempotency table example but found only the SAM template.

### Is this related to an existing documentation section?

https://awslabs.github.io/aws-lambda-powertools-python/2.16.2/utilities/idempotency/#required-resources

### How can we improve?

Add CDK construct example

### Got a suggestion in mind?

I'll do it :)

### Acknowledgment

- [X] I understand the final update might be different from my proposed suggestion, or refused.

**Comment by rubenfonseca** [comment]
@ran-isenberg thanks for submitting this! Looking at it now
