### ISSUE TITLE
APIGatewayRestResolver route matching order

### ISSUE THREAD

**Issue by royassis** [awslabs/aws-lambda-powertools-python#2439]
### Expected Behaviour

When there are two routes:
1. GET /studies/fetch
2. GET /studies/{studyid}

And a request is sent to /studies/fetch, the request should be routed to the first endpoint.

### Current Behaviour

Request if routed to the second endpoint.

### Code snippet

```python
from aws_lambda_powertools.event_handler import APIGatewayRestResolver

app = APIGatewayRestResolver()


@app.get("/studies/<studyid>")
def get_study(studyid):
    return "get_study"


@app.get("/studies/fetch")
def fetch_studies():
    return "fetch_studies"


def handler(event, context):
    return app.resolve(event, context)
```

### Steps to Reproduce

Create a SAM project with the snippet as a lambda. 
Invoke with /studies/fetch

### Powertools for AWS Lambda (Python) version

latest

### AWS Lambda function runtime

3.10

### Packaging format used

Serverless Application Repository (SAR) App

**Comment by royassis** [comment]
Seems like using **strip_prefixes** in the init parameters like it says in the [docs](https://awslabs.github.io/aws-lambda-powertools-python/2.16.2/core/event_handler/api_gateway/#custom-domain-api-mappings), resolved the issue. 
Seems that I missed it.

**Comment by royassis** [comment]
Seems that it didn't help. It might be related to the order in which the functions (with the routing decorators) are defined.

**Comment by rubenfonseca** [comment]
Looking at this now

**Comment by rubenfonseca** [comment]
Great finding @royassis, submitting a PR in a few minutes.

**Comment by heitorlessa** [comment]
@rubenfonseca is controlling the release date this week but let us know if you can't workaround it now @royassis (I'd say you can given the order of registration as annoying as it is).

Thank you so much for taking valuable time to report it (everyone appreciates it!) <3

**Comment by royassis** [comment]
Hey @heitorlessa I can workaround it for now 👍
