### ISSUE TITLE
Docs: Type mismatch for `N` attributes in dynamo_db_stream_event.TypeDeserializer 

### ISSUE THREAD

**Issue by abbasyadollahi** [awslabs/aws-lambda-powertools-python#2462]
### What were you searching in the docs?

I wasn't sure which type of issue this is, but felt like documentation was the most appropriate.

After fetching an `N` attribute from a DynamoDB [`StreamRecord`](https://github.com/awslabs/aws-lambda-powertools-python/blob/develop/aws_lambda_powertools/utilities/data_classes/dynamo_db_stream_event.py#L109), I get a `Decimal` object (as expected given the [`_deserialize_n`](https://github.com/awslabs/aws-lambda-powertools-python/blob/develop/aws_lambda_powertools/utilities/data_classes/dynamo_db_stream_event.py#L75) method), although the [`deserialize` docstring](https://github.com/awslabs/aws-lambda-powertools-python/blob/develop/aws_lambda_powertools/utilities/data_classes/dynamo_db_stream_event.py#L42) indicates that it should be a `str`.

```python
@event_source(data_class=DynamoDBStreamEvent)
def handler(event: DynamoDBStreamEvent, context: LambdaContext) -> None:
    for record in event.records:
        print(type(record.dynamodb.new_image.get("Timestamp")))

>>> <class 'decimal.Decimal'>
```

### Is this related to an existing documentation section?

https://github.com/awslabs/aws-lambda-powertools-python/blob/develop/aws_lambda_powertools/utilities/data_classes/dynamo_db_stream_event.py#L42

### How can we improve?

Just need to update the `deserializer` docstring, easy fix.

Before:
```python
"""
{'N': str(value)}                       str(value)
"""
```

After:
```python
"""
{'N': Decimal(value)}                   Decimal(value)
"""
```

### Acknowledgment

- [X] I understand the final update might be different from my proposed suggestion, or refused.

**Comment by rubenfonseca** [comment]
@abbasyadollahi this is absolutely spot on, thank you for the clear explanation! Would you mind submit a PR for it? I can help you to quickly merge it :)

**Comment by abbasyadollahi** [comment]
@rubenfonseca pushed out a PR with the changes, just a heads up, took the lazy route and didn't test it since it's just a docstring change 😅
