### ISSUE TITLE
Feature request: Customize error messages on SchemaValidationError exception

### ISSUE THREAD

**Issue by leonartdoss** [awslabs/aws-lambda-powertools-python#2463]
### Use case

I’m using the function “validate” from aws_lambda_powertools.utilities.validation to validate my JSON Schemas. The problem is that I’m not able to customize the error message whenever a schema is not valid (it’s encapsulated).
![IMG_2007](https://github.com/awslabs/aws-lambda-powertools-python/assets/8484872/69cb59da-28d7-436c-b4c5-4d4ca5122e7d)

### Solution/User Experience

My idea would be to have an attribute into the schema property like “errorMessage” which would contain the custom message. When handling the exception SchemaValidationError we can check if this attribute exists in the property and assign it to SchemaValidationError.validation_message.

![IMG_2008](https://github.com/awslabs/aws-lambda-powertools-python/assets/8484872/dfb2fc00-2df6-4dd2-ac94-4cd2e991d377)

I don’t know if it would be enough or if it’s also necessary to change the code of fastjsonschema library. Maybe it must know the key “errorMessage” in that approach?

### Acknowledgment

- [X] This feature request meets [Powertools for AWS Lambda (Python) Tenets](https://awslabs.github.io/aws-lambda-powertools-python/latest/#tenets)
- [X] Should this be considered in other Powertools for AWS Lambda languages? i.e. [Java](https://github.com/awslabs/aws-lambda-powertools-java/), [TypeScript](https://github.com/awslabs/aws-lambda-powertools-typescript/), and [.NET](https://github.com/awslabs/aws-lambda-powertools-dotnet/)

**Comment by rubenfonseca** [comment]
Looking at this now.

**Comment by rubenfonseca** [comment]
Oi @gamaleonardo, tudo bem?

Thank you for opening this! Have you considered catching the exception yourself and re-throwing it with your own message? I'm a little unsure about adding such a customization to a library.

Example:

```python
from aws_lambda_powertools.utilities.validation import SchemaValidationError, validate


def lambda_handler(event) -> dict:
    try:
        validate(event=event, schema={})
        return {"body": "validated", "statusCode": 200}
    except SchemaValidationError as exception:
        return {"body": f"error validating {exception.path}: {exception.validation_message}", "statusCode": 400}
```

**Comment by leonartdoss** [comment]
Oi @rubenfonseca! Tudo bem e você? :)

So, I found another solution in the meantime...
It's quite exactly the same thing I thought to implement:

```python
try:
     jsonschema.validate(event=event, schema={})
except  ValidationError as e:
     return {"message": e.schema["errorMessage"]}, http.client.BAD_REQUEST
```

It will take directly the key "errorMessage" in the property:

```json
"properties": {
     "propertyName": {
          "title": "The type",
          "type": "string",
          "errorMessage": "message"
     }
}
```

So unfortunately I had to change the library I was using from aws_lambda_powertools. But it would be interesting to have also the same functionality, what do you think?

Thank you for your feedback!

**Comment by leandrodamascena** [comment]
Opa @gamaleonardo! 

If I understand correctly, you're trying to create a custom error message for each property to make it easier to return it to whoever invokes this API, right? I would say based on this line:

`return {"message": e.schema["errorMessage"]}, http.client.BAD_REQUEST`

If this is correct, I have a few considerations:

1 - Our validation utility supports [Official JSON Schema](https://json-schema.org/learn/getting-started-step-by-step.html) and in the official definition the `errorMessage` field does not exist. What you can do is create a new field called `properties` and add this custom field inside it, like this:

```json
"properties": {
     "propertyName": {
          "title": "The type",
          "type": "string",
          "properties": {
	        "errorMessage": {
	          "type": "string"
	        },
     }
}
```

2 - We use `fastjsonschema` in our validation utility, and the API definition for a `JsonSchemaException` does not support any fields other than message, path, type, definition, rule, and rule_definition. Reference here: https://horejsek.github.io/python-fastjsonschema/#api

3 - The [fastjsonschema.validate](https://github.com/awslabs/aws-lambda-powertools-python/blob/develop/aws_lambda_powertools/utilities/validation/base.py#L32) does not fail validation per field, it validates the entire schema and returns an error if validation fails. So even if we had a way to access the `errorMessage` property, I don't see a good design/DX for implementing this as we don't know exactly which field failed.

4 - Is not useful for you to catch the error as @rubenfonseca suggested?

I don't think we will be able to support this at the moment, but I think you can open an [RFC](https://github.com/awslabs/aws-lambda-powertools-python/issues/new?assignees=&labels=RFC%2Ctriage&projects=&template=rfc.yml&title=RFC%3A+TITLE) telling us your need and we can discuss how to implement this, or even change the library we use. This will have to be done via RFC as there will possibly be breaking changes and we are extremely careful with that.

Thanks so much for opening this up, it might be an interesting use case for more users as well.

Em tempo, saudades da terra boa da Bahia :)

**Comment by rubenfonseca** [comment]
Hi @gamaleonardo let us know if you still need assistance with this issue, otherwise we would be happy to close it!

_Adding "revisit-in-3-months" tag_

**Comment by leonartdoss** [comment]
Hi @rubenfonseca, @leandrodamascena!
Sorry for the delay. No worries, I think you can close it. And thank you very much for your feedbacks!

Grande abraço!

**Comment by leandrodamascena** [comment]
Obrigado @gamaleonardo!
