### ISSUE TITLE
Bug: Response headers not applying

### ISSUE THREAD

**Issue by JacksonBowe** [awslabs/aws-lambda-powertools-python#2464]
### Expected Behaviour

When returning `app.resolve` the docs say that the response content-type will be 'application/json'. 
> We serialize Dict responses as JSON, trim whitespace for compact responses, set content-type to application/json, and return a 200 OK HTTP status.

### Current Behaviour

This doesn't seem to be applying with this code:
```python
def handler(event, context):
    r = app.resolve(event, context)
    print(r)
    return r
```

Printing `r` shows the following:
```json
{
    "statusCode": 200,
    "body": "{\"message\":\"You've requested note with id: t\"}",
    "isBase64Encoded": false,
    "multiValueHeaders": {
        "Content-Type": [
            "application/json"
        ]
    }
}
```

However if I make the get request and inspect the response in Chomes Network tab I see:
```
Content-Type: text/plain
```

### Code snippet

```python
See above and below
```

### Possible Solution

Workaround is to manually add the correct header in:
```python
def handler(event, context):
    r = app.resolve(event, context)
    r['headers'] = { 'Content-Type': 'application/json' }
    return r
```

### Steps to Reproduce

Use the sample code from the tutorial.
```python
def handler(event, context):
    return app.resolve(event, context)
```

### Powertools for AWS Lambda (Python) version

latest

### AWS Lambda function runtime

3.7

### Packaging format used

Lambda Layers

**Comment by rubenfonseca** [comment]
Looking at this now

**Comment by rubenfonseca** [comment]
Hi @JacksonBowe, thank you for bringing up this issue! Based on your previous comment, it seems that the event handler resolver is returning the correct MIME type in the response. However, you mentioned that when accessing the API through the browser, you are getting the `text/plain` MIME type instead.

It's interesting to note that manually setting the `headers` resolves the problem. This leads me to a couple of observations:

1. You might be using the wrong resolver for the type of API Gateway you are working with. For example, if you are using the [API Gateway HTTP](https://awslabs.github.io/aws-lambda-powertools-python/2.16.2/core/event_handler/api_gateway/#event-resolvers) resolver, it may not function correctly with the [API Gateway REST](https://docs.aws.amazon.com/apigateway/latest/developerguide/apigateway-rest-api.html) setup.
2. If you are using the appropriate API Gateway type, there could be a misconfiguration in your route mapping that is overriding the intended MIME type.

To help us debug the issue further, could you please provide more details about the API Gateway you are using and the configuration of your route mapping? This information will assist us in resolving the problem effectively.

**Comment by rubenfonseca** [comment]
Hi @JacksonBowe please let us know if there's still a problem with this issue, otherwise maybe we can close it?

_Adding revisit-in-3-months tag_

**Comment by JacksonBowe** [comment]
@rubenfonseca Hi, sorry for the delay in my responses. I did the classic programmer move of "oh yeah that was the problem (wipes brain)".
I was creating a HTTP Api instead of a Rest one. Converting to APIGatewayHttpResolver was the fix.

**Comment by rubenfonseca** [comment]
@JacksonBowe yup, it happened to me in the past too! Happy to hear that the problem is gone, please feel free to always reach out for help!
