### ISSUE TITLE
Bug: Treat missing idempotency key as non-idempotent transaction

### ISSUE THREAD

**Issue by heitorlessa** [awslabs/aws-lambda-powertools-python#2465]
### Expected Behaviour

By default, treat a transaction that is missing idempotency key as a NO-OP transaction. That means, we will continue to log a warning **and** will not save at the configured persistence storage layer.

This prevents mistakes when an application is designed to optionally send an unique value (e.g., X-Idempotency-Value) and `NULL` doesn't get a unique sentinel value (e.g., UUID) in its absence.

### Current Behaviour

[By default,](https://awslabs.github.io/aws-lambda-powertools-python/2.16.2/utilities/idempotency/#customizing-the-default-behavior) `raise_on_no_idempotency_key` is set to `False`. This means we will log a warning when the idempotency key is missing, since we don't know if that's intentional or not. [However we continue treating the transaction like we normally would](https://github.com/awslabs/aws-lambda-powertools-python/blob/develop/aws_lambda_powertools/utilities/idempotency/persistence/base.py#L185), hash the `None` value, and save it in the persistence store.

[Tests confirming behaviour](https://github.com/awslabs/aws-lambda-powertools-python/blob/develop/tests/functional/idempotency/test_idempotency.py#L994)

### Code snippet

```python
from aws_lambda_powertools.utilities.idempotency import (
    DynamoDBPersistenceLayer, idempotent
)

persistence_layer = DynamoDBPersistenceLayer(table_name="IdempotencyTable")
config = IdempotencyConfig(
    event_key_jmespath="headers.X-Idempotency-Value",  # Browser Might Not Send It
)

@idempotent(persistence_store=persistence_layer)
def handler(event, context):
    return {
        "message": "FIRST REQUEST",
        "statusCode": 200,
    }
```

### Possible Solution

https://github.com/awslabs/aws-lambda-powertools-typescript/issues/1501

### Steps to Reproduce

Calling the handler twice without the `X-Idempotency-Value` HTTP Header will return the first response in both requests.

### Powertools for AWS Lambda (Python) version

latest

### AWS Lambda function runtime

3.10

### Packaging format used

Lambda Layers

**Comment by heitorlessa** [comment]
Originally discussed in TypeScript repo: https://github.com/awslabs/aws-lambda-powertools-typescript/issues/1501

**Comment by rubenfonseca** [comment]
Looking at this now.
