### ISSUE TITLE
Feature request: Better strip-prefixes for APIGatewayRestResolver  

### ISSUE THREAD

**Issue by royassis** [awslabs/aws-lambda-powertools-python#2494]
### Use case

I have multiple API Gateway Rest apis backed by AWS Lambda.
I want to these APIs to the same **Custom domain name** with different **path**s. 

For example I have APIs with these urls, each backed by a different lambda:
1. https://xxx.execute-api.us-east-1.amazonaws.com/v1
2. https://yyy.execute-api.us-east-1.amazonaws.com/v1
3. https://xxx_test.execute-api.us-east-1.amazonaws.com/v1
4. https://yyy_test.execute-api.us-east-1.amazonaws.com/v1

I want both of them to be available from:
1. https://mydomain.com/api/v1/xxx
2. https://mydomain.com/api/v1/yyy
3. https://mydomain.com/api/test/xxx
4. https://mydomain.com/api/test/yyy
respectively.

When Init-ing the APIGatewayRestResolver class I would have to pass in the **strip_prefixes**. 
```
strip_prefixes=["/api/v1/xxx", "/api/test/xxx"]
```
We could potentials go to a high level of options due to combinatorics.

### Solution/User Experience

1. Use regex:
```
strip_prefixes=["^.*?xxx"]
```

2. The path will be stripped of the prefixes one by one from left to right.
```
strip_prefixes=["api", "v1" ,"test","xxx"]
```
So if out initial path is `/api/v1/xxx` it will strip "api" first:
 `/api/v1/xxx` ->  `/v1/xxx`
Then v1 
`/v1/xxx` -> `/xxx`
Then it will try to strip "test" but nothing would change:
`/xxx` - > `/xxx`
Then it will strip "xxx"
`/xxx` - > `/`
 

### Acknowledgment

- [X] This feature request meets [Powertools for AWS Lambda (Python) Tenets](https://awslabs.github.io/aws-lambda-powertools-python/latest/#tenets)
- [X] Should this be considered in other Powertools for AWS Lambda languages? i.e. [Java](https://github.com/awslabs/aws-lambda-powertools-java/), [TypeScript](https://github.com/awslabs/aws-lambda-powertools-typescript/), and [.NET](https://github.com/awslabs/aws-lambda-powertools-dotnet/)

**Comment by leandrodamascena** [comment]
Hi @royassis! Thanks for opening this issue and bringing up your use case. Do you have bandwidth to send a PR to add regex support for this field?

**Comment by royassis** [comment]
@leandrodamascena https://github.com/aws-powertools/powertools-lambda-python/pull/2521

**Comment by rubenfonseca** [comment]
Looking at this now
