### ISSUE TITLE
Bug: Docs doesn't upload versions.json when being updated

### ISSUE THREAD

**Issue by sthulb** [awslabs/aws-lambda-powertools-python#2504]
### Expected Behaviour

When generating the docs and uploading to S3, the versions.json file should be updated

### Current Behaviour

The action responsible for docs, doesn't generate the versions.json file

### Code snippet

```python
N/A
```

### Steps to Reproduce

On release, observe the lack of versions.json file being upload

### Powertools for AWS Lambda (Python) version

latest

### AWS Lambda function runtime

3.10

### Packaging format used

PyPi

**Comment by leandrodamascena** [comment]
Thanks for opening this issue @sthulb! Waiting to Convert PR to Ready to Review to verify it.
