### ISSUE TITLE
Maintenance: Restructure tests

### ISSUE THREAD

**Issue by heitorlessa** [awslabs/aws-lambda-powertools-python#251]
**Problem**: As more utilities were added such as `Parser` and `Event source data classes`, we have duplicated fixtures along with helper functions to retrieve event samples.

We should restructure our tests to make better use of `conftest`, and optionally clean up any test names/similar tests

**Comment by michaelbrewer** [comment]
@heitorlessa i do like the idea of having a directory of example events json for the fixtures (but also in general uses)
