### ISSUE TITLE
Maintenance: Pull requests automation failing after migration

### ISSUE THREAD

**Issue by heitorlessa** [awslabs/aws-lambda-powertools-python#2511]
### Why is this needed?

Ensure automation and governance works as expected

### Acknowledgment

- [X] This request meets [Powertools for AWS Lambda (Python) Tenets](https://docs.powertools.aws.dev/lambda-python/latest/#tenets)
- [ ] Should this be considered in other Powertools for AWS Lambda languages? i.e. [Java](https://github.com/aws-powertools/powertools-lambda-java/), [TypeScript](https://github.com/aws-powertools/powertools-lambda-typescript/), and [.NET](https://github.com/aws-powertools/powertools-lambda-dotnet/)

**Comment by heitorlessa** [comment]
Gonna investigate it today.

**Comment by heitorlessa** [comment]
All working actually (cc @leandrodamascena) except those Documentation build + Changelogs + Version bump automation that need to create a Pull Request due to protected branch.

This will be fixed once OSPO addresses a disabled setting.


---

* [x] PR extraction from fork (works)
* [x] On new PR
  * [x] Check for missing issue
  * [x] Check for acknowledgment
* [x] On label added ([works](https://github.com/aws-powertools/powertools-lambda-python/pull/2506#issuecomment-1600783764))
* [x] Label PR based on title ([works](https://github.com/aws-powertools/powertools-lambda-python/pull/2510), [also continue to work on editing](https://github.com/aws-powertools/powertools-lambda-python/pull/2506))
* [x] On PR merge ([works](https://github.com/aws-powertools/powertools-lambda-python/issues/2302))

**Comment by rubenfonseca** [comment]
@leandrodamascena do you know if we can close this one?

**Comment by rubenfonseca** [comment]
Closing as done.
