### ISSUE TITLE
Docs: Update language and roadmap links to new location

### ISSUE THREAD

**Issue by heitorlessa** [awslabs/aws-lambda-powertools-python#2543]
### What were you searching in the docs?

Link to Java, .NET, TypeScript, and the new board of activities. 

### Is this related to an existing documentation section?

homepage and roadmap

### How can we improve?

Update links

### Got a suggestion in mind?

* [Update roadmap page](https://docs.powertools.aws.dev/lambda/python/latest/roadmap/) to point to the new board: https://github.com/orgs/aws-powertools/projects/3?query=is%3Aopen+sort%3Aupdated-desc
* Deprecate the previous board by disabling workflows and having a text pointing to the new one
* Update links to other Powertools languages to : **/lambda/<language** -- Java is the only one not working yet
  * .NET: https://docs.powertools.aws.dev/lambda/dotnet/
  * TS: https://docs.powertools.aws.dev/lambda/typescript/latest/
  * Python: https://docs.powertools.aws.dev/lambda-typescript/latest/
  * Hold on ^ as Java isn't working yet 

### Acknowledgment

- [X] I understand the final update might be different from my proposed suggestion, or refused.

**Comment by dreamorosi** [comment]
PR open, to be merged today: aws-powertools/powertools-lambda-typescript#1531 for roadmap

**Comment by heitorlessa** [comment]
@sthulb fixed Java link: https://docs.powertools.aws.dev/lambda/java/

Making a PR shortly
