### ISSUE TITLE
Feature request: Add Event handler for Amazon VPC Lattice

### ISSUE THREAD

**Issue by leandrodamascena** [awslabs/aws-lambda-powertools-python#2577]
### Use case

With the general availability of [Amazon VPC Lattice](https://aws.amazon.com/about-aws/whats-new/2023/03/general-availability-amazon-vpc-lattice/?nc1=h_ls) and considering that VPC Lattice supports Lambda as a target for [VPC Target Group](https://docs.aws.amazon.com/vpc-lattice/latest/ug/lambda-functions.html), then Powertools should add VPC Lattice as a new Event Handler to help customers easily manipulate routes, handle errors, custom response and so on.

This should have the same capabilities as other event handlers.

### Solution/User Experience

```python
import requests
from requests import Response

from aws_lambda_powertools.event_handler import VPCLatticeResolver
from aws_lambda_powertools.utilities.typing import LambdaContext

app = VPCLatticeResolver()

@app.get("/todo")
def get_todo():
    todos: Response = requests.get("https://jsonplaceholder.typicode.com/todos")
    todos.raise_for_status()

    # for brevity, we'll limit to the first 10 only
    return {"todos": todos.json()[:10]}

def lambda_handler(event: dict, context: LambdaContext) -> dict:
    return app.resolve(event, context)

```

### Acknowledgment

- [X] This feature request meets [Powertools for AWS Lambda (Python) Tenets](https://docs.powertools.aws.dev/lambda/python/latest/#tenets)
- [X] Should this be considered in other Powertools for AWS Lambda languages? i.e. [Java](https://github.com/aws-powertools/powertools-lambda-java/), [TypeScript](https://github.com/aws-powertools/powertools-lambda-typescript/), and [.NET](https://github.com/aws-powertools/powertools-lambda-dotnet/)

**Comment by rubenfonseca** [comment]
Super interesting @leandrodamascena, this seems bigger than the event parser though. But let me know if you want to work on it :)

**Comment by rubenfonseca** [comment]
Removed `help wanted` since there's a PR already
