### ISSUE TITLE
Feature request: add event envelope and parser model for VPC Lattice

### ISSUE THREAD

**Issue by leandrodamascena** [awslabs/aws-lambda-powertools-python#2579]
### Use case

With the general availability of [Amazon VPC Lattice](https://aws.amazon.com/about-aws/whats-new/2023/03/general-availability-amazon-vpc-lattice/?nc1=h_ls) and considering that VPC Lattice supports Lambda as a target for [VPC Target Group](https://docs.aws.amazon.com/vpc-lattice/latest/ug/lambda-functions.html), then Powertools should add Parser support to VPC Lattice.

### Solution/User Experience

```python
@event_parser(model=VPCLattice, envelope=envelopes.VPCLattice)
def handler(event: VPCLattice, context: LambdaContext):
    print(event.body)
```

### Acknowledgment

- [X] This feature request meets [Powertools for AWS Lambda (Python) Tenets](https://docs.powertools.aws.dev/lambda/python/latest/#tenets)
- [ ] Should this be considered in other Powertools for AWS Lambda languages? i.e. [Java](https://github.com/aws-powertools/powertools-lambda-java/), [TypeScript](https://github.com/aws-powertools/powertools-lambda-typescript/), and [.NET](https://github.com/aws-powertools/powertools-lambda-dotnet/)

**Comment by rubenfonseca** [comment]
Thanks @leandrodamascena! Would you like to work on this this week?
