### ISSUE TITLE
Feature request: Patch botocore.session.Session with custom User-Agent header

### ISSUE THREAD

**Issue by roger-zhangg** [awslabs/aws-lambda-powertools-python#2626]
### Use case

Need to add a standard user-agent in SDK calls originated from botocore.session. 
E.g. KMS clients in data-masking feature are init by botocore.session.Session [here](https://github.com/aws/aws-encryption-sdk-python/blob/560e7143ac7caf98e190b17ce2af97b7eea6be16/src/aws_encryption_sdk/key_providers/kms.py#L671C60-L671C60)

### Solution/User Experience

```python
session = botocore.session.Session()
register_feature_to_botocore_session(session, "data-masking")
# use session as is
```

### Acknowledgment

- [X] This feature request meets [Powertools for AWS Lambda (Python) Tenets](https://docs.powertools.aws.dev/lambda/python/latest/#tenets)
- [X] Should this be considered in other Powertools for AWS Lambda languages? i.e. [Java](https://github.com/aws-powertools/powertools-lambda-java/), [TypeScript](https://github.com/aws-powertools/powertools-lambda-typescript/), and [.NET](https://github.com/aws-powertools/powertools-lambda-dotnet/)

**Comment by leandrodamascena** [comment]
Hey @roger-zhangg! Thanks for opening the issue and sending the PR. Let me take a look on this.
