### ISSUE TITLE
Docs: All pages have a banner stating "You're not viewing the latest version"

### ISSUE THREAD

**Issue by allanlewis** [awslabs/aws-lambda-powertools-python#2628]
### What were you searching in the docs?

Nothing in particular

### Is this related to an existing documentation section?

All pages, e.g. the homepage: https://docs.powertools.aws.dev/lambda/python/latest/

### How can we improve?

Remove the banner when I'm viewing the latest version of the docs.

### Got a suggestion in mind?

The link "Click here to go to latest" points to this URL: https://docs.powertools.aws.dev/lambda/python/
Perhaps that's not the correct link?

I also note that the `versions.json` retrieved by my browser on load has an `aliases` key for each version. For most versions it's an empty array but for 2.19.0 it's `"latest"`, i.e. a string not an array: should this be `["latest"]`, i.e. an array containing a single string?

### Acknowledgment

- [X] I understand the final update might be different from my proposed suggestion, or refused.

**Comment by heitorlessa** [comment]
thank you so much @allanlewis for the heads up - we're merging the fix now cc @sthulb

**Comment by heitorlessa** [comment]
@allanlewis could you double check from your end? It should be fixed now - we'll monitor for a newer release to avoid regression.

**Comment by allanlewis** [comment]
Yep, that looks good now - I had to clear my cache before the banner was gone, but confirmed in a Chrome "incognito" window.
