### ISSUE TITLE
Docs: Create your own batch processor documentation inconsistency

### ISSUE THREAD

**Issue by erikayao93** [awslabs/aws-lambda-powertools-python#2688]
### What were you searching in the docs?

While investigating the capabilities of the batch processor in Python for a similar implementation in TypeScript, I found an inconsistency in the description compared to the code example.

The description states that developers should inherit the `BasePartialProcessor` class, which would require them to implement the abstract methods of `prepare`, `clean`, and `process_record` (or `async_process_record`).

However, the code example creates a class that inherits the `BasePartialBatchProcessor` class.

### Is this related to an existing documentation section?

https://docs.powertools.aws.dev/lambda/python/2.19.0/utilities/batch/#create-your-own-partial-processor

### How can we improve?

There should be clarity on which class developers are meant to inherit from.

If developers should inherit from `BasePartialProcessor`, the code example should be updated so that the code is usable. This may require other backend updates, as several pieces of functionality in the code example are reliant on capabilities of the `BasePartialBatchProcessor` class.

### Acknowledgment

- [X] I understand the final update might be different from my proposed suggestion, or refused.

**Comment by heitorlessa** [comment]
great catch @erikayao93 - we had a major refactor recently and the old name wasn't updated in this section of the docs. I'll double check the correct one and update the docs today.

UPDATE: Correct one: `BasePartialProcessor` since it's the ABC. `BasePartialBatchProcessor` is the new one that has the base implementation for SQS/Kinesis/DynamoDB -- the former only has the contracts.

THANK YOU!

**Comment by erikayao93** [comment]
One more thing to note here -- the `process_partial_response` method that is used in the example expects a `BasePartialBatchProcessor` -- not a `BasePartialProcessor`, so I don't think the example would be functional in this case. The example could call directly as a context manager instead?

**Comment by leandrodamascena** [comment]
> One more thing to note here -- the `process_partial_response` method that is used in the example expects a `BasePartialBatchProcessor` -- not a `BasePartialProcessor`, so I don't think the example would be functional in this case. The example could call directly as a context manager instead?

Hello @erikayao93! Thank you for pointing that out. Indeed, the `process_partial_response` signature expects a `BasePartialBatchProcessor`, but we can use `BasePartialProcessor` and implement the `process` method in this processor. To avoid any problems if someone wants to create their own BatchProcessor and guide our customers in the right way, let me recreate this example with comments and a better example.

Reopening the issue.

**Comment by leandrodamascena** [comment]
I'm working on it and plan to create a PR tomorrow.
