### ISSUE TITLE
Tech debt: Use `packaging.version` instead of deprecated `Version` classes from `distutils`

### ISSUE THREAD

**Issue by allanlewis** [awslabs/aws-lambda-powertools-python#2747]
### Why is this needed?

This library, as of v2.19.0, causes Python to emit a warning:

```
DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
```

The sole use of `distutils` appears to be in `utilities.streaming.compat`: https://github.com/aws-powertools/powertools-lambda-python/blob/v2.19.0/aws_lambda_powertools/utilities/streaming/compat.py#L27

### Which area does this relate to?

Streaming

### Suggestion

The new approach is to depend on `packaging` and use [`packaging.version`](https://packaging.pypa.io/en/stable/version.html) instead of `distutils`.

### Acknowledgment

- [X] This request meets [Powertools for AWS Lambda (Python) Tenets](https://docs.powertools.aws.dev/lambda/python/latest/#tenets)
- [ ] Should this be considered in other Powertools for AWS Lambda languages? i.e. [Java](https://github.com/aws-powertools/powertools-lambda-java/), [TypeScript](https://github.com/aws-powertools/powertools-lambda-typescript/), and [.NET](https://github.com/aws-powertools/powertools-lambda-dotnet/)

**Comment by leandrodamascena** [comment]
Hi @allanlewis! Thanks for opening this issue. I'll check this out tomorrow. 

This is not required, but if you have time can you tell us how this affects your projects? Does it break any of your CI pipelines? Do you have any project restrictions on using libraries marked with deprecation?

Thanks a lot

**Comment by allanlewis** [comment]
> ...can you tell us how this affects your projects?

We configure our unit tests to run with `PYTHONWARNINGS=error`, meaning we need to avoid warnings or explicitly suppress them.

> Does it break any of your CI pipelines?

Yes, if I don't explicitly ignore this warning.

> Do you have any project restrictions on using libraries marked with deprecation?

Not specifically, we take that sort of issue case by case.

The reason I raised this is more to highlight that this will break at some point, whenever `setuptools` decides to drop `distutils` entirely.

**Comment by leandrodamascena** [comment]
Thanks for the detailed explanation @allanlewis!

Hi @rubenfonseca! Can we easily replace this library? Testing here I got it with no problems, but I'd like to double-check since you created this utility from scratch.


![image](https://github.com/aws-powertools/powertools-lambda-python/assets/4295173/41e5283c-5398-454a-abb1-7758598d7f54)
![image](https://github.com/aws-powertools/powertools-lambda-python/assets/4295173/aa62e98b-630e-4cfd-9ea1-43b14211c36e)

**Comment by rubenfonseca** [comment]
I see that `packaging` is not part of the Python stdlib. It might work on Powertools because it's a transitive dependency. Should we make it explicit?

**Comment by allanlewis** [comment]
Perhaps you could drop the dependency entirely and just compare the tuple resulting from splitting the version string on `.`?

**Comment by leandrodamascena** [comment]
Or we can do something like this

https://github.com/aws-powertools/powertools-lambda-python/pull/2733/files#diff-e365f962d911ce02a1b8bc9212e0d7aca9451f332a5b377d98ed2bcc1458ce6bR1

Do you have bandwidth to send a PR to fix it @allanlewis?

**Comment by allanlewis** [comment]
> Do you have bandwidth to send a PR to fix it @allanlewis?

Sorry, I don't. Although the change might be small, I think using something other than `packaging.version` would require research into the possible formats of the version string, historically, which would take some time.

**Comment by leandrodamascena** [comment]
> > Do you have bandwidth to send a PR to fix it @allanlewis?
> 
> Sorry, I don't. Although the change might be small, I think using something other than `packaging.version` would require research into the possible formats of the version string, historically, which would take some time.

No problem @allanlewis! Let me fix this and make it available in our next release. Thank you so much for taking the time to help make the project even better. 🚀
