### ISSUE TITLE
Docs: Incorrect example for SSMProvider.get_multiple

### ISSUE THREAD

**Issue by bram-tv** [awslabs/aws-lambda-powertools-python#2749]
### What were you searching in the docs?

Documentation for the `get_multiple` call of the SSMProvider.

### Is this related to an existing documentation section?

https://docs.powertools.aws.dev/lambda/python/latest/api/utilities/parameters/ssm.html

### How can we improve?

The examples listed under:
- Retrieves multiple parameter values from Systems Manager Parameter Store using a path prefix
- Retrieves multiple parameter values from Systems Manager Parameter Store passing options to the SDK call

do not appear to be correct.

Taking the first example:
```
>>> from aws_lambda_powertools.utilities.parameters import SSMProvider
>>> ssm_provider = SSMProvider()
>>>
>>> values = ssm_provider.get_multiple("/my/path/prefix")
>>>
>>> for key, value in values.items():
...     print(key, value)
/my/path/prefix/a   Parameter value a
/my/path/prefix/b   Parameter value b
/my/path/prefix/c   Parameter value c
```

This shows that `/my/path/prefix/` is part of the `key` name but that is not (or no longer the case).
Looking at the code: https://github.com/aws-powertools/powertools-lambda-python/blob/2c4420731f2e36f4e0ef3eb11c4a5e13296070c5/aws_lambda_powertools/utilities/parameters/ssm.py#L215

```
                # Standardize the parameter name
                # The parameter name returned by SSM will contain the full path.
                # However, for readability, we should return only the part after
                # the path.
                name = parameter["Name"]
                if name.startswith(path):
                    name = name[len(path) :]
                name = name.lstrip("/")
```

It always removes the `path` from the `name`.

### Got a suggestion in mind?

Updates the example to:
```
>>> ...
>>> for key, value in values.items():
...     print(key, value)
a   Parameter value a
b   Parameter value b
c   Parameter value c
```

### Acknowledgment

- [X] I understand the final update might be different from my proposed suggestion, or refused.

**Comment by leandrodamascena** [comment]
Hi @bram-tv! Thanks so much for raising this issue! We strive to keep our documentation and docstring as up-to-date as possible, but sometimes we miss something, like this case. This case is the docstring of the method and we can update it to make it clearer for our customers.

Do you think it's worth putting something like: "considering the path /my/path/prefix/ which has the parameters a, b and c...?" This way it makes the example more explicit for the user that we remove the path.

Do you have bandwidth to send a PR to fix this? 

Thanks!

**Comment by heitorlessa** [comment]
@leandrodamascena taking this one FYI

**Comment by heitorlessa** [comment]
Apologies for the delay @bram-tv but we've got a PR now. Besides API docs, I've also improved the User Guide docs with more details and examples too (including comments in the code snippet provided).

Can't thank you enough for taking the time in helping us improve the docs.

---

<img width="1309" alt="image" src="https://github.com/aws-powertools/powertools-lambda-python/assets/3340292/9faf3b2c-303c-4439-989b-d70594ad9327">


<img width="1265" alt="image" src="https://github.com/aws-powertools/powertools-lambda-python/assets/3340292/ac7a1042-f252-41cb-bf76-0197e1f3e1b5">

**Comment by heitorlessa** [comment]
Now in stage (prod after our release this week): https://docs.powertools.aws.dev/lambda/python/stage/api/utilities/parameters/index.html#aws_lambda_powertools.utilities.parameters.get_parameters

User-guide docs: https://docs.powertools.aws.dev/lambda/python/stage/utilities/parameters/#fetching-parameters
