### ISSUE TITLE
[Support Lambda Powertools]: Jit Security

### ISSUE THREAD

**Issue by ohaval** [awslabs/aws-lambda-powertools-python#2787]
### Organization Name

Jit Security

### Your Name

Ohav

### Your current position

Software Developer

### (Optional) Use case

Today at Jit, we use the idempotency module to avoid handling multiple executions on the same event. As our architecture is heavily based on async invocations of Lambda functions, we find it very useful and can already sense the added benefit it brings to us.

In addition to using the module, we also developed helpful utilities and creative ways to test our lambda functions or custom functions, which are decorated with the `idempotent` decorator.

### Also using other Powertools for AWS Lambda languages?

- [ ] Java
- [ ] TypeScript
- [ ] .NET

**Comment by leandrodamascena** [comment]
Hello @ohaval! Thanks so much for raising this issue and allowing us to use the `Jit Security` as a public reference! This is very important for us.

I will work to add this today!

**Comment by leandrodamascena** [comment]
Just confirming: this is the website, right?

https://www.jit.io/

**Comment by ohaval** [comment]
@leandrodamascena correct :)
