### ISSUE TITLE
Maintenance: Add nofollow & noopener to external links

### ISSUE THREAD

**Issue by sthulb** [awslabs/aws-lambda-powertools-python#2830]
### Why is this needed?

It's possible that Google and other search engines have given aws.dev special status. Malicious actors could use this to raise the profile of their SEO standing.

### Which area does this relate to?

Other

### Solution

To combat any potential for this being an issue, we should add `rel="nofollow noopener"` to external links. 

- https://www.semrush.com/blog/nofollow-links/
- https://www.elegantthemes.com/blog/wordpress/rel-noopener-noreferrer-nofollow#noopener

### Acknowledgment

- [X] This request meets [Powertools for AWS Lambda (Python) Tenets](https://docs.powertools.aws.dev/lambda/python/latest/#tenets)
- [X] Should this be considered in other Powertools for AWS Lambda languages? i.e. [Java](https://github.com/aws-powertools/powertools-lambda-java/), [TypeScript](https://github.com/aws-powertools/powertools-lambda-typescript/), and [.NET](https://github.com/aws-powertools/powertools-lambda-dotnet/)

**Comment by heitorlessa** [comment]
good catch! It's a good candidate to create our first markdownlint custom rule - we'll surely miss this eventually

**Comment by leandrodamascena** [comment]
When I was working on issue #2260 I spent time researching this and it may not be necessary to add the `nofollow` attribute as it is automatically added by newer browsers.

References: 
https://chromestatus.com/feature/6140064063029248
https://bugs.chromium.org/p/chromium/issues/detail?id=898942
https://bugs.webkit.org/show_bug.cgi?id=155166
https://bugzilla.mozilla.org/show_bug.cgi?id=1222516

**Comment by sthulb** [comment]
Cool, we can drop noopener then and just add `nofollow` which is observed by search engines

**Comment by leandrodamascena** [comment]
Nice @sthulb! Can you send the PR or do we wait a bit and do it next week? Just let me know.
