### ISSUE TITLE
Docs: Improve guidance to developers on reflecting record failures

### ISSUE THREAD

**Issue by 94Sip** [awslabs/aws-lambda-powertools-python#2848]
### What were you searching in the docs?

I was specifically looking for guidance in the docs on what the record_handler function should return to reflect a record (batch item) could not be handled successfully.

### Is this related to an existing documentation section?

https://docs.powertools.aws.dev/lambda/python/latest/utilities/batch/#partial-failure-mechanics

### How can we improve?

My recommendation is to specifically state that developers should raise an Exception (in python, for example) for any record that could not be processed successfully, and explicitly state the the "partial_process_response" object will handle any exceptions thrown by the record handler.

By looking at the "sample response" section, it implies that the "batchItemFailures" dictionary is returned, but it doesn't explicitly state how that response gets generated and what is required of the developer. 

### Got a suggestion in mind?

Responsibility of the developer/engineer implementing the record_handler method:
1. Allow Exceptions to be propagated to the partial_process_response object, and/or
2. Explicitly raise an Exception in the record handler

Either way, an Exception is used to notify the partial_process_response object that record handling was not successful.

From that point forward, the partial_process_response object will take care of formatting the "batchItemFailures" dictionary back to SQS.

### Acknowledgment

- [X] I understand the final update might be different from my proposed suggestion, or refused.

**Comment by heitorlessa** [comment]
Thank you so much for taking the time to report on Discord and create a beautifully detailed issue @94Sip - we'll ping once we have a draft for review.

Thanks!

**Comment by heitorlessa** [comment]
Took the liberty to improve other areas in the Batch documentation (diagrams!!), so I'll send the complete PR tomorrow.

Here's the initial draft for this specific section. I used code annotations (works on mobile too) to hide details of exception propagation besides what's written upfront. I'll also create a sequence diagram under Mechanics section to it can be referenced to more easily (like Idempotency).

**🆕 Error handling section**

<img width="1586" alt="image" src="https://github.com/aws-powertools/powertools-lambda-python/assets/3340292/7b6247d5-c981-4cfc-b999-8d4ca9ff3b09">

**Code annotation**

<img width="1377" alt="image" src="https://github.com/aws-powertools/powertools-lambda-python/assets/3340292/fe61a428-8df3-4fb1-a9e7-76c97b3d7adb">

**Code annotation**

<img width="994" alt="image" src="https://github.com/aws-powertools/powertools-lambda-python/assets/3340292/29cba3e3-5ed2-4fcb-a5eb-16837ac67b5a">


---

🆕 Sequence diagrams section

**SQS Standard queues**

<img width="1068" alt="image" src="https://github.com/aws-powertools/powertools-lambda-python/assets/3340292/0c39ef3f-c24c-4453-9d03-fcabe47d63fb">


**SQS FIFO**

<img width="1694" alt="image" src="https://github.com/aws-powertools/powertools-lambda-python/assets/3340292/b543dd34-0ab7-4f1c-8aa1-4f80b61c76dd">

**Kinesis and DynamoDB**

<img width="1486" alt="image" src="https://github.com/aws-powertools/powertools-lambda-python/assets/3340292/ee4834c8-1717-4026-9801-4e1597d5209a">

<img width="1492" alt="image" src="https://github.com/aws-powertools/powertools-lambda-python/assets/3340292/bd186b99-4af0-4864-add2-8c75f9483b15">

---

**Raw processing revamped plus samples**

<img width="1368" alt="image" src="https://github.com/aws-powertools/powertools-lambda-python/assets/3340292/719cb450-2e0f-4651-9fb1-7cd4dfb955c2">

**Comment by heitorlessa** [comment]
PR is now up with all changes: https://github.com/aws-powertools/powertools-lambda-python/pull/2857

**Comment by heitorlessa** [comment]
Closing manually as automation seems to have failed upon release: https://docs.powertools.aws.dev/lambda/python/latest/utilities/batch/#error-handling
