### ISSUE TITLE
Maintenance: Update roadmap 

### ISSUE THREAD

**Issue by heitorlessa** [awslabs/aws-lambda-powertools-python#2914]
### Why is this needed?

Roadmap is currently out of date

### Which area does this relate to?

Other

### Solution

Update roadmap page

### Acknowledgment

- [X] This request meets [Powertools for AWS Lambda (Python) Tenets](https://docs.powertools.aws.dev/lambda/python/latest/#tenets)
- [ ] Should this be considered in other Powertools for AWS Lambda languages? i.e. [Java](https://github.com/aws-powertools/powertools-lambda-java/), [TypeScript](https://github.com/aws-powertools/powertools-lambda-typescript/), and [.NET](https://github.com/aws-powertools/powertools-lambda-dotnet/)

**Comment by leandrodamascena** [comment]
Closed through  #2915
