### ISSUE TITLE
Tech debt: Improve Metrics provider to make it more maintainable

### ISSUE THREAD

**Issue by leandrodamascena** [awslabs/aws-lambda-powertools-python#2916]
### Why is this needed?

In the PR #2194 we refactored the Metrics utility to allow bring new utilities. But it created some technical debt that must be addressed now.

Some items we need to fix:

- [ ] Cleanup the slight confusion in OOO / Protocol
- [x] Fix possible mistakes in docstrings
- [x] Remove old and commented code
- [x] Refactor _extract_* into standalone functions to reduce call graph
- [ ] Split up functional and unit tests with new providers

### Which area does this relate to?

Metrics

### Acknowledgment

- [X] This request meets [Powertools for AWS Lambda (Python) Tenets](https://docs.powertools.aws.dev/lambda/python/latest/#tenets)
- [ ] Should this be considered in other Powertools for AWS Lambda languages? i.e. [Java](https://github.com/aws-powertools/powertools-lambda-java/), [TypeScript](https://github.com/aws-powertools/powertools-lambda-typescript/), and [.NET](https://github.com/aws-powertools/powertools-lambda-dotnet/)

**Comment by heitorlessa** [comment]
adjusting labels to prevent incorrect metrics
