### ISSUE TITLE
Maintenance: As a Developer `make pr` doe snot work due to linting errors in documentation

### ISSUE THREAD

**Issue by walmsles** [awslabs/aws-lambda-powertools-python#2919]
### Expected Behaviour

`make pr`  is reporting on markdown linting errors in my dev environment (maybe its just me?) and not allowing me to continue with `make pr` and being a good pull request citizen for powertools.  Need some help here?

### Current Behaviour

```bash

$> make pr
poetry run black aws_lambda_powertools tests examples
All done! ✨ 🍰 ✨
349 files left unchanged.
poetry run ruff aws_lambda_powertools tests examples
docker run -v /Users/walmlses/dev/open-source/aws-lambda-powertools-python:/markdown 06kellyjac/markdownlint-cli "docs"
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
docs/maintainers.md:293:381 MD013/line-length Line length [Expected: 380; Actual: 395]
docs/utilities/validation.md:116:381 MD013/line-length Line length [Expected: 380; Actual: 401]
make: *** [lint-docs] Error 1
```

### Code snippet

```python
No Code required.
```

### Possible Solution

Unsure - the actual documentation lines already have `<!-- markdownlint-disable-next-line MD013 --> above them but are not working when I run `make pr` ?

### Steps to Reproduce

`make pr`

### Powertools for AWS Lambda (Python) version

latest

### AWS Lambda function runtime

3.7

### Packaging format used

PyPi

### Debugging logs

```python
poetry run black aws_lambda_powertools tests examples
All done! ✨ 🍰 ✨
349 files left unchanged.
poetry run ruff aws_lambda_powertools tests examples
docker run -v /Users/walmlses/dev/open-source/aws-lambda-powertools-python:/markdown 06kellyjac/markdownlint-cli "docs"
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
docs/maintainers.md:293:381 MD013/line-length Line length [Expected: 380; Actual: 395]
docs/utilities/validation.md:116:381 MD013/line-length Line length [Expected: 380; Actual: 401]
make: *** [lint-docs] Error 1
```

**Comment by heitorlessa** [comment]
Thanks a lot for raising this @walmsles - sending a PR soon to ignore that rule for that file.

**Comment by walmsles** [comment]
@heitorlessa  can you make sure to ignore **both** the files, there are 2 (just in case you only did 1)

**Comment by heitorlessa** [comment]
yeeah, I did both maintainers and validation. I ran `make pr` locally to be triple sure. Just waiting @leandrodamascena to wake up as he's in a different timezone

**Comment by leandrodamascena** [comment]
This fix has been pushed to the develop branch. Closing this issue.
