### ISSUE TITLE
Maintenance: building changelog, e2e tests and docs fails in forks

### ISSUE THREAD

**Issue by ivica-k** [awslabs/aws-lambda-powertools-python#2921]
### Why is this needed?

Repositories that fork this repo inherit its Github actions, some of which fail regularly; [failed changelog rebuild](https://github.com/ivica-k/aws-lambda-powertools-python/actions/runs/5736170327), [failed changelog publish](https://github.com/ivica-k/aws-lambda-powertools-python/actions/runs/5759420680/job/15613492591).

This creates a bit of spam for the fork owner and can potentially incur costs.

### Which area does this relate to?

Automation

### Solution

Github actions relating to packaging and releasing new versions of LPT should only run in the original repository, not in forks.

### Acknowledgment

- [X] This request meets [Powertools for AWS Lambda (Python) Tenets](https://docs.powertools.aws.dev/lambda/python/latest/#tenets)
- [X] Should this be considered in other Powertools for AWS Lambda languages? i.e. [Java](https://github.com/aws-powertools/powertools-lambda-java/), [TypeScript](https://github.com/aws-powertools/powertools-lambda-typescript/), and [.NET](https://github.com/aws-powertools/powertools-lambda-dotnet/)

**Comment by ivica-k** [comment]
I would be happy to implement the changes. [Example for dispatching analytics](https://github.com/aws-powertools/powertools-lambda-python/blob/develop/.github/workflows/dispatch_analytics.yml#L25).

**Comment by heitorlessa** [comment]
thank you!!!
