### ISSUE TITLE
Docs: Include environment variables in Tracer

### ISSUE THREAD

**Issue by heitorlessa** [awslabs/aws-lambda-powertools-python#2923]
### What were you searching in the docs?

Environment variables I can use with Tracer

### Is this related to an existing documentation section?

https://docs.powertools.aws.dev/lambda/python/latest/core/tracer/

### How can we improve?

Introduce a new subsection `Environment variables` in the Tracer docs, so customers don't have to have two tabs opened, or miss this is possible.

https://docs.powertools.aws.dev/lambda/python/latest/#environment-variables

### Got a suggestion in mind?

Proposal graciously done by [@barreeeiroo](https://github.com/barreeeiroo) already

https://github.com/aws-powertools/powertools-lambda-python/pull/2922

### Acknowledgment

- [X] I understand the final update might be different from my proposed suggestion, or refused.

**Comment by heitorlessa** [comment]
PR was created before an issue. Created for process purposes. 

#2922

**Comment by barreeeiroo** [comment]
FYI, I've now created https://github.com/aws-powertools/powertools-lambda-python/pull/2925 which targets all pages (not only Tracer), so maybe you may want to edit this issue or create a new one superseding this one.

**Comment by heitorlessa** [comment]
@leandrodamascena is on it. Last suggestions and we're good to merge.
