### ISSUE TITLE
Bug: API Gateway - invalid escape sequence '\['

### ISSUE THREAD

**Issue by nejcskofic** [awslabs/aws-lambda-powertools-python#2980]
### Expected Behaviour

When importing from `aws_lambda_powertools.event_handler.api_gateway` there should be no warning raised.

### Current Behaviour

Deprecation warning is raised on import on [api_gateway.pyL46](https://github.com/aws-powertools/powertools-lambda-python/blob/ac4fe43eab9201a70ba581bdafe8850ef7b6fdbd/aws_lambda_powertools/event_handler/api_gateway.py#L46):
```
DeprecationWarning: invalid escape sequence '\['
_UNSAFE_URI = "%<> \[\]{}|^"  # noqa: W605
```
If pytest is run with warnings as errors, Syntax error is raised instead and module loading is terminated.

### Code snippet

```python
import warnings


def test_api_gateway_import():
    with warnings.catch_warnings():
        warnings.simplefilter("error")
        from aws_lambda_powertools.event_handler.api_gateway import APIGatewayRestResolver
```

### Possible Solution

Remove `# noqa: W605` and prefix pattern with raw string modifier. I haven't checked if this is an issue elsewhere in the codebase.

### Steps to Reproduce

1. Remove `__pycache__` from `aws_lambda_powertools/event_handler` (once code is bytecompiled error is no longer triggered)
2. Run above code snippet as pytest test

### Powertools for AWS Lambda (Python) version

latest

### AWS Lambda function runtime

3.10

### Packaging format used

PyPi

**Comment by rubenfonseca** [comment]
Looking at this now

**Comment by rubenfonseca** [comment]
Thank you so much for the very very clear explanation of the problem, and the steps to reproduce! I'm opening a PR in a few minutes.

**Comment by rubenfonseca** [comment]
@nejcskofic I've opened a PR to fix this, can you take a look to see if it makes sense?

**Comment by nejcskofic** [comment]
@rubenfonseca Looks good, thank you for the quick response!
