### ISSUE TITLE
Bug: `pyproject.toml` does not allow `pydantic` v2

### ISSUE THREAD

**Issue by majacannavo** [awslabs/aws-lambda-powertools-python#2998]
### Expected Behaviour

Expected behavior: installation of `aws-lambda-powertools` with `pydantic` extra dependency is compatible with installation of other libraries that require `pydantic` v2

### Current Behaviour

Current behavior: `pydantic` extra dependency does not allow `pydantic` v2 to be used; requires v1

### Code snippet

```python
Line 34 from pyproject.toml explicitly does not allow pydantic 2.x:

pydantic = { version = "^1.8.2", optional = true }
```

### Possible Solution

Update line 34 from `pyproject.toml` to the following: 
```
pydantic = { version = ">=1.8.2, <3", optional = true } 
```

### Steps to Reproduce

Attempt to install `aws-lambda-powertools` with the `pydantic` extra along with another library that requires `pydantic` 2.x

### Powertools for AWS Lambda (Python) version

latest

### AWS Lambda function runtime

3.9

### Packaging format used

PyPi

**Comment by leandrodamascena** [comment]
Looking at this now.

**Comment by leandrodamascena** [comment]
Hello @majacannavo! Thank you for opening this issue! 

This is actually not a bug. We added support to Pydantic v2, but we've kept Pydantic v1 as the default in Powertools to avoid issues with dependency resolutions for customers who are using Powertools with Pydantic v1 and don't want to switch to Pydantic v2.

To add the use of Pydantic v2 with Powertools, you must remove the optional dependency for Pydantic. Create a file like this:

```
aws-lambda-powertools
pydantic>=2.0.3
otherdependencies
```

Please let me know if you need any additional help.

Reference: https://docs.powertools.aws.dev/lambda/python/latest/utilities/parser/#using-pydantic-v2

Thanks

**Comment by majacannavo** [comment]
Got it, thanks! Appreciate the clarification!

**Comment by mtvx** [comment]
For anyone coming here, the `parser` extra is what points to the `pydantic` dependency, see https://github.com/aws-powertools/powertools-lambda-python/blob/93b331dd7067011cade3125b11ea479c36ee9645/pyproject.toml#L95

In Poetry terms, to avoid the 1.x requirement, if you had:

```toml
aws-lambda-powertools = {version = "^2.21.0", extras = ["parser"]}
```

Drop the `parser` extra and define `pydantic` as explicit dependency, is the solution:

```toml
aws-lambda-powertools = {version = "^2.21.0"}
pydantic = "^2.0.3"
```
