### ISSUE TITLE
Bug: APIGatewayRestResolver does not capture path segment with + sign

### ISSUE THREAD

**Issue by nejcskofic** [awslabs/aws-lambda-powertools-python#3006]
### Expected Behaviour

If handler is registered for dynamic path, I would expect that segment containing plus sign is captured.

Example:
```
@app.get("/dummy/<value>")
def handler(value: str): ...
```
Resolver is invoked with: `GET /dummy/a+b`

### Current Behaviour

Resolver returns 404 error.

### Code snippet

```python
from dataclasses import dataclass

import pytest
from aws_lambda_powertools.event_handler import APIGatewayRestResolver


@pytest.fixture
def lambda_context():
    @dataclass
    class LambdaContext:
        function_name: str = "test"
        memory_limit_in_mb: int = 128
        invoked_function_arn: str = "arn:aws:lambda:eu-west-1:123456789012:function:test"
        aws_request_id: str = "da658bd3-2d6f-4e7b-8ec2-937234644fdc"

    return LambdaContext()


def test_api_gateway_plus_path_capturing(lambda_context):
    app = APIGatewayRestResolver()

    @app.get("/dummy/<value>")
    def handler(value: str):
        assert value == "a+b"
        return {}

    response = app.resolve(
        {
            "path": "/dummy/a+b",
            "httpMethod": "GET",
            "requestContext": {"requestId": "227b78aa-779d-47d4-a48e-ce62120393b8"}
        },
        lambda_context
    )

    assert response["statusCode"] == 200
```

### Possible Solution

[api_gateway.pyL44](https://github.com/aws-powertools/powertools-lambda-python/blob/53650982c51f54cf448100a819aadb1ea5a23489/aws_lambda_powertools/event_handler/api_gateway.py#L44) contains definition of safe characters. This list is incomplete. By rfc3986 Section 3.3 path is built from segments where segments can contain `sub-delims` which are defined as:
```
sub-delims  = "!" / "$" / "&" / "'" / "(" / ")"
                  / "*" / "+" / "," / ";" / "="
```
API Gateway resolver is using this list of characters when building route regex:
```
_SAFE_URI = "-._~()'!*:@,;="
```
Plus sign (`+`), dollar sign (`$`) and ampersand sign (`&`) are missing from that list. Adding them would resolve this issue.

### Steps to Reproduce

Run above code snippet as pytest test.

### Powertools for AWS Lambda (Python) version

latest

### AWS Lambda function runtime

3.10

### Packaging format used

PyPi

**Comment by leandrodamascena** [comment]
Looking at this now.

**Comment by leandrodamascena** [comment]
Hello @nejcskofic! I can confirm that this is indeed a bug and we need to fix it. Our Resolver must be able to handle these additional characters: `$/&`.

Do you want to submit a fix + tests for this issue? We plan to launch a release on Friday and we'd love it if you would send in a PR to contribute to Powertools for AWS Lambda.

Don't worry if you can't, We know everyone's been very busy and I can fix that.

**Comment by nejcskofic** [comment]
Hello @leandrodamascena. Thanks for the response. I can take a look at it later today. One question though: in your response you mention only `$` and `&`. What about `+` (which was my original issue)?

**Comment by leandrodamascena** [comment]
Sorry, I made a mistake! Yes, include `+` as well. 😑.

Thanks and let me know if you need any help.
