### ISSUE TITLE
Tech debt: BasePartialBatchProcessor response() and process_partial_response() should have the same response typing

### ISSUE THREAD

**Issue by adriantomas** [awslabs/aws-lambda-powertools-python#3020]
### Why is this needed?

This method https://github.com/aws-powertools/powertools-lambda-python/blob/develop/aws_lambda_powertools/utilities/batch/base.py#L256 and https://github.com/aws-powertools/powertools-lambda-python/blob/024c3f2ed8858643a2d303e5c3928aa58e168c7c/aws_lambda_powertools/utilities/batch/decorators.py#L128C16-L128C16

Should have the same response typing https://github.com/aws-powertools/powertools-lambda-python/blob/024c3f2ed8858643a2d303e5c3928aa58e168c7c/aws_lambda_powertools/utilities/batch/types.py#L32

So that users can easily guess that using one method or another produces the same output.

### Which area does this relate to?

Static typing

### Suggestion

I can submit a PR with the changes.

### Acknowledgment

- [X] This request meets [Powertools for AWS Lambda (Python) Tenets](https://docs.powertools.aws.dev/lambda/python/latest/#tenets)
- [ ] Should this be considered in other Powertools for AWS Lambda languages? i.e. [Java](https://github.com/aws-powertools/powertools-lambda-java/), [TypeScript](https://github.com/aws-powertools/powertools-lambda-typescript/), and [.NET](https://github.com/aws-powertools/powertools-lambda-dotnet/)

**Comment by leandrodamascena** [comment]
Hello @adriantomas! I totally agree that `response()` should have the same response type as `process_partial_response()`. When we refactored the Batch Process utility with the new `process_partial_response()` function, we created this type to make it easier for clients to access the properties of this response and we forget to annotate `response()` function, sorry for that :disappointed:.

Please, send a PR to fix this and we can merge :)

Thanks a lot
