### ISSUE TITLE
Maintenance: Review pipeline to update the aws-actions/configure-aws-credentials action

### ISSUE THREAD

**Issue by leandrodamascena** [awslabs/aws-lambda-powertools-python#3025]
### Why is this needed?

The v3 major version of aws-actions/configure-aws-credentials has been released and is breaking our CI.

The role assumed in https://github.com/aws-powertools/powertools-lambda-python/blob/develop/.github/workflows/reusable_deploy_v2_sar.yml#L182 is different from the role that should be outputted by this command https://github.com/aws-powertools/powertools-lambda-python/blob/develop/.github/workflows/reusable_deploy_v2_sar.yml#L103.

Also, accountid is not masked by default and need to add special configuration to avoid problems with special characters (https://github.com/aws-actions/configure-aws-credentials#special-characters-in-aws_secret_access_key).

### Which area does this relate to?

Automation

### Solution

Investigate these problems before update this dependency.

### Acknowledgment

- [X] This request meets [Powertools for AWS Lambda (Python) Tenets](https://docs.powertools.aws.dev/lambda/python/latest/#tenets)
- [X] Should this be considered in other Powertools for AWS Lambda languages? i.e. [Java](https://github.com/aws-powertools/powertools-lambda-java/), [TypeScript](https://github.com/aws-powertools/powertools-lambda-typescript/), and [.NET](https://github.com/aws-powertools/powertools-lambda-dotnet/)

**Comment by dreamorosi** [comment]
We merged the change and confirmed that the new version works: aws-powertools/powertools-lambda-typescript#1662

Another change in 3.x is that you [now have to pass](https://github.com/aws-actions/configure-aws-credentials/blob/v3.0.1/CHANGELOG.md#features-1) `output-credentials` for the credentials to be set as output of the step. We are not using that feature since we read from the environment, but you might have to put it since one of your examples reads from the steps.

**Comment by leandrodamascena** [comment]
Hello @dreamorosi! Thank you so much for sharing this. I think our issue is with this `output-credentials` parameter. We'll investigate further, but this investigation of yours has shortened the path by miles.

:rocket:

**Comment by heitorlessa** [comment]
Adding `triage` back as I'm not sure where we landed with this. I suspect it's done?

**Comment by leandrodamascena** [comment]
This was updated in V3 pipeline! Closing.
