### ISSUE TITLE
feat: Only install typing-extensions dependency when necessary missing in some files

### ISSUE THREAD

**Issue by HarbingersRequiem** [awslabs/aws-lambda-powertools-python#3091]
### Use case

This is the same issue as noted in https://github.com/aws-powertools/powertools-lambda-python/issues/280. Looks like the following files are missing the conditionals put in which is causing issues, for me at least, with some Lambda scripts:

- aws_lambda_powertools/event_handler/middlewares/base.py
- aws_lambda_powertools/metrics/provider/cloudwatch_emf/types.py
- aws_lambda_powertools/metrics/types.py
- aws_lambda_powertools/utilities/batch/types.py
- aws_lambda_powertools/utilities/parameters/ssm.py
- aws_lambda_powertools/utilities/parameters/types.py
- aws_lambda_powertools/utilities/streaming/s3_object.py

### Solution/User Experience

Same as previous feat. Add the conditionals around the import for typing_extensions

### Acknowledgment

- [X] This feature request meets [Powertools for AWS Lambda (Python) Tenets](https://docs.powertools.aws.dev/lambda/python/latest/#tenets)
- [ ] Should this be considered in other Powertools for AWS Lambda languages? i.e. [Java](https://github.com/aws-powertools/powertools-lambda-java/), [TypeScript](https://github.com/aws-powertools/powertools-lambda-typescript/), and [.NET](https://github.com/aws-powertools/powertools-lambda-dotnet/)

**Comment by heitorlessa** [comment]
hey @HarbingersRequiem, thank you for reporting it -- did it cause you a runtime error in Lambda? if so, we'll switch it to `bug` and get on it now.

Apologies for letting this slip during PRs, we'll think of a linter or a shared types to make this sustainable.

**Comment by HarbingersRequiem** [comment]
Hey @heitorlessa, it did, yeah. Got this out of it "[ERROR] Runtime.ImportModuleError: Unable to import module 'lambda_function': No module named 'typing_extensions' Traceback (most recent call last):"

Thanks for the quick response on it!

**Comment by heitorlessa** [comment]
okay, working on that now. Switching to bug.

**Comment by heitorlessa** [comment]
One quick note only... `typing_extensions`  is a required dependency in Powertools. Back then we made it optional for 3.7 only.

https://github.com/aws-powertools/powertools-lambda-python/blob/86619e5ae4f29d68abfc6c20e708eedb8a9a6ca4/pyproject.toml#L36

That shouldn't cause the `No module named 'typing_extensions'`.

**Comment by heitorlessa** [comment]
PR in, classified as `typing` instead of `bug` as couldn't reproduce at runtime using the latest version given it's a runtime dependency.

**Comment by heitorlessa** [comment]
All good and tested. Because we can't reproduce at runtime when installing the latest powertools for AWS version, we'll make a release tomorrow instead of now.

Still, we care about it :)
