### ISSUE TITLE
Feature request: Remove duplication of type when parsing event

### ISSUE THREAD

**Issue by Tom01098** [awslabs/aws-lambda-powertools-python#3173]
### Use case

When using the `event_parser` decorator to parse the `event`, the type will be duplicated if using type hints as a best practice.

```python
@event_parser(model=Order)
def handler(event: Order, context: LambdaContext):
    ...
```

### Solution/User Experience

I am proposing that we can drop the `model` parameter as we can infer it from `event`s type hint.

```python
@event_parser
def handler(event: Order, context: LambdaContext):
    ...
```

I am very happy to contribute this feature request, it should be very small and is totally backwards-compatible (`model` will still be accepted and chosen before type hints are inspected).

### Alternative solutions

```markdown
Keep as-is.
```

### Acknowledgment

- [X] This feature request meets [Powertools for AWS Lambda (Python) Tenets](https://docs.powertools.aws.dev/lambda/python/latest/#tenets)
- [ ] Should this be considered in other Powertools for AWS Lambda languages? i.e. [Java](https://github.com/aws-powertools/powertools-lambda-java/), [TypeScript](https://github.com/aws-powertools/powertools-lambda-typescript/), and [.NET](https://github.com/aws-powertools/powertools-lambda-dotnet/)

**Comment by heitorlessa** [comment]
Great idea @Tom01098 -- please feel free to send a PR as you suggested 🫶

It's still within our Progressive tenet -- explicit for most of us, and implicit via type hint for the cutting edge.

Feel free to ping on Discord or here if we can help with anything
