### ISSUE TITLE
[Support Powertools for AWS Lambda (Python)]: Vertex Pharmaceuticals

### ISSUE THREAD

**Issue by rwiturralde** [awslabs/aws-lambda-powertools-python#3207]
### Organization Name

Vertex Pharmaceuticals

### Your Name

Roberto Iturralde

### Your current position

Sr Director, Software Engineering

### Also using other Powertools for AWS Lambda languages?

- [X] Java
- [ ] TypeScript
- [ ] .NET

**Comment by leandrodamascena** [comment]
Hello @rwiturralde! Thank you so much for opening this issue and let us use Vertex Pharmaceuticals as a public reference for Powertools for AWS Lambda. This is priceless for us. :heart:
