### ISSUE TITLE
Bug: POWERTOOLS_PARAMETERS_SSM_DECRYPT environment variable not respected for get multiple

### ISSUE THREAD

**Issue by sean-hernon** [awslabs/aws-lambda-powertools-python#3240]
### Expected Behaviour

When the environment variable `POWERTOOLS_PARAMETERS_SSM_DECRYPT` is set to `true`, a call to `get_multiple` parameters should automatically decrypt the values, as is the way with a call to `get`.

### Current Behaviour

The `POWERTOOLS_PARAMETERS_SSM_DECRYPT` is ignored when calling `get_multiple` and only the explicit `decrypt` argument is respected.

### Code snippet

```python
from aws_lambda_powertools.utilities.parameters.ssm import SSMProvider
import os

os.environ['POWERTOOLS_PARAMETERS_SSM_DECRYPT'] = 'true'
ssm_provider = SSMProvider()

for _, v in ssm_provider.get_multiple('/some/parameters').items():
    print(v) # Still encrypted
```

### Possible Solution

https://github.com/aws-powertools/powertools-lambda-python/pull/3241

### Steps to Reproduce

Please see code snippet

### Powertools for AWS Lambda (Python) version

latest

### AWS Lambda function runtime

3.10

### Packaging format used

PyPi

**Comment by leandrodamascena** [comment]
Hi @sean-hernon! Thank you so much for reporting this bug and sending the PR to fix it! I'll review it tomorrow so we can merge it.
