### ISSUE TITLE
Docs: Native middleware 'SchemaValidationMiddleware' has invalid link

### ISSUE THREAD

**Issue by jvnsg** [awslabs/aws-lambda-powertools-python#3246]
### What were you searching in the docs?

Missing documentation for native middleware 'SchemaValidationMiddleware'. The link given in [Doc-EventHandler-ApiGatreway](https://github.com/aws-powertools/powertools-lambda-python/blob/b901f231bd99f6f6cd2763470cfbb0ef2b208288/docs/core/event_handler/api_gateway.md) is invalid. Therefor the use of 'SchemaValidationMiddleware' isnt't clear.

### Is this related to an existing documentation section?

https://github.com/aws-powertools/powertools-lambda-python/blob/b901f231bd99f6f6cd2763470cfbb0ef2b208288/docs/core/event_handler/api_gateway.md?plain=1#L578

### How can we improve?

Add valid documentation for 'SchemaValidationMiddleware'.

### Acknowledgment

- [X] I understand the final update might be different from my proposed suggestion, or refused.

**Comment by leandrodamascena** [comment]
Hey @jvnsg! Thanks for opening this issue and in fact the link is wrong. This should be https://docs.powertools.aws.dev/lambda/python/latest/api/event_handler/middlewares/schema_validation.html.

What do you think about sending a Pull Request to fix this? We'd love to have your first contribution here.
