### ISSUE TITLE
Docs: New OpenAPI and Swagger UI support in Event Handler REST

### ISSUE THREAD

**Issue by heitorlessa** [awslabs/aws-lambda-powertools-python#3325]
### What were you searching in the docs?

(future) How to create an `/swagger` endpoint to visualize my API, and how to generate an OpenAPI Schema out of my code.

### Is this related to an existing documentation section?

https://docs.powertools.aws.dev/lambda/python/latest/core/event_handler/api_gateway/

### How can we improve?

Create the doc out of [implementation](https://github.com/aws-powertools/powertools-lambda-python/pull/3109)

### Got a suggestion in mind?

Split out OpenAPI into a separate subsection due to complexity for advanced customers wanting to extend all parts of it.

### Acknowledgment

- [X] I understand the final update might be different from my proposed suggestion, or refused.

**Comment by rubenfonseca** [comment]
Closed by #3386
