### ISSUE TITLE
Feature request: Leverage new DynamoDB Failed Conditional Writes behavior

### ISSUE THREAD

**Issue by dastra** [awslabs/aws-lambda-powertools-python#3327]
### Use case

The new idempotency utility uses conditional writes against DynamoDB for its locking mechanism.

When the conditional write fails, the record is considered locked and the request is already processed. In that case, a query is issued against DynamoDB to fetch the cached result and return it.

This means for this scenario that customers must wait and pay for [both a write and read](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/WorkingWithItems.html#WorkingWithItems.ConditionalWrites.ReturnConsumedCapacity), even though the write fails.

On June 30, 2023, [DynamoDB announced](https://aws.amazon.com/about-aws/whats-new/2023/06/amazon-dynamodb-cost-failed-conditional-writes/) the ability for a failed conditional write to return a copy of the existing record. This would allow the package to skip performing the query, improving performance and lowering cost.

### Solution/User Experience

In the idempotency utility, use the new [DynamoDB conditional write behavior](https://aws.amazon.com/about-aws/whats-new/2023/06/amazon-dynamodb-cost-failed-conditional-writes/) to return the current state of the item in the same conditional write operation. Remove the follow-up query.

### Acknowledgment

- [X] This feature request meets [Powertools for AWS Lambda (Python) Tenets](https://docs.powertools.aws.dev/lambda/python/latest/#tenets)
- [X] Should this be considered in other Powertools for AWS Lambda languages? i.e. [Java](https://github.com/aws-powertools/powertools-lambda-java/), [TypeScript](https://github.com/aws-powertools/powertools-lambda-typescript/), and [.NET](https://github.com/aws-powertools/powertools-lambda-dotnet/)

**Comment by heitorlessa** [comment]
Great idea, Dan! We totally missed it. We’re all hands on deck for reinvent
but if this is something you’d like to contribute we’d be more than happy
to answer any question you have.

Setting expectation

The hardest part until we rewrite is tests. Idempotency wasn’t designed to
split the storage provider from day 1, and we’re fixing that on a Redis PR…
but we’re here to help.

We created our own framework for E2E test to make things easier at scale;
should be easy enough to add a new E2E test in Idempotency — it supports
step through debugging in PyCharm too.

Documented here

https://docs.powertools.aws.dev/lambda/python/latest/maintainers/#e2e-framework
