### ISSUE TITLE
Maintenance: Run pydantic v2 workflow only for features using pydantic

### ISSUE THREAD

**Issue by heitorlessa** [awslabs/aws-lambda-powertools-python#3349]
### Why is this needed?

Our CI times doubled as GH has a limit of concurrent workflows run, increasing our lead time.

### Solution

Short-term: change `paths` in Pydantic V2 workflow to only use Event Handler, Parser, and Batch.

Medium-term: if CI time continues to be high, we use `nox` like solution to dynamically swap Pydantic version at runtime (no additional workflow).

Long-term: Launch v3 with Pydantic v2 and drop v1.

### Acknowledgment

- [X] This request meets [Powertools for AWS Lambda (Python) Tenets](https://docs.powertools.aws.dev/lambda/python/latest/#tenets)
- [ ] Should this be considered in other Powertools for AWS Lambda languages? i.e. [Java](https://github.com/aws-powertools/powertools-lambda-java/), [TypeScript](https://github.com/aws-powertools/powertools-lambda-typescript/), and [.NET](https://github.com/aws-powertools/powertools-lambda-dotnet/)

**Comment by leandrodamascena** [comment]
Hey @heitorlessa! Our tests takes +-30s to complete and I think we can start removing lint/static checking. Let me send the PR to check this.

![image](https://github.com/aws-powertools/powertools-lambda-python/assets/4295173/fc04b5d1-cc73-4f88-99c4-162cf5f4693d)
