### ISSUE TITLE
Static typing: Logger.exception() exc_info type does not match Python's built-in one

### ISSUE THREAD

**Issue by rafrafek** [awslabs/aws-lambda-powertools-python#3356]
### Static type checker used

pyright/pylance

### AWS Lambda function runtime

3.11

### Powertools for AWS Lambda (Python) version

latest

### Static type checker info

Pyright 1.1.331

### Code snippet

```python
from aws_lambda_powertools.logging import Logger
logger = Logger(name="%(name)s")
...
ex = Exception()
logger.exception(
    f"Failed to launch workflow: {ex!r}",
    extra=None,
    exc_info=(type(ex), ex, ex.__traceback__),
)
```

### Possible Solution

`exc_info` should not be `bool` only, it should be:
"_ExcInfoType" which accepts:

"None"
"bool"
"tuple[type[BaseException], BaseException, TracebackType | None]"
"tuple[None, None, None]"
"BaseException"

**Comment by rafrafek** [comment]
Workaround:

Use `logger._logger.exception()` instead of `logger.exception()` to satisfy the static type checker.

**Comment by heitorlessa** [comment]
hey @rafrafek thanks for spotting yet another one - we must have missed during the review (it was workaround override for the lack of stackframe in 3.8 only in logging.Logger).

Tackling that shortly

**Comment by heitorlessa** [comment]
I see why this was copied as-is from CPython logging impl: https://github.com/python/cpython/blob/d67f947c72af8a215db2fd285e5de9b1e671fde1/Lib/logging/__init__.py#L1537

**Comment by heitorlessa** [comment]
Waiting for CI to confirm it won't break previous versions, as I'm unsure when CPython added that typing alias since the `exception()` implementation don't have it either.

**Comment by heitorlessa** [comment]
Closing, coming up in the next release. Thank you one more time @rafrafek for reporting it!
