### ISSUE TITLE
Feature request: Add `addFilter` and `removeFilter` to Logger

### ISSUE THREAD

**Issue by rafrafek** [awslabs/aws-lambda-powertools-python#3358]
### Use case

Pyright complains:
```python
import logging
from aws_lambda_powertools.logging import Logger
logger = Logger(name="%(name)s")
temp_filter = logging.Filter()
logger.addFilter(temp_filter)  # Cannot access member "addFilter" for type "Logger"
logger.removeFilter(temp_filter)  # Cannot access member "removeFilter" for type "Logger"
```

### Solution/User Experience

Add `addFilter` and `removeFilter` to Logger to match the built-in Python's logger.

### Alternative solutions

```markdown
import logging
from aws_lambda_powertools.logging import Logger
logger = Logger(name="%(name)s")
temp_filter = logging.Filter()
logger._logger.addFilter(temp_filter)
logger._logger.removeFilter(temp_filter)
```

### Acknowledgment

- [X] This feature request meets [Powertools for AWS Lambda (Python) Tenets](https://docs.powertools.aws.dev/lambda/python/latest/#tenets)
- [ ] Should this be considered in other Powertools for AWS Lambda languages? i.e. [Java](https://github.com/aws-powertools/powertools-lambda-java/), [TypeScript](https://github.com/aws-powertools/powertools-lambda-typescript/), and [.NET](https://github.com/aws-powertools/powertools-lambda-dotnet/)

**Comment by heitorlessa** [comment]
hey @rafrafek thanks a lot for reporting it, working on it now.

**Comment by heitorlessa** [comment]
Done - should be out in the next release after re:Invent. https://github.com/aws-powertools/powertools-lambda-python/pull/3380

**Comment by rafrafek** [comment]
Thank you! Can you include `removeFilter`?

**Comment by heitorlessa** [comment]
Oops, forgot! Sending that shortly

**Comment by rafrafek** [comment]
Thanks!

**Comment by heitorlessa** [comment]
All done, merging shortly. Fixed the exception type too #3356

**Comment by heitorlessa** [comment]
Closing, coming up in the next release. Thank you one more time @rafrafek for reporting it!

**Comment by heitorlessa** [comment]
@rafrafek releasing it now so you don't have to wait until re:Invent is over :) A logger bugfix along with the release too

**Comment by rafrafek** [comment]
Thank you very much!
