### ISSUE TITLE
FIX shared.functions.resolve_env_var_choice function inverting params

### ISSUE THREAD

**Issue by TheUncleRemus** [awslabs/aws-lambda-powertools-python#3371]
### Expected Behaviour

The signature of the function `shared.functions.resolve_env_var_choice` is:

```python
def resolve_env_var_choice(
    env: Optional[str] = None,
    choice: Optional[Union[str, float]] = None,
) -> Optional[Union[str, float]]:
``` 
the its docstring: """_Pick explicit choice over env, if available, otherwise return env value received_""", and its return code is:

```python
return choice if choice is not None else env
``` 

In every class or function where the above function (`shared.functions.resolve_env_var_choice`) is called, the calling is this:
```python
resolve_env_var_choice(
            choice=service,
            env=os.getenv(constants.SERVICE_NAME_ENV, "service_undefined"),
        )
``` 

If I call the `shared.functions.resolve_env_var_choice`, with input param:
-  `choice="choice_name"`
- `env="env_name"` 

in according with its docstring, the expected beahviour should be: `choice_name`. **But this is not true**. Because as you can see the function take and evaluate the params in different order than to the 'call' order. 

The question is: the docstring is wrong or the signature of the function (`shared.functions.resolve_env_var_choice`) is wrong?

### resolve_env_var_choice
```python
def resolve_env_var_choice(
    env: Optional[str] = None,
    choice: Optional[Union[str, float]] = None,
) -> Optional[Union[str, float]]:
    """Pick explicit choice over env, if available, otherwise return env value received

    NOTE: Environment variable should be resolved by the caller.

    Parameters
    ----------
    env : str, Optional
        environment variable actual value
    choice : str|float, optional
        explicit choice

    Returns
    -------
    choice : str, Optional
        resolved choice as either bool or environment value
    """
    return choice if choice is not None else env
``` 

### caller (example using `logging.logger.Logger`)
```python
 self.service = resolve_env_var_choice(
            choice=service,
            env=os.getenv(constants.SERVICE_NAME_ENV, "service_undefined"),
        )
``` 

### with input
-  `choice="choice_name"`
- `env="env_name"` 

### result
return the value inside `choice` param but the current value - inside in `choice` param - is the result of env evaluation by the caller. 

### Code snippet

```python
import unittest

class ResolveEnvVarChoice(unittest.TestCase):
    """ResolveEnvVarChoice"""
    
    @staticmethod
    def resolve_env_var_choice(
        """shared.functions.resolve_env_var_choice"""
        env: Optional[str] = None,
        choice: Optional[Union[str, float]] = None,
    ) -> Optional[Union[str, float]]:


    def test_resolve_env_var_choice_caller(self):
        self.resolve_env_var_choice(choice='my_choice_name', env='my_env_name')

# run test
if __name__ == '__main__':
     unittest.main()
```

### Possible Solution

First of all, all callers call this function at the same way, this:
```python
self.service = resolve_env_var_choice(
            choice=service,
            env=os.getenv('an env key name'),
        )
```

for this reason, a solution should be:

### from
def resolve_env_var_choice(
    env: Optional[str] = None,
    choice: Optional[Union[str, float]] = None,
) -> Optional[Union[str, float]]:
    """Pick explicit choice over env, if available, otherwise return env value received

    NOTE: Environment variable should be resolved by the caller.

    Parameters
    ----------
    env : str, Optional
        environment variable actual value
    choice : str|float, optional
        explicit choice

    Returns
    -------
    choice : str, Optional
        resolved choice as either bool or environment value
    """
    return choice if choice is not None else env 

### to
def resolve_env_var_choice(
    choice: Optional[Union[str, float]] = None,
    env: Optional[str] = None,
) -> Optional[Union[str, float]]:
    """Pick explicit choice over env, if available, otherwise return env value received

    NOTE: Environment variable should be resolved by the caller.

    Parameters
    ----------
    env : str, Optional
        environment variable actual value
    choice : str|float, optional
        explicit choice

    Returns
    -------
    choice : str, Optional
        resolved choice as either bool or environment value
    """
    return choice if choice is not None else env

### Steps to Reproduce

# method 1
passing the logegr environment variable, called: **POWERTOOLS_SERVICE_NAME** (using **aws console** or serverless framework, like below)
```
functions:
    myfun:
        handler: myhandler
        runtime: python 3.x
        environment:
            POWERTOOLS_SERVICE_NAME: myservice_name
``` 
# method 2
cut & paste the below unitest class code (as previously explained i the '_code snippet_' section)
```python
import unittest

class ResolveEnvVarChoice(unittest.TestCase):
    """ResolveEnvVarChoice"""
    
    @staticmethod
    def resolve_env_var_choice(
        """shared.functions.resolve_env_var_choice"""
        env: Optional[str] = None,
        choice: Optional[Union[str, float]] = None,
    ) -> Optional[Union[str, float]]:


    def test_resolve_env_var_choice_caller(self):
        self.resolve_env_var_choice(choice='my_choice_name', env='my_env_name')

# run test
if __name__ == '__main__':
     unittest.main()
``` 

### Powertools for AWS Lambda (Python) version

latest

### AWS Lambda function runtime

3.7

### Packaging format used

Serverless Application Repository (SAR) App

**Comment by heitorlessa** [comment]
hey @TheUncleRemus thanks for taking the time to write this bug report -- Did you run into any actual problem at runtime? This is an internal function and shouldn't be relied.

If I understood your report, you're suggesting these findings:

1. An explicit `choice` is **not** being returned when both `choice` and `env` parameters are used
2. The internal function `resolve_env_var_choice` signature uses `env` as the first parameter but calls to this function always uses `choice` first

Did I get these right?

Assuming I did, here's their respective answers:

1. Unless I'm misreading and need more coffee, our [dedicated unit tests](https://github.com/aws-powertools/powertools-lambda-python/blob/b20bbe806aed41bd4c0fcf36b4eb7a2ed52b247d/tests/unit/test_shared_functions.py#L24) and functional tests in multiple places ([Logger for example](https://github.com/aws-powertools/powertools-lambda-python/blob/b20bbe806aed41bd4c0fcf36b4eb7a2ed52b247d/tests/functional/test_logger.py#L78)) are attesting it works. Screenshot for a quick exploratory test at the bottom just in case.
2. I think there's a confusion about Python's **keyword** arguments vs **positional** arguments. While I agree that this function signature could be inverted based on our internal pattern, [it shouldn't make a difference as we use keyword arguments when calling it](https://docs.python.org/3/c-api/call.html).

I'm resolving but please feel free to reopen if I misinterpreted your findings.

---

**Exploratory test**

<img width="604" alt="image" src="https://github.com/aws-powertools/powertools-lambda-python/assets/3340292/39ff097d-397f-4e15-93e5-ae34a5881f13">

**Debugging keyword argument (PyObject + LOAD opcode)**

<img width="1855" alt="image" src="https://github.com/aws-powertools/powertools-lambda-python/assets/3340292/706fb5d1-f8ef-444a-9686-107124e5d2c3">

**Comment by TheUncleRemus** [comment]
Hi @heitorlessa You've right! Sorry!
I don't know what I did... propably your coffee is ok but my wine is to much :) enjoy!

**Comment by heitorlessa** [comment]
hahahaa it's alright ;) have a fantastic week @TheUncleRemus !!
