### ISSUE TITLE
Feature request: allow custom timestamps for metrics

### ISSUE THREAD

**Issue by pseidel-kcf** [awslabs/aws-lambda-powertools-python#3429]
### Use case

I'm creating a lambda to report metrics from an external source to Cloudwatch for observability within AWS. I'm looking for a way to set a custom timestamp for the metrics emitted each invocation.

The metrics I'm querying from the external source will basically be a list of (metric name, value) tuples for a specific time. This specific time will be in the recent past, maybe a few minutes old, but I'm not sure that matters here.

I can easily add the key and values to metrics, however I cannot set an explicit time because Metrics does not expose a way and the the time ultimately always set to [`datetime.now()`](https://github.com/aws-powertools/powertools-lambda-python/blob/56c2ee846124895ce3de19011aec3424ff0e0712/aws_lambda_powertools/metrics/provider/cloudwatch_emf/cloudwatch.py#L233) when rendered to emf. 

### Solution/User Experience

I'm imagining a simple api to set the timestamp on the Metrics object. If a timestamp is not specific then the current time should be used.

```
metrics = Metrics()

@metrics.log_metrics 
def lambda_handler(event: dict, context: LambdaContext):
    time = ...
    metric_values: list[(string, string)] = ...
    for (name, value) in metric_values:
            metrics.add_metric(name=name unit=MetricUnit.Count, value=value)
   metrics.set_timestamp(time) # <---
```

### Alternative solutions

[aws-embedded-metrics-python](https://github.com/awslabs/aws-embedded-metrics-python) supports setting the timestamp on their MetricLogger class. 

### Acknowledgment

- [X] This feature request meets [Powertools for AWS Lambda (Python) Tenets](https://docs.powertools.aws.dev/lambda/python/latest/#tenets)
- [X] Should this be considered in other Powertools for AWS Lambda languages? i.e. [Java](https://github.com/aws-powertools/powertools-lambda-java/), [TypeScript](https://github.com/aws-powertools/powertools-lambda-typescript/), and [.NET](https://github.com/aws-powertools/powertools-lambda-dotnet/)

**Comment by heitorlessa** [comment]
Hey! Thank you so much for opening a feature request — we should do this,
it wasn’t allowed by CloudWatch EMF in the earlier implementation but I
checked and it is now!

We’re at reinvent this week hence the delay. If you’d like to take a stab
at it and open up a PR, we’d be more than happy to review and/or improve it.

**Comment by rubenfonseca** [comment]
@pseidel-kcf just checking to see if you would like to work on this one?

**Comment by pseidel-kcf** [comment]
Thanks for the follow up. 

I don't have capacity to work on this. 

This is no longer a blocker for me because the external source from my example is implementing a built-in way to export metrics.

**Comment by rubenfonseca** [comment]
No problem! We'll keep it in the backlog to see if there's more interest in this feature. Thank you so much for opening this!

**Comment by MatasNed** [comment]
@rubenfonseca Would it be possible for me to contribute to this? I'd be interested. Let me know

**Comment by leandrodamascena** [comment]
Hey everyone! I submitted a PullRequest to add this new feature, but I have some questions.

#### 1 - Timestamp type
> According to the [AWS Documentation](https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/CloudWatch_Embedded_Metric_Format_Specification.html) timestamp **is a number** representing the time stamp used for metrics extracted from the event. Values MUST be expressed as the number of milliseconds after Jan 1, 1970 00:00:00 UTC.

That said, should we only allow int inputs with epoch value, or should customers be able to pass `datetime` objects and have them converted internally?

#### 2 - Invalid values
If a customer passes an invalid number, we will emit a warning and fallback to the current timestamp instead of raising an exception.

I'm still working on the pull request and I expect to have it merged by next week. 

Thank you.

**Comment by rubenfonseca** [comment]
1 - I agree that we should start simple with "int", as we can always overload the function later if there's the demand for other types

Great job picking this up Leandro
