### ISSUE TITLE
Bug: Remove get_lambda function from API Gateway proxy event

### ISSUE THREAD

**Issue by leandrodamascena** [awslabs/aws-lambda-powertools-python#3453]
### Expected Behaviour

The [API Gateway v2 payload ](https://docs.aws.amazon.com/apigateway/latest/developerguide/http-api-develop-integrations-lambda.html) doesn´t have any field called `lambda` and we should not have this in our Data Class.

 

### Current Behaviour

Unecessary [get_lambda](https://github.com/aws-powertools/powertools-lambda-python/blob/ddd9bd8174549672590196e91b667bd9b78c612c/aws_lambda_powertools/utilities/data_classes/api_gateway_proxy_event.py#L183) function.

### Code snippet

```python
No code snippet
```

### Possible Solution

Remove this and adjust tests/payload

```python
@property
def get_lambda(self) -> Optional[Dict[str, Any]]:
    """Lambda authorization context details"""
    return self.get("lambda")
```

### Steps to Reproduce

No necessary

### Powertools for AWS Lambda (Python) version

latest

### AWS Lambda function runtime

3.10

### Packaging format used

PyPi

**Comment by heitorlessa** [comment]
Adding update as it turned out docs were wrong, `lambda` key is always present; we only didn't do a good job in providing a consistent UX in getting Authorizer Context keys injected by Lambda Authorizers.

---

Potential solution discussed in today's sync:

```python
from aws_lambda_powertools.utilities.data_classes.api_gateway_proxy_event import APIGatewayProxyEvent, APIGatewayProxyEventV2

a = APIGatewayProxyEvent({})
b = APIGatewayProxyEventV2({})

ctx: dict = a.request_context.authorizer.get_context()  # or get_lambda_context
ctx_two: dict = b.request_context.authorizer.get_context()  # or get_lambda_context

ctx.get("tenant_id")
ctx_two.get("tenant_id")

```
