### ISSUE TITLE
Static typing: utilities.parameters.get_parameter

### ISSUE THREAD

**Issue by troyswanson** [awslabs/aws-lambda-powertools-python#3507]
### Static type checker used

pyright/pylance

### AWS Lambda function runtime

3.10

### Powertools for AWS Lambda (Python) version

2.29.1

### Static type checker info

> Argument of type "str | dict[Unknown, Unknown] | bytes" cannot be assigned to parameter "__x" of type "ConvertibleToInt" in function "__new__"

### Code snippet

```python
from aws_lambda_powertools.utilities.parameters import get_parameter


param_value = get_parameter("/My/Parameter")
param_as_int = int(param_value)
```

### Possible Solution

I believe this is happening because the `get_parameter` function can be configured via the `transform` argument to convert the param into a dictionary (if the response if a JSON string) or bytes (if the response is a base64 encoded string).

The type annotation for the function return can be overloaded depending on what value is used for that argument.

**Comment by rubenfonseca** [comment]
Looking at this now

**Comment by rubenfonseca** [comment]
@troyswanson I need a little more help here. Is this on VSCode? I pasted your code into a file but I can't generate an error message. Can you please give me more information about the setup?

**Comment by troyswanson** [comment]
Yes, I'm using VSCode. Here's a screenshot from my computer while hovering over the `param_value` variable.

<img width="619" alt="Screenshot 2023-12-15 at 9 53 31 AM" src="https://github.com/aws-powertools/powertools-lambda-python/assets/1420926/611a14ae-cc95-4503-97e9-b8b63ca53d29">

The return type for `get_parameter` is `str | dict[Unknown, Unknown] | bytes` because the function has the ability to transform the data from SSM into a dict or bytes. However, if you don't specify a transformation, it will just return as a str.

Using the `int` function on a dict type will always fail, which is why the type checker is throwing the warning.

A fix that I can make in my code would be to use `typing.cast` to force the type checker to assume the value is a str type, but I believe this can be solved in the Powertools library by overloading the type hints for the `get_parameter` function depending on what kind of arguments are being passed to it.

**Comment by rubenfonseca** [comment]
Thank you for the update and for testing the issue locally! It sounds like you've pinpointed the challenge with the SSM provider. However I'm not seeing a simple way of implementing the override, mainly due to it being very specific to the SSM provider.

If you have a clear direction in mind for a solution, we'd greatly appreciate your contribution. Please feel free to open a pull request, and we can collaborate to refine the implementation and get it ready for merging. Looking forward to seeing your approach and working together on this!
