### ISSUE TITLE
Bug: swagger ui try out bugs with simple query string params

### ISSUE THREAD

**Issue by danikenan** [awslabs/aws-lambda-powertools-python#3515]
### Expected Behaviour

Allow filling out fields and executing (try out) simple requests in swagger ui without validation errors.

Please note: 
The openapi json (extracted from the swagger html) works well in other swaggers editors. I tested with several editors.

### Current Behaviour

Multiple bugs in the swagger ui:

1. Two input fields representing two distinct query params seem to somehow be connected. They initialize to the same value (with no reason) and when the changes in the first field are also shown in the second.

2. Even when both required fields are filled, the ui reports of a validation error as if one of the field is missing

### Code snippet

```python
app = APIGatewayRestResolver(
    enable_validation=True,
)

app.enable_swagger(
    path="/docs/swagger",
    title="My Company API",
)

@app.get("/v1/audience-anywhere")
def audience_anywhere(
    network: Annotated[
        Literal["twitter", "reddit"],
        Query(description="The network name. Currently only 'twitter' supported"),
    ],
    hashed_user_id: Annotated[str, Query(alias="hashed-user-id")],
) -> AudienceAnywhereResponse:
    logger.debug({"network": network, "hashed-user-id": hashed_user_id})
    return AudienceAnywhereResponse(audiences=["some value"])

```

### Steps to Reproduce

create a simple lambda with the above code, deploy and test in browser

![Screenshot 2023-12-15 at 14 21 57](https://github.com/aws-powertools/powertools-lambda-python/assets/887919/a88fb3c3-fe45-4e23-8174-0c69196539f8)

### Powertools for AWS Lambda (Python) version

latest

### AWS Lambda function runtime

3.12

### Packaging format used

Lambda Layers

**Comment by rubenfonseca** [comment]
Looking at this now

**Comment by rubenfonseca** [comment]
We were using an outdated version of the Swagger UI that had problems, submitting a new PR to fix this!
