### ISSUE TITLE
Bug: get_openapi_json_schema() default openapi version 3.0.0 

### ISSUE THREAD

**Issue by MCR2019** [awslabs/aws-lambda-powertools-python#3519]
### Expected Behaviour

api_gateway.py docstring on line 1500 states:

"""
openapi_version: str, default = "3.1.0"
        The version of the OpenAPI Specification (which the document uses).
        """

When creating a openapi json schema with no `openapi_version` specified it is expected that the version defaults to `3.1.0`.

### Current Behaviour

When creating an openpi json schema with no openapi version specified (openapi_version) it defaults to `3.0.0`.

### Code snippet

```python
from aws_lambda_powertools.event_handler import APIGatewayRestResolver

app = APIGatewayRestResolver(enable_validation=True)


@app.put(
    "/example-resource",
    responses={200: {"description": "Todo item found"}},
    tags=["Examples"]
)
def put():
    pass


if __name__ == "__main__":
    print(app.get_openapi_json_schema())
```

### Possible Solution

Either update the docstring or update the constant: `DEFAULT_OPENAPI_VERSION = "3.0.0"`

### Steps to Reproduce

Create an openapi json schema with no `openapi_version` specified and view the output.

### Powertools for AWS Lambda (Python) version

2.30.1

### AWS Lambda function runtime

3.10

### Packaging format used

PyPi

**Comment by rubenfonseca** [comment]
Awesome catch! Fixing it now.

**Comment by rubenfonseca** [comment]
Your effort to ensure consistency across our documentation regarding the default OpenAPI version is much appreciated. It's great to see the clarification that version 3.0.0 is supported by default. Your contributions help make our documentation clearer for everyone. Thanks again for your diligent work!
