### ISSUE TITLE
Bug: openAPI json spec generation - path tags validation failure - property type must be string

### ISSUE THREAD

**Issue by MCR2019** [awslabs/aws-lambda-powertools-python#3520]
### Expected Behaviour

When generating the openAPI json schema using `get_openapi_json_schema()` and specifying path tags, the produced schema should validate against OAS 3.0.0 or 3.1.0 and path tags should be an array of strings.

[OAS3.1.0](https://github.com/OAI/OpenAPI-Specification/blob/main/schemas/v3.1/schema.yaml)
'  operation:
    $comment: https://spec.openapis.org/oas/v3.1.0#operation-object
    type: object
    properties:
      tags:
        type: array
        items:
          type: string'

### Current Behaviour

When generating the openAPI json schema using `get_openapi_json_schema()` and specifying path tags, the produced schema raises a validation error against OAS 3.0.0 or 3.1.0 with the following error:

`property type must be string`

### Code snippet

```python
from aws_lambda_powertools.event_handler import APIGatewayRestResolver

app = APIGatewayRestResolver(enable_validation=True)


@app.put(
    "/example-resource",
    tags=["Examples"]
)
def put():
    pass


if __name__ == "__main__":
    print(app.get_openapi_json_schema())
```

### Steps to Reproduce

- Create a simple path with tags and attach to an APIGatewayRestResolver.
- Create and print the openapi_json_schema.
- Compare the output to OAS 3.1.0 or 3.0.0 
- Output shows:

`"paths": {
    "/example-resource": {
      "put": {
        "tags": [
          {
            "name": "Examples"
          }
        ],
        "summary": "PUT /example-resource",`

Which is not correct as OAS 3.1.0 (and 3.0.0) ([OAS3.1.0](https://github.com/OAI/OpenAPI-Specification/blob/main/schemas/v3.1/schema.yaml)) specify an array of strings:

`  operation:
    $comment: https://spec.openapis.org/oas/v3.1.0#operation-object
    type: object
    properties:
      tags:
        type: array
        items:
          type: string`

### Powertools for AWS Lambda (Python) version

2.30.1

### AWS Lambda function runtime

3.10

### Packaging format used

PyPi

**Comment by rubenfonseca** [comment]
Looking at this one now

**Comment by rubenfonseca** [comment]
Thank you for confirming the bug and for taking the initiative to open this bug report. It's great to know that operation tags should be a simple list of strings, and your effort in addressing this issue is truly appreciated. I'm working right now on the fix.

**Comment by MCR2019** [comment]
Thank you!
