### ISSUE TITLE
List intersection action for conditions in feature flags

### ISSUE THREAD

**Issue by Rogalek** [awslabs/aws-lambda-powertools-python#3531]
### Use case

I was thinking if there is a way to write action for condition in feature flags that can do list Intersection. 
https://www.geeksforgeeks.org/python-intersection-two-lists/

### Solution/User Experience

So user could provide key: [A, B] and inside AWS Appconfig json there will be stored value: [B, C]
And if at least one elements match for both list that this will match criteria.

### Acknowledgment

- [X] This feature request meets [Powertools for AWS Lambda (Python) Tenets](https://docs.powertools.aws.dev/lambda/python/latest/#tenets)
- [ ] Should this be considered in other Powertools for AWS Lambda languages? i.e. [Java](https://github.com/aws-powertools/powertools-lambda-java/), [TypeScript](https://github.com/aws-powertools/powertools-lambda-typescript/), and [.NET](https://github.com/aws-powertools/powertools-lambda-dotnet/)

**Comment by rubenfonseca** [comment]
Interesting, the existing `KEY_IN_VALUE` does not cover a scenario where both items are lists. Is this something you would be able to contribute with a pull request? I would love to help you merge it.

**Comment by Rogalek** [comment]
Yes, sure I can try to create PR after Christmas and New Year

**Comment by gwlester** [comment]
May want a couple of intersections:

- ANY_IN_VALUE
- ALL_IN_VALUE
- NONE_IN_VALUE

**Comment by leandrodamascena** [comment]
Hi @Rogalek and @gwlester! Thanks for sharing this idea to add more features to our Feature Flags utility. For me, it makes a lot of sense to expand this support. After all, we open up more opportunities to use this utility, such as checking if, given an array, `ANY` of those elements are present, something that we don't support nowadays because we don't check individual values passed in the context.

Just a small comment:

> * ALL_IN_VALUE

We already support it if you use `EQUALS`.

Do you still have plans to send a PR with these changes @Rogalek? Please let me know and we can work together to get it merged.

**Comment by gwlester** [comment]
@leandrodamascena 
You wrote:
ALL_IN_VALUE
We already support it if you use EQUALS.

They are not the same -- All_IN_VALUE would mean that all in the list are in the value, but does not also mean that all in the value are in the list.   EQUAL means that all in the list are in the value and also that all in the value are in the list.

**Comment by gwlester** [comment]
I think I may be taking a shot at implementing this over the next couple of weeks -- does anyone have any issues with that?

@heitorlessa , @leandrodamascena

**Comment by gwlester** [comment]
I have the code at https://github.com/gwlester/aws-lambda-powertools-python/tree/feature-3531 -- but not sure what to do about the tests.   With the way they are organized now, I don't see a good way to add ones for these three actions (there is another ticket to refactor them).

Can I get some feedback about the tests?

**Comment by leandrodamascena** [comment]
> @leandrodamascena You wrote: ALL_IN_VALUE We already support it if you use EQUALS.
> 
> They are not the same -- All_IN_VALUE would mean that all in the list are in the value, but does not also mean that all in the value are in the list. EQUAL means that all in the list are in the value and also that all in the value are in the list.

Hey @gwlester! Yep, you're right, I agree!

> I have the code at [gwlester/aws-lambda-powertools-python@feature-3531](https://github.com/gwlester/aws-lambda-powertools-python/tree/feature-3531?rgh-link-date=2024-01-31T19%3A45%3A56Z) -- but not sure what to do about the tests.

Do you want to open a PR without testing and we can work together to add these tests? We can do some code reviews until we reach the ideal code for merge. It makes sense?

Thanks

**Comment by gwlester** [comment]
@leandrodamascena pull request created: https://github.com/aws-powertools/powertools-lambda-python/pull/3692

**Comment by heitorlessa** [comment]
Adding a sample schema for reference as I didn't find them earlier.

---

**ALL_IN_VALUE**

> `context=["Gerald"]`

```json
{
    "my_feature": {
        "default": false,
        "rules": {
            "tenant_id is in allowed list": {
                "when_match": true,
                "conditions": [
                    {
                        "action": "ALL_IN_VALUE",
                        "key": "tenant_id",
                        "value": [
                            "Łukasz",
                            "Gerald",
                            "Leandro",
                            "Heitor"
                        ]
                    }
                ]
            }
        }
    }
}
```

**ANY_IN_VALUE**

> `context=["Gerald"]`

```json
{
    "my_feature": {
        "default": false,
        "rules": {
            "tenant_id is in allowed list": {
                "when_match": true,
                "conditions": [
                    {
                        "action": "ANY_IN_VALUE",
                        "key": "tenant_id",
                        "value": [
                            "Łukasz",
                            "Gerald",
                            "Leandro",
                            "Heitor"
                        ]
                    }
                ]
            }
        }
    }
}
```

**NONE_IN_VALUE**

> `context=["Simon"]`

```json
{
    "my_feature": {
        "default": false,
        "rules": {
            "tenant_id is in allowed list": {
                "when_match": true,
                "conditions": [
                    {
                        "action": "NONE_IN_VALUE",
                        "key": "tenant_id",
                        "value": [
                            "Łukasz",
                            "Gerald",
                            "Leandro",
                            "Heitor"
                        ]
                    }
                ]
            }
        }
    }
}
```

**Comment by heitorlessa** [comment]
@Rogalek @gwlester I've noticed this is our first built-in condition that an input may not be a list and a silent error (False flag) may not be ideal -- instead of failing flat causing further disruption to other flags, I'm gonna add an exception handler that you could use to trap ANY exception.

[I'm refactoring the last bits oft the implementation](https://github.com/aws-powertools/powertools-lambda-python/pull/3775), and will work on the exception handler. For that reason, we'll release early next week only - mon/tue.

**Comment by heitorlessa** [comment]
Closing as it's coming in this week's release. PR merged w/ refactorings.
