### ISSUE TITLE
Feature request: openAPI - support for top level tags metadata

### ISSUE THREAD

**Issue by MCR2019** [awslabs/aws-lambda-powertools-python#3533]
### Expected Behaviour

tag objects should support optional metadata such as `description` and `externalDocs` as in the openAPI spec: [OAS](https://github.com/OAI/OpenAPI-Specification/blob/main/schemas/v3.1/schema.json)

<img width="1101" alt="image" src="https://github.com/aws-powertools/powertools-lambda-python/assets/19569678/498ba94b-b778-41e3-a0fb-0c9692a57af5">

(just adding the description would be great)

### Current Behaviour

Currently only the required tag name is supported.

### Code snippet

```python
from aws_lambda_powertools.event_handler import APIGatewayRestResolver

app = APIGatewayRestResolver(enable_validation=True)


@app.put(
    "/example-resource",
    tags=["Example Tag"]
)
def put():
    pass


if __name__ == "__main__":
    print(app.get_openapi_json_schema(
        tags=["Example Tag"]
    ))
```

### Steps to Reproduce

- Create an operation and specify a tag.
- There is no way to specify anything other than the tag name

### Powertools for AWS Lambda (Python) version

2.30.2

### AWS Lambda function runtime

3.10

### Packaging format used

PyPi

**Comment by rubenfonseca** [comment]
Looking at this now

**Comment by leandrodamascena** [comment]
I am classifying this issue as a feature request instead of a bug and assigning it to @rubenfonseca.

**Comment by rubenfonseca** [comment]
Hi @MCR2019 thank you for opening this issue. It seems our top level OpenAPI object is only supporting strings at the moment.

Please notice that [according to the spec](https://swagger.io/specification/#operation-object), **tags in Operations are just lists of strings**. The only place where a Tag is an object with additional fields is on the top level OpenAPI object:

```python
from aws_lambda_powertools.event_handler import APIGatewayRestResolver
from aws_lambda_powertools.event_handler.openapi.models import ExternalDocumentation, Tag

app = APIGatewayRestResolver(enable_validation=True)


@app.put("/example-resource", tags=["Example Tag"])
def put():
    pass


if __name__ == "__main__":
    print(
        app.get_openapi_json_schema(
            tags=[
                Tag(
                    name="Example",
                    description="This is a description",
                    externalDocs=ExternalDocumentation(url="https://example.org", description="Example website"),
                )
            ]
        )
    )

```

I'll be working on adding support for this.
