### ISSUE TITLE
Feature request: Add Canada - Calgary region to the Lambda Layers Deployment

### ISSUE THREAD

**Issue by leandrodamascena** [awslabs/aws-lambda-powertools-python#3545]
### Use case

AWS recently launched new region:

Canada (Calgary) - ca-west-1

https://aws.amazon.com/blogs/aws/the-aws-canada-west-calgary-region-is-now-available/

This region doesn't support arm64, so we need to add in exception list.

### Solution/User Experience

Deploy Lambda Layers to these new region.

### Acknowledgment

- [X] This feature request meets [Powertools for AWS Lambda (Python) Tenets](https://docs.powertools.aws.dev/lambda/python/latest/#tenets)
- [X] Should this be considered in other Powertools for AWS Lambda languages? i.e. [Java](https://github.com/aws-powertools/powertools-lambda-java/), [TypeScript](https://github.com/aws-powertools/powertools-lambda-typescript/), and [.NET](https://github.com/aws-powertools/powertools-lambda-dotnet/)

**Comment by rubenfonseca** [comment]
> CompatibleArchitectures are not supported in ca-west-1

Note: ca-west-1 currently does not support arm64 lambdas
