### ISSUE TITLE
Feature request: Publish AWS Lambda layers under /aws/service/list

### ISSUE THREAD

**Issue by avoidik** [awslabs/aws-lambda-powertools-python#3586]
### Use case

I would like to be able to dynamically lookup the latest available AWS Lambda layer ARN. 

### Solution/User Experience

AWS has already been maintaining a list of public SSM parameters, please consider enlisting `powertools-lambda-python` too. Similar to ref. https://aws-sdk-pandas.readthedocs.io/en/latest/install.html#aws-lambda-layer

```terminal
$ aws ssm get-parameters-by-path --path /aws/service/list
$ aws ssm describe-parameters --parameter-filters 'Key=Name, Option=BeginsWith, Values=/aws/service/aws-sdk-pandas/' --query 'sort_by(Parameters, &LastModifiedDate)'
```

Sample code

```python
powertools_layer_arn = ssm.StringParameter.from_string_parameter_attributes(self, "MyValue",
  parameter_name="/aws/service/powertools-lambda-python/x.y.z/py3.xx/x86_64/layer-arn"
).string_value
```

### Alternative solutions

```markdown
Hardcoded Lambda layer ARN
```

### Acknowledgment

- [X] This feature request meets [Powertools for AWS Lambda (Python) Tenets](https://docs.powertools.aws.dev/lambda/python/latest/#tenets)
- [X] Should this be considered in other Powertools for AWS Lambda languages? i.e. [Java](https://github.com/aws-powertools/powertools-lambda-java/), [TypeScript](https://github.com/aws-powertools/powertools-lambda-typescript/), and [.NET](https://github.com/aws-powertools/powertools-lambda-dotnet/)

**Comment by leandrodamascena** [comment]
Hello @avoidik! Thanks for opening this issue to add our Lambda layer in public parameters. This feature makes it easier to automate the use of the latest layer in customer's pipelines. However, we need to do some internal processes to add our layer to this list and I don't have an ETA for completing this as it involves other teams.

Starting tomorrow I will carry out these processes and as soon as I have an update I will let you know here.

Thank you.

**Comment by Dilski** [comment]
Just want to +1 this, it would make it a lot easier for us to keep our layers/dependencies up to date.

**Comment by sthulb** [comment]
We have nearly completed work on this and will be available shortly.
