### ISSUE TITLE
[I Made This]: Creating a serverless API using AWS Lambda Powertools and CDK

### ISSUE THREAD

**Issue by thomasgtaylor** [awslabs/aws-lambda-powertools-python#3595]
### Link to your material

https://how.wtf/creating-a-serverless-api-using-aws-lambda-powertools-and-cdk.html

### Description

This article walks through the process of using the AWS CDK to deploy an L3 construct, `LambdaRestApi`, with a lambda proxy integration that leverages the AWS Powertools SDK end-to-end. Readers walk away with a CDK-deployable application.

Techniques include:
- Leveraging SAR
- Using L3 constructs
- Explaining the Powertools
- etc.

### Preferred contact

Thomas Taylor

### (Optional) Social Network

https://www.linkedin.com/in/iamthomastaylor/

### Acknowledgment

- [X] I understand this content may be removed from Powertools for AWS Lambda (Python) documentation if it doesn't conform with the [Code of Conduct](https://aws.github.io/code-of-conduct)

**Comment by leandrodamascena** [comment]
Hi @iamthomastaylor! We're really happy when the community spends their time creating content using Powertools, this is what motivates us to work hard in this project!

I'll read the article tomorrow, make comments (if needed) and add it in our documentation!

Thanks :heart:

**Comment by thomasgtaylor** [comment]
Hey @leandrodamascena! I'm always happy to spread the word! For context, this blog gets around 13,000 monthly viewers - so hopefully it'll gain some well-deserved attention for Powertools!

Please let me know if something does not suffice!

**Comment by leandrodamascena** [comment]
> Hey @leandrodamascena! I'm always happy to spread the word! For context, this blog gets around 13,000 monthly viewers - so hopefully it'll gain some well-deserved attention for Powertools!

Wow, those are impressive numbers of viewers!!

> Please let me know if something does not suffice!

Just a note and this is not mandatory, but we recently renamed the project from AWS Lambda Powertools to Powertools for AWS Lambda and it might be cool in this/future articles for you to use the new name!

Working now to open the PR to include this article!
