### ISSUE TITLE
bug: Swagger UI is breaking with certain characters

### ISSUE THREAD

**Issue by ran-isenberg** [awslabs/aws-lambda-powertools-python#3599]
### What were you searching in the docs?

In customizing_api_operations.py, there's an example:
description="Loads a todo item identified by the `todo_id`",

It might be just silly old me, but i changed the text, forgot one of these: ` at the end so it was:
"bla bla `"  and the /swagger endpoint would not load at all. OpenAPI file was valid.

### How can we improve?

Maybe it's best to escape or remove this example?

### Acknowledgment

- [X] I understand the final update might be different from my proposed suggestion, or refused.

**Comment by leandrodamascena** [comment]
Hey @ran-isenberg! Thanks for opening this issue. I'll send a PR to fix this documentation and the bug when using the backtick character.

**Comment by leandrodamascena** [comment]
Assinging to @rubenfonseca!

**Comment by leandrodamascena** [comment]
Hi @ran-isenberg! I changed the title of this issue because it is a bug in our codebase and not in the documentation. Now we fix that.
