### ISSUE TITLE
Feature: Event handler Swagger doesnt add 422 response to openapi when adding custom responses

### ISSUE THREAD

**Issue by ran-isenberg** [awslabs/aws-lambda-powertools-python#3600]
### Expected Behaviour

422 is a built in schema that i as a user don't control, i expect it to be there even though I'm adding other responses (501 , 404 etc.).

### Current Behaviour

422 is omitted from schema when adding a custom response.
In addition, the 422 schema says there's a msg: string in the schema but in my tests i didnt get that fields, maybe it's optional?

### Code snippet

```python
See:
https://github.com/ran-isenberg/aws-lambda-handler-cookbook/pull/784/files#diff-03a550a2c5158da1b1459e42e5799bdfe3809d2563dfb16014d3ea3bcd7cd043R20
```

### Steps to Reproduce

add the snippet, go to /swagger

### Powertools for AWS Lambda (Python) version

latest

### AWS Lambda function runtime

3.12

### Packaging format used

PyPi

**Comment by leandrodamascena** [comment]
Assigning myself to answer it tomorrow!

**Comment by leandrodamascena** [comment]
Hi @ran-isenberg! I've changed this issue to a feature request. We agree that adding 422 should be mandatory even when the customer creates custom responses on specific routes, but we need to investigate whether it is possible to allow clients to customize the 422 response if necessary.

I'm adding this feature to our backlog and will probably deliver it in the next releases.

Thanks for reporting this and helping us to improve this new feature.

**Comment by ran-isenberg** [comment]
I found a workaround for now @leandrodamascena 
I added it manually and i created a proper pydantic code.
Here's the pydantic class:
```python
from typing import Annotated, List, Optional, Union

from pydantic import BaseModel, Field



class PydanticError(BaseModel):
    loc: Annotated[List[Union[str, int]], Field(description='Error location')]
    type: Annotated[str, Field(description='Error type')]
    msg: Annotated[Optional[str], Field(description='Error message')]


class InvalidRestApiRequest(BaseModel):
    details: Annotated[List[PydanticError], Field(description='Error details')]

```


here's the code:
```python
responses={
        200: {
            'description': 'The created order',
            'content': {'application/json': {'model': MyModel}},
        },
        442: {
            'description': 'Invalid create order request',
            'content': {'application/json': {'model': InvalidRestApiRequest}},
        },
        501: {
            'description': 'Internal server error',
            'content': {'application/json': {'model': MyErrorModel}},
        },
```

**Comment by rubenfonseca** [comment]
I'm looking at this today, see if there's a way to move forward.
