### ISSUE TITLE
Docs: Missing closing ``` from function comment

### ISSUE THREAD

**Issue by massi-ang** [awslabs/aws-lambda-powertools-python#3644]
### What were you searching in the docs?

https://docs.powertools.aws.dev/lambda/python/latest/api/event_handler/bedrock_agent.html

The example is not correctly displayed as there are missing closing ```

### Is this related to an existing documentation section?

https://docs.powertools.aws.dev/lambda/python/latest/api/event_handler/bedrock_agent.html

### How can we improve?

Add the ```

### Got a suggestion in mind?

Add ``` to close the example

### Acknowledgment

- [X] I understand the final update might be different from my proposed suggestion, or refused.

**Comment by leandrodamascena** [comment]
Hi @massi-ang! Thanks for pointing this out, nice catch! Do you want to send a PR to fix it? That would be amazing.

We haven't officially released this feature yet and are still working on documentation. We expect to launch it by the end of this month.
