### ISSUE TITLE
Feature request: event_handler Resolver ability to return http response 

### ISSUE THREAD

**Issue by jordital** [awslabs/aws-lambda-powertools-python#3689]
### Use case

A lambda function URL response with a http redirect.

### Solution/User Experience

ResponseBuilder.build method to return direct route function result when is a dict with `statusCode`, `body` attributes

### Acknowledgment

- [X] This feature request meets [Powertools for AWS Lambda (Python) Tenets](https://docs.powertools.aws.dev/lambda/python/latest/#tenets)
- [ ] Should this be considered in other Powertools for AWS Lambda languages? i.e. [Java](https://github.com/aws-powertools/powertools-lambda-java/), [TypeScript](https://github.com/aws-powertools/powertools-lambda-typescript/), and [.NET](https://github.com/aws-powertools/powertools-lambda-dotnet/)

**Comment by leandrodamascena** [comment]
Hello @jordital! Thank you for opening this issue. Can you help me better understand the problem here? Maybe providing a code snippet to understand the challenge and how we can help you with this?

**Comment by leandrodamascena** [comment]
Hello, @jordital! Just wanted to check if you still need help with this. Please let us know.

**Comment by leandrodamascena** [comment]
Closing this issue! Please feel free to reopen.
