### ISSUE TITLE
RFC: Dynamodb endpoint url for local testing

### ISSUE THREAD

**Issue by rtrive** [awslabs/aws-lambda-powertools-python#370]
## Key information

* RFC PR: 
* Related issue(s), if known:
* Area: Utilities-Parameters-DynamoDB
* Meet [tenets](https://awslabs.github.io/aws-lambda-powertools-python/#tenets): Yes
* Approved by: ''
* Reviewed by: ''

## Summary
[summary]: #summary

Add possibility to use this library in AWS lambda with DynamoDB local that run on docker.  

## Motivation
[motivation]: #motivation

When you want to test your lambda locally you could user DynamoDB local to avoid to interact with remote database. Right now the parameter `endpoint_url` is missing on dynamodb provider configuratio

## Proposal
[proposal]: #proposal

```python
  def __init__(
      self,
      table_name: str,
      key_attr: str = "id",
      sort_attr: str = "sk",
      value_attr: str = "value",
      endpoint_url: Optional[str] = None,
      config: Optional[Config] = None,
  ):
      """
      Initialize the DynamoDB client
      """

      config = config or Config()
      self.table = boto3.resource("dynamodb", endpoint_url=endpoint_url, config=config).Table(table_name)
```
Insert `enpoindt_url` parameter as init config of dynamodb provider

**If this feature should be available in other runtimes (e.g. Java, Typescript), how would this look like to ensure consistency?**

## Drawbacks
[drawbacks]: #drawbacks

> Why should we *not* do this? Few people are interested on local dynamodb

> Do we need additional dependencies? Impact performance/package size? no

## Rationale and alternatives
[rationale-and-alternatives]: #rationale-and-alternatives

* **What other designs have been considered? Why not them?**
* **What is the impact of not doing this?**

## Unresolved questions
[unresolved-questions]: #unresolved-questions

> Optional, stash area for topics that need further development e.g. TBD

**Comment by heitorlessa** [comment]
Ciao Riccardo!! Definitely on-board with that. There are two things I wanted to do here but might be able to do only next week:

1. Add this - Should be a quick PR, so happy to [guide a contribution](https://github.com/awslabs/aws-lambda-powertools-python/blob/develop/CONTRIBUTING.md) if you'd like
2. Also add a Session parameter - This will allow customers to fetch parameters across account, as boto Config object isn't enough

I tagged this to make sure it's done and available in the next minor release ;)

Thank you!

**Comment by rtrive** [comment]
Ciao @heitorlessa!!

i build a small PR only for `endpoint_url` and i will try to merged it asap :)

**Comment by heitorlessa** [comment]
Merged 🎉 this will be out in the next release hopefully by next EOW

**Comment by heitorlessa** [comment]
hey @rtrive this is now out as part of 1.14.0 release ;) Thanks a lot for contributing it!

**Comment by rtrive** [comment]
it's a pleasure ;)
