### ISSUE TITLE
Nathan Hanks:  Boost App Engagement with AWS CloudWatch Metrics & Powertools for AWS

### ISSUE THREAD

**Issue by ran-isenberg** [awslabs/aws-lambda-powertools-python#3726]
### Link to your material

https://www.ranthebuilder.cloud/post/boost-app-engagement-with-aws-cloudwatch-metrics-powertools-for-aws

### Description

CloudWatch custom metrics, often utilized as key performance indicators (KPIs), possess versatile applications beyond their conventional use. Powertools for AWS Lambda simplifies the process of writing these metrics, unlocking innovative use cases. 

This article will guide you through personalizing observability by integrating CloudWatch metrics into mobile push notifications, a strategy that significantly enhances mobile app engagement. If you're a data engineer looking to instrument an ingestion pipeline, or an application developer aiming to deliver user-specific metric notifications, this post offers valuable insights tailored for you.

### Preferred contact

Nathan Hanks

### (Optional) Additional notes

I created a PR for Nathan who posted on my website.
here's the PR https://github.com/aws-powertools/powertools-lambda-python/pull/3727

### Acknowledgment

- [X] I understand this content may be removed from Powertools for AWS Lambda (Python) documentation if it doesn't conform with the [Code of Conduct](https://aws.github.io/code-of-conduct)

**Comment by ran-isenberg** [comment]
here's the PR https://github.com/aws-powertools/powertools-lambda-python/pull/3727

**Comment by sthulb** [comment]
Thanks Ran & Nathan!
