### ISSUE TITLE
Bedrock Agent resolver security assessment

### ISSUE THREAD

**Issue by rubenfonseca** [awslabs/aws-lambda-powertools-python#3733]
We need to run a security assessment for the new Bedrock Agent resolver

**Comment by sthulb** [comment]
Thank you @rubenfonseca for the issue. We’ll look into prioritising this during our next team sync

**Comment by heitorlessa** [comment]
@sthulb updates? Flipped to `Pending Review` instead of `Triage`.

**Comment by leandrodamascena** [comment]
Closing as completed.
