### ISSUE TITLE
Bedrock Agents resolver blog post

### ISSUE THREAD

**Issue by rubenfonseca** [awslabs/aws-lambda-powertools-python#3734]
A new blog post will be created to annouce the new powertools bedrock agents resolver

**Comment by sthulb** [comment]
Thank you @rubenfonseca for the issue. We’ll look into prioritising this during our next team sync

**Comment by sthulb** [comment]
https://aws.amazon.com/about-aws/whats-new/2024/05/powertools-aws-lambda-python-support-agents-bedrock/
