### ISSUE TITLE
Static typing: headers in Response should be Mapping instead of Dict

### ISSUE THREAD

**Issue by tonnico** [awslabs/aws-lambda-powertools-python#3743]
### Static type checker used

mypy (project's standard)

### AWS Lambda function runtime

3.12

### Powertools for AWS Lambda (Python) version

latest

### Static type checker info

```
error: Argument "headers" to "Response" has incompatible type "dict[str, str]"; expected
"dict[str, str | list[str]] | None"  [arg-type]
            headers=headers,
                    ^~~~~~~
note: "Dict" is invariant -- see https://mypy.readthedocs.io/en/stable/common_issues.html#variance
note: Consider using "Mapping" instead, which is covariant in the value type
```

### Code snippet

```python
headers = {"str": "str"}
Response(200, headers=headers)
```

### Possible Solution

Instead of `Dict[str, Union[str, List[str]]` use `Mapping[str, Union[str, List[str]]`.
E.g. https://stackoverflow.com/a/73603324/6621062

**Comment by heitorlessa** [comment]
thanks a lot @Wurstnase for taking the time, truly ;) Merging shortly so it's part of today's release!!

**Comment by heitorlessa** [comment]
Merged, should be available to everyone in the next few hours on PyPi and Lambda Layers. 

Huge welcome to the Powertools for AWS community @Wurstnase <3
