### ISSUE TITLE
Maintenance: Update readme to style badge and remove email

### ISSUE THREAD

**Issue by hjgraca** [awslabs/aws-lambda-powertools-python#3769]
### Why is this needed?

Update readme to style discord badge and remove DevAx contact email

### Acknowledgment

- [X] This request meets [Powertools for AWS Lambda (Python) Tenets](https://docs.powertools.aws.dev/lambda/python/latest/#tenets)
- [X] Should this be considered in other Powertools for AWS Lambda languages? i.e. [Java](https://github.com/aws-powertools/powertools-lambda-java/), [TypeScript](https://github.com/aws-powertools/powertools-lambda-typescript/), and [.NET](https://github.com/aws-powertools/powertools-lambda-dotnet/)

**Comment by rubenfonseca** [comment]
Closed as the PR was merged already.
