### ISSUE TITLE
Idempotency Getting Started Documentation

### ISSUE THREAD

**Issue by weallwegot** [awslabs/aws-lambda-powertools-python#377]
**What were you initially searching for in the docs?**
I want to use the idempotency power tool utility to help prevent lambdas from multiple executions

**Is this related to an existing part of the documentation? Please share a link**
https://awslabs.github.io/aws-lambda-powertools-python/utilities/idempotency/

**Describe how we could make it clearer**
Currently there is a template.yml provided to set up the DynamoDB table required for the example, but it would be great to also have just screenshots of how one would set up DynamoDB from the console as well. I'm having an issue configuring my table correctly and i cant pinpoint if I've done it wrong or its an issue elsewhere.

Could also be helpful to note if anything needs to be done differently if you are setting up with a lambda that exists in a VPC, for instance do i need an endpoint? 

**If you have a proposed update, please share it here**

Proposed update would be another tab next to the template.yml that shows the equivalent configuration for the console.

**Comment by michaelbrewer** [comment]
@cakepietoast  @heitorlessa  hopefully a good case for an article / repo for idempotent feature.

**Comment by heitorlessa** [comment]
hey @weallwegot Thanks for helping us make the docs better!

I've added a table explaining the two configuration and their values that we expect if you're not overriding the default behaviour - Thanks to your suggestion, this should help anyone not using Infrastructure as Code to quickly create one in the Console.

I didn't add a Console screenshot as this might change and misguide customers, for example if the TTL attribute can be created in a different part of the console.

Docs: https://awslabs.github.io/aws-lambda-powertools-python/develop/utilities/idempotency/#required-resources

![image](https://user-images.githubusercontent.com/3340292/114148953-a3b9e300-991a-11eb-985f-b578f3ae6137.png)
