### ISSUE TITLE
[I Made This]: reinvent session & code with Heitor

### ISSUE THREAD

**Issue by ran-isenberg** [awslabs/aws-lambda-powertools-python#3789]
### Link to your material

see PR

### Description

I'd like to add the reinvent session we did about serverless which included lots of powertools usage and also the code repo which has many examples.

### Preferred contact

Ran Isenberg

### Acknowledgment

- [X] I understand this content may be removed from Powertools for AWS Lambda (Python) documentation if it doesn't conform with the [Code of Conduct](https://aws.github.io/code-of-conduct)

**Comment by heitorlessa** [comment]
<3
