### ISSUE TITLE
Docs: Fix feature flags documentation

### ISSUE THREAD

**Issue by ran-isenberg** [awslabs/aws-lambda-powertools-python#3791]
### What were you searching in the docs?

1. Some line markers in the code examples were not in the correct lines.
2. The envelope example was not correct, it's supposed to be the "features" sub dictionary and not the "features_flags" value which i assume was meant as the appconfig configuration name.

### Is this related to an existing documentation section?

https://docs.powertools.aws.dev/lambda/python/latest/utilities/feature_flags/#getting-all-enabled-features

### How can we improve?

I opened the PR :)

### Acknowledgment

- [X] I understand the final update might be different from my proposed suggestion, or refused.

**Comment by rubenfonseca** [comment]
Looking at this now

**Comment by heitorlessa** [comment]
[future] go ahead with the merge Rubao as we chatted. I'll create another much larger PR refreshing the entire feature flags docs with examples, diagrams, etc., after the refactoring today
