### ISSUE TITLE
Bug: Swagger generated UI has JSON format invalid URL

### ISSUE THREAD

**Issue by ran-isenberg** [awslabs/aws-lambda-powertools-python#3793]
### Expected Behaviour

I deployed my API gateway to https://tzmt8vspl4.execute-api.us-east-1.amazonaws.com/prod/ 
It has the prod stage.
When i enter the /swagger URL, and click on the /swagger?format=json, i get the json file.

### Current Behaviour

I get an invalid url and a permissions denied.
The generated URL there doesnt include the '/prod' part.

### Code snippet

```python
See https://github.com/ran-isenberg/aws-lambda-handler-cookbook/blob/main/cdk/service/api_construct.py the create swagger function.
```

### Steps to Reproduce

Deploy the cookbook code.

### Powertools for AWS Lambda (Python) version

latest

### AWS Lambda function runtime

3.12

### Packaging format used

PyPi

**Comment by rubenfonseca** [comment]
Looking at this now

**Comment by rubenfonseca** [comment]
Confirmed, working on a fix.
