### ISSUE TITLE
Static typing: missing @overload to ensure return type is a str when default_value is set

### ISSUE THREAD

**Issue by tonnico** [awslabs/aws-lambda-powertools-python#3839]
### Static type checker used

pyright/pylance

### AWS Lambda function runtime

3.12

### Powertools for AWS Lambda (Python) version

latest

### Static type checker info

Expression of type "str | None" cannot be assigned to declared type "str"

### Code snippet

```python
header_value: str = event.get_header_value("name", "")
```

### Possible Solution

`@overload`

**Comment by heitorlessa** [comment]
pending CI checks ;)
