### ISSUE TITLE
Feature request: Add event object sent from Cloudwatch Alarms 

### ISSUE THREAD

**Issue by jaydm26** [awslabs/aws-lambda-powertools-python#3848]
### Use case

AWS has added a trigger for [Cloudwatch Alarms that can trigger lambdas](https://aws.amazon.com/about-aws/whats-new/2023/12/amazon-cloudwatch-alarms-lambda-change-action/). Thus, it would be helpful to include this in the available data classes.

More on the event object can be found here: https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/AlarmThatSendsEmail.html#alarms-and-actions

### Solution/User Experience

The required data classes are added to AWS Powertools

### Acknowledgment

- [X] This feature request meets [Powertools for AWS Lambda (Python) Tenets](https://docs.powertools.aws.dev/lambda/python/latest/#tenets)
- [ ] Should this be considered in other Powertools for AWS Lambda languages? i.e. [Java](https://github.com/aws-powertools/powertools-lambda-java/), [TypeScript](https://github.com/aws-powertools/powertools-lambda-typescript/), and [.NET](https://github.com/aws-powertools/powertools-lambda-dotnet/)

**Comment by leandrodamascena** [comment]
Hi @jaydm26! Thanks for opening this issue and remembering that we need to add this new event source data class.

Do you want to send a PR to implement this? We'd love to have your first contribution here 🚀.

**Comment by jaydm26** [comment]
Hi @leandrodamascena 

I would be happy to. Might take some time to implement it. 

If someone takes it up before I take it up, go ahead. I will update the thread again when I begin.

**Comment by par6n** [comment]
I have opened a pull request (still on draft) for this, as I've already implemented something similar in my team. I'd be more than happy to hear your feedback/comments/opinions on the changes! 😃

**Comment by rubenfonseca** [comment]
@par6n awesome work! Feel free to publish the PR and I'll be happy to review and help you merge your contribution!

**Comment by leandrodamascena** [comment]
Closing as completed!
