### ISSUE TITLE
Add Validation Schema Examples

### ISSUE THREAD

**Issue by PixelAmp** [awslabs/aws-lambda-powertools-python#386]
**What were you initially searching for in the docs?**
I wanted to implement the Validation utility to validate data received by my requests, but was unfamiliar with writing JSONSchema.

**Is this related to an existing part of the documentation? Please share a link**
https://awslabs.github.io/aws-lambda-powertools-python/latest/utilities/validation/

There are no working examples of valid `json_schema_dict` within the documentation.
They are all collapsed making it difficult to get an idea for how JSONSchema should be structured.

`json_schema_dict = {..}`

**Describe how we could make it clearer**
The [fastjsonschema](https://horejsek.github.io/python-fastjsonschema/) library is linked, however an actual example within this documentation page would make improve comprehension.   

For example [Unwrapping events prior to validation](https://awslabs.github.io/aws-lambda-powertools-python/latest/utilities/validation/#unwrapping-events-prior-to-validation) has `sample_wrapped_event.json`, but it does not show what the accompanying schema should look like.

**If you have a proposed update, please share it here**
I suggest adding a tab with some example inputs and their schema. as well as adding what a `SchemaValidationError` exception looks like for different scenarios.

For example, the a rudimentary validation schema for `sample_wrapped_event.json` would likely look like this (but with better regex and pattern matching)
```
json_schema_dict = {
    "type": "object",
    "properties": {
        "id": {"type": "string"},
        "detail-type": {"type": "string"},
        "source": {"type": "string"},
        "account": {"type": "string"},
        "time": {"type": "string"},
        "region": {"type": "string"},
        "resources": {"type": "string"},
        "detail": {
            "type": "object",
            "properties": {
                "message": {"type": "string"},
                "username": {"type": "string"},
            }
        }
    }
}

```

**Comment by heitorlessa** [comment]
Hola @PixelAmp - Thanks for helping us improve the documentation! We'll surely do that after this week's release :) 

In the meantime, you can find a few within validator's functional tests: https://github.com/awslabs/aws-lambda-powertools-python/blob/develop/tests/functional/validator/conftest.py

**Background**: Historically, it wasn't there because the older documentation system didn't support tabbed content and made it more verbose, so we stripped it.

**Comment by heitorlessa** [comment]
hey @PixelAmp - This is now live in staging: https://awslabs.github.io/aws-lambda-powertools-python/develop/utilities/validation/

I've added a JSON Schema and event for every sample, reformat navigation to use the new Getting started vs Advanced use cases too.

Let me know if that helps :)

**Comment by PixelAmp** [comment]
That looks great! 

Those examples significantly improve the readability of the module and will make it a lot easier to quickly get it up and running.

Thanks!
