### ISSUE TITLE
Bug: SQSMessageAttributes __getitem__ has a different type to items() values

### ISSUE THREAD

**Issue by palfrey** [awslabs/aws-lambda-powertools-python#3880]
### Expected Behaviour

I'd expect the value of `items()` calls to equal the values from `__getitem__`

### Current Behaviour

You get SQSMessageAttribute from `__getitem__` and `(str, Any)` Tuples from `items`

### Code snippet

```python
attributes = SQSMessageAttributes({"key":{"stringValue":"value", "dataType":"String"}})

assert attributes.items()[0][0] != attributes[attributes.key()]
```

### Possible Solution

Either rewrite on the way in, or override items.

### Steps to Reproduce

attributes = SQSMessageAttribute({"key":{"stringValue":"value", "dataType":"String"}})

assert attributes.items()[0][0] != attributes[attributes.key()]

### Powertools for AWS Lambda (Python) version

latest

### AWS Lambda function runtime

3.8

### Packaging format used

PyPi

**Comment by rubenfonseca** [comment]
Looking at this now

**Comment by rubenfonseca** [comment]
Good catch. I was thinking on overriding the items method like this:

```python
    def items(self) -> Iterator[Tuple[str, SQSMessageAttribute]]:
        return ((k, SQSMessageAttribute(v)) for k, v in super().items())
```

What do you think?

**Comment by palfrey** [comment]
> Good catch. I was thinking on overriding the items method like this:
> 
> ```python
>     def items(self) -> Iterator[Tuple[str, SQSMessageAttribute]]:
>         return ((k, SQSMessageAttribute(v)) for k, v in super().items())
> ```
> 
> What do you think?

That works. Can't think of any other path currently to get items from the dict so just doing the `items` override should be enough.
