### ISSUE TITLE
Feature request: Remove 'service' dimension from single_metric()

### ISSUE THREAD

**Issue by nikevp** [awslabs/aws-lambda-powertools-python#3917]
### Use case

My team has a specific metric format used across lambda runtimes with the following dimensions: [Operation, Function]. I would like to use `single_metric` without 'service' added as a third dimension.

I would remove POWERTOOLS_SERVICE_NAME, but we also leverage the powertools Logger.

### Solution/User Experience

The ability to exclude 'service' as a dimension from `single_metric` calls.

### Alternative solutions

```markdown
Support ignoring POWERTOOLS_SERVICE_NAME globally in Metric() since it is required by Logger.
```

### Acknowledgment

- [X] This feature request meets [Powertools for AWS Lambda (Python) Tenets](https://docs.powertools.aws.dev/lambda/python/latest/#tenets)
- [ ] Should this be considered in other Powertools for AWS Lambda languages? i.e. [Java](https://github.com/aws-powertools/powertools-lambda-java/), [TypeScript](https://github.com/aws-powertools/powertools-lambda-typescript/), and [.NET](https://github.com/aws-powertools/powertools-lambda-dotnet/)

**Comment by leandrodamascena** [comment]
Hello @nikevp! Thanks for opening this issue! I'd like to hear from other maintainers what they think about this, as disabling `POWERTOOLS_SERVICE_NAME` globally can be a problem and lead to unexpected behavior. Adding a flag to `single_metric` makes this very specialized and perhaps not the best developer experience.
I'm not saying that we won't analyze how to implement this or that I'm against it, but I don't have a strong opinion on this matter and I would like to ask my peers for help.

For now, if this is a mandatory requirement and is harming your production environment I might suggest you set the public `service` variable to `None` before single_metric's ContextManager flushes it. It's not the best experience, but it works as a workaround while we try to figure out a solution to this.

Something like this:

```python
import os

from aws_lambda_powertools import single_metric
from aws_lambda_powertools.metrics import MetricUnit
from aws_lambda_powertools.utilities.typing import LambdaContext

STAGE = os.getenv("STAGE", "dev")


def lambda_handler(event: dict, context: LambdaContext):
    with single_metric(name="MySingleMetric", unit=MetricUnit.Count, value=1, namespace="TEST") as metric:
        metric.add_dimension(name="environment", value=STAGE)
        metric.add_dimension(name="xyz", value="123")
        metric.service = None
```

cc @sthulb @rubenfonseca 

Thanks

**Comment by rubenfonseca** [comment]
Agree with @leandrodamascena comments. At most, we could add a service kwarg to the `single_metric` call to make it easier to remove it, but this is not recommended behaviour anyway. The workaround may be sufficient.

**Comment by sthulb** [comment]
I agree with @rubenfonseca – I think using @leandrodamascena's code snippet, you could wrap it in a function to ensure that you get what you want without having context managers everywhere in your code

**Comment by nikevp** [comment]
Thanks for the quick reply @leandrodamascena. Your example works perfectly for my use case and I'm already using a singleton function for the logic. 

I was running into issues Friday trying to pass `service=None` which is ignored due to https://github.com/aws-powertools/powertools-lambda-python/blob/fa235c0d7335265342f3f13d189d7e10af0ed0b6/aws_lambda_powertools/metrics/base.py#L189

Since you can easily remove the dimension before emitting, I no longer see any need for a code change. However, it might be worth noting in the logger documentation that adding $POWERTOOLS_SERVICE_NAME will automatically add a dimension to all metrics. This might be a rare edge case, but could negatively impact existing alarm coverage.

**Comment by leandrodamascena** [comment]
Hi @nikevp! Thank you for the feedback! I'm pleased to hear that you were able to resolve the issue.
We have a section in our documentation explaining that a new dimension will be created. While I believe it's well-explained, I'd appreciate your opinion on whether we should enhance this message.

https://docs.powertools.aws.dev/lambda/python/latest/core/metrics/#getting-started
![image](https://github.com/aws-powertools/powertools-lambda-python/assets/4295173/8067e9b9-ba05-4e9e-b3f7-b23d23e4d3e8)

Thank you.

**Comment by nikevp** [comment]
Hey @leandrodamascena, I agree the metric ENV documentation is clear. On my side, I overlooked the implications of adding POWERTOOLS_SERVICE_NAME to the logger without considering the impact on metrics. 

Here it does not indicate adding POWERTOOLS_SERVICE_NAME will impact metrics: https://docs.powertools.aws.dev/lambda/python/latest/core/logger/#getting-started

It's easy to catch in development by reviewing the logs, but only if you are setting up Metrics after Logger. If you setup the Metrics feature and later on add the Logger, a user might add POWERTOOLS_SERVICE_NAME without knowing it changes dimensions. This might not be a common migration pattern so I'm okay with the current documentation. 

If you think it's worth revising to clarify the dependency, you might do something like:


There are some [other environment variables](https://docs.powertools.aws.dev/lambda/python/latest/core/logger/#environment-variables) which can be set to modify Logger's settings at a global scope. The POWERTOOLS_SERVICE_NAME environment variable is shared with other features and adds a [default service dimension](https://docs.powertools.aws.dev/lambda/python/latest/core/metrics/#getting-started) to Metrics.
