### ISSUE TITLE
Feature request: Add compression for swagger ui

### ISSUE THREAD

**Issue by xquek** [awslabs/aws-lambda-powertools-python#3935]
### Use case

Hi when serving swagger over ALB, there is a 1 MB limit. 

We are able to get pass it by using swagger_base_url and servce the js file from it. 
But i was wondering if ti will be possible to add a `compress` flag and return a compress response when setting `enable_swagger`

### Solution/User Experience

```
# usage 
app.enable_swagger(..., compress=True)
```
and then in line https://github.com/aws-powertools/powertools-lambda-python/blob/fa235c0d7335265342f3f13d189d7e10af0ed0b6/aws_lambda_powertools/event_handler/api_gateway.py#L1720

```
def enable_swagger(...):
   ...
   return Response(
        compress = compress 
   )
```

or at 
https://github.com/aws-powertools/powertools-lambda-python/blob/fa235c0d7335265342f3f13d189d7e10af0ed0b6/aws_lambda_powertools/event_handler/api_gateway.py#L1662C8-L1662C74

```
       @self.get(path, middlewares=middlewares, include_in_schema=False, compress = compress)
        def swagger_handler():
```

I have tested this on my local development stack, it went from over 1mb which results in 502, to ~ 330kb in response size.

We can set the default as false so it is backwards compatible 

### Acknowledgment

- [X] This feature request meets [Powertools for AWS Lambda (Python) Tenets](https://docs.powertools.aws.dev/lambda/python/latest/#tenets)
- [X] Should this be considered in other Powertools for AWS Lambda languages? i.e. [Java](https://github.com/aws-powertools/powertools-lambda-java/), [TypeScript](https://github.com/aws-powertools/powertools-lambda-typescript/), and [.NET](https://github.com/aws-powertools/powertools-lambda-dotnet/)

**Comment by leandrodamascena** [comment]
Hi @xquek! Thanks for opening this issue with this important feature request. I completely agree with you that we should provide a way to allow customers to choose whether they want the HTTP Response to be compressed or not when serving the swagger file. This can be a challenge for anyone using a browser request that doesn't add the "Accept-Encoding" header, for example, but it's something we add in our documentation so the customer is aware.

I like the implementation of adding a parameter `compress` in `enable_swagger` function and setting `False` as default to keep backwards compatibility.

Do you want to send a PR to add this feature? We can work together to get it merged before our next release.

Thanks

**Comment by xquek** [comment]
Hi @leandrodamascena! thanks for the feedback! ill be very happy to send in a PR! Thanks!!

**Comment by xquek** [comment]
Hi there , i created - https://github.com/aws-powertools/powertools-lambda-python/pull/3946 let me know if there is any question! thanks!
