### ISSUE TITLE
Docs: Incorrect OpenAPI Param used in example

### ISSUE THREAD

**Issue by eldritchideen** [awslabs/aws-lambda-powertools-python#3945]
### What were you searching in the docs?

The Customizing API operations example is using the wrong OpenAPI param. The example uses Query, when it should be Path. 
https://docs.powertools.aws.dev/lambda/python/latest/core/event_handler/bedrock_agents/#customizing-api-operations:~:text=Customzing%20API%20operations

### Is this related to an existing documentation section?

https://docs.powertools.aws.dev/lambda/python/latest/core/event_handler/bedrock_agents/#customizing-api-operations:~:text=Customzing%20API%20operations

### How can we improve?

Simple updates to the example code. 

### Acknowledgment

- [X] I understand the final update might be different from my proposed suggestion, or refused.

**Comment by eldritchideen** [comment]
Happy to submit a PR to fix this, I'll work on it.

**Comment by rubenfonseca** [comment]
Thank you so much for catching this @eldritchideen ! We would love your PR to fix this :)
