### ISSUE TITLE
Default API Reference Link Broken

### ISSUE THREAD

**Issue by michaelbrewer** [awslabs/aws-lambda-powertools-python#396]
### Steps to reproduce:

1. Vist https://awslabs.github.io/aws-lambda-powertools-python/latest/
2. Click on "API Reference"

<img width="578" alt="Screen Shot 2021-04-13 at 4 42 27 AM" src="https://user-images.githubusercontent.com/5442469/114546982-a9614280-9c12-11eb-8922-21552b82c961.png">

## NOTE

- https://awslabs.github.io/aws-lambda-powertools-python/develop/ does work

**Comment by heitorlessa** [comment]
Fix that for now, will permanently fix in GitHub Actions when I'm back from PTO

**Comment by heitorlessa** [comment]
Resolving this now as it'll be merged as soon as checks pass.
