### ISSUE TITLE
Static typing: APIGatewayRestResolver `.post()` decorator return type Unknown

### ISSUE THREAD

**Issue by rafrafek** [awslabs/aws-lambda-powertools-python#3990]
### Static type checker used

pyright/pylance

### AWS Lambda function runtime

3.12

### Powertools for AWS Lambda (Python) version

latest

### Static type checker info

Latest Pylance, latest VS Code, type checking mode strict.

```
Untyped function decorator obscures type of function
```

Screenshot:

<img width="634" alt="image" src="https://github.com/aws-powertools/powertools-lambda-python/assets/23004737/be7a9be9-0f17-44e4-8cac-8982ed4fce24">

### Code snippet

```python
from aws_lambda_powertools.event_handler import APIGatewayRestResolver

app = APIGatewayRestResolver()

@app.post("/v1/demo")
def demo() -> str:
    return "demo"
```

### Possible Solution

return `Callable[..., T]` or something like that

**Comment by rafrafek** [comment]
I think the solution may look similar to this:

```python
from typing import Any, Callable, TypeVar


T_route = TypeVar("T_route", bound=Callable[..., Any])


class Resolver:

    def route(self, rule: str, method: str) -> Callable[[T_route], T_route]:

        def register_resolver(func: T_route) -> T_route:
            print(rule, method)
            return func

        return register_resolver

    def post(self, rule: str) -> Callable[[T_route], T_route]:
        return self.route(rule=rule, method="POST")


app = Resolver()


@app.route("/v1/demo", "GET")
def demo() -> str:
    return "demo"


@app.post("/v1/demo_post")
def demo_post() -> str:
    return "demo post"

```

**Comment by leandrodamascena** [comment]
Hello @rafrafek! Thanks for opening this issue! I'm planning to review this next week.

**Comment by heitorlessa** [comment]
Adding help wanted label as we were unable to prioritize it. Any PR welcome <3

**Comment by rafrafek** [comment]
Created PR for this, appreciate reviewing it: https://github.com/aws-powertools/powertools-lambda-python/pull/5601
