### ISSUE TITLE
docs/typing: `validate` method should support `event` as Any type

### ISSUE THREAD

**Issue by michaelbrewer** [awslabs/aws-lambda-powertools-python#401]
## Problem

In some cases you want to use `validate` for something internal, like a downstream api call with returns a list of data:

<img width="821" alt="Screen Shot 2021-04-17 at 2 52 47 PM" src="https://user-images.githubusercontent.com/5442469/115127612-a062cf00-9f8c-11eb-8dbf-9e637bb78d65.png">

Currently `validate` type hints `event` as only a `Dict`, but it might be a `List` or `Tuple` etc..

## Solution?

Just type `event` as `Any`

**Comment by heitorlessa** [comment]
will be merged once checks pass - one of those that MyPy/Pyright will catch once in CI. Thanks again!!!
