### ISSUE TITLE
Feature request: Add parser API GW v1 proxy schema & envelope

### ISSUE THREAD

**Issue by risenberg-cyberark** [awslabs/aws-lambda-powertools-python#402]
This schema exists in the validator but not in the parser. It was requested in the webinar audience.
This feature will also provide an envelope class which will parse the string body parameter as a pydantic Model.

Also added new identity parameters as defined at https://docs.aws.amazon.com/apigateway/latest/developerguide/http-api-develop-integrations-lambda.html

**Comment by risenberg-cyberark** [comment]
@heitorlessa i think we can close this issue.

**Comment by heitorlessa** [comment]
> @heitorlessa i think we can close this issue.

I'm leaving them opened and tagged as staged next release ;-) 

I'll close it on 1.15.0 release next week

**Comment by heitorlessa** [comment]
This is now out as part of 1.15.0!!! Thanks a lot again for the contribution ;) 

https://github.com/awslabs/aws-lambda-powertools-python/discussions/423
