### ISSUE TITLE
[I Made This]: <TITLE>Streaming data with AWS Lambda

### ISSUE THREAD

**Issue by taupirho** [awslabs/aws-lambda-powertools-python#4041]
### Link to your material

https://medium.com/towardsdev/streaming-data-with-aws-lambda-5f0e81f854cd?sk=c8fc59ebd8c98facd2bec0d64fcf59a4

### Description

Shows how to use the AWS Powertool and Lambda to read big data via streaming

### Preferred contact

https://www.linkedin.com/in/tom-reid-5a2a3a/

### Acknowledgment

- [X] I understand this content may be removed from Powertools for AWS Lambda (Python) documentation if it doesn't conform with the [Code of Conduct](https://aws.github.io/code-of-conduct)

**Comment by leandrodamascena** [comment]
Thanks for opening this issue @taupirho! I'll review and make sure to add this content early next week.

**Comment by leandrodamascena** [comment]
This blog post is very helpful with good insights on enhancing Lambda functions performance with Powertools. I'm planning to send a PR tomorrow to include this content in the [We Made This](https://docs.powertools.aws.dev/lambda/python/latest/we_made_this/) section.

Thanks for sharing this with us @taupirho.
