### ISSUE TITLE
Bug: Error parsing AmazonMQ message

### ISSUE THREAD

**Issue by SZubarev** [awslabs/aws-lambda-powertools-python#4051]
### Expected Behaviour

AmazonMQ (ActiveMQ) message contains queue name in 
`...'destination': {'physicalName': 'MY.QUEUE.NAME'}...` as per [documentation](https://docs.aws.amazon.com/lambda/latest/dg/with-mq.html)
while parsing code is looking for 
`return self["destination"]["physicalname"]`
which causes parsing error

### Current Behaviour

Error when calling message.destination_physicalname

### Code snippet

```python
for message in event.messages:
        payload_decoded = message.decoded_data
        queue: str = message.destination_physicalname
```

### Possible Solution

[Fix typo here](https://github.com/aws-powertools/powertools-lambda-python/blob/a8cb3578e52634b95905c3cc612413dd985af33b/aws_lambda_powertools/utilities/data_classes/active_mq_event.py#L62)

### Steps to Reproduce

Send message via AmazonMQ, connect lambda function as event consumer

### Powertools for AWS Lambda (Python) version

latest

### AWS Lambda function runtime

3.11

### Packaging format used

Lambda Layers

### Debugging logs

```python
[ERROR] KeyError: 'physicalname'
Traceback (most recent call last):
  File "/var/task/archive.py", line 129, in lambda_handler
    queue: str = message.destination_physicalname
  File "/opt/python/aws_lambda_powertools/utilities/data_classes/active_mq_event.py", line 62, in destination_physicalname
    return self["destination"]["physicalname"]
```

**Comment by leandrodamascena** [comment]
Hi @SZubarev! Thanks for reporting this bug! We would greatly appreciate your contribution. Would you be interested in submitting a PR to fix this?
