### ISSUE TITLE
Maintenance: Pydantic v1 end of life

### ISSUE THREAD

**Issue by leandrodamascena** [awslabs/aws-lambda-powertools-python#4067]
### Why is this needed?

Pydantic plays a critical role in Powertools, working as a key dependency across various utilities. While Powertools is fully compatible with Pydantic v2, the default version remains Pydantic v1. The active development of Pydantic v1 ceased with the launch of v2.
Although Pydantic v1 continues to address bug fixes and security problems, development will come to a definitive halt, including security updates, as of 30/06/2024.

I'm opening this issue to keep it on our radar and initiate a discussion about definitively dropping support for Pydantic v1.

https://docs.pydantic.dev/latest/version-policy/#pydantic-v1

>Active development of V1 has already stopped, however critical bug fixes and security vulnerabilities will be fixed in V1 for one year after the release of V2 (June 30, 2024).

### Which area does this relate to?

Parser

### Acknowledgment

- [X] This request meets [Powertools for AWS Lambda (Python) Tenets](https://docs.powertools.aws.dev/lambda/python/latest/#tenets)
- [ ] Should this be considered in other Powertools for AWS Lambda languages? i.e. [Java](https://github.com/aws-powertools/powertools-lambda-java/), [TypeScript](https://github.com/aws-powertools/powertools-lambda-typescript/), and [.NET](https://github.com/aws-powertools/powertools-lambda-dotnet/)

**Comment by rubenfonseca** [comment]
Thank you for opening this Leandro. I will try to understand the impact this might have on the Bedrock Agents resolver, including timelines.

**Comment by medley56** [comment]
This is really messing up my development. I use Pydantic elsewhere in my codebase for direct model validation and I'd like to use a non EOL version of Pydantic but I can't because I have to satisfy the ^1.8.2 pin in the metadata (pyproject.toml) of Powertools.

Please prioritize this. Pydantic is already on 2.8.

**Comment by sthulb** [comment]
@medley56 Hi there, current versions of Powertools are compatible with Pydantic v2. 

There’s a note in the docs on how to do this https://docs.powertools.aws.dev/lambda/python/latest/utilities/parser/#using-pydantic-v2

**Comment by leandrodamascena** [comment]
We are working to release Powertools v3 soon (hopefully in August) and in this new major release we are removing Pydantic v1.

https://github.com/aws-powertools/powertools-lambda-python/issues/4189

**Comment by leandrodamascena** [comment]
We are working on the RFC for Powertools V3. Check more information here: https://github.com/aws-powertools/powertools-lambda-python/issues/4189
