### ISSUE TITLE
Docs: Note on default payload_format_version when using Terraform's apigatewayv2

### ISSUE THREAD

**Issue by rubenfonseca** [awslabs/aws-lambda-powertools-python#4089]
### What were you searching in the docs?

When reading the docs on the [API Gateway HTTP integration](https://docs.powertools.aws.dev/lambda/python/latest/core/event_handler/api_gateway/#api-gateway-http-api)  we find this:

> Using HTTP API v1 payload? Use APIGatewayRestResolver instead. APIGatewayHttpResolver defaults to v2 payload.

However, when using Terraform's API Gateway v2 module, it [defaults to payload version v1](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/apigatewayv2_integration#payload_format_version). 

This can take a long time to debug.

### Is this related to an existing documentation section?

https://docs.powertools.aws.dev/lambda/python/latest/core/event_handler/api_gateway/#api-gateway-http-api

### How can we improve?

Add a note to the documentation that you need to explicitly tell Terraform to use the v2 payload format version.

### Acknowledgment

- [X] I understand the final update might be different from my proposed suggestion, or refused.

**Comment by leandrodamascena** [comment]
I agree that we can improve our documentation to make it clearer. And I've already opened an issue in the Terraform repository to change this and maintain the same behavior when using AWS and Terraform.

https://github.com/hashicorp/terraform-provider-aws/issues/37035
