### ISSUE TITLE
Maintenance: Deprecate `tracing.base.BaseProvider`

### ISSUE THREAD

**Issue by roger-zhangg** [awslabs/aws-lambda-powertools-python#4105]
### Why is this needed?

In PR #2342 we are providing a observability provider friendly tracing provider to deprecate the current X-Ray specific provider `tracing.base.baseprovider` and `tracing.base.BaseSegment`. This new provider solution will enable our customer to send traces to Third party observability provider with ease. After #2342 is merged, the current provider will no longer be used in Tracer.

### Which area does this relate to?

Tracer

### Solution

This Deprecation is straightforward. This provider class is mostly for internal purpose and X-ray only. If there are customers developing their own provider based on this base provider, they will be able to migrate to the new provider proposed in #2342 with few method/class name changes

### Acknowledgment

- [X] This request meets [Powertools for AWS Lambda (Python) Tenets](https://docs.powertools.aws.dev/lambda/python/latest/#tenets)
- [X] Should this be considered in other Powertools for AWS Lambda languages? i.e. [Java](https://github.com/aws-powertools/powertools-lambda-java/), [TypeScript](https://github.com/aws-powertools/powertools-lambda-typescript/), and [.NET](https://github.com/aws-powertools/powertools-lambda-dotnet/)

**Comment by rubenfonseca** [comment]
Thank you for opening this @roger-zhangg ! Adding tags to track it for Powertools v3

**Comment by leandrodamascena** [comment]
We won't deprecate those classes in V3. We will keep as is but instead we'll open doors to new providers.

We can plan to remove this in V4, but wee ned to plan this in advanced.
