### ISSUE TITLE
Static typing: Missing DeadLetterQueueSourceArn on SqsAttributesModel

### ISSUE THREAD

**Issue by amyc92** [awslabs/aws-lambda-powertools-python#4111]
### Static type checker used

pyright/pylance

### AWS Lambda function runtime

3.12

### Powertools for AWS Lambda (Python) version

2.34.2

### Static type checker info

VS Code, basic type checking enabled

```
Cannot access member "DeadLetterQueueSourceArn" for type "SqsAttributesModel"
  Member "DeadLetterQueueSourceArn" is unknownPylance[reportAttributeAccessIssue](https://github.com/microsoft/pyright/blob/main/docs/configuration.md#reportAttributeAccessIssue)
```

### Code snippet

```python
from aws_lambda_powertools.utilities.parser.models import SqsModel
from aws_lambda_powertools.utilities.parser.parser import event_parser

@event_parser(model=SqsModel)
def handler(payload: SqsModel) -> str | None:
    return payload.Records[0].attributes.DeadLetterQueueSourceArn
```

**Comment by rubenfonseca** [comment]
Looking at this now

**Comment by rubenfonseca** [comment]
It seems the `DeadLetterQueueSourceArn `attribute is not [part of our SqsAttributesModel](https://github.com/aws-powertools/powertools-lambda-python/blob/ca0091fbee68995a8c30e4c583d2411e8a72f8c9/aws_lambda_powertools/utilities/parser/models/sqs.py#L9-L17)

Investigating if it should be there. @amyc92 if you could provide us with a sample Payload, it would help :)

**Comment by rubenfonseca** [comment]
Note: if the field is missing, it's also missing on our data class https://github.com/aws-powertools/powertools-lambda-python/blob/f1b95d2aab93fb2194eb1827423b2b44acec3801/aws_lambda_powertools/utilities/data_classes/sqs_event.py#L9-L56

**Comment by rubenfonseca** [comment]
@amyc92 just to confirm, this happens when you re-drive the SQS messages from a DLQ, correct?

**Comment by rubenfonseca** [comment]
Note: one Typescript implementation adds the field [as undocumented](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/62aac965a724d818b9651fccf11f13e82b6f4a22/types/aws-lambda/trigger/sqs.d.ts#L33C1-L34C1)

**Comment by rubenfonseca** [comment]
Only mentioned on official AWS docs [here](https://docs.aws.amazon.com/AWSSimpleQueueService/latest/APIReference/API_Message.html)

**Comment by rubenfonseca** [comment]
I think we need to add the field. @amyc92 is this something you would like to contribute? Otherwise we can add it too :)

**Comment by leandrodamascena** [comment]
We need to add this in the SQS parser model as well.

https://github.com/aws-powertools/powertools-lambda-python/blob/develop/aws_lambda_powertools/utilities/parser/models/sqs.py#L9

**Comment by rubenfonseca** [comment]
> We need to add this in the SQS parser model as well.
> 
> [`develop`/aws_lambda_powertools/utilities/parser/models/sqs.py#L9](https://github.com/aws-powertools/powertools-lambda-python/blob/develop/aws_lambda_powertools/utilities/parser/models/sqs.py?rgh-link-date=2024-04-12T09%3A58%3A22Z#L9)

https://github.com/aws-powertools/powertools-lambda-python/issues/4111#issuecomment-2049323706

**Comment by amyc92** [comment]
> I think we need to add the field. @amyc92 is this something you would like to contribute? Otherwise we can add it too :)

Sorry @rubenfonseca for missing this - I see you've made the changes now. Thank you!
