### ISSUE TITLE
Static typing: missing @overload to ensure return type is a str when default_value is set

### ISSUE THREAD

**Issue by tonnico** [awslabs/aws-lambda-powertools-python#4113]
### Static type checker used

pyright/pylance

### AWS Lambda function runtime

3.12

### Powertools for AWS Lambda (Python) version

latest

### Static type checker info

Expression of type "str | None" cannot be assigned to declared type "str"

Like in #3839 I found some more places for missing overloads.

### Code snippet

```python
header_value: str = event.get_header_value("name", "")
```

**Comment by rubenfonseca** [comment]
Looking at this now

**Comment by rubenfonseca** [comment]
Awesome, a lot to review here, but thank you already for opening this!
