### ISSUE TITLE
Docs: Incorrect Highlighted Lines in Documentation

### ISSUE THREAD

**Issue by Emerson-MM-Filho** [awslabs/aws-lambda-powertools-python#4117]
### What were you searching in the docs?

I was searching for information on lambda context typing and how to deal with it in test cases. While reviewing the documentation, I noticed that the highlighted lines in the code snippet were incorrect.

### Is this related to an existing documentation section?

https://docs.powertools.aws.dev/lambda/python/latest/utilities/typing/#working-with-context-methods-and-properties

### How can we improve?

To improve the experience, ensuring that the highlighted lines in code snippets accurately reflect the relevant lines would enhance clarity and correctness in the documentation.

### Got a suggestion in mind?

Update the highlighted lines in the file `/examples/typing/src/working_with_context_function.py` to correctly reflect lines `15`, `22`, and `23` 
https://github.com/aws-powertools/powertools-lambda-python/blob/ca0091fbee68995a8c30e4c583d2411e8a72f8c9/examples/typing/src/working_with_context_function.py#L15
https://github.com/aws-powertools/powertools-lambda-python/blob/ca0091fbee68995a8c30e4c583d2411e8a72f8c9/examples/typing/src/working_with_context_function.py#L22-L23
instead of lines `16`, `25`, and `26`
https://github.com/aws-powertools/powertools-lambda-python/blob/ca0091fbee68995a8c30e4c583d2411e8a72f8c9/examples/typing/src/working_with_context_function.py#L16
https://github.com/aws-powertools/powertools-lambda-python/blob/ca0091fbee68995a8c30e4c583d2411e8a72f8c9/examples/typing/src/working_with_context_function.py#L25-L26

This change will ensure accuracy in the highlighted lines for clarity and correctness in the documentation.

### Acknowledgment

- [X] I understand the final update might be different from my proposed suggestion, or refused.

**Comment by rubenfonseca** [comment]
Looking at this now

**Comment by rubenfonseca** [comment]
AMAZING ATTENTION TO DETAIL, thank you @Emerson-MM-Filho !! Would you like to submit a fix yourself? We would love your contribution on Powertools!

**Comment by Emerson-MM-Filho** [comment]
> AMAZING ATTENTION TO DETAIL, thank you @Emerson-MM-Filho !! Would you like to submit a fix yourself? We would love your contribution on Powertools!

Absolutely! I'm thrilled to hear that my attention to detail is appreciated. I'd be more than happy to submit a fix for Powertools. Let me know how I can get started! 🚀

**Comment by rubenfonseca** [comment]
@Emerson-MM-Filho super glad to hear :D Follow the ["Development environment"](https://docs.powertools.aws.dev/lambda/python/latest/contributing/setup/) and ["Your first contribution"](https://docs.powertools.aws.dev/lambda/python/latest/contributing/getting_started/) guide and send us a PR with the fix!

Specifically, in your case, you should edit the `hl_lines` commands that appear on the relevant documentation page. (e.g: [here](https://github.com/aws-powertools/powertools-lambda-python/blob/32e733b4e67784dce67e56668cc54588bfd3565c/docs/utilities/typing.md?plain=1#L31))

You can also verify if the fix looks good by generating the documentation locally with `make docs-local`

We're here to help so if you're stuck reach out here on on [our Discord](https://discord.gg/B8zZKbbyET)!

**Comment by Emerson-MM-Filho** [comment]
Thanks so much for the opportunity, @rubenfonseca! I'm grateful for your encouragement and guidance.

Excited to contribute to Powertools! 🚀

**Comment by leandrodamascena** [comment]
> Excited to contribute to Powertools! 🚀

Amamos contribuções da comunidade, @Emerson-MM-Filho! 🚀 

Thank you for helping us make Powertools for AWS Lambda even better.

**Comment by Emerson-MM-Filho** [comment]
Thank you so much for the warm welcome, @leandrodamascena!

I'm thrilled to be a part of the community and excited to help make Powertools for AWS Lambda even better.
