### ISSUE TITLE
Static typing: case_sensitive should only be bool

### ISSUE THREAD

**Issue by tonnico** [awslabs/aws-lambda-powertools-python#4127]
### Static type checker used

mypy (project's standard)

### AWS Lambda function runtime

3.12

### Powertools for AWS Lambda (Python) version

latest

### Static type checker info

It is possible to use `get_header_value(headers, name, case_sensitive=None)`.

### Code snippet

```python
def get_header_value(
    headers: dict[str, Any],
    name: str,
    default_value: str | None = None,
    case_sensitive: bool | None= False,
) -> str:
```

### Possible Solution

```python
def get_header_value(
    headers: dict[str, Any],
    name: str,
    default_value: str | None = None,
    case_sensitive: bool = False,
) -> str:
```

**Comment by rubenfonseca** [comment]
Thank you for opening this! Will look at it after the weekend
