### ISSUE TITLE
Static typing: resolved_headers_field is not Optional

### ISSUE THREAD

**Issue by tonnico** [awslabs/aws-lambda-powertools-python#4147]
### Static type checker used

pyright/pylance

### AWS Lambda function runtime

3.12

### Powertools for AWS Lambda (Python) version

latest

### Static type checker info

```
Expression of type "Dict[str, Any] | None" cannot be assigned to declared type "dict[str, list[str]]"
  Type "Dict[str, Any] | None" cannot be assigned to type "dict[str, list[str]]"
    "None" is incompatible with "dict[str, list[str]]"
```

### Code snippet

```python
import json
from aws_lambda_powertools.event_handler.router import ALBRouter
router = ALBRouter()
@router.get("/")
def get_headers() -> str:
    headers: dict[str, list[str]] = router.current_event.resolved_headers_field
    return json.dumps(headers)
```
```


### Possible Solution

Remove `Optional` 

```diff
- def resolved_headers_field(self) -> Optional[Dict[str, Any]]:
+ def resolved_headers_field(self) -> Dict[str, Any]:
```

**Comment by rubenfonseca** [comment]
Hi @Wurstnase I'm not sure I follow this one. `resolved_headers_field` is currently marked as returning an Optional, meaning that in some cases it can return None. Shouldn't you handle that in your code instead of changing the API signature?

One could argue that checking the implementation, the field is always present. But due to [Hyrum's Law](https://www.hyrumslaw.com/) I would prefer to add this to our v3 branch (more on that earlier next week).

@leandrodamascena I would appreciate your thoughts here too

**Comment by leandrodamascena** [comment]
Yes! I agree with you @rubenfonseca that we should avoid doing this now and tag this issue/pr as eligible for Powertools V3.

**Comment by rubenfonseca** [comment]
Hope that's ok with you @Wurstnase. I'll add this to our v3 queue. I promise v3 is not far ahead ;)

**Comment by tonnico** [comment]
@rubenfonseca @leandrodamascena 
I can't see how this code ever can become `None`?

```python
def resolved_headers_field(self) -> Optional[Dict[str, Any]]:
        headers: Dict[str, Any] = {}

        if self.multi_value_headers:
            headers = self.multi_value_headers
        else:
            headers = self.headers
        return {key.lower(): value for key, value in headers.items()}
```

As you can see, finally we return a dict at any time. It is impossible to return None.
If something is `None` it will raise an exception.

At least this could become an empty dict, but never None.

**Comment by heitorlessa** [comment]
Nico is correct, `headers` will be an empty dict in the worst case - https://github.com/aws-powertools/powertools-lambda-python/blob/4e32f087b471da9bbcf2c5e8703cc077169d15f7/aws_lambda_powertools/utilities/data_classes/common.py#L101

That said, there's a few other places for its associated PR to be statically correct., Sending fixes today

**Comment by heitorlessa** [comment]
fixes pushed, tests suite ran successfully. Pending PR CI suite

**Comment by heitorlessa** [comment]
Everyone - appreciate the help and cautious in raising the bar for everyone's experience. Merged, ran e2e tests, and pushed additional fixes to complete the PR. 

Bottom line: `headers` are present, when it is not we default to `{}`, so we were overly cautious on `Optional` there.
