### ISSUE TITLE
Feature request: Change the default TTL (cache) to 5 minutes in the Parameters utility

### ISSUE THREAD

**Issue by leandrodamascena** [awslabs/aws-lambda-powertools-python#4193]
### Use case

When using the Parameters utility, customers can leverage caching to minimize API calls. The default cache TTL is 5 seconds, after which Powertools expires the cache and if the parameter value is required inside the Lambda handler, a new API call may be triggered.

We suggest increasing this value to 300 seconds (5 minutes) to avoid spikes in a highly intensive workload.

### Solution/User Experience

Increase the default TTL value to 300 seconds (5 minutes).

### Acknowledgment

- [X] This feature request meets [Powertools for AWS Lambda (Python) Tenets](https://docs.powertools.aws.dev/lambda/python/latest/#tenets)
- [X] Should this be considered in other Powertools for AWS Lambda languages? i.e. [Java](https://github.com/aws-powertools/powertools-lambda-java/), [TypeScript](https://github.com/aws-powertools/powertools-lambda-typescript/), and [.NET](https://github.com/aws-powertools/powertools-lambda-dotnet/)

**Comment by heitorlessa** [comment]
Small note that the reason we're choosing **5 minutes** is to sync with customers feedback who used [SSM extension](https://docs.aws.amazon.com/systems-manager/latest/userguide/ps-integration-lambda-extensions.html#ps-integration-lambda-extensions-config)
