### ISSUE TITLE
Maintenance: Ensure Bedrock Agents resolver works with Pydantic v2

### ISSUE THREAD

**Issue by rubenfonseca** [awslabs/aws-lambda-powertools-python#4196]
### Why is this needed?

As we prepare to drop Pydantic v2, we need to ensure that the Bedrock Agents functionality still works. Bedrock Agents only accepts OpenAPI version 3.0, whereas Pydantic v2 generates schemas that are valid for OpenAPI 3.1.

### Which area does this relate to?

Event Handler - REST API

### Solution

Research shows that we can take an OpenAPI 3.1 schema and make it compatible with Bedrock Agents by doing some simple changes, like removing new fields and changing the schema version.

After implementing those we need to do extensive testing to ensure the feature is not broken when using Agents.

### Acknowledgment

- [X] This request meets [Powertools for AWS Lambda (Python) Tenets](https://docs.powertools.aws.dev/lambda/python/latest/#tenets)
- [ ] Should this be considered in other Powertools for AWS Lambda languages? i.e. [Java](https://github.com/aws-powertools/powertools-lambda-java/), [TypeScript](https://github.com/aws-powertools/powertools-lambda-typescript/), and [.NET](https://github.com/aws-powertools/powertools-lambda-dotnet/)

**Comment by leandrodamascena** [comment]
Closing as completed.
