### ISSUE TITLE
Feature request: Remove the flag log_uncaught_exceptions in the Logger utility

### ISSUE THREAD

**Issue by leandrodamascena** [awslabs/aws-lambda-powertools-python#4199]
### Use case

The flag `log_uncaught_exceptions` doesn't work in the Lambda Runtime, so we need to remove it.

### Solution/User Experience

Remove the `log_uncaught_exceptions` flag.

### Acknowledgment

- [X] This feature request meets [Powertools for AWS Lambda (Python) Tenets](https://docs.powertools.aws.dev/lambda/python/latest/#tenets)
- [X] Should this be considered in other Powertools for AWS Lambda languages? i.e. [Java](https://github.com/aws-powertools/powertools-lambda-java/), [TypeScript](https://github.com/aws-powertools/powertools-lambda-typescript/), and [.NET](https://github.com/aws-powertools/powertools-lambda-dotnet/)

**Comment by rubenfonseca** [comment]
Added v3 tags

**Comment by heitorlessa** [comment]
we're not gonna need it anymore. Closing; see comment: https://github.com/aws-powertools/powertools-lambda-python/issues/1798#issuecomment-2147866913
