### ISSUE TITLE
Maintenance: remove unused rules from markdownlint

### ISSUE THREAD

**Issue by dreamorosi** [awslabs/aws-lambda-powertools-python#4208]
### Why is this needed?

While adding markdownlint to the TypeScript repo, @am29d pointed out that two of the settings used in the config are invalid.

Specifically, the [`headers` one under MD013](https://github.com/aws-powertools/powertools-lambda-python/blob/757db0e88c6efd42716523817099224c36acaecd/.markdownlint.yaml#L77) and the [`allow_different_nesting` one under MD024](https://github.com/aws-powertools/powertools-lambda-python/blob/develop/.markdownlint.yaml#L111).

Neither of these two appear in the [tool rules docs](https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md) which indicates that they might have been removed or they were incorrect in the first place.

### Solution

Remove the two settings from the config file.

I am available to open a PR if welcome.

### Acknowledgment

- [X] This request meets [Powertools for AWS Lambda (Python) Tenets](https://docs.powertools.aws.dev/lambda/python/latest/#tenets)
- [ ] Should this be considered in other Powertools for AWS Lambda languages? i.e. [Java](https://github.com/aws-powertools/powertools-lambda-java/), [TypeScript](https://github.com/aws-powertools/powertools-lambda-typescript/), and [.NET](https://github.com/aws-powertools/powertools-lambda-dotnet/)

**Comment by leandrodamascena** [comment]
Thanks for opening this @dreamorosi!

`allow_different_nesting` - Removed in this issue https://github.com/DavidAnson/markdownlint/issues/1121 
`headers` - Couldn't find any reference.

I'll remove both in the next week, thanks

**Comment by leandrodamascena** [comment]
Hey @dreamorosi! We fixed these problems in this PR - https://github.com/aws-powertools/powertools-lambda-python/pull/4295/files#diff-39aecbc26791dd03b9a4fdc1f856769ea73308294b7111d70f279ac9bdef35bd

Closing this issue.
