### ISSUE TITLE
Tech debt: Review the name of the method extract_data_from_envelope in JMESPath Functions

### ISSUE THREAD

**Issue by leandrodamascena** [awslabs/aws-lambda-powertools-python#4218]
### Why is this needed?

The `extract_data_from_envelope` method name seems strange for customers to understand what it is for. We now have the opportunity to deprecate this method, add a warning, and create a new one.

### Which area does this relate to?

JMESPath functions

### Suggestion

Deprectaed this method.

### Acknowledgment

- [X] This request meets [Powertools for AWS Lambda (Python) Tenets](https://docs.powertools.aws.dev/lambda/python/latest/#tenets)
- [ ] Should this be considered in other Powertools for AWS Lambda languages? i.e. [Java](https://github.com/aws-powertools/powertools-lambda-java/), [TypeScript](https://github.com/aws-powertools/powertools-lambda-typescript/), and [.NET](https://github.com/aws-powertools/powertools-lambda-dotnet/)

**Comment by dreamorosi** [comment]
We just added this method in the TypeScript repo a few weeks ago.

Do we have any anecdotes for deprecating this and how we can improve?

I'm not necessarily challenging the idea, I'm more interested in how we can disambiguate it and make it clearer.

**Comment by leandrodamascena** [comment]
Hello @dreamorosi! I don't have enough anecdotes about this. @heitorlessa may have more context about the reasons behind this change and any customer feedback received.
Regardless, we do not plan to remove this method entirely. Instead, we will add a deprecation warning and remove it in the V4 release. As for the new method name, we believe `query` would be a good name, as it better conveys the idea of retrieving data, and the `query` name is more commonly used across similar concepts of data querying.

**Comment by leandrodamascena** [comment]
Closed via #4907
