### ISSUE TITLE
multi threaded xray support

### ISSUE THREAD

**Issue by ItayGoren** [awslabs/aws-lambda-powertools-python#429]
**Is your feature request related to a problem? Please describe.**
Looking at xray documentation, to work with multi-threads i need to do the following:
1. pass xray_recorder.get_trace_entity() to each thread as parameter
2. call xray_recorder.set_trace_entity(trace_entity) at the start of each thread
3. call xray_recorder.clear_trace_entities() at the end at the end of each thread
There is no such option to do with powertools.

**Describe the solution you'd like**
Any solution to work with powertools and xray with multiple threads

**Describe alternatives you've considered**
Other products have such support.

**Comment by heitorlessa** [comment]
Hey @ItayGoren - thanks for raising this.

This is supported through our escape hatch mechanism:

https://awslabs.github.io/aws-lambda-powertools-python/1.15.0/core/tracer/#escape-hatch-mechanism

We essentially expose xray_recorded via the "provider" property.

Happy to add a more specific example in the docs for threading later this week

**Comment by heitorlessa** [comment]
Hey Itay - could you share if that worked for you?

**Comment by tibbe** [comment]
I was converting from the raw SDK to this package today and also wondered how it would work with multi-threading. Did you end up adding an example to the docs? I couldn't find it.
