### ISSUE TITLE
v1.15.0 does not support string formatting "%s" anymore

### ISSUE THREAD

**Issue by MicheledG** [awslabs/aws-lambda-powertools-python#431]
Hi all,

our team has recently noticed that logs produced by lambda functions using this `aws_lambda_powertools.Logger` report the operator "%s" instead of the actual value of the variable/string provided as a parameter to the logger function (such as `debug|info|etc...`).

Since the issue suddenly showed up after 2021-05-07, we have the doubt the library update (v1.15.0) introduced the problem.

In order to verify this assumption, we have executed few lines of code locally with 2 different versions of `aws_lambda_powertools`.

With version 1.14.0, everything worked as expected instead, with 1.15.0, the problem has been reproduced.

## Previous Behavior

In [1]: from aws_lambda_powertools import Logger
In [2]: logger = Logger()
In [3]: logger.info("test %s", "hello")

{"level": "INFO", "location": "<module>:1", **"message": "test hello"**, "timestamp": "2021-05-13 12:13:48,727", "service": "service_undefined", "sampling_rate": 0.0}

**Powertools version used**: 1.14.0

## Current Behavior

In [1]: from aws_lambda_powertools import Logger
In [2]: logger = Logger()
In [3]: logger.info("test %s", "hello")

{"level":"INFO","location":"<module>:1",**"message":"test %s"**,"timestamp":"2021-05-13 12:48:43,830+0200","service":"service_undefined"}

**Powertools version used**: 1.15.0

## Environment

* macOS Big Sure: 11.2.3
* python: 3.8.6
* ipython: 7.19.0

**Comment by heitorlessa** [comment]
Hi @MicheledG - we've merged the fix in develop, and will be releasing a patch either today or tomorrow the latest.

Thanks for reporting it

**Comment by heitorlessa** [comment]
@MicheledG 1.15.1 is now out with the fix -- could you please triple check that this works now?

**Comment by MicheledG** [comment]
I confirm that now the string formatting is correctly executed, thank you very much for the quick support!
