### ISSUE TITLE
Persist authorization data across browser close/refresh for OpenAPI Swagger UI

### ISSUE THREAD

**Issue by nlykkei** [awslabs/aws-lambda-powertools-python#4314]
### Use case

Currently, each time the user refreshes the Swagger UI or closes the browser, the authorization data, e.g. OAuth 2.0 tokens, is lost, which forces the user to re-authenticate to call APIs.

While one may argue that transient authorization data is more secure, it's not a great user experience. Many web applications persist short-lived tokens.

The `persistAuthorization` option to Swagger UI persists the authorization data in local storage, so it remains across browser close/refresh:

https://swagger.io/docs/open-source-tools/swagger-ui/usage/configuration/#:~:text=persistAuthorization 

### Solution/User Experience

Provide an extra argument `persist_authorization` to `enable_swagger()`

### Acknowledgment

- [X] This feature request meets [Powertools for AWS Lambda (Python) Tenets](https://docs.powertools.aws.dev/lambda/python/latest/#tenets)
- [X] Should this be considered in other Powertools for AWS Lambda languages? i.e. [Java](https://github.com/aws-powertools/powertools-lambda-java/), [TypeScript](https://github.com/aws-powertools/powertools-lambda-typescript/), and [.NET](https://github.com/aws-powertools/powertools-lambda-dotnet/)

**Comment by leandrodamascena** [comment]
Thanks for opening this! Working to merge the PR
