### ISSUE TITLE
Feature request: Add CloudFormation CustomResource events to EventSource dataclasses

### ISSUE THREAD

**Issue by phipag** [awslabs/aws-lambda-powertools-python#4332]
### Use case

I am building a Lambda handler for managing CDK CustomResources (https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.custom_resources-readme.html).

### Solution/User Experience

As a user of AWS Lambda Powertools I would like to have dataclass parsing and type-safety for all standard Lambda events coming from an AWS service. CloudFormation custom resources are missing.

### Acknowledgment

- [X] This feature request meets [Powertools for AWS Lambda (Python) Tenets](https://docs.powertools.aws.dev/lambda/python/latest/#tenets)
- [X] Should this be considered in other Powertools for AWS Lambda languages? i.e. [Java](https://github.com/aws-powertools/powertools-lambda-java/), [TypeScript](https://github.com/aws-powertools/powertools-lambda-typescript/), and [.NET](https://github.com/aws-powertools/powertools-lambda-dotnet/)

**Comment by leandrodamascena** [comment]
Hello @phipag! Thank you for opening this issue. We already support this in [Parser](https://docs.powertools.aws.dev/lambda/python/latest/utilities/parser/#built-in-models) and we really need to add support for this in our EventSource data class. Would you like to submit a PR to implement this? We can work together to merge it and include it in the release - scheduled for 17/05.

**Comment by phipag** [comment]
Hi @leandrodamascena, yes, I'm happy to contribute this feature. What are the next steps here?

**Comment by leandrodamascena** [comment]
Hello @phipag! That's amazing to hear! Check out the steps below and let me know if you need additional help.

We use Poetry as the package manager and we have a `Makefile` to make things easier. So basically you need to fork the repository, create a new branch from your fork and type `make dev` to create your development environment. After that, you can do the following steps:

1 - You need to create a new file called `cloudformation_custom_resource_event.py` - Use this class as an example: [develop/aws_lambda_powertools/utilities/data_classes/vpc_lattice.py](https://github.com/aws-powertools/powertools-lambda-python/blob/develop/aws_lambda_powertools/utilities/data_classes/vpc_lattice.py?rgh-link-date=2023-07-29T22%3A13%3A39Z)

2 - You need to export this new class here - [develop/aws_lambda_powertools/utilities/data_classes/__init__.py](https://github.com/aws-powertools/powertools-lambda-python/blob/develop/aws_lambda_powertools/utilities/data_classes/__init__.py?rgh-link-date=2023-07-29T22%3A13%3A39Z)

3 - You need to create a file with a fake payload here - [develop/tests/events](https://github.com/aws-powertools/powertools-lambda-python/tree/develop/tests/events?rgh-link-date=2023-07-29T22%3A13%3A39Z)

4 - You need to write a new test for this new class - Use this test as an example - [develop/tests/unit/data_classes/test_vpc_lattice_event.py](https://github.com/aws-powertools/powertools-lambda-python/blob/develop/tests/unit/data_classes/test_vpc_lattice_event.py?rgh-link-date=2023-07-29T22%3A13%3A39Z)

5 - You need to add this new class to the documentation - [develop/docs/utilities/data_classes.md](https://github.com/aws-powertools/powertools-lambda-python/blob/develop/docs/utilities/data_classes.md?rgh-link-date=2023-07-29T22%3A13%3A39Z)

6 - Run the tests by typing `make test` and after that use `make pr` to make sure that everything is right.

7 - If everything is right, just open the PullRequest and have a cold drink 🍹

**Comment by phipag** [comment]
Cool. Thanks for detailed steps. That all makes sense to me. I'll reach out if something comes up on the way.

**Comment by phipag** [comment]
@leandrodamascena I submitted above PR for this.
