### ISSUE TITLE
Bug: jmespath is an undeclared dependency of Logger utility

### ISSUE THREAD

**Issue by TonySherman** [awslabs/aws-lambda-powertools-python#4340]
### Expected Behaviour

Powertools includes dependencies unless the feature states that it needs extras.

### Current Behaviour

The `Logger` utility will not work without `jmespath`. Importing the logger causes the following error:
`ModuleNotFoundError: No module named 'jmespath'`

### Code snippet

```python
from aws_lambda_powertools.logging import Logger

logger = Logger()

logger.info('test')
```

### Possible Solution

This issue is unlikely to cause problems in _most_ cases. There are very few use cases where this code would be run somewhere that does not have `jmespath` available via boto/botocore.

It could be noted in the docs in the extra dependencies section.
<img width="1288" alt="image" src="https://github.com/aws-powertools/powertools-lambda-python/assets/100969281/207a9875-3ca0-46c7-b643-8c6d521023a1">

### Steps to Reproduce

- Create a new virtual environment:
`python -m venv .venv`
- Activate environment
`source .venv/bin/activate`
- Install Powertools with no extras
` pip install aws-lambda-powertools`
- Run example code snippet.

### Powertools for AWS Lambda (Python) version

latest

### AWS Lambda function runtime

3.11

### Packaging format used

PyPi

**Comment by heitorlessa** [comment]
Thanks a lot for opening the issue as discussed on discord ;) 

We'll add it for the next release
