### ISSUE TITLE
Docs: Change installation from CDK v1 to CDK v2

### ISSUE THREAD

**Issue by keithrozario** [awslabs/aws-lambda-powertools-python#4353]
### What were you searching in the docs?

The installation steps for Powertools using CDK. 

### Is this related to an existing documentation section?

https://docs.powertools.aws.dev/lambda/python/latest/#cdk

### How can we improve?

Changing the example to support CDK v2 instead. The current steps here will fail on CDK v2.

### Got a suggestion in mind?

Change import statements and initializers to CDK v2 formats. :)

https://github.com/aws-powertools/powertools-lambda-python/pull/4351

### Acknowledgment

- [X] I understand the final update might be different from my proposed suggestion, or refused.

**Comment by leandrodamascena** [comment]
Thanks for opening this issue @keithrozario!
