### ISSUE TITLE
Security issue in Pydanic

### ISSUE THREAD

**Issue by risenberg-cyberark** [awslabs/aws-lambda-powertools-python#436]
Upgrade Pydantic to 1.8.2 to resolve the security issue. 
See
https://pydantic-docs.helpmanual.io/changelog/
and 
https://github.com/samuelcolvin/pydantic/security/advisories/GHSA-5jqp-qgf6-3pvh

**Comment by heitorlessa** [comment]
Released as part of 1.16.1
