### ISSUE TITLE
[Support Lambda Powertools]: Recast

### ISSUE THREAD

**Issue by russellpierce** [awslabs/aws-lambda-powertools-python#4477]
### Organization Name

Recast

### Your Name

Russell Pierce

### Your current position

VP of Engineering

### Also using other Powertools for AWS Lambda languages?

- [ ] Java
- [ ] TypeScript
- [ ] .NET

**Comment by leandrodamascena** [comment]
Hi @russellpierce! This is absolutely amazing! I'll send a pull request to add Recast as a public reference. Just confirming that the link is https://getrecast.com/, right?

We always love to hear about how customers are using Powertools for AWS Lambda and the ideas they have, the challenges they're facing, and how we can make it even better. We're completely open to scheduling a meeting and hearing from you about any needs or requirements you may have. If you'd like, please send an email to `aws-powertools-maintainers at amazon.com`, and we can arrange a meeting to discuss further.

We're eager to learn about your use cases and happy to assist you in any way we can.

Thanks

**Comment by leandrodamascena** [comment]
Closed via #4491
