### ISSUE TITLE
Support JSON Schema referencing in validation utils (by using fastjsonschema's handlers param)

### ISSUE THREAD

**Issue by danieljnchen** [awslabs/aws-lambda-powertools-python#4499]
### Use case

`fastjsonschema`, which is used internally by [aws-lambda-powertools' validation utilities](https://github.com/aws-powertools/powertools-lambda-python/blob/develop/aws_lambda_powertools/utilities/validation/base.py#L32), supports [JSON Schema's schema referencing](https://json-schema.org/understanding-json-schema/structuring#dollarref), but it by default launches an http request to the url provided. However, in the case that users don't want to launch an http request to fetch the referenced schemas (for example, because the references are stored locally), `fastjsonschema` also provides the `handlers` parameter to its validation methods ([docs](https://horejsek.github.io/python-fastjsonschema/#fastjsonschema.compile))

> You can pass mapping from URI to function that should be used to retrieve remote schemes used in your definition in parameter handlers.

### Solution/User Experience

Update aws-lambda-powertools' validation functions to support passing the `handlers` param to fastjsonschema's `validate` call. As far as I can tell, this would require adding the param to [validate_data_against_schema](https://github.com/aws-powertools/powertools-lambda-python/blob/develop/aws_lambda_powertools/utilities/validation/base.py#L32) and to the user-facing methods/decorators [validate and validator](https://github.com/aws-powertools/powertools-lambda-python/blob/develop/aws_lambda_powertools/utilities/validation/validator.py)

### Acknowledgment

- [X] This feature request meets [Powertools for AWS Lambda (Python) Tenets](https://docs.powertools.aws.dev/lambda/python/latest/#tenets)
- [ ] Should this be considered in other Powertools for AWS Lambda languages? i.e. [Java](https://github.com/aws-powertools/powertools-lambda-java/), [TypeScript](https://github.com/aws-powertools/powertools-lambda-typescript/), and [.NET](https://github.com/aws-powertools/powertools-lambda-dotnet/)

**Comment by heitorlessa** [comment]
hey @danieljnchen, thanks for taking the time to cut a feature request and the investigation -- it makes total sense we support it. 

Would you be interested in creating a PR? we can guide it. We're currently focused on fixing a release pipeline issue and V3, which means we have no ETA when this would be looked at right now.

Edit: it'd be great to have an escape hatch where customers could provide additional keyword arguments so they're not blocked in the futur

**Comment by danieljnchen** [comment]
@heitorlessa Thanks for the quick response! I'd be happy to make a PR -- I'll look through the contributing docs and hopefully have something up shortly

**Comment by danieljnchen** [comment]
@heitorlessa I've posted a draft PR: https://github.com/aws-powertools/powertools-lambda-python/pull/4508

I had some difficulty getting the dev environment setup -- I used gitpod as directed in the Contributing guidelines, but `make dev-gitpod` failed, and I encountered a lot of missing dependencies when trying to run unit tests. What should I do to move this PR along?

**Comment by leandrodamascena** [comment]
> @heitorlessa I've posted a draft PR: #4508
> 
> I had some difficulty getting the dev environment setup -- I used gitpod as directed in the Contributing guidelines, but `make dev-gitpod` failed, and I encountered a lot of missing dependencies when trying to run unit tests. What should I do to move this PR along?

Hi @danieljnchen, I'm seeing this comment now. Did you manage to resolve the problem with the environment?

**Comment by danieljnchen** [comment]
> > @heitorlessa I've posted a draft PR: #4508
> > I had some difficulty getting the dev environment setup -- I used gitpod as directed in the Contributing guidelines, but `make dev-gitpod` failed, and I encountered a lot of missing dependencies when trying to run unit tests. What should I do to move this PR along?
> 
> Hi @danieljnchen, I'm seeing this comment now. Did you manage to resolve the problem with the environment?

Thanks for checking in! Unfortunately not; here's the error I'm getting when I run `make-devgitpod`:
![image](https://github.com/aws-powertools/powertools-lambda-python/assets/10577526/d85f9d43-736a-4ecb-b88e-1801c70ecca8)
![image](https://github.com/aws-powertools/powertools-lambda-python/assets/10577526/47f85108-f6a7-4b25-b406-cfc75ea62075)

**Comment by leandrodamascena** [comment]
Hello @danieljnchen! Yes, I was able to reproduce this error and opened an issue to fix this. I'm working on it now and hope to finish it early next week.

https://github.com/aws-powertools/powertools-lambda-python/issues/4530
