### ISSUE TITLE
Maintenance: introduce nox to test optional dependencies

### ISSUE THREAD

**Issue by heitorlessa** [awslabs/aws-lambda-powertools-python#4501]
### Why is this needed?

Today's release suffered a regression due to static typing accidentally requiring an optional dependency for customers.

We must not make any release until we have a safeguard to prevent this in the future.

https://github.com/aws-powertools/powertools-lambda-python/issues/4498

### Update with task list - 14/06

- [x] #4519
- [x] #4520
- [x] #4521
- [x] #4522
- [x] #4523
- [x] #4553
- [x] #4562
- [x] #4554
- [x] #4555
- [x] #4561
- [x] #4556
- [x] #4560
- [x] #4557
- [x] #4558
- [x] #4559
- [x] #4573

### Solution

Use nox, or create new workflows where we test bare dependencies, and every optional dependencies.

### Acknowledgment

- [X] This request meets [Powertools for AWS Lambda (Python) Tenets](https://docs.powertools.aws.dev/lambda/python/latest/#tenets)
- [ ] Should this be considered in other Powertools for AWS Lambda languages? i.e. [Java](https://github.com/aws-powertools/powertools-lambda-java/), [TypeScript](https://github.com/aws-powertools/powertools-lambda-typescript/), and [.NET](https://github.com/aws-powertools/powertools-lambda-dotnet/)

**Comment by leandrodamascena** [comment]
Assigning to me.

**Comment by leandrodamascena** [comment]
Introducing nox requires a lot of changes to our tests and can easily become a PR with hundreds of lines of changes. So I'll break this down into small PRs to make reviewing easier.
