### ISSUE TITLE
Bug: KafkaEventRecord Incorrect types for offset and partition properties

### ISSUE THREAD

**Issue by scampbell5** [awslabs/aws-lambda-powertools-python#4504]
### Expected Behaviour

The properties for `offset` and `partition` are the correct `int` type on the `KafkaEventRecord` class.

### Current Behaviour

The properties for `offset` and `partition` on the `KafkaEventRecord` are currently defined as `str` type.

### Code snippet

```python
class KafkaEventRecord(DictWrapper):
    @property
    def topic(self) -> str:
        """The Kafka topic."""
        return self["topic"]

    @property
    def partition(self) -> str:
        """The Kafka record parition."""
        return self["partition"]

    @property
    def offset(self) -> str:
        """The Kafka record offset."""
        return self["offset"]
```

https://github.com/aws-powertools/powertools-lambda-python/blob/develop/aws_lambda_powertools/utilities/data_classes/kafka_event.py#L18

### Possible Solution

Change the type to `int` for the `partition` and `offset` properties on the `KafkaEventRecord` class.

### Steps to Reproduce

```
from aws_lambda_powertools.utilities.data_classes import event_source, KafkaEvent

@event_source(data_class=KafkaEvent)
def lambda_handler(event: KafkaEvent, context):
    assert isinstance(event.record.offset, int)
    assert isinstance(event.record.partition, int)
```

### Powertools for AWS Lambda (Python) version

latest

### AWS Lambda function runtime

3.11

### Packaging format used

Lambda Layers

**Comment by leandrodamascena** [comment]
Hi @scampbell5! Thanks for pointing out this bug. Actually, you're 100% right, these fields should be `int` instead of `str`. Do you want to submit a PR to fix this? We can work together to merge it.

References:
https://docs.aws.amazon.com/lambda/latest/dg/with-kafka.html
https://github.com/aws/aws-lambda-go/blob/main/events/kafka.go

**Comment by scampbell5** [comment]
@leandrodamascena Appreciate the quick response! I'll work on putting together a PR later tonight to fix this.

**Comment by leandrodamascena** [comment]
Perfect, let me know if you have any questions or blocks, and we can work together on this!

We truly appreciate when the community contributes to the project. 🚀

**Comment by scampbell5** [comment]
@leandrodamascena I've submitted this PR if you don't mind taking a look when you have time: https://github.com/aws-powertools/powertools-lambda-python/pull/4515
