### ISSUE TITLE
Maintenance: Create a development release versions in pypi

### ISSUE THREAD

**Issue by leandrodamascena** [awslabs/aws-lambda-powertools-python#4506]
### Why is this needed?

Development releases allow customers to preview upcoming changes in advance. Although these releases should not be used in production, this allows customers to test bug fixes, new features, and other changes in advance.

To add this new package in Pypi, we must follow the Python packaging guide defined here for Development releases: https://packaging.python.org/en/latest/specifications/version-specifiers/#public-version-identifiers

### Which area does this relate to?

Automation

### Acknowledgment

- [X] This request meets [Powertools for AWS Lambda (Python) Tenets](https://docs.powertools.aws.dev/lambda/python/latest/#tenets)
- [ ] Should this be considered in other Powertools for AWS Lambda languages? i.e. [Java](https://github.com/aws-powertools/powertools-lambda-java/), [TypeScript](https://github.com/aws-powertools/powertools-lambda-typescript/), and [.NET](https://github.com/aws-powertools/powertools-lambda-dotnet/)

**Comment by heitorlessa** [comment]
yup, this would be technically a [**pre-release**](https://packaging.python.org/en/latest/specifications/version-specifiers/#pre-release-spelling) in PyPi. 

What I love about this is that customers would have to intentionally want to install a pre-release version, allowing bugfixes to land quicker for those who can't wait w/o impacting stability for the majority of customers.

**Comment by leandrodamascena** [comment]
Assinging to @heitorlessa! 
BTW, I prefer to use the `.alpha` name as suffix.

**Comment by heitorlessa** [comment]
@leandrodamascena how much of a deal breaker it is if we can't have `.alpha` suffix? I asked poetry a question as they hard code `a` suffix: https://github.com/orgs/python-poetry/discussions/9496

If it is, I might need an extra day to think of a non-fragile way of letting Poetry resolve a newer pre-release version, parse it, then replace `pyproject.toml` and `shared/version.py` with the `.alpha` suffix.

Listing out requirements in the meantime shortly

**Comment by leandrodamascena** [comment]
Let's keep the standard and not complicate things, Heitor. 
If they follow the specification, we will also follow and use `a`. 🚀

**Comment by heitorlessa** [comment]
Perfect, figured as much.. tks for confirming! 

---

List of requirements - lemme know if I missed anything. 

* [x] Confirm whether `.alpha` over poetry default `.a` is a deal breaker _(nope)_
* [ ] Release **every weekday** early morning _(on-call coverage, no impact to release day)_
* [ ] Do not touch `CHANGELOG` _(avoid spam, doesn't affect stable release on what's in it)_
* [ ] **PyPi only**; do not release a new Lambda Layer _(no alias yet, it'd impact versioning)_
* [ ] Create PR to update `pyproject.toml` and `shared/version.py` _(ensure deterministic for next release)_
* [ ] Ensure it doesn't create a new release notes _(avoid spam, provenance signing etc)_
* [ ] Always autoincrement pre-release version _(keep it simple over substantial checking for changes, dep/runtime devs etc)_ 
* [ ] Run full quality check and test suite
* [ ] Do not release docs for each pre-release _(`develop` covers it, avoid dropdown UX issue)_
* [ ] Allow manual trigger a.k.a `dispatch`
* [ ] Release to PyPi prod, not PyPi test _(test pypi maintenance and supply chain differences)_
* [ ] Do not touch `pending-release` issues _(no post-release prod tasks)_

---

Separate PR

* [ ] Update docs to tell customers about unstable/prereleases
