### ISSUE TITLE
[Support Powertools for AWS Lambda (Python)]: Brsk

### ISSUE THREAD

**Issue by ChrisHills463** [awslabs/aws-lambda-powertools-python#4591]
### Organization Name

Brsk

### Your Name

Chris Hills

### Your current position

Platform Engineer

### (Optional) Company logo

https://cdn.brsk.co.uk/branding/brsk-fullfibre-no-slogan-blue.svg

### Also using other Powertools for AWS Lambda languages?

- [ ] Java
- [ ] TypeScript
- [ ] .NET

**Comment by ChrisHills463** [comment]
The URL for our company is https://www.brsk.co.uk

**Comment by leandrodamascena** [comment]
Hey @ChrisHills463! This is fantastic, thanks a lot for supporting us!
