### ISSUE TITLE
Add method to DynamoDB Stream Event AttribubuteValue to return the proper type for that AttribubuteValue

### ISSUE THREAD

**Issue by gwlester** [awslabs/aws-lambda-powertools-python#461]
**Is your feature request related to a problem? Please describe.**

When attempting to transverse a **DynamoDB Stream Event**, it would be nice to know the datatype of an **AttributeValue** so the correct call to get the value could be made.  I.E. string vs list vs map.

**Describe the solution you'd like**

Add an **AtributeValue** method that would return the type of value for that attribute.  It would be also nice to have enumerated labels for the types.

**Describe alternatives you've considered**

We always get all three and test the class.

**Additional context**

**Comment by michaelbrewer** [comment]
@gwlester I have a PR for this https://github.com/awslabs/aws-lambda-powertools-python/pull/462.

Can you check if this is what you want.

**Comment by gwlester** [comment]
Since the PR got merged -- should this issue be closed now?

Just asking,

**Comment by michaelbrewer** [comment]
@gwlester kind of, us to you ;-). Once it is deployed, maybe you can help validate that it works for you.

**Comment by gwlester** [comment]
@michaelbrewer -- let me know when 1.17.0 is available to deploy!  Thanks again!!!

**Comment by heitorlessa** [comment]
hey @gwlester this is now available! Added an example in the release notes as well as the docs: https://github.com/awslabs/aws-lambda-powertools-python/releases/tag/v1.17.0

Closing this now as it's already available in PyPi too :) 

Thanks a lot @michaelbrewer for the implementation
