### ISSUE TITLE
Roadmap update reminder weekly - Python

### ISSUE THREAD

**Issue by dreamorosi** [awslabs/aws-lambda-powertools-python#4611]
Quick report of top 3 issues/PRs to assist in roadmap updates. Issues or PRs with the following labels are excluded:

* do-not-merge
* need-issue
* need-rfc
* need-customer-feedback

> **NOTE**: It does not guarantee they will be in the roadmap. Some might already be and there might be a blocker.

## Untriaged Issues

| title       | created_at  | last_update | labels      |
| ----------- | ----------- | ----------- | ----------- |
| [Maintenance: Review pipeline to update the aws-actions/configure-aws-credentials action](https://github.com/aws-powertools/powertools-lambda-python/issues/3025) | August 29, 2023 | 14 days     | `triage`<br>`internal` |
| [Static typing: APIGatewayRestResolver `.post()` decorator return type Unknown](https://github.com/aws-powertools/powertools-lambda-python/issues/3990) | March 20, 2024 | 14 days     | `help wanted`<br>`triage`<br>`typing` |
| [REST API: Provide a way to add extra JSON to generated OpenAPI schema endpoints](https://github.com/aws-powertools/powertools-lambda-python/issues/4035) | March 28, 2024 | 0 days      | `help wanted`<br>`triage`<br>`feature-request`<br>`openapi-schema` |

## Top Bug Issues

| title       | created_at  | last_update | labels      |
| ----------- | ----------- | ----------- | ----------- |
| [Bug: logger_handler argument is ignored if logging.getLogger() already has a handler.](https://github.com/aws-powertools/powertools-lambda-python/issues/4277) | May 5, 2024 | 37 days     | `bug`<br>`logger` |
| [Cannot use models generated by `datamodel-codegen` from OpenAPI 3.0 spec with property-level `example:`s](https://github.com/aws-powertools/powertools-lambda-python/issues/4476) | June 10, 2024 | 6 days      | `bug`<br>`event_handlers`<br>`openapi-schema` |
| [Bug: Event handler + cors + headers](https://github.com/aws-powertools/powertools-lambda-python/issues/4589) | June 20, 2024 | 0 days      | `bug`       |

## Top Long Running Pull Requests

Pull Requests updated in the last 7 days are excluded.

| title       | created_at  | last_update | reviewers   | labels      |
| ----------- | ----------- | ----------- | ----------- | ----------- |
| [feat(tracer): Support for external observability providers - Tracer](https://github.com/aws-powertools/powertools-lambda-python/pull/2342) | May 30, 2023 | 67 days     |             | `dependencies`<br>`feature`<br>`size/L`<br>`tests`<br>`tracer` |
| [feat(nested-event-sources): Generic unwrapping of event source data](https://github.com/aws-powertools/powertools-lambda-python/pull/4069) | April 4, 2024 | 18 days     |             | `feature`<br>`size/XL`<br>`tests` |
| [refactor(event_source): fix type hint](https://github.com/aws-powertools/powertools-lambda-python/pull/4165) | April 19, 2024 | 48 days     |             | `size/M`<br>`enhancement`<br>`middleware_factory` |

## Items pending release

| title       | created_at  | last_update | labels      |
| ----------- | ----------- | ----------- | ----------- |
| [Maintenance: Create a development release versions in pypi](https://github.com/aws-powertools/powertools-lambda-python/issues/4506) | June 13, 2024 | 3 days      | `pending-release`<br>`internal` |
| [[I Made This]: Best practices for accelerating development with serverless blueprints](https://github.com/aws-powertools/powertools-lambda-python/issues/4517) | June 14, 2024 | 7 days      | `pending-release`<br>`community-content` |
| [Maintenance: Install and configure nox](https://github.com/aws-powertools/powertools-lambda-python/issues/4519) | June 14, 2024 | 5 days      | `pending-release`<br>`internal`<br>`tests` |
| [Maintenance: add the Metrics feature to nox tests](https://github.com/aws-powertools/powertools-lambda-python/issues/4521) | June 14, 2024 | 4 days      | `pending-release`<br>`internal`<br>`tests` |
| [Maintenance: add the Tracer feature to nox tests](https://github.com/aws-powertools/powertools-lambda-python/issues/4522) | June 14, 2024 | 4 days      | `pending-release`<br>`internal`<br>`tests` |
| [Maintenance: add the Event Handler feature to nox tests](https://github.com/aws-powertools/powertools-lambda-python/issues/4523) | June 14, 2024 | 4 days      | `pending-release`<br>`internal`<br>`tests` |
| [Maintenance: Fix error when creating a developer environment in Gitpod](https://github.com/aws-powertools/powertools-lambda-python/issues/4530) | June 14, 2024 | 0 days      | `pending-release`<br>`internal` |
| [Maintenance: add the Parameters feature to nox tests](https://github.com/aws-powertools/powertools-lambda-python/issues/4553) | June 18, 2024 | 4 days      | `pending-release`<br>`internal`<br>`tests` |
| [Maintenance: add the Typing feature to nox tests](https://github.com/aws-powertools/powertools-lambda-python/issues/4554) | June 18, 2024 | 4 days      | `pending-release`<br>`internal`<br>`tests` |
| [Maintenance: add the Validation feature to nox tests](https://github.com/aws-powertools/powertools-lambda-python/issues/4555) | June 18, 2024 | 4 days      | `pending-release`<br>`internal`<br>`tests` |

## Prioritary Milestone Issues

| title       | last_update | labels      | assignee    |
| ----------- | ----------- | ----------- | ----------- |
| [Publish layer to Gov Cloud regions](https://github.com/aws-powertools/powertools-lambda-python/issues/1166) | 3 days      | `feature-request`<br>`need-customer-feedback`<br>`internal`<br>`v3` | rubenfonseca |
| [Feature request: query_string_parameters should never be None](https://github.com/aws-powertools/powertools-lambda-python/issues/1359) | 1 days      | `feature-request`<br>`breaking-change`<br>`need-customer-feedback`<br>`event_handlers` | No assignee |
| [Feature request: Return empty Dict or List in Event Source Data Classes instead of None](https://github.com/aws-powertools/powertools-lambda-python/issues/2605) | 13 days     | `help wanted`<br>`feature-request`<br>`breaking-change`<br>`need-customer-feedback`<br>`need-rfc`<br>`revisit`<br>`v3` | No assignee |

<details>

<summary>Remaining Prioritary Milestone Issues</summary>

| title       | last_update | labels      | assignee    |
| ----------- | ----------- | ----------- | ----------- |
| [Feature request: event_parser envelopes should handle unions of BaseModels](https://github.com/aws-powertools/powertools-lambda-python/issues/2734) | 16 days     | `feature-request`<br>`breaking-change`<br>`v3` | sthulb      |
| [Feature request: Pydantic v2 managed layer](https://github.com/aws-powertools/powertools-lambda-python/issues/2939) | 139 days    | `feature-request`<br>`need-customer-feedback`<br>`v3` | No assignee |
| [Tech debt: refactor the SSMProvider class to implement the get_multiple method](https://github.com/aws-powertools/powertools-lambda-python/issues/3252) | 242 days    | `tech-debt`<br>`v3` | leandrodamascena |
| [Maintenance: Create a Powertools Lambda layer for each Python version](https://github.com/aws-powertools/powertools-lambda-python/issues/3859) | 62 days     | `internal`<br>`v3` | No assignee |
| [Maintenance: Pydantic v1 end of life](https://github.com/aws-powertools/powertools-lambda-python/issues/4067) | 67 days     | `internal`<br>`v3` | No assignee |
| [Maintenance: Deprecate `tracing.base.BaseProvider`](https://github.com/aws-powertools/powertools-lambda-python/issues/4105) | 74 days     | `internal`<br>`v3` | No assignee |
| [RFC: Powertools for AWS Lambda (Python) v3](https://github.com/aws-powertools/powertools-lambda-python/issues/4189) | 23 days     | `RFC`<br>`v3` | rubenfonseca |
| [Maintenance: Add the aws-encryption-sdk dependency in the Lambda layer](https://github.com/aws-powertools/powertools-lambda-python/issues/4192) | 61 days     | `internal`<br>`v3`<br>`data-masking` | No assignee |
| [Tech debt: Refactor api_gateway.py file by splitting its code into multiple files.](https://github.com/aws-powertools/powertools-lambda-python/issues/4194) | 35 days     | `event_handlers`<br>`tech-debt`<br>`v3` | No assignee |
| [Maintenance: Ensure Bedrock Agents resolver works with Pydantic v2](https://github.com/aws-powertools/powertools-lambda-python/issues/4196) | 60 days     | `internal`<br>`v3` | No assignee |
| [Feature request: Support for retrieving batch of secrets](https://github.com/aws-powertools/powertools-lambda-python/issues/4200) | 25 days     | `feature-request`<br>`parameters`<br>`v3` | No assignee |
| [Tech debt: Review the name of the method extract_data_from_envelope in JMESPath Functions](https://github.com/aws-powertools/powertools-lambda-python/issues/4218) | 14 days     | `good first issue`<br>`help wanted`<br>`jmespath`<br>`tech-debt`<br>`v3` | No assignee |

</details>

**Comment by heitorlessa** [comment]
> NOTE: there were some issues with listing triaged/bug issues; we answered and addressed them regardless.

## Low hanging fruits

* [Bug/NotBug: Swagger redirect](https://github.com/aws-powertools/powertools-lambda-python/issues/4427)
* [Docs: Idempotency revamp](https://github.com/aws-powertools/powertools-lambda-python/issues/4197) - PR incoming
* [Typing: Metrics decorator missing Lambda context](https://github.com/aws-powertools/powertools-lambda-python/issues/4088)
* [Typing: Event Handler .post decorator incorrect return](https://github.com/aws-powertools/powertools-lambda-python/issues/3990)
* [Feature: Batch fail early incorrect input error message](https://github.com/aws-powertools/powertools-lambda-python/issues/2394)
* [Doc: Event Handler Routing syntax](https://github.com/aws-powertools/powertools-lambda-python/issues/2962)

## Batch

* [Feature: DynamoDB Stream Processor fail early](https://github.com/aws-powertools/powertools-lambda-python/issues/2850)
* [Feature: Kinesis Processor fail early](https://github.com/aws-powertools/powertools-lambda-python/issues/2850)
* Send entire batch (customer controls what was failure) - Need issue

## AppSync milestone (backport REST features)

* [Feature: Exception Handler support](https://github.com/aws-powertools/powertools-lambda-python/issues/2184)
* [Feature: Middleware support](https://github.com/aws-powertools/powertools-lambda-python/issues/4600)

## Must answer this week

* [Logger debug logs](https://github.com/aws-powertools/powertools-lambda-python/issues/4432)
