### ISSUE TITLE
UnitTests result in `AttributeError: 'NoneType' object has no attribute 'function_name'`

### ISSUE THREAD

**Issue by JonHolman** [awslabs/aws-lambda-powertools-python#469]
I have added AWS lambda powertools to one of my projects and now I am having trouble getting the unit tests working again.  Initially I was getting an error:
`aws_xray_sdk.core.exceptions.exceptions.SegmentNotFoundException: cannot find the current segment/subsegment, please make sure you have a segment open`

so I added the following to my tests/__init__.py file:
`import os

os.environ["POWERTOOLS_TRACE_DISABLED"] = "1"
`

Now I am getting:
`AttributeError: 'NoneType' object has no attribute 'function_name'
`

How do I get around that?  Thanks for your help.

This is the full stack trace from one of the tests:
`Traceback (most recent call last):
  File "/Users/me/repos/my-project/src/tests/test_version.py", line 19, in test_response
    result = version.lambda_handler(None, None)
  File "/Users/me/repos/my-project/src/layer/python/aws_lambda_powertools/metrics/metrics.py", line 184, in decorate
    response = lambda_handler(event, context)
  File "/Users/me/repos/my-project/src/layer/python/aws_lambda_powertools/tracing/tracer.py", line 313, in decorate
    response = lambda_handler(event, context, **kwargs)
  File "/Users/me/repos/my-project/src/layer/python/aws_lambda_powertools/logging/logger.py", line 323, in decorate
    lambda_context = build_lambda_context_model(context)
  File "/Users/me/repos/my-project/src/layer/python/aws_lambda_powertools/logging/lambda_context.py", line 52, in build_lambda_context_model
    "function_name": context.function_name,
AttributeError: 'NoneType' object has no attribute 'function_name'`

**Comment by heitorlessa** [comment]
Hey @JonHolman, thanks for opening your first issue ;) Could you share a snippet of your test?

By looking at the stack trace, it seems that your unit test doesn't pass a fake Lambda Context, and therefore `@logger.inject_lambda_context` fails to get `function_name` property as part of your unit test.

We have a section in our documentation with sample code you can use to solve this: https://awslabs.github.io/aws-lambda-powertools-python/latest/core/logger/#testing-your-code

Also, for Tracer, you might want to set that environment variable before your test framework tries to collect your tests - here's an example of how we typically do in pytest: https://awslabs.github.io/aws-lambda-powertools-python/latest/core/tracer/#testing-your-code

Ping back if you run into any other problem.

Thank you

**Comment by JonHolman** [comment]
Thanks @heitorlessa .  I'll try adding this stuff.  FYI, this full test file is currently just this: 

`import unittest
import warnings
import mock
from src.version import version


class TestVersion(unittest.TestCase):
    def setUp(self):
        warnings.filterwarnings("ignore", category=ResourceWarning, message="unclosed.*<ssl.SSLSocket.*>")

    def test_response(self):
        print()
        print("Testing version response.")
        result = version.lambda_handler(None, None)
        print(result)
        self.assertEqual(result['statusCode'], 200)
        self.assertEqual(result['headers']['Content-Type'], 'text/plain')
`

**Comment by heitorlessa** [comment]
Great, that’s exactly it — None as the context argument will cause that
issue you bumped into. That LambdaContext sample in the Logger docs will
fix it ;)

Lemme know otherwise and I can send you a sample tomorrow morning (I’m
based in the Netherlands)

**Comment by JonHolman** [comment]
It's fixed.  Thank you so much @heitorlessa .
