### ISSUE TITLE
Investigate dependabot not returning CHANGELOG

### ISSUE THREAD

**Issue by heitorlessa** [awslabs/aws-lambda-powertools-python#47]
Dependabot isn't picking up changes defined in the CHANGELOG

#46 might solve it but needs further investigation in dependabot docs, and possibly source code as to what logic it follows - e.g. does it need a Github release, or CHANGELOG should be sufficient?

**Comment by heitorlessa** [comment]
Created a dummy project with dependabot to test this as a consumer:  https://github.com/heitorlessa/test-actions/commit/8ddf530c9b79f5ed24278308a71c5dcb5b6e5b24

**Comment by michaelbrewer** [comment]
@heitorlessa  works perfectly for me now

**Comment by heitorlessa** [comment]
Mystery solved 🥳  Thanks for reporting back @michaelbrewer. Github release notes and repo automation next...
