### ISSUE TITLE
Feature request: allow to provide an `appconfigdata` client in the `AppConfigStore`

### ISSUE THREAD

**Issue by adriantomas** [awslabs/aws-lambda-powertools-python#4728]
### Use case

Sometimes users want to reuse the `appconfigdata` client for their own cases or cache it between invocations outside the handler.

It may also be the case that they want to modify the `endpoint_url` client initialization argument to point to local emulators or to the [AWS AppConfig Agent Lambda Extension](https://docs.aws.amazon.com/appconfig/latest/userguide/appconfig-integration-lambda-extensions.html).

### Solution/User Experience

The solution is to add an argument to be able to send a boto3 client instance of `appconfigdata` to the `AppConfigStore`.

### Acknowledgment

- [X] This feature request meets [Powertools for AWS Lambda (Python) Tenets](https://docs.powertools.aws.dev/lambda/python/latest/#tenets)
- [X] Should this be considered in other Powertools for AWS Lambda languages? i.e. [Java](https://github.com/aws-powertools/powertools-lambda-java/), [TypeScript](https://github.com/aws-powertools/powertools-lambda-typescript/), and [.NET](https://github.com/aws-powertools/powertools-lambda-dotnet/)

**Comment by leandrodamascena** [comment]
Thanks for opening the issue @adriantomas!
