### ISSUE TITLE
Feature request: `validate()` to return validated payload

### ISSUE THREAD

**Issue by dracozombie19** [awslabs/aws-lambda-powertools-python#4797]
### Use case

The Validation feature in Powertools uses `fastjsonschema.validate()` to perform the validation.  This function in `fastjsonschema` returns the validated payload.  While usually this is exactly the same as the input payload, `fastjsonschema` also populates `default` values in missing fields.  For example, with this schema:

```
{
  "properties": {
   "required_id": {
    "type": "integer"
   },
   "test_default": {
    "type": "string",
    "default": "def"
   }
  },
  "required": [
   "required_id"
  ],
  "type": "object"
}
```
And this payload:
```
{
  "required_id": 1234
}
```

The `validate()` function will return:

```
{
  "required_id": 1234,
  "test_default": "def"
}
```

### Solution/User Experience

I'm wondering if we can have the Powertools `validate()` function return the results from `fastjsonschema.validate()`.

### Acknowledgment

- [X] This feature request meets [Powertools for AWS Lambda (Python) Tenets](https://docs.powertools.aws.dev/lambda/python/latest/#tenets)
- [ ] Should this be considered in other Powertools for AWS Lambda languages? i.e. [Java](https://github.com/aws-powertools/powertools-lambda-java/), [TypeScript](https://github.com/aws-powertools/powertools-lambda-typescript/), and [.NET](https://github.com/aws-powertools/powertools-lambda-dotnet/)

**Comment by heitorlessa** [comment]
Nice!! Didn’t know it was a thing (default values) — feel free to make a
pull request and a simple test to confirm the returned value, and we can
prioritize it for this Thursday’s release (otherwise when we have the
bandwidth to do so).

Thanks a lot for flagging it

**Comment by dracozombie19** [comment]
I did some work on this last week but ran into trouble getting the tests to run in the cloud development environment for some reason.  I'll try to revisit it this week.

**Comment by dracozombie19** [comment]
See: https://github.com/aws-powertools/powertools-lambda-python/pull/4839
