### ISSUE TITLE
[I Made This]: Serverless multi-channel alerting solution based on user preferences

### ISSUE THREAD

**Issue by kubernoobie** [awslabs/aws-lambda-powertools-python#4804]
### Link to your material

https://github.com/aws-samples/multichannel-app-to-person-alerting

### Description

Implemented idempotency into my multi-channel alerting solution, using the message ID sent with the API request as the idempotency token/key. 

### Preferred contact

Orsolya B

### Acknowledgment

- [X] I understand this content may be removed from Powertools for AWS Lambda (Python) documentation if it doesn't conform with the [Code of Conduct](https://aws.github.io/code-of-conduct)

**Comment by leandrodamascena** [comment]
Hi @kubernoobie! Thanks for adding Powertools to your project. Can you tell us a little bit more about how Powertools helped you on this journey? Problems it solved and how Powertools makes the experience easier. We need to add some context and show to our customers the experience with Powertools.

Thanks

**Comment by leandrodamascena** [comment]
Hello! This issue has been without any response or interaction for a while! I am closing and please reopen it whenever you want.

Thank you
