### ISSUE TITLE
[Support Lambda Powertools]: Caylent

### ISSUE THREAD

**Issue by ranman** [awslabs/aws-lambda-powertools-python#4816]
### Organization Name

Caylent

### Your Name

Randall Hunt

### Your current position

VP Cloud

### (Optional) Company logo

https://awsmp-logos.s3.amazonaws.com/ca3d951d-f8e1-4e22-bddc-5cae46f9cb2e/c59fb78ec2b02e331936c4050956b5a7.png

### (Optional) Use case

Caylent is an AWS Premier Tier consulting partner, and we love AWS Lambda Powertools. We use Powertools across virtually all of our customers and solutions. ❤️

For instance, just today we coded up a simple tool to log Route53 hosted zone changes to slack. With powertools EventBridge dataclass we got done in minutes without having to mess around with various payloads. Thank you!

### Also using other Powertools for AWS Lambda languages?

- [X] Java
- [X] TypeScript
- [X] .NET

**Comment by leandrodamascena** [comment]
Thanks so much for adding Caylent as a public reference for this project @ranman! This means a lot to us! ❤️
