### ISSUE TITLE
Feature request: Simplify experience in discovering how much time left before Idempotency record expiration

### ISSUE THREAD

**Issue by heitorlessa** [awslabs/aws-lambda-powertools-python#4818]
### Use case

Provide a method to return a `datetime` object to make it easier to manipulate for customers building APIs, webhooks, and observable systems. 

> [Docs](https://docs.powertools.aws.dev/lambda/python/latest/utilities/idempotency/#manipulating-the-idempotent-response)

As of now, this is what we are expecting customers to do which is error prone for the non-initiated.

```python
...

    # expiry_timestamp could be None so include if set
    expiry_timestamp = idempotent_data.expiry_timestamp
    if expiry_timestamp:
        expiry_time = datetime.datetime.fromtimestamp(int(expiry_timestamp))
        response["x-idempotent-expiration"] = expiry_time.isoformat()

    # Must return the response here
    return response
```

### Solution/User Experience

```python
    # this solution is not correct for edge cases, mostly for illustration
    def get_expiration_datetime(self) -> datetime | None:
        if self.expiry_timestamp:
            return datetime.datetime.fromtimestamp(int(self.expiry_timestamp))
        return None
```

### Alternative solutions

```markdown
Customers use the `expiry_timestamp` which they need to convert and manipulate from scratch.

https://docs.powertools.aws.dev/lambda/python/latest/utilities/idempotency/#manipulating-the-idempotent-response
```

### Acknowledgment

- [X] This feature request meets [Powertools for AWS Lambda (Python) Tenets](https://docs.powertools.aws.dev/lambda/python/latest/#tenets)
- [X] Should this be considered in other Powertools for AWS Lambda languages? i.e. [Java](https://github.com/aws-powertools/powertools-lambda-java/), [TypeScript](https://github.com/aws-powertools/powertools-lambda-typescript/), and [.NET](https://github.com/aws-powertools/powertools-lambda-dotnet/)

**Comment by heitorlessa** [comment]
cc @dreamorosi @hjgraca @jeromevdl so it's on everyone's radar for a good UX and think a name+logic that works for everyone

**Comment by leandrodamascena** [comment]
Closed as complete.
