### ISSUE TITLE
Feature request: support metrics with unit "None"

### ISSUE THREAD

**Issue by ethantkoenig** [awslabs/aws-lambda-powertools-python#4834]
### Use case

https://docs.aws.amazon.com/AmazonCloudWatch/latest/APIReference/API_MetricDatum.html reports that "None" is a valid unit for CloudWatch metrics, but the [`MetricUnit`](https://github.com/aws-powertools/powertools-lambda-python/blob/3d1685700576ff0d53bc306656be7162ad0f47bf/aws_lambda_powertools/metrics/provider/cloudwatch_emf/metric_properties.py#L6) enum does not have a member for this unit.

The lack of such a member means that there is no way to create metrics with unit "None" via Powertools. One cannot pass the string `"None"` as the [`unit` parameter of `Metric.add_metric`](https://github.com/aws-powertools/powertools-lambda-python/blob/3d1685700576ff0d53bc306656be7162ad0f47bf/aws_lambda_powertools/metrics/metrics.py#L108), due to [this code](https://github.com/aws-powertools/powertools-lambda-python/blob/3d1685700576ff0d53bc306656be7162ad0f47bf/aws_lambda_powertools/metrics/base.py#L470-L477).

### Solution/User Experience

Of course, I realize that a `MetricUnit` member for "None" cannot be named `None`, but can a member with a different name (perhaps named `None_` or `NoUnit`) please be added to the enum?

### Acknowledgment

- [X] This feature request meets [Powertools for AWS Lambda (Python) Tenets](https://docs.powertools.aws.dev/lambda/python/latest/#tenets)
- [X] Should this be considered in other Powertools for AWS Lambda languages? i.e. [Java](https://github.com/aws-powertools/powertools-lambda-java/), [TypeScript](https://github.com/aws-powertools/powertools-lambda-typescript/), and [.NET](https://github.com/aws-powertools/powertools-lambda-dotnet/)

**Comment by sthulb** [comment]
Hi @ethantkoenig 

~~I think we’re able to support this easily by adding a None element to the MetricUnit class/enum. I can’t see this causing any issues since it would always be used as `MetricUnit.None`~~

I was wrong, Python does indeed care about `None` even as a property
