### ISSUE TITLE
[Support Lambda Powertools]: CHS Inc

### ISSUE THREAD

**Issue by Srinu3366** [awslabs/aws-lambda-powertools-python#4879]
### Organization Name

CHS Inc

### Your Name

Srinivasu Reddy

### Your current position

Solution Architect

### (Optional) Company logo

https://mc-607b9d1c-3283-4f31-97f8-4475-cdn-endpoint.azureedge.net/-/media/project/chs/chs-inc/meta/chs-logo.png?rev=9496ecf42ff24b5a80af3e0e178c8442&extension=webp&hash=79B27F6F73724BBD9DC3C46F9D494577

### (Optional) Use case

Logger, Tracer, Metrics, REST and GraphQL Event Handler

### Also using other Powertools for AWS Lambda languages?

- [ ] Java
- [ ] TypeScript
- [ ] .NET

**Comment by leandrodamascena** [comment]
Hi @Srinu3366! Thank you for opening this issue to add CHS Inc. as a public reference for the project! This means a lot to us.
