### ISSUE TITLE
Technical Debt: Enable TCH, UP and FA100 rules in the Ruff linter

### ISSUE THREAD

**Issue by leandrodamascena** [awslabs/aws-lambda-powertools-python#5016]
### Why is this needed?

Reference: https://github.com/aws-powertools/powertools-lambda-python/issues/4607

We have refactored our codebase to ensure we are following best practices defined by the [PEP](https://peps.python.org/pep-0001/) documents and implemented by [Ruff](https://docs.astral.sh/ruff/).

This implementation should not consider the example/tests folder and if necessary, these folders should be added as an exception in the `lint.per-file-ignores` section in the `ruff.toml` file.

### Which area does this relate to?

Automation

### Acknowledgment

- [X] This request meets [Powertools for AWS Lambda (Python) Tenets](https://docs.powertools.aws.dev/lambda/python/latest/#tenets)
- [ ] Should this be considered in other Powertools for AWS Lambda languages? i.e. [Java](https://github.com/aws-powertools/powertools-lambda-java/), [TypeScript](https://github.com/aws-powertools/powertools-lambda-typescript/), and [.NET](https://github.com/aws-powertools/powertools-lambda-dotnet/)

**Comment by leandrodamascena** [comment]
Hey @ericbn! I'm working on that and will submit a PR to review, ok?

**Comment by ericbn** [comment]
I have these changes ready already and I can open as PR right away if that sounds good to you.

**Comment by leandrodamascena** [comment]
> I have these changes ready already and I can open as PR right away if that sounds good to you.

Please go ahead!!! 😊😊

**Comment by ericbn** [comment]
Cool! Just opened #5017.

**Comment by leandrodamascena** [comment]
Closing as completed!
