### ISSUE TITLE
Docs: Minor typo for log_level example

### ISSUE THREAD

**Issue by ashemedai** [awslabs/aws-lambda-powertools-python#5037]
### What were you searching in the docs?

I was reading about the log_level property.

### Is this related to an existing documentation section?

https://docs.powertools.aws.dev/lambda/python/latest/core/logger/#log-levels

### How can we improve?

The current piece of documentation reads:

```md
If you want to access the numeric value of the current log level, you can use the `log_level` property. For example, if the current log level is `INFO`, `logger.log_level` property will return `10`.
```

This contradicts the table above it, which lists:

```md
| Level      | Numeric value | Standard logging   |
| ---------- | ------------- | ------------------ |
| `DEBUG`    | 10            | `logging.DEBUG`    |
| `INFO`     | 20            | `logging.INFO`     |
```

So either INFO needs to change to DEBUG in the example, or the value needs to change from 10 to 20.

### Got a suggestion in mind?

This should be changed to:

```md
If you want to access the numeric value of the current log level, you can use the `log_level` property. For example, if the current log level is `INFO`, `logger.log_level` property will return `20`.
```

### Acknowledgment

- [X] I understand the final update might be different from my proposed suggestion, or refused.

**Comment by leandrodamascena** [comment]
Hey @ashemedai! Thanks for opening this issue, in fact we need to fix this error in our documentation.

Do you want to submit a PR to fix this? We'd love to have your contribution here.

**Comment by ashemedai** [comment]
@leandrodamascena Can do.

**Comment by ashemedai** [comment]
Done, see #5039
