### ISSUE TITLE
Feature request: Add CodeDeploy Lifecycle hook event to data classes

### ISSUE THREAD

**Issue by mw-root** [awslabs/aws-lambda-powertools-python#5171]
### Use case

CodeDeploy uses lambdas to run health checks on deployments. 
I'd like to see it's event type in data classes alongside codedeploy jobs etc.

### Solution/User Experience

I'll push a PR with the proposed changes. Essentially a WrappedDict with defined parameters like the other event types.

### Acknowledgment

- [X] This feature request meets [Powertools for AWS Lambda (Python) Tenets](https://docs.powertools.aws.dev/lambda/python/latest/#tenets)
- [X] Should this be considered in other Powertools for AWS Lambda languages? i.e. [Java](https://github.com/aws-powertools/powertools-lambda-java/), [TypeScript](https://github.com/aws-powertools/powertools-lambda-typescript/), and [.NET](https://github.com/aws-powertools/powertools-lambda-dotnet/)

**Comment by sthulb** [comment]
Hi @mw-root we're in the process of releasing v3 of Powertools for AWS Lambda, until we've completed the release (next Monday), we're not merging anything.

Feel free to create a PR and we'll merge it once we've completed the release!

**Comment by mw-root** [comment]
@sthulb , that's exciting news!

Thanks for the heads up. I'll revisit #5172 after the release.

Have a good one!

**Comment by mw-root** [comment]
#5172 has been closed and #5219 opened based on the v3 release.

Thanks!
