### ISSUE TITLE
Bug: x86_64 Lambda layers uses the wrong name

### ISSUE THREAD

**Issue by sthulb** [awslabs/aws-lambda-powertools-python#5227]
### Expected Behaviour

AWS Lambda layers for the x86_64 architecture are currently mislabeled as "x86". This naming inconsistency may lead to confusion and potential compatibility issues. We need to update our layer naming convention to accurately reflect the `x86_64` architecture.

### Current Behaviour

Layers are marked as "x86" using the following ARN:

`arn:aws:lambda:{region}:017000801446:layer:AWSLambdaPowertoolsPythonV3-{python_version}-x86:1`

### Code snippet

```python
N/A
```

### Possible Solution

Rename layers to `arn:aws:lambda:{region}:017000801446:layer:AWSLambdaPowertoolsPythonV3-{python_version}-x86_64:1`. This forces the deployment of this new `x86_64` layer name that exists in version 1 as `x86`.

### Steps to Reproduce

Read the docs

### Powertools for AWS Lambda (Python) version

latest

### AWS Lambda function runtime

3.8

### Packaging format used

Lambda Layers

**Comment by leandrodamascena** [comment]
Thanks for opening this issue @sthulb.
