### ISSUE TITLE
Please document what "extras dependencies" are included in the Extra layer

### ISSUE THREAD

**Issue by gwlester** [awslabs/aws-lambda-powertools-python#538]
**What were you initially searching for in the docs?**

What additional packages are included in the Extras Layer.

**Is this related to an existing part of the documentation? Please share a link**
Does not appear to be.

**Describe how we could make it clearer**
List the extra packages included in the Extra Layer.

**If you have a proposed update, please share it here**

**Comment by am29d** [comment]
Hi @gwlester, just to clarify: do you want to know what powertools functionality you will have by using the extras layer or are you interested in the python modules that are inside the extras layer? 

I can see that the former is not clearly explained in the docs. The latter is part of the dependency definition in [pyproject.toml]([tool.poetry.extras])

**Comment by gwlester** [comment]
FormerSent from my T-Mobile 4G LTE Device
-------- Original message --------From: Alex ***@***.***> Date: 7/23/21  00:57  (GMT-06:00) To: awslabs/aws-lambda-powertools-python ***@***.***> Cc: Gerald Leter ***@***.***>, Mention ***@***.***> Subject: Re: [awslabs/aws-lambda-powertools-python] Please document what "extras dependencies" are included in the Extra layer (#538) 
Hi @gwlester, just to clarify: do you want to know what powertools functionality you will have by using the extras layer or are you interested in the python modules that are inside the extras layer?
I can see that the former is not clearly explained in the docs. The latter is part of the dependency definition in pyproject.toml

**Comment by am29d** [comment]
Hey @gwlester , I think something went wrong in your last answer 😅 I can't really see the content of the message.

**Comment by gwlester** [comment]
what powertools functionality you will have by using the extras layer

**Comment by am29d** [comment]
Hi @gwlester ,

thanks for the follow up. The extra layer is only required for the parser utility function, from the docs:

> Core plus extra dependencies such as pydantic that is required by parser utility.

I will make it more crispy in the docs that this heavy 75mb dependencies on top will only be necessary for the `parser` feature.

**Comment by DanyC97** [comment]
@am29d  i think the documentation was [updated](https://awslabs.github.io/aws-lambda-powertools-python/latest/utilities/parser/) for it no ?

**Comment by am29d** [comment]
Hey @DanyC97 thanks for the info. Yes, I double checked and it is actually already in the docs. 👍
