### ISSUE TITLE
BaseProxyEvent: This should draw from self.decoded_body()

### ISSUE THREAD

**Issue by whardier** [awslabs/aws-lambda-powertools-python#544]
It seems as though .json_body() would also attempt to decode the body of a proxyevent if the body is marked as base64 encoded.

https://github.com/awslabs/aws-lambda-powertools-python/blob/cb0d54bc36513961422fdebd5953bc11453b4651/aws_lambda_powertools/utilities/data_classes/common.py#L68

**Comment by michaelbrewer** [comment]
@whardier  i have a patch for that. Going to add an example test case to

**Comment by heitorlessa** [comment]
Thanks @michaelbrewer and thanks @whardier for raising it.

@whardier we'd appreciate if you use the issue templates we have available next time you open an issue.

Tagging this for 1.19.0 in early August

**Comment by heitorlessa** [comment]
Now released as part of 1.19.0: https://github.com/awslabs/aws-lambda-powertools-python/releases/tag/v1.19.0

**Comment by whardier** [comment]
YAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAY
