### ISSUE TITLE
Feature request: Add Functionality to allow CodePipeline Event to Manage Output Artifacts

### ISSUE THREAD

**Issue by mw-root** [awslabs/aws-lambda-powertools-python#5447]
### Use case

`CodePipelineJobEvent` allows us to retrieve input artifacts, but does not have functionality to manage and upload output artifacts.

Since the CodePipeline artifact buckets can be very strict, and the event provides credentials, it makes sense to add methods to interact with, and upload, output artifacts.

### Solution/User Experience

I believe this should be a new method like `event.put_artifact` and whatever methods are required to support this.

The bucket, credentials, and encryption configuration should all be auto-magic.

### Acknowledgment

- [x] This feature request meets [Powertools for AWS Lambda (Python) Tenets](https://docs.powertools.aws.dev/lambda/python/latest/#tenets)
- [x] Should this be considered in other Powertools for AWS Lambda languages? i.e. [Java](https://github.com/aws-powertools/powertools-lambda-java/), [TypeScript](https://github.com/aws-powertools/powertools-lambda-typescript/), and [.NET](https://github.com/aws-powertools/powertools-lambda-dotnet/)

**Comment by leandrodamascena** [comment]
Assing to @anafalcao.
