### ISSUE TITLE
Feature request: MutualTLS Security Scheme for OpenAPI

### ISSUE THREAD

**Issue by Sector95** [awslabs/aws-lambda-powertools-python#5483]
### Use case

Currently this framework supports `apiKey`, `http`, `oauth2`, and `openIdConnect` security schemes in the OpenAPI specification.  However, as of 3.1, there is one more type: `mutualTLS`.

https://swagger.io/specification/#security-scheme-object

### Solution/User Experience

Adding the necessary types to support the `mutualTLS` types in `event_handler/openapi/models.py` should enable this functionality.

### Acknowledgment

- [x] This feature request meets [Powertools for AWS Lambda (Python) Tenets](https://docs.powertools.aws.dev/lambda/python/latest/#tenets)
- [x] Should this be considered in other Powertools for AWS Lambda languages? i.e. [Java](https://github.com/aws-powertools/powertools-lambda-java/), [TypeScript](https://github.com/aws-powertools/powertools-lambda-typescript/), and [.NET](https://github.com/aws-powertools/powertools-lambda-dotnet/)

**Comment by leandrodamascena** [comment]
Hi @Sector95! Thanks a lot for this great catch! We were missing the mTLS security scheme. I'm approving and merging the PR.
