### ISSUE TITLE
Feature request: Parser models for API GW Websockets Events

### ISSUE THREAD

**Issue by ran-isenberg** [awslabs/aws-lambda-powertools-python#5543]
### Use case

I can implement it myself, it's been a while :)
I'd like to present/demo this feature in an upcoming blog post

3 times of events:
connect: https://gist.github.com/ran-isenberg/7c73a1db17a5d47ac5da5e19f0a3529f

message over a route : https://gist.github.com/ran-isenberg/35ceae2179ed9c26e459450825561369

disconnect:  https://gist.github.com/ran-isenberg/2bffedaacc4423d7d23901b803cc280a

### Solution/User Experience

Add Parser models and envelope to parse the event.
Same experience as API GW usage.

### Alternative solutions

```markdown
write the model by myself and use pure pydantic like a savage.
```

### Acknowledgment

- [x] This feature request meets [Powertools for AWS Lambda (Python) Tenets](https://docs.powertools.aws.dev/lambda/python/latest/#tenets)
- [x] Should this be considered in other Powertools for AWS Lambda languages? i.e. [Java](https://github.com/aws-powertools/powertools-lambda-java/), [TypeScript](https://github.com/aws-powertools/powertools-lambda-typescript/), and [.NET](https://github.com/aws-powertools/powertools-lambda-dotnet/)

**Comment by leandrodamascena** [comment]
Hi @ran-isenberg! Thanks a lot for opening this issue!

I'm working on adding support for Python 3.13 and I'll take a look at this issue tomorrow and we can add this to the parser/eventsource schemas/class.

**Comment by ran-isenberg** [comment]
lemme know if you want to write it yourself, or do you want me to give it a try ;)

**Comment by anafalcao** [comment]
Hi Ran,
Thank you for opening this issue! I'm the new maintainer of Powertools, and I'll be working with you on this. Great catch, it will simplify the process when using WebSocket and Lambda together.
Would you like to submit this PR? I noticed it's been a while since we've had a pull request from you :smile:
It'd be a pleasure to work with you to get this merged!
Let me know if you need any assistance or have any questions along the way

**Comment by ran-isenberg** [comment]
Hey @anafalcao , nice to meet you!
Looking forward to meeting you and seeing the team again at Vegas!
I'll try to write a PR later tonight, it's been a while!

**Comment by ran-isenberg** [comment]
@anafalcao  see https://github.com/aws-powertools/powertools-lambda-python/pull/5597

**Comment by ran-isenberg** [comment]
@leandrodamascena  when will you release it?
