### ISSUE TITLE
Bug: CORS support doe not add headers to response

### ISSUE THREAD

**Issue by dave-dotnet-overall** [awslabs/aws-lambda-powertools-python#5550]
### Expected Behaviour

After following the document to enable CORS when i execute my lambda via api gateway from postman there are no CORS headers been added to the response. I have tried every documented option but to no avail, so either there is documentation missing or this is a bug

### Current Behaviour

After enabling CORS i would expect to see the CORS headers been added to the response before it is sent back to the client.

### Code snippet

```python
Just copy what is in the documentation and inspect the returned headers in postman.
```

### Steps to Reproduce

Just copy what is in the documentation and inspect the returned headers in postman.

### Powertools for AWS Lambda (Python) version

latest

### AWS Lambda function runtime

3.12

### Packaging format used

Lambda Layers

### Debugging logs

```python

```

**Comment by leandrodamascena** [comment]
Hi @dave-dotnet-overall! Thanks for opening this issue! Can you pls give me more details?

- What headers are you using in this request?
- What HTTP method?
- Do you have CORS enabled in APIGW or not?

Thanks

**Comment by dave-dotnet-overall** [comment]
hi @leandrodamascena 

Nor sure what you mean what headers im using in this request, basically my React developer said they got an error saying "CORS error: "CORS header 'Access-Control-Allow-Origin' missing." when they tried to connect to the API and the reason was because i am not sending CORS headers back. Ive looked at the output from the APIGatewayResolver in the lambda handler and sure enough there are no CORS headers been injected by powertools even though i have set up them according to the documentation.

HTTP method is  GET

According to the AWS docs for Lamba with proxy integration it is the responsibility of the lambda function to return the headers and not api gw

**Comment by garym-krrv** [comment]
I have the same issue when executing a Lambda function directly using the URL or via an APi Gateway.
I am using postman to call a function or API Gateway resource and I never receieve any CORS Headers.

My APi Gateway is running Lambda in Proxy Mode.
Also when calling Lambda function directly I recieve same issue

My Test Code

`import json

from aws_lambda_powertools import Logger
from aws_lambda_powertools.event_handler import APIGatewayRestResolver, LambdaFunctionUrlResolver, CORSConfig, content_types
from aws_lambda_powertools.utilities.typing.lambda_context import LambdaContext
logger = Logger()

# Initialize variables
cors_config = CORSConfig(allow_origin="*",max_age=300)

#app = LambdaFunctionUrlResolver(cors=cors_config,debug=True)
app = APIGatewayRestResolver(cors=cors_config,debug=True)

@app.get("/test", cors=True)
def ping():
    return {"message": "pong"}  

@app.get("/", cors=True)
def ping():
    return {"message": "pong"}  

def lambda_handler(event: dict, context: LambdaContext) -> dict:
    print(json.dumps(app.resolve(event, context)))
    return app.resolve(event, context)`

**Comment by dave-dotnet-overall** [comment]
Turns out the react developers were not sending an "Origin" header with their request and as a result the server does not send the CORS headers

**Comment by leandrodamascena** [comment]
> Turns out the react developers were not sending an "Origin" header with their request and as a result the server does not send the CORS headers

Hi @dave-dotnet-overall, thanks for updating this issue! Yes, that's why I asked what headers you were using to make this request. CORs needs the `Origin` header to trigger the validation and Postman doesn't send the `Origin` header by default.

Please reopen this issue if you need any other help.
