### ISSUE TITLE
Bug: KafkaSelfManagedEventModel eventSource not correct

### ISSUE THREAD

**Issue by Mavtti** [awslabs/aws-lambda-powertools-python#5559]
### Expected Behaviour

Hello,

the envelope KafkaSelfManagedEventModel should have `eventSource = Literal["SelfManagedKafka"]`

### Current Behaviour

Currently, it expects  `eventSource = Literal["aws:SelfManagedKafka"]`

### Code snippet

```python
class KafkaSelfManagedEventModel(KafkaBaseEventModel):
    """Self-managed Apache Kafka event trigger
    Documentation:
    --------------
    - https://docs.aws.amazon.com/lambda/latest/dg/with-kafka.html
    """

    eventSource: Literal["SelfManagedKafka"]
```

### Steps to Reproduce

parse with envelope

### Powertools for AWS Lambda (Python) version

latest

### AWS Lambda function runtime

3.9

### Packaging format used

PyPi

### Debugging logs

```python

```

**Comment by leandrodamascena** [comment]
Hi @Mavtti! Thank you very much for catching this bug! We need to fix this.

Please let me know if you want to submit a PR to fix it, otherwise I can do it.
