### ISSUE TITLE
Maintenance: AppSyncResolverEvent uses `typeName` instead of `parentTypeName`

### ISSUE THREAD

**Issue by aminalaee** [awslabs/aws-lambda-powertools-python#5560]
### Why is this needed?

I'm new to GraphQL in general, but I think in the original PR #323 the `AppSyncResolverEvent` was based on AWS Amplify, so instead of reading `parentTypeName`, we are reading `typeName`.

It confused me that the code is consistent (in some ways) with AWS AppSync Context info:

```ts
type Info = {
  fieldName: string;
  parentTypeName: string;
  variables: any;
  selectionSetList: string[];
  selectionSetGraphQL: string;
};
```

But we are assigning variables in a way they are not clear:

https://github.com/aws-powertools/powertools-lambda-python/blob/a3f3359bafeba39002a27ee9d02c66c57ed32bbc/aws_lambda_powertools/utilities/data_classes/appsync_resolver_event.py#L161

And we define different property names for reading the `parentTypeName`:

https://github.com/aws-powertools/powertools-lambda-python/blob/a3f3359bafeba39002a27ee9d02c66c57ed32bbc/aws_lambda_powertools/utilities/data_classes/appsync_resolver_event.py#L121-L124

https://github.com/aws-powertools/powertools-lambda-python/blob/a3f3359bafeba39002a27ee9d02c66c57ed32bbc/aws_lambda_powertools/utilities/data_classes/appsync_resolver_event.py#L165-L168

This has the side-effect that when setting up an AppSync resolved in AWS like the following, it does not work out of the box and you have to pass `typeName` to make it work:

```ts
import { util } from '@aws-appsync/utils';

/**
 * Sends a request to a Lambda function. Passes all information about the request from the `info` object.
 * @param {import('@aws-appsync/utils').Context} ctx the context
 * @returns {import('@aws-appsync/utils').LambdaRequest} the request
 */
export function request(ctx) {
    return {
        operation: 'Invoke',
        payload: {
            fieldName: ctx.info.fieldName,
            parentTypeName: ctx.info.parentTypeName,
            typeName: ctx.info.parentTypeName,  // Extra field which is exactly the same as the one above
            arguments: {}, // Extra field
            variables: ctx.info.variables,
            selectionSetList: ctx.info.selectionSetList,
            selectionSetGraphQL: ctx.info.selectionSetGraphQL,
        },
    };
}

/**
 * Process a Lambda function response
 * @param {import('@aws-appsync/utils').Context} ctx the context
 * @returns {*} the Lambda function response
 */
export function response(ctx) {
    const { result, error } = ctx;
    if (error) {
        util.error(error.message, error.type, result);
    }
    return result;
}

```

### Which area does this relate to?

Event Source Data Classes

### Solution

I'm not sure if it was the intention and it should stay the same, but I think we can improve this in different ways:

- If the old approach is not desired, we can just deprecate it and mention `parent_type_name` should be used
- If the old approach is still valid, we can try to read `info` from `parentTypeName` after `typeName` is checked. This way it is consistent with the AWS Resolver context [here](https://docs.aws.amazon.com/appsync/latest/devguide/resolver-context-reference-js.html) and with the Amplify structure

I can prepare a PR if the suggestion makes sense.

### Acknowledgment

- [x] This request meets [Powertools for AWS Lambda (Python) Tenets](https://docs.powertools.aws.dev/lambda/python/latest/#tenets)
- [ ] Should this be considered in other Powertools for AWS Lambda languages? i.e. [Java](https://github.com/aws-powertools/powertools-lambda-java/), [TypeScript](https://github.com/aws-powertools/powertools-lambda-typescript/), and [.NET](https://github.com/aws-powertools/powertools-lambda-dotnet/)

**Comment by leandrodamascena** [comment]
Hi @aminalaee! Thanks for reporting this! I'll check on Monday, but I think we have a bug here.

The reason I'll check out this is because we use some of these fields in our `AppSync Event Handler` utility and I don't know if we have this bug there as well, so I want to test everything together.

**Comment by aminalaee** [comment]
Thanks, And about your point of this usage, I think it's kind of the same that in other places `type_name` is used where we mean `parent_type_name`. To me seems like this was only to follow AWS Amplify and seems like that is not consistent with AWS Resolver Context.

https://github.com/aws-powertools/powertools-lambda-python/blob/a3f3359bafeba39002a27ee9d02c66c57ed32bbc/aws_lambda_powertools/event_handler/appsync.py#L377
https://github.com/aws-powertools/powertools-lambda-python/blob/a3f3359bafeba39002a27ee9d02c66c57ed32bbc/aws_lambda_powertools/event_handler/appsync.py#L425


https://docs.amplify.aws/gen1/react/build-a-backend/graphqlapi/custom-business-logic/#structure-of-the-function-event

**Comment by leandrodamascena** [comment]
Hi @aminalaee! Sorry for the late reply, I'm working on a fix until the end of this week and will let you know when we release it.

Thanks a lot for pointing that out.

**Comment by leandrodamascena** [comment]
Hey @aminalaee! I sent a PR to fix this, and it will be released in the first (or second) week of January.
The old approach is still valid. We can check `parentTypeName` before `typeName`, which will help keep the field names more consistent.

I apologize for the delay in fixing this. We have been very busy this month and last month.
