### ISSUE TITLE
[Maintenance] Parameters: max_age and other provider settings not discoverable in high level methods

### ISSUE THREAD

**Issue by heitorlessa** [awslabs/aws-lambda-powertools-python#561]
Get_secret for example doesn't expose max_age parameter which makes customers believe they have to use SecretsProvider adding a few more lined in the UX.

We do propagate the parameters if they use them, so we must improve their experience

**Comment by michaelbrewer** [comment]
@heitorlessa  Sounds like a small patch. Depending on the planned release schedule i can fit this in

**Comment by michaelbrewer** [comment]
@heitorlessa - I think we can close this now :)
