### ISSUE TITLE
[Maintenance] Parameters: transform: auto

### ISSUE THREAD

**Issue by dreamorosi** [awslabs/aws-lambda-powertools-python#562]
**What were you initially searching for in the docs?**

Studying the Parameters BaseClass implementation I noticed that the `get_multiple()` method accepts also a value equal to `auto`.

This value is documented only in the docstring of the method but not on the actual documentation.

**Is this related to an existing part of the documentation? Please share a link**

https://awslabs.github.io/aws-lambda-powertools-python/latest/utilities/parameters/

**Describe how we could make it clearer**

Add the parameter to the documentation.

**If you have a proposed update, please share it here**

Happy to help with documenting this.

**Comment by heitorlessa** [comment]
Ciao Andrea - yes, please! I could use any help I could get :)

 I’ve noticed other inconsistencies too that’s missing in the docs and
params.

Running the docs locally: make docs-local-docker

**Comment by michaelbrewer** [comment]
@dreamorosi  - it is worth looking at the test cases. I worked on this feature, but definitely missed out on clear docs for it

**Comment by heitorlessa** [comment]
Now released as part of 1.19.0: https://github.com/awslabs/aws-lambda-powertools-python/releases/tag/v1.19.0
