### ISSUE TITLE
Feature request: Mark API operation as `deprecated` for OpenAPI documentation

### ISSUE THREAD

**Issue by tcysin** [awslabs/aws-lambda-powertools-python#5674]
### Use case

When [customizing API operations](https://docs.powertools.aws.dev/lambda/python/latest/core/event_handler/api_gateway/#customizing-api-operations), I'd like to be able to mark an operation as **deprecated** (see [Operation Object, OAS v3.0.3](https://spec.openapis.org/oas/v3.0.3.html#operation-object)).

This helps to tell the users that an operation will be, well, deprecated. Here's what it looks like with _Petstore_ example in [Swagger Editor](https://editor-next.swagger.io/):

<img src="https://github.com/user-attachments/assets/5070d024-fe9e-46cd-b646-3d43fb22b193" width="320">

### Solution/User Experience

An extra `deprecated` boolean parameter with a `False` default:

```python
from aws_lambda_powertools.event_handler import APIGatewayRestResolver
from aws_lambda_powertools.event_handler.api_gateway import Router

app = APIGatewayRestResolver()

@app.get("/spam", deprecated=True)
def spam(name):
    return {"message": "mmm... tasty"}

@app.get("/eggs")  # deprecated=False by default
def eggs(name):
    return {"message": "cheese"}

router = Router()

@router.get("/ham", deprecated=True)
def ham():
    return {"message": "ham!"}
```

### Acknowledgment

- [x] This feature request meets [Powertools for AWS Lambda (Python) Tenets](https://docs.powertools.aws.dev/lambda/python/latest/#tenets)
- [ ] Should this be considered in other Powertools for AWS Lambda languages? i.e. [Java](https://github.com/aws-powertools/powertools-lambda-java/), [TypeScript](https://github.com/aws-powertools/powertools-lambda-typescript/), and [.NET](https://github.com/aws-powertools/powertools-lambda-dotnet/)

Thanks for your hard work!

**Comment by anafalcao** [comment]
Hi @tcysin ! Thanks for opening this feature request, and sorry for the delay, we were at re:invent last week. 
Would you like to open a PR with your solution or do you prefer us to work on it and come back to you?

**Comment by tcysin** [comment]
It's all good 👍
Yeah, I'm giving it a try.
