### ISSUE TITLE
Bug: Missing dependency jsonpath_ng for Data Masking in package version 3.3.0

### ISSUE THREAD

**Issue by tzahari** [awslabs/aws-lambda-powertools-python#5715]
### Expected Behaviour

Usage of the [DataMasking](https://docs.powertools.aws.dev/lambda/python/latest/utilities/data_masking/) tool is working without import error.

### Current Behaviour

The following error occurred: 
`ModuleNotFoundError: No module named 'jsonpath_ng'`

### Code snippet

```python
from aws_lambda_powertools.utilities.data_masking import DataMasking

data_masker = DataMasking()
data = {'password': 'secret!', 'login': 'login1'}
erased = data_masker.erase(data, fields=["password"])
print(erased)
```

### Possible Solution

Add `jsonpath_ng` to the package dependencies

### Steps to Reproduce

1. install powertools version 3.3.0
2. run the example script

### Powertools for AWS Lambda (Python) version

3.3.0

### AWS Lambda function runtime

3.12

### Packaging format used

PyPi

### Debugging logs

```python

```

**Comment by anafalcao** [comment]
Hi @tzahari ! The DataMasking utility requires some additional dependencies that aren't included in the core package.

To resolve this issue, you'll need to ensure you're installing the datamasking extras. Here's how you can do that:

If you're installing directly with pip, for example:
`pip install "aws-lambda-powertools[datamasking]"`

This will ensure all necessary dependencies, including `jsonpath-ng`, are installed. You can find more information about this in our documentation: https://docs.powertools.aws.dev/lambda/python/latest/utilities/data_masking/#install

We appreciate you taking the time to report this. It's a great opportunity to clarify this aspect of Powertools and hopefully help other users who might encounter the same situation. Let us know if you have any further questions or if you need any more assistance!

**Comment by tzahari** [comment]
Hi @anafalcao ,
Thanks for this head up. I missed that in the documentation... sorry for that. 
Maybe move the DataMasking part completely into the extra package? 
Best Regards
