### ISSUE TITLE
adding data_as_bytes to KinesisStreamRecordPayload

### ISSUE THREAD

**Issue by hjurong** [awslabs/aws-lambda-powertools-python#617]
**Is your feature request related to a problem? Please describe.**

currently the `KinesisStreamRecordPayload` has `data_as_text` and `data_as_json` helpers which are useful for deserialising text/json payload; however, we can have gzipped payload (e.g., from cloudwatch logs) which we don't want to convert to `str` but still want to leverage the dataclass to do the base64 decode

**Describe the solution you'd like**

a `data_as_bytes` method in `KinesisStreamRecordPayload`

**Describe alternatives you've considered**

Another custom wrapper class, or just getting the `record.kinesis.data` attribute then do the base64 decode; but both are not as clean as having a helper on `KinesisStreamRecordPayload` 

**Additional context**

N/A

**Comment by heitorlessa** [comment]
Coming in today's release!
