### ISSUE TITLE
Document how to unit test idempotency

### ISSUE THREAD

**Issue by heitorlessa** [awslabs/aws-lambda-powertools-python#631]
**What were you initially searching for in the docs?**

How to unit test code when using [idempotency utility](https://awslabs.github.io/aws-lambda-powertools-python/latest/utilities/idempotency/)

**Is this related to an existing part of the documentation? Please share a link**

**Describe how we could make it clearer**

Like other utilities, create a section `Testing your code` with an example test.

**If you have a proposed update, please share it here**

**Comment by lucasam** [comment]
We are facing issues with UT as well.

Our main issue is that, as DynamoDBPersistenceLayer is eager to create table. Every python script that we use this annotation needs have mocks in place in advance. Even to test non annotated methods at the same python file.

My question is:
- Am i missing something?
- Can i cut a ticket and raise a PR to make `DynamoDBPersistenceLayer` to lazy create boto resources?

**Comment by heitorlessa** [comment]
Hey @lucasam if you could contribute that would be awesome, as I'm on vacation for two more weeks.

**Comment by heitorlessa** [comment]
Thanks a lot @cakepietoast !!!
