### ISSUE TITLE
Include THIRD-PARTY-LICENSES in PyPI tarball

### ISSUE THREAD

**Issue by BastianZim** [awslabs/aws-lambda-powertools-python#634]
**Is your feature request related to a problem? Please describe.**

Currently, THIRD-PARTY-LICENSES is not included in the PyPI tarball: https://pypi.org/project/aws-lambda-powertools/#files

**Describe the solution you'd like**

It would be great, if the THIRD-PARTY-LICENSES file is also included.

**Describe alternatives you've considered**

**Additional context**

I am the maintainer of the [conda-forge feedstock](https://github.com/conda-forge/aws-lambda-powertools-feedstock) and am currently manually including the file.

**Comment by BastianZim** [comment]
Happy to put in a PR if this is something that's acceptable.

**Comment by heitorlessa** [comment]
Hey Bastian - absolutely, feel free to open a PR and we can merge it;
sounds like it was an oversight on my part

**Comment by BastianZim** [comment]
Hi Heitor, awesome, have added the PR (At least that's where I think it's included). Thanks!

**Comment by heitorlessa** [comment]
Thanks a lot @BastianZim foe the PR - merged it earlier. I'll ping here once we make a release in the coming weeks - we've got some new enhancements we want to work on first.

Also, first time I hear about conde feedstock, so thanks a lot for including us :-)

**Comment by BastianZim** [comment]
My pleasure, thanks for merging @heitorlessa! Of course, nothing urgent on my side. I'm following the releases so no ping needed for me, just FYI. :)

Of course! Let me know if anyone here wants to be a maintainer there as well at some point.

**Comment by heitorlessa** [comment]
Available now in PyPi as 1.20.1 ;)

**Comment by BastianZim** [comment]
Thank you!

**Comment by BastianZim** [comment]
@heitorlessa Would you mind opening the issue again? Unfortunately, the license is still not included: https://pypi.org/project/aws-lambda-powertools/#files
Not entirely sure why as I thought this is done through the Manifest but I have to admit that I'm not the greatest expert on python packaging so I'll try but am probably the wrong person to investigate this further.
