### ISSUE TITLE
native logger integration / dep loglevel config?

### ISSUE THREAD

**Issue by KiaraGrouwstra** [awslabs/aws-lambda-powertools-python#649]
Python comes with some logging niceties [built-in](https://docs.python.org/3/howto/logging.html), among which the ability to use yaml-based configuration for logging. this facilitates e.g. the configuration of logging levels of dependencies.
this sounds nice, but i'm not sure how to achieve something similar with powertools's logger. is this something that is currently possible, or might this be desirable as a potential enhancement?

**Comment by heitorlessa** [comment]
hey @KiaraGrouwstra thank you for creating it - apologies for the delay, just got back from a long vacation.

For setting the log level, you can use either `Logger(level="DEBUG")` or simply the environment variable `LOG_LEVEL` as per our docs: https://awslabs.github.io/aws-lambda-powertools-python/latest/core/logger/#getting-started

Child loggers (`Logger(child=true)`) have bi-directional sync, which means if you change the logger it'll replicate both ways, for example if you add a new key: `logger.append_keys(payment_id="123")`

We don't plan to add a YAML based config as you don't need to configure it like you do the traditional logger, you simply do `logger = Logger()`, and it just works. You can opt-in for other features like setting correlation ID, log sampling, but you'd want to do this conditionally, not statically.

Does that help?

I'm more than happy to clarify any questions you might have.

**Comment by KiaraGrouwstra** [comment]
hi,
this issue i'm concerned about is about dependencies.
i know that for my own code i can control which logging level of messages will be printed.
the issue is, i'm consuming other pip packages that log things as well, and in some cases turn out buggy.
in such cases, i would like to be able to print debug-level info for such a broken package.
that is something that by default python logging can achieve. however, as i currently understand it, since the powertools logging library does not hook into this built-in way of logging, it lacks that functionality.
is this understanding correct?

**Comment by heitorlessa** [comment]
Ah! I totally misunderstood, sorry.

You can get the namespace logger and set the level as you normally would
with any logging that used std logging, or set the level at the root logger
and it will be propagated.

Could you share the workflow you have in mind so I can share a snippet with
you?

I don’t wanna assume you want to propagate down, upwards, or in another way
I might not be thinking.

**Comment by heitorlessa** [comment]
Checking in to see if this helped, and whether we could have more details on the issue report about the workflow to address this properly
