### ISSUE TITLE
Idempotent documentation examples could be misleading

### ISSUE THREAD

**Issue by walmsles** [awslabs/aws-lambda-powertools-python#657]
**What were you initially searching for in the docs?**
How to use the Idempotent utility

**Is this related to an existing part of the documentation? Please share a link**
[Link to documentation section](https://awslabs.github.io/aws-lambda-powertools-python/latest/utilities/idempotency/#choosing-a-payload-subset-for-idempotency)

**Describe how we could make it clearer**

The example uses the following config:

```python
config = IdempotencyConfig(event_key_jmespath="body")
```

What I feel is missing from the documentation is that the Idempotent decorator does not do any type coersion on the **event_key_jmespath** so this data hash key used in dynamodb is based on the **String** data in the event body attribute.

For a standard APIGatewayProxyEvent for a json REST Api that means the following body strings are different even though logically the API Json payloads are actually identical (in API terms).   If I follow the example verbatim the following body values will be seen as different API invocations:

```python
{
   "more_data": "more data 1",
"data": "test message 1"
}
```

```python
{
   "more_data": "more data 1",
   "data": "test message 1"
}
```

```python
{

   "more_data": "more data 1",







"data": "test message 1"

}
```
maps to a body of "{\n\n   \"more_data\": \"more data 1\",\n\n\n\n\n\n\n\n\"data\": \"test message 1\"\n\n}" in the API Gateway event (i.e. includes all the white space).

I feel the example should include the event source for API Gateway events resulting in the following:

```python
import json
from aws_lambda_powertools.utilities.idempotency import (
    IdempotencyConfig, DynamoDBPersistenceLayer, idempotent
)
from aws_lambda_powertools.utilities.data_classes import (
    event_source, APIGatewayProxyEvent
)

persistence_layer = DynamoDBPersistenceLayer(table_name="IdempotencyTable")

config = IdempotencyConfig(event_key_jmespath="json_body")
@event_source(data_class=APIGatewayProxyEvent)
@idempotent(config=config, persistence_store=persistence_layer)
def handler(event:APIGatewayProxyEvent, context):
    body = json.loads(event['body'])
    payment = create_subscription_payment(
        user=body['user'],
        product=body['product_id']
    )
    ...
    return {
        "payment_id": payment.id,
        "message": "success",
        "statusCode": 200
    }
```

**If you have a proposed update, please share it here**
Maybe change the example to include the event_source coersion to stop people copying that example thinking their API will be idempotent - when it will when the exact body string is used.  Its not obvious from the documentation (or maybe its just me)

**Comment by cakepietoast** [comment]
Thanks @walmsles - I added some small feedback on your PR

**Comment by cakepietoast** [comment]
Thanks @walmsles! I've had a look at the PR and requested a few small changes there.

**Comment by heitorlessa** [comment]
Closing this now as it's available in the staged docs: https://awslabs.github.io/aws-lambda-powertools-python/develop/utilities/idempotency/

We'll work on exposing JMESPath Functions to all customers along with our handy functions, so they can use them like we do anywhere in their code.

Thank you so much for the help again @walmsles !
