### ISSUE TITLE
Allow bring your own logger to Feature Flags

### ISSUE THREAD

**Issue by gwlester** [awslabs/aws-lambda-powertools-python#702]
**Is your feature request related to a problem? Please describe.**

Users would like to use a customized logger.

**Describe the solution you'd like**

Add the ability to pass a _logger_ instance, defaulted to **None** into the object creation of the following classes:

- **AppConfigStore**
- **FeatureFlags**
- **SchemaValidator**
- **FeaturesValidator**
- **RulesValidator**
- **ConditionsValidator**

The **init** method would create a logger instance if **None** was passed in.

**Describe alternatives you've considered**

**Additional context**

**Comment by gwlester** [comment]
I attempted to push an implementation of this up to then create a push request, but it seems I'm not authorized.

Can I get added to the contributors list?

**Comment by cakepietoast** [comment]
@gwlester you'll need to fork this repository then push your changes to a branch in your own fork. You can then create a PR from your own fork against this repo. If you're having issues, come ping us in #lambda-powertools on the AWS Developer Slack ([invite if you need one](https://join.slack.com/t/awsdevelopers/shared_invite/zt-gu30gquv-EhwIYq3kHhhysaZ2aIX7ew)) and we'll help.

**Comment by heitorlessa** [comment]
Now available as part of 1.21.0 :) https://github.com/awslabs/aws-lambda-powertools-python/releases/tag/v1.21.0
