### ISSUE TITLE
Logger extra fields appended to end of log message instead of beginning  

### ISSUE THREAD

**Issue by mccauleyp** [awslabs/aws-lambda-powertools-python#707]
**Is your feature request related to a problem? Please describe.**

I think it would be nice if by default, keys appended to the structure log messages with the `extra=fields` parameter appeared at the end of the log message rather than the beginning. That's actually the behavior shown in the sample CloudWatch logs in the documentation (https://awslabs.github.io/aws-lambda-powertools-python/latest/core/logger/), but I see the additional keys at the start of the log message when I use the `extra` argument. That makes it a bit harder to scroll through to find what I'm looking for in the logs.

**Describe the solution you'd like**

I think the default formatter could be updated for this to be the default. 

**Describe alternatives you've considered**

I could create my own `LambdaPowertoolsFormatter` instance and order the keys explicitly but am hoping to avoid that and am wondering if this is the intended behavior already given how the sample logs look in the documentation. 

**Additional context**

I'm using power tools version 1.20.2 and Python 3.8

![Screen Shot 2021-09-28 at 12 52 56 PM](https://user-images.githubusercontent.com/66882763/135157043-c3a54cd1-018f-4fa6-9320-b4a2ab86fcf8.png)

**Comment by heitorlessa** [comment]
Hey @mccauleyp thank you for raising this - it's definitely something we should fix it. It's a rather quick one so I'll work on that now to make it available for next week's release ;)

**Comment by heitorlessa** [comment]
Done - should be available next week as we complete other critical areas before releasing 1.21 ;)

https://github.com/awslabs/aws-lambda-powertools-python/pull/722

Thanks again for flagging it!

**Comment by mccauleyp** [comment]
Awesome, thanks! I'll close this ticket now and reopen if it seems like it's not working after I switch to 1.21 after it's released.
