### ISSUE TITLE
Feature Flag only evaluates first rule in a feature

### ISSUE THREAD

**Issue by gwlester** [awslabs/aws-lambda-powertools-python#714]
**What were you trying to accomplish?**
Having a feature flag with multiple rules.

## Expected Behavior

Rules should be evaluated for a feature until one is true or all rules have been evaluated.  It appears that test test_flags_conditions_rule_match_multiple_actions_multiple_rules_multiple_conditions does not work as expected.

## Current Behavior

The default is returned if the first rule is false.

## Possible Solution

I will submit a pull request to correct the code.
I have not debugged the test.

## Steps to Reproduce (for bugs)

1. See test_flags_conditions_rule_match_multiple_actions_multiple_rules_multiple_conditions
2.

## Environment

* **Powertools version used**: 1.20.2
* **Packaging format (Layers, PyPi)**: Layers
* **AWS Lambda function runtime:** 3.8
* **Debugging logs**

> [How to enable debug mode](https://awslabs.github.io/aws-lambda-powertools-python/#debug-mode)**

```python
# paste logs here
```

**Comment by gwlester** [comment]
@heitorlessa -- I think this should have the label: **status/staged-next-release**

**Comment by heitorlessa** [comment]
This is now available as part of today's 1.21.0 release -- Thank you for the contribution, credits given at the top ;)

https://github.com/awslabs/aws-lambda-powertools-python/releases/tag/v1.21.0
