### ISSUE TITLE
Utilities -> Parser -> Validating Entire Model -> Typo in "Example"

### ISSUE THREAD

**Issue by nsandar** [awslabs/aws-lambda-powertools-python#729]
**What were you initially searching for in the docs?**
I was trying to understand how to implement the input model parser with validations.

**Is this related to an existing part of the documentation? Please share a link**
https://awslabs.github.io/aws-lambda-powertools-python/latest/utilities/parser/#validating-entire-model

**Describe how we could make it clearer**
The example provided uses the `@root_validator` decorator, but the `import` statement is only importing `validator` (which is unused).

**If you have a proposed update, please share it here**
In the `import` statement, please replace `validator` with `root_validator`.

**Comment by heitorlessa** [comment]
Thanks a lot @nsandar for flagging this - I've just merged and it's available in the staging docs --- it'll be available in the latest today as part of the next release

https://awslabs.github.io/aws-lambda-powertools-python/develop/utilities/parser/#validating-entire-model
