### ISSUE TITLE
Utilities -> Parser -> event_parser-decorator -> Unused Import in Example Code

### ISSUE THREAD

**Issue by nsandar** [awslabs/aws-lambda-powertools-python#748]
**What were you initially searching for in the docs?**
 I was trying to understand how to implement `@event_parser` decorator.

**Is this related to an existing part of the documentation? Please share a link**
https://awslabs.github.io/aws-lambda-powertools-python/latest/utilities/parser/#event_parser-decorator

**Describe how we could make it clearer**
The example provided imports the `ValidationError`, but that error is unused in the example. The `ValidationError` is only used in the `parse function` example.

**If you have a proposed update, please share it here**
Remove the unused `ValidationError` from the `import` statement in the `event_parser decorator` example

**Comment by heitorlessa** [comment]
Closing as this will be available in today's release docs; already available in staging docs. Thanks a lot again for reporting it!
