### ISSUE TITLE
Event Handler: API Gateway current_event doesn't show all properties

### ISSUE THREAD

**Issue by heitorlessa** [awslabs/aws-lambda-powertools-python#761]
When trying to access `request_context` when using either API Gateway v1 or v2 we can't have type hinting due to ALB being different - both inherit from [BaseProxyEvent](https://github.com/awslabs/aws-lambda-powertools-python/blob/d02dd2eed07f3d67ca0c02437c6a31b3360b5b41/aws_lambda_powertools/utilities/data_classes/common.py#L47).

Overloading the internal method [_to_proxy_event](https://github.com/awslabs/aws-lambda-powertools-python/blob/6fcedeca10e54312ddc9e00eb1ca8fe27064f7dc/aws_lambda_powertools/event_handler/api_gateway.py#L517) with all potential returns, even with `Literal[ProxyEventType.APIGatewayProxyEvent]` didn't seem to yield any result, as MyPy and Intelisense continues to think it's a `BaseProxyEvent`.

Need a deeper understanding of MyPy and type invariants to potentially solve this.

```python
from aws_lambda_powertools.event_handler.api_gateway import ApiGatewayResolver

app = ApiGatewayResolver()


@app.get("/test")
def test_it():
	# this should autocomplete when not using ALB as the ProxyType argument in ApiGatewayResolver
	app.current_event.request_context.identity.account_id 
    ...


def handler(event, context):
    app.resolve(event, context)


app({}, None)
```

**Comment by michaelbrewer** [comment]
@heitorlessa any suggestions on how to implement this on Python? I am not sure how generics would work on Python.

Another option would be to add properties that cast to the preferred type `app.current_alb_event`, `app.current_http_event`?

**Comment by heitorlessa** [comment]
Because we have a parameter that indicates which Proxy Type to use, we can use [function overloading from typing](https://mypy.readthedocs.io/en/stable/more_types.html#function-overloading) to indicate the return type will be different based on the params received.

I'm considering to have an entire release just focused on MyPy stuff as more and more customers are raising issues on typing that could've been prevented, then enable MyPy at CI level -- it's a good thing, we just need a focused release or else other higher priorities will take place.

After the next release I'll write a plan for this on all areas we need. MyPy and Integ test for runtime botocore are my top concerns now

**Comment by heitorlessa** [comment]
Dumping it here for posterity.

None of the techniques I tried worked [due to being late-bound:](https://github.com/awslabs/aws-lambda-powertools-python/blob/develop/aws_lambda_powertools/event_handler/api_gateway.py#L232) Dynamically inject properties, Create BaseProxyEvent at runtime, Use generic to propagate, etc. The closest I've got working is using an Union of all Proxy Event types -- auto-completion works as expected, but it shows attributes that might not be there leading to an `AttributeError`.

Two potential solutions in my head now:

* 1/ Create a separate class for each type of event and update the docs (ApiGatewayV1Resolver, etc.) 
* 2/ Keep Union type, explicitly call out in the docs that it's best to use type annotation to have precise types -- Cons: Potential AttributeError and possibly methods that might not exist (need to check)
* 3/ Refactor the class instance that was created as part of Router's implementation, so we can use `@overload type` to dynamically set the type based on arguments.

cc @cakepietoast @mploski as I need some brainstorming.

**Comment by michaelbrewer** [comment]
DX from https://github.com/awslabs/aws-lambda-powertools-python/pull/978

---

Example of an Application Load Balancer handler (ALBResolver) where current_event can only be an ALBEvent

```python3
from aws_lambda_powertools.event_handler import ALBResolver

app = ALBResolver()

@app.get("/lambda")
def foo():
    # Now you can access ALBEvent specific attributes
    assert app.current_event.request_context.elb_target_group_arn is not None
    return Response(200, content_types.TEXT_HTML, "foo")
```

---

Example of an REST API handler (APIGatewayRestResolver) where current_event can only be an APIGatewayProxyEvent

```python3
from aws_lambda_powertools.event_handler import APIGatewayRestResolver

app = APIGatewayRestResolver()

@app.get("/my/path")
def get_lambda() -> Response:
    # Now you can access APIGatewayProxyEvent specific attributes
    assert app.current_event.request_context.domain_name == "id.execute-api.us-east-1.amazonaws.com"
    return Response(200, content_types.APPLICATION_JSON, json.dumps({"foo": "value"}))
```
---

Example of an Http API handler (APIGatewayHttpResolver) where current_event can only be an APIGatewayProxyEventV2

```python3
from aws_lambda_powertools.event_handler import APIGatewayHttpResolver

app = APIGatewayHttpResolver()

@app.post("/my/path")
def my_path() -> Response:
    # Now you can access APIGatewayProxyEventV2 specific attributes
    assert app.current_event.cookies[0] == "cookie1"
    return Response(200, content_types.TEXT_PLAIN, "Foo")
```
