### ISSUE TITLE
Metrics - Array of Objects / Loop

### ISSUE THREAD

**Issue by stephenbawks** [awslabs/aws-lambda-powertools-python#765]
**Is your feature request related to a problem? Please describe.**
I have a list of objects that I am trying to get individual counts on each item.  I have an event that is coming in from that contains an event where we have a "source" field and a "target" field.  The target is actually a list where I might have 1 item or up to four, or more in the future.  I am adding counts to my function so that I am get a "count" via Metrics() so that I can see when an event is firing and I want to be able to get a count for each target item.  

Right now I am doing something like this

```    
for item in data['target']:
        metrics.add_metric(name="Count", unit=MetricUnit.Count, value=1)
        metrics.add_dimension(name="EventType", value="Publisher")
        metrics.add_dimension(name="Source", value=data['source'])
        metrics.add_dimension(name="Target", value=item)
        metrics.serialize_metric_set()
```

**Describe the solution you'd like**
Just wondering if there would be an easier way to handle this. Thinking if the metric() would handle an array, where I tell it I have this list of items and I need you to iterate through this particular key and use this for the dimensions, instead of having to do a loop....?

**Comment by stephenbawks** [comment]
Ok thank you.  I was looking at the single stuff but did not think it was going to fit.  I just tried it out and it appears to be working just as you said.  So thank you!

**Comment by heitorlessa** [comment]
Awesome to hear @stephenbawks ! Closing this now
