### ISSUE TITLE
High resolution metrics in CloudWatch

### ISSUE THREAD

**Issue by nikevp** [awslabs/aws-lambda-powertools-python#779]
**Is your feature request related to a problem? Please describe.**

I need to graph estimated TPS for a 3rd party api. We have a TPS rate limit that must be monitored closely using Count/Second metrics. The current implementation aggregates metrics at a 1 minute interval even if the "CountPerSecond" unit is specified. I recognize metrics are grouped together under one timestamp, which might make this feature request a lower priority.

**Describe the solution you'd like**

Parameter to enable "High-Resolution Metrics" for 1 second intervals

**Describe alternatives you've considered**

Rest API / Cloudwatch SDK for these metrics. 

**Additional context**

Official Docs: https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/publishingMetrics.html#high-resolution-metrics

**Comment by heitorlessa** [comment]
I'm gonna close this now since we added this as a feature request for the CloudWatch EMF team
