### ISSUE TITLE
Change users.py to location.py

### ISSUE THREAD

**Issue by trey-rosius** [awslabs/aws-lambda-powertools-python#830]
**What were you initially searching for in the docs?**

I was searching on the new `Split operations with Router`
**Is this related to an existing part of the documentation? Please share a link**
yes,
https://awslabs.github.io/aws-lambda-powertools-python/1.22.0/core/event_handler/appsync/#split-operations-with-router
**Describe how we could make it clearer**

> Let's assume you have `app.py` as your Lambda function entrypoint and routes in `users.py`, this is how you'd use the Router feature.

I think you meant to say 

> Let's assume you have `app.py` as your Lambda function entrypoint and routes in `location.py`, this is how you'd use the Router feature.

Because the example given below is from the `location.py` file
**If you have a proposed update, please share it here**
It should be

>Let's assume you have `app.py` as your Lambda function entrypoint and routes in `location.py`, this is how you'd use the Router feature.

**Comment by heitorlessa** [comment]
Err, my bad, when copying things over before today’s release. Will send an
update shortly — thanks a lot for catching it!!

**Comment by trey-rosius** [comment]
My pleasure 😊. Closing now
