### ISSUE TITLE
Provide a LambdaContext object for use in testing

### ISSUE THREAD

**Issue by alexmuller** [awslabs/aws-lambda-powertools-python#833]
**Is your feature request related to a problem? Please describe.**

We test our Lambdas with pytest and do something like this:

```python
event = {}
context = {}
response = handler(event, context)
assert response == 1
```

When integrating this project we discovered that we'd have to set up a LambdaContext object and pass that in.

**Describe the solution you'd like**

It would be great if this library provided a context-like object that we could use in our tests

```python
from aws_lambda_powertools.utilities.typing.lambda_context import LambdaContext
context = LambdaContext(function_name='test', ...)

response = handler(event, context)
```

However the `LambdaContext` object (which is provided for IDE type hints) doesn't allow properties to be set.

**Describe alternatives you've considered**

We've used this snippet of code:

```python
lambda_context = {
    'function_name': 'test',
    ...
}
context = namedtuple("LambdaContext", lambda_context.keys())(*lambda_context.values())
```

from [here](https://stackoverflow.com/questions/65611351/using-aws-lambda-powertools-python-with-python-class-lambda) but it would be lovely to have this built-in to the library.

**Comment by heitorlessa** [comment]
hey @alexmuller - Check this out: https://github.com/awslabs/aws-lambda-powertools-roadmap/issues/14

We would love ideas on what a testing utility could look like. Lambda Context would be a quick one, but interested to hear your thoughts on how other events could look like, and what else could be helpful (and their UX more or less).

**Comment by alexmuller** [comment]
Thank you @heitorlessa, this looks great! The Lambda context would be a brilliant first step for me - but I'm also going to have a think about event handlers for SQS and SNS which would also be useful.

I'm going to close this issue as it's on the roadmap - thanks very much for your reply.
