### ISSUE TITLE
ApiGatewayResolver doesn't allow passing a list of methods to the `route` decorator

### ISSUE THREAD

**Issue by cakepietoast** [awslabs/aws-lambda-powertools-python#837]
**What were you trying to accomplish?**
Add a function to handle multiple http methods using the ApiGatewayResolver:

```python
app = ApiGatewayResolver(proxy_type=ProxyEventType.APIGatewayProxyEventV2)
@app.route("/", method=["GET", "PUT", "POST"])
def event_handler():
    return {"path_received": app.current_event.path, "method": app.current_event.http_method}
```

## Expected Behavior

It should be supported to pass a list of methods to `ApiGatewayResolver.route`, the same way it is supported for the `Router.route` method.

## Current Behavior

Exception is thrown.

## Solution
PR on its way

**Comment by heitorlessa** [comment]
Now released as part of 1.23 version
