### ISSUE TITLE
Feature: Powertools for other languages

### ISSUE THREAD

**Issue by jason-riddle** [awslabs/aws-lambda-powertools-python#84]
**Is your feature request related to a problem? Please describe.**

Love the idea of this project. It would be great to have this for other languages.

**Describe the solution you'd like**

The same easy-of-use of this project, but tailored to the best practices for other languages.

**Describe alternatives you've considered**

There isn't an alternative. Lots of extra undifferentiated heavy lifting of having to implement metrics, tracing, and logging over and over for other projects.

**Additional context**

My personal next preference would be Go, but I'm eager to hear the team's general thoughts.

**Comment by heitorlessa** [comment]
Hi @jason-riddle - Thanks for reaching out and raising this feature request. 

As of now, we're currently evaluating Typescript and Go as a prospect for the next language. Ideally, we'd like to have Powertools for all Lambda runtimes. 

I'll leave an additional comment to gauge interest in Go from the community as people can upvote in the meantime.

**Comment by heitorlessa** [comment]
Vote with +1 if you'd like Powertools for Golang

**Comment by stevehouel** [comment]
Vote with +1 if you'd like Powertools for Java

**Comment by sliedig** [comment]
Vote with +1 if you'd like Powertools for dotnet (C#)

**Comment by snetty** [comment]
+1 for Typescript 👍🏼

**Comment by monnecc** [comment]
+1 for C#

**Comment by eriklztiqqe** [comment]
+1 for Go and .NET (including F#!)

**Comment by weizhang9** [comment]
+1 for Go and Rust please 👍

**Comment by CABellamy** [comment]
+1 for Go please!

**Comment by bls20AWS** [comment]
+1 for PHP ;)

**Comment by heitorlessa** [comment]
Java is now OUT as Beta cc @oappicgi, @xaitek, @rajeshrajaian, @VanOvermeire, @stefaniuk

* **Repository**: https://github.com/awslabs/aws-lambda-powertools-java/
* **Tweet by Mark**: https://twitter.com/MarkSailes3/status/1300388020433059845

**Comment by mwarkentin** [comment]
+1 for NodeJS

**Comment by heitorlessa** [comment]
Hey! We now have an external email that we'd love to hear from you and what company you work for to help us prioritize additional runtimes. 📧 **aws-lambda-powertools-feedback@amazon.com**

I'm closing this now but here are some updates for you ;)

* **Java** - It's now GA :) https://github.com/awslabs/aws-lambda-powertools-java
* **Typescript/NodeJS** - We're going to work on this next. We welcome your feedback via email on the User Experience you'd love to have. 
* **Golang and C#** - We're actively considering it. We need more feedback from companies who'd want to use it including the experience they're after - This will help us prioritize.
* **Rust** - We won't be supporting it unless Lambda makes it a native runtime (part of our [tenets](https://awslabs.github.io/aws-lambda-powertools-python/#tenets)) - For that, you can help us by using #awswishlist on Twitter, and by talking to your AWS representative ;)

We hugely appreciate everyone's kind messages across many channels, keep your feedback coming via email, and stay tuned for Typescript!
