### ISSUE TITLE
Logger Sampling debug not working dynamically with AWS Chalice serverless framework.

### ISSUE THREAD

**Issue by viniciusao** [awslabs/aws-lambda-powertools-python#841]
## Current Behavior

It's simply not dynamically logging, but either log (>= 0.6) or not (<= 0.6) based on sampling_rate's argument value.

## Steps to Reproduce (for bugs)

1. chalice local
2. Postman run collection with iteration.
```
@app.route('/')
def greeting():
    session = requests.Session()
    path = '/status/500'
    logger.debug('', extra={'statuscode': 500})
    response = session.get(f'https://httpbin.org/{path}')
    response.raise_for_status()
    return {'hello': 'world'}
```

## Environment

* **Powertools version used**: 1.22.0
* **Python:** 3.8

**Comment by heitorlessa** [comment]
Hey @viniciusao - I'd need to set some time aside to setup a chalice app to better understand the middleware functionality before replying.

From Powertools Logger perspective, sampling is calculated at the instance initialisation (e.g., Logger()), as we explain in the docs.

This often happens at the global scope and has two effects:

1. Sampling decision will only occur at cold start, not on a per invocation
2. Chalice local or SAM CLI local with warm container support (container reuse) will have the same effect as warm invocation (sampling calculated once)

I'd suggest two possible outcomes: **1/** Create a feature request to calculate at per invocation - e.g., a new flag for inject_lambda_context decorator, or **2/** Create a Logger instance inside the handler (not practical)
