### ISSUE TITLE
Compatibility with xray 2.6.0

### ISSUE THREAD

**Issue by Nr18** [awslabs/aws-lambda-powertools-python#88]
**Is your feature request related to a problem? Please describe.**
We are currently using [aws-xray-sdk-python 2.6.0](https://github.com/aws/aws-xray-sdk-python/releases) and I wanted to test the power tools but it seems that this project is not compatible with the latest release of  the X-Ray SDK.

**Describe the solution you'd like**
This project to stay up to date with the new SDK releases, 2.6.0 has been released more than a month ago.

**Describe alternatives you've considered**
Downgrading the SDK but we want to keep up with the latest versions of packages to reduce bugs/vulnerabilities and benefit from new features.

**Additional context**
Not sure if it has a compatibility reason or just done out of foresight:  `~= 2.5.0` see https://github.com/awslabs/aws-lambda-powertools-python/blob/0670e5efa09b60f0dd6d040a1a3b37225c94b516/pyproject.toml#L22

**Comment by heitorlessa** [comment]
Hi Joris - Thanks for opening up the issue -- Its definitely an oversight, as we should be compatible with any 2.* version

If you could do a quick PR I'd gladly accept it, or I can do this next week :)

Thanks again!

**Comment by Nr18** [comment]
@heitorlessa not sure if this is the only place where it needs to be updated but I created #89. Although you mentioned any 2.* version I used 2.5.0 as the first one since that was already set.

**Comment by heitorlessa** [comment]
Just released **1.0.2** with this fix - Thanks a lot for the contribution :) 

**PS**: I think I finally remember why your login looked familiar. @Nr18 .... it was back then with the cookiecutter for SAM Python, which I intend to update to use this library now ;)

Closing this now, and thank you again!

**Comment by Nr18** [comment]
That is correct, I noticed that when you responded to this issue.

Happy to help out!
