### ISSUE TITLE
Log pydantic models as structured JSON, not str(...)

### ISSUE THREAD

**Issue by huonw** [awslabs/aws-lambda-powertools-python#904]
**Is your feature request related to a problem? Please describe.**

The structured logging/auto-JSON-ification support is great and makes our logs much better, thank you.

We occasionally log a pydantic model directly and this unfortunately doesn't work so well by default, as it uses the models `str`, rather than convert it (recursively) to JSON:

```python
import pydantic
from datetime import datetime, timezone
from aws_lambda_powertools.logging import Logger
import json

logger = Logger()


class Inner(pydantic.BaseModel):
    x: int
    y: str
    z: datetime = datetime(2000, 1, 2, 3, 4, 5, 6, tzinfo=timezone.utc)


class Outer(pydantic.BaseModel):
    inner: Inner
    extra: float


value = Outer(inner=Inner(x=1, y="y"), extra=2.3)

print("Default")
logger.info(value)
logger.info({"nested": [("deeply", value)]})

print("\nDesired (powertools JSON encoding)")
logger.info(value.dict())
logger.info({"nested": [("deeply", value.dict())]})

print("\nDesired (pydantic JSON encoding)")
logger.info(json.loads(value.json()))
logger.info({"nested": [("deeply", json.loads(value.json()))]})
```

Output:

```
Default
{"level":"INFO","location":"<module>:24","message":"inner=Inner(x=1, y='y', z=datetime.datetime(2000, 1, 2, 3, 4, 5, 6, tzinfo=datetime.timezone.utc)) extra=2.3","timestamp":"2021-12-17 08:16:32,658+1100","service":"service_undefined"}
{"level":"INFO","location":"<module>:25","message":{"nested":[["deeply","inner=Inner(x=1, y='y', z=datetime.datetime(2000, 1, 2, 3, 4, 5, 6, tzinfo=datetime.timezone.utc)) extra=2.3"]]},"timestamp":"2021-12-17 08:16:32,658+1100","service":"service_undefined"}

Desired (powertools JSON encoding)
{"level":"INFO","location":"<module>:28","message":{"inner":{"x":1,"y":"y","z":"2000-01-02 03:04:05.000006+00:00"},"extra":2.3},"timestamp":"2021-12-17 08:16:32,658+1100","service":"service_undefined"}
{"level":"INFO","location":"<module>:29","message":{"nested":[["deeply",{"inner":{"x":1,"y":"y","z":"2000-01-02 03:04:05.000006+00:00"},"extra":2.3}]]},"timestamp":"2021-12-17 08:16:32,658+1100","service":"service_undefined"}

Desired (pydantic JSON encoding)
{"level":"INFO","location":"<module>:32","message":{"inner":{"x":1,"y":"y","z":"2000-01-02T03:04:05.000006+00:00"},"extra":2.3},"timestamp":"2021-12-17 08:16:32,658+1100","service":"service_undefined"}
{"level":"INFO","location":"<module>:33","message":{"nested":[["deeply",{"inner":{"x":1,"y":"y","z":"2000-01-02T03:04:05.000006+00:00"},"extra":2.3}]]},"timestamp":"2021-12-17 08:16:32,658+1100","service":"service_undefined"}
```

In particular, compare:

- default: `"inner=Inner(x=1, y='y', z=datetime.datetime(2000, 1, 2, 3, 4, 5, 6, tzinfo=datetime.timezone.utc)) extra=2.3"`
- JSON-ified: `{"inner":{"x":1,"y":"y","z":"2000-01-02 03:04:05.000006+00:00"},"extra":2.3}` 
 
(The exact format of the JSON will depend on whether it converts to python types via `.dict()` and then uses powertools' JSON encoding, or uses pedantic's JSON encode via `.json()` then back to Python types with `json.loads` (https://github.com/samuelcolvin/pydantic/issues/1409 is related, for the latter).)

**Describe the solution you'd like**

The default `json_default` value for `LambdaPowertoolsFormatter` could detect Pydantic (and maybe other JSON-like structures, like dataclasses?) to coerce those to structured data. For instance:

```python
try:
    import pydantic
except ImportError:
    pydantic = None

import dataclasses

def default_json_default(value: Any) -> Any:
    if pydantic is not None and isinstance(value, pydantic.BaseModel):
        return value.dict()
    elif dataclasses.is_dataclass(value): # (haven't tested this)
        return value.asdict()

    return str(value)
```

This potentially imposes an undesired performance cost on logging, but I haven't investigated.

**Describe alternatives you've considered**

Everyone providing our own custom `json_default` argument to `LambdaPowertoolsFormatter` (we're doing this currently):

```python
def json_default(value):
    if isinstance(value, pydantic.BaseModel):
        return value.dict()
    return str(value)


logger = Logger(json_default=json_default)
```

**Additional context**

Exact requirements for example above:

```
aws-lambda-powertools==1.22.0
aws-xray-sdk==2.9.0
boto3==1.20.24
botocore==1.23.24
fastjsonschema==2.15.2
future==0.18.2
jmespath==0.10.0
pydantic==1.8.2
python-dateutil==2.8.2
s3transfer==0.5.0
six==1.16.0
typing_extensions==4.0.1
urllib3==1.26.7
wrapt==1.13.3
```

**Comment by ran-isenberg** [comment]
Not related to your suggestion but a general comment:
You should be really careful with full object logging as you might log PII (personal information). I usually just log the most important/identifiable field/fields and not the entire object.

**Comment by huonw** [comment]
Yep, definitely something to be careful of. For our full object logging, it's almost always internal utility models for which Pydantic allows convenient manipulation not API/database models (for instance, models parsed from some internal configuration files rather than user data).

**Comment by heitorlessa** [comment]
hey @huonw I thought about this long and hard even for Dataclasses, but this would decrease security posture & compliance like Well-Architected, NIST and others -- while I trust you'll do this carefully we can't guarantee others will be due diligent when it comes to defensive programming and data leaking.

`json_default` is the way go and the reason we exposed it, so you can make an explicit decision to go down that route.

Meanwhile, I'm working prepping the next release and will include your other great suggestion on Logger datetime string parsing ;)

Thank you as always!
