### ISSUE TITLE
Docs: Admonitions consitency

### ISSUE THREAD

**Issue by DanyC97** [awslabs/aws-lambda-powertools-python#917]
**What were you initially searching for in the docs?**

While i was browsing the [docs](https://awslabs.github.io/aws-lambda-powertools-python/develop/core/event_handler/api_gateway/#http-methods), i've noticed something is not right with the format

![image](https://user-images.githubusercontent.com/7383422/146782148-a6bde14b-f734-4ce2-839a-848c5b48f08f.png)

and when i started to work on a PR, i've noticed a bit of inconsistency on various pages where:

* on some pages we have admonitions with title: Info/ Warning/ Note etc
* on some we don't

**Describe how we could make it clearer**

I'd like to suggest we adhere to a convention whereby

* every admonition will have the default title 

**_Current_**

![image](https://user-images.githubusercontent.com/7383422/146784580-290e91db-d360-4fb9-935b-be133567fc6a.png)

**_Proposed_** 

![image](https://user-images.githubusercontent.com/7383422/146784821-c282a2aa-c192-4707-9103-8a98c914fa00.png)

* for cases where we provide a custom title, we prefix it with the default title in the format `<default title>: <custom title> - i.e Tip: DynamoDB`

**_Current_**

![image](https://user-images.githubusercontent.com/7383422/146785388-881d2d1a-44cc-42a6-97cd-b7697e2ffe3d.png)

**_Proposed_** 

![image](https://user-images.githubusercontent.com/7383422/146785536-5baaf5c9-31da-4243-ad52-ef1e2501c2ff.png)

* use the example admonition instead of question mark or quote

**_Current_**

![image](https://user-images.githubusercontent.com/7383422/146786938-96874bd1-3162-45ce-9509-66c9fa35b128.png)

**_Proposed_** 

![image](https://user-images.githubusercontent.com/7383422/146787189-88bc6994-e430-455d-a7d0-0423373aaa09.png)

* nice to have - collapsible blocks ( default open)

**_Open block_**

![image](https://user-images.githubusercontent.com/7383422/146786427-d1c71c26-33f4-4984-bb2f-b6c5e176b25e.png)

_**Closed block**_

![image](https://user-images.githubusercontent.com/7383422/146786511-2e4ef31c-6060-44fa-80a5-7d667a12285d.png)

If you happy with my suggestion, i'll start working on a PR to address all the pages from A to Z.

**Comment by heitorlessa** [comment]
I like them!!! Please go ahead and we can make some small tweaks as part of the PR :) Thank you so much @DanyC97 !

**Comment by heitorlessa** [comment]
Hey @DanyC97 thank you again **so much** for the help here, docs is so crucial to us and it's hard to get quality contributions like these. 

Now available in the latest docs!
