### ISSUE TITLE
Null type becomes BOOL

### ISSUE THREAD

**Issue by sergiors** [awslabs/aws-lambda-powertools-python#928]
**Is your feature request related to a problem? Please describe.**

I did a stream to copy dynamodb to elasticsearch, I used the object `DynamoDBStreamEvent`, until that okey,
but when I try get the values, the null type becomes a boolean type.

**Describe the solution you'd like**

I read the [source-code](https://github.com/awslabs/aws-lambda-powertools-python/blob/develop/aws_lambda_powertools/utilities/data_classes/dynamo_db_stream_event.py#L109) the `AttributeValue.null_value` and think the null value should back to python native value, like described in [ boto3 types ](https://boto3.amazonaws.com/v1/documentation/api/latest/_modules/boto3/dynamodb/types.html#Binary)

**Describe alternatives you've considered**

**Additional context**

As alternative to fix the stream copy, the only value that I need to check is the null value.
```python
{k: v.get_value if not v.null_value else None for k, v in dct.items()}
```

**Comment by michaelbrewer** [comment]
Been a while since i did this, but if this is for deserialization, then `"NULL": true` would map to Python `None`. 

I will double check @heitorlessa

**Comment by michaelbrewer** [comment]
@sergiors @heitorlessa 
Ok i made a PR to fix this (https://github.com/awslabs/aws-lambda-powertools-python/pull/929). It would be a breaking change (_if you where expecting `null_value` to return a boolean_), however this was the wrong behavior.

FYI, `get_value` is a convenient way to get the value out.
