### ISSUE TITLE
tests: metrics tests fail when `PYTHONWARNINGS="ignore"`

### ISSUE THREAD

**Issue by michaelbrewer** [awslabs/aws-lambda-powertools-python#993]
**What were you trying to accomplish?**

Run `make test` when `PYTHONWARNINGS="ignore"`

## Expected Behavior

Test should pass

## Current Behavior

```
_____________________________________________________________________________________________________ test_log_metrics_decorator_no_metrics_warning _____________________________________________________________________________________________________

dimensions = [{'name': 'test_dimension', 'value': 'test'}, {'name': 'test_dimension_2', 'value': 'test'}], namespace = 'test_namespace', service = 'test_service'

    def test_log_metrics_decorator_no_metrics_warning(dimensions, namespace, service):
        # GIVEN Metrics is initialized
        my_metrics = Metrics(namespace=namespace, service=service)
    
        # WHEN using the log_metrics decorator and no metrics have been added
        @my_metrics.log_metrics
        def lambda_handler(evt, context):
            pass
    
        # THEN it should raise a warning instead of throwing an exception
        with warnings.catch_warnings(record=True) as w:
            lambda_handler({}, {})
>           assert len(w) == 1
E           assert 0 == 1
E             +0
E             -1

tests/functional/test_metrics.py:555: AssertionError
```

## Possible Solution

Temp set `warnings.simplefilter("default")`

- PR: https://github.com/awslabs/aws-lambda-powertools-python/pull/994

## Steps to Reproduce (for bugs)
1. `export PYTHONWARNINGS="ignore"`
2. `make test`

## Environment

* **Powertools version used**:
* **Packaging format (Layers, PyPi)**:
* **AWS Lambda function runtime:**
* **Debugging logs**

**Comment by heitorlessa** [comment]
@michaelbrewer could you provide more details about this issue before we merge? How did you run into it since this flag isn't set by default?

Looking at the docs, it seems we should be doing this for all utilities not just metrics: https://docs.python.org/3/library/warnings.html#overriding-the-default-filter

**Comment by michaelbrewer** [comment]
i was trying to disabled some setup issues with poetry on my m1 mac and it prints out warnings.

**Comment by michaelbrewer** [comment]
@heitorlessa this is based on pythons recommended way for testing warnings:

```python3
import warnings

def fxn():
    warnings.warn("deprecated", DeprecationWarning)

with warnings.catch_warnings(record=True) as w:
    # Cause all warnings to always be triggered.
    warnings.simplefilter("always")
    # Trigger a warning.
    fxn()
    # Verify some things
    assert len(w) == 1
    assert issubclass(w[-1].category, DeprecationWarning)
    assert "deprecated" in str(w[-1].message)
```
