### ISSUE TITLE
Create a new section for community resources

### ISSUE THREAD

**Issue by heitorlessa** [awslabs/aws-lambda-powertools-python#995]
**What were you initially searching for in the docs?**

A list of non-AWS examples, blog posts, tutorials, and guides about Lambda Powertools.

**Is this related to an existing part of the documentation? Please share a link**

No.

**Describe how we could make it clearer**

Create a new section grouping best community resources that other customers can learn from. These are particular helpful because it conveys the value of Powertools, use cases, and lessons from their lenses. There's been plenty of articles including in Japanese but not easily discoverable from our docs.

**If you have a proposed update, please share it here**

Similar example: https://aws.github.io/copilot-cli/community/guides/

**Comment by ran-isenberg** [comment]
we have 2 webinars together - one about the parser and the other about the feature flags. I also have blogs posts about them both and very soon 2 blogs about the tracer/logger.

**Comment by ran-isenberg** [comment]
feature flags blog: https://medium.com/cyberark-engineering/aws-feature-flags-made-simpler-and-smarter-f78d4b4ca933
feature flags webinar on aws twitch:  https://www.twitch.tv/aws/video/1174133534
parser blog: https://medium.com/cyberark-engineering/aws-lambda-event-validation-in-python-now-with-powertools-431852ac7caa

parser webinar: https://www.twitch.tv/videos/1034744364

**Comment by elthrasher** [comment]
[First Look at Lambda Powertools TypeScript](https://dev.to/aws-builders/first-look-at-lambda-powertools-typescript-2k3p)

**Comment by ran-isenberg** [comment]
Logger: https://isenberg-ran.medium.com/aws-lambda-cookbook-elevate-your-handlers-code-part-1-bc160a10679a

**Comment by walmsles** [comment]
Here's my latest addition - AWS Lambda Powertools for Python Workshop

https://github.com/walmsles/lambda-powertools-coding-workshop

It's a Live code-along workshop I am presenting  at Melbourne AWS Programming and Tools Meetup in about 12 hours 🙂

**Comment by walmsles** [comment]
..... and the recording of the AWS Programming and Tools Meetup :-). 

https://www.youtube.com/watch?v=N1r7J3Xztsc

**Comment by ran-isenberg** [comment]
Parser: https://www.ranthebuilder.cloud/post/aws-lambda-cookbook-elevate-your-handler-s-code-part-5-input-validation

**Comment by eliasbrange** [comment]
A hands-on guide on how to use Lambda Powertools for Python to implement observability best practices for FastAPI applications running in Lambda functions: https://www.eliasbrange.dev/posts/observability-with-fastapi-aws-lambda-powertools/

**Comment by michaelbrewer** [comment]
Add lambda guide cover powertools help with different event sources:
- https://lambda.101i.de/

**Comment by ran-isenberg** [comment]
feature flags and configuration utility:
https://www.ranthebuilder.cloud/post/aws-lambda-cookbook-part-6-feature-flags-configuration-best-practices

**Comment by heitorlessa** [comment]
reopening as I'll create the new docs section **We Made This (community)** next week. We now have an issue template as intake to feature community content ;) 

https://github.com/awslabs/aws-lambda-powertools-python/issues/new?assignees=&labels=community-content&template=share_your_work.yml&title=%5BI+Made+This%5D%3A+%3CTITLE%3E

**Comment by heitorlessa** [comment]
Now live at: https://awslabs.github.io/aws-lambda-powertools-python/2.0.0/we_made_this/
